### ISSUE TITLE
'coordinator' panicked at 'sinks should be validated by sequence_create_sink: Catalog(Error { kind: Stash(StashError { inner: Transaction(Commit(StashError { inner: Postgres(Error { kind: Closed, cause: None }) })) }) })'

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17885] opened 2023-03-01 13:29 UTC
### What version of Materialize are you using?

 v0.45.0-dev

### How did you install Materialize?

Docker image

### What is the issue?

This Nightly step:

https://buildkite.com/materialize/nightlies/builds/1874#01869d28-f4a1-4072-81e9-f99fdb6139c

```
cd test/zippy
./mzcompose run default --scenario=CrdbRestart --actions=1000 --cockroach-tag=latest
```
Produced this panic:

```
zippy-materialized-1     | coordinator' panicked at 'sinks should be validated by sequence_create_sink: Catalog(Error { kind: Stash(StashError { inner: Transaction(Commit(StashError { inner: Postgres(Error { kind: Closed, cause: None }) })) }) })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord/message_handler.rs:494:22
```

@mjibson FYI

ci-regexp: sinks should be validated by sequence_create_sink

### Relevant log output

```source
zippy-materialized-1     | coordinator' panicked at 'sinks should be validated by sequence_create_sink: Catalog(Error { kind: Stash(StashError { inner: Transaction(Commit(StashError { inner: Postgres(Error { kind: Closed, cause: None }) })) }) })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord/message_handler.rs:494:22
zippy-materialized-1     | stack backtrace:
zippy-materialized-1     | environmentd: 2023-03-01T12:55:09.885311Z  WARN deadpool.postgres: Connection error: connection closed    
zippy-materialized-1     |    0: rust_begin_unwind
zippy-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
zippy-materialized-1     |    1: core::panicking::panic_fmt
zippy-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
zippy-materialized-1     |    2: core::result::unwrap_failed
zippy-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
zippy-materialized-1     |    3: <core::result::Result<(), mz_adapter::error::AdapterError>>::expect
zippy-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
zippy-materialized-1     |    4: <mz_adapter::coord::Coordinator>::message_sink_connection_ready::{closure#0}::{closure#0}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord/message_handler.rs:484:21
zippy-materialized-1     |    5: <mz_adapter::coord::Coordinator>::message_sink_connection_ready::{closure#0}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord/message_handler.rs:462:5
zippy-materialized-1     |    6: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord/message_handler.rs:58:93
zippy-materialized-1     |    7: <mz_adapter::coord::Coordinator>::serve::{closure#0}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord.rs:1229:37
zippy-materialized-1     |    8: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
zippy-materialized-1     |    9: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
zippy-materialized-1     |   10: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
zippy-materialized-1     |   11: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
zippy-materialized-1     |   12: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
zippy-materialized-1     |   13: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
zippy-materialized-1     |   14: mz_adapter::coord::serve::{closure#0}::{closure#1}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0796a7fb280dc49be-1/materialize/tests/src/adapter/src/coord.rs:1408:17
zippy-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jkosh44** [comment] 2023-03-01 14:54
The error comes from here: https://github.com/MaterializeInc/materialize/blob/bf77cc18827d116225e15297860c3931e7016afc/src/adapter/src/coord/message_handler.rs#L474-L505
which has multiple comments about how the `expect` that causes this error is scary.

**Comment by jkosh44** [comment] 2023-03-01 14:57
Sink creation happens in two steps:
1. Initially create a pending sink in the catalog and then establish a connection asynchronously to the external system.
2. Once the connection has been established, update the catalog to indicate that the sink is no longer pending.

From reading the error message, it looks like step two failed because we lost our connection to the stash and couldn't update the sink in the catalog.

**Comment by mjibson** [comment] 2023-03-01 16:33
Duplicate of #17862.

**Comment by mjibson** [comment] 2023-03-01 16:34
(All errors that occur for the next few days with `Transaction(Commit(StashError` in their error message are the same, and are absolutely expected during cockroach restarts.

**Closed by mjibson** 2023-03-01 16:33 UTC
Labels: C-bug, release-blocker, A-ADAPTER, ci-flake
