### ISSUE TITLE
Support parsing csvs with strings containing newlines

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#2462] opened 2020-03-27 21:32 UTC
This might be a little difficult given our setup but some users have experienced problems where they has csv data containing strings which themselves contain newlines and we are not able to parse those

**Comment by frankmcsherry** [comment] 2020-03-28 01:19
I think the csv parser can take an arbitrary newline character? Needs to be plumbed through, but I believe the tech exists.

**Comment by benesch** [comment] 2020-03-28 02:47
The problem isn't the CSV parser. The problem is the way we try to separate the framing of records from the format within each record. The file decoder currently split blindly at newlines, assuming every newline marks the end of one record and the start of the next. I guess this doesn't work right for CSVs, where a newline inside of quotes isn't interpreted as a record separator but as  a literal newline (I think).

I don't know of a good way to solve this besides what we do for Avro OCF, where we just stop pretending there is a clean separation between the file connector and the decoder.

**Comment by brandonbloom** [comment] 2020-04-17 16:51
Running in to this myself. Just wanted to add that Postgresql is one of the CSV producers that does not escape newlines inside quotes, in case that helps you in prioritization.

**Comment by umanwizard** [comment] 2021-07-28 14:32
This is fixed now

**Closed by umanwizard** 2021-07-28 14:32 UTC
Labels: A-source, C-feature
