### ISSUE TITLE
frontier in `SUBSCRIBE` error does not match any in `EXPLAIN TIMESTAMP`

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#21236] opened 2023-08-17 18:45 UTC
### What version of Materialize are you using?

v0.64.0

### What is the issue?

While playing around with the metrics tables that have 30d retention, I noticed that I'm not able to `SUBSCRIBE AS OF` any time older than when (I think) `envd` booted, at the very least not the full retention window.

Here's an example: `EXPLAIN TIMESTAMP` shows that `since` is 30d ago

```
materialize=> EXPLAIN TIMESTAMP FOR (SELECT * FROM mz_internal.mz_cluster_replica_metrics);
                                 Timestamp
---------------------------------------------------------------------------
                 query timestamp: 1692218351448 (2023-08-16 20:39:11.448) +
           oracle read timestamp: 1692218351448 (2023-08-16 20:39:11.448) +
 largest not in advance of upper: 1692218351448 (2023-08-16 20:39:11.448) +
                           upper:[1692218351449 (2023-08-16 20:39:11.449)]+
                           since:[1689626351000 (2023-07-17 20:39:11.000)]+
         can respond immediately: true                                    +
                        timeline: Some(EpochMilliseconds)                 +
               session wall time: 1692218351662 (2023-08-16 20:39:11.662) +
                                                                          +
 source mz_internal.mz_cluster_replica_metrics (s332, storage):           +
                   read frontier:[1689626351000 (2023-07-17 20:39:11.000)]+
                  write frontier:[1692218351449 (2023-08-16 20:39:11.449)]+
```

but trying to `SUBCRIBE` errors with a much more recent frontier, that matches none of the ones from `EXPLAIN TIMESTAMP`:

```
materialize=> COPY (SUBSCRIBE (SELECT * FROM mz_internal.mz_cluster_replica_metrics) AS OF 0) TO STDOUT;
ERROR:  Timestamp (0) is not valid for all inputs: [Antichain { elements: [1692218320454] }]
```

Restarting `envd` will advance the frontier in the error message.

**Comment by ggnall** [comment] 2023-08-17 21:08
@umanwizard offered to take a look at this, and it would be great if @mjibson or @andrewrodriguez-m have any insights about timestamp bheavior

**Comment by andrewrodriguez-m** [comment] 2023-08-17 21:12
Nothing comes to mind off the top of my head

**Comment by andrewrodriguez-m** [comment] 2023-08-18 17:54
seems like a dupe of #21268

**Comment by ggnall** [comment] 2023-08-18 18:37
Duplicate of https://github.com/MaterializeInc/materialize/issues/21268

**Closed by ggnall** 2023-08-18 18:37 UTC
Labels: C-bug, A-COMPUTE, A-ADAPTER
