### ISSUE TITLE
Replace frontegg-react login flow in Console

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#28620] opened 2024-07-29 22:01 UTC
Link to the Notion Epic: https://www.notion.so/Replace-frontegg-react-login-flow-in-Console-114cf90c35e94fa4a92ae8be69420a5a

**Comment by chaas** [comment] 2024-07-29 22:01
Duplicate of https://github.com/MaterializeInc/console/issues/1398

**Closed by chaas** 2024-07-29 22:01 UTC
