### ISSUE TITLE
Casting interval to time panics: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24719] opened 2024-01-26 11:12 UTC
### What version of Materialize are you using?

1efa5662ef

### What is the issue?

```sql
SELECT '-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL::TIME;
```
Panics:
```
thread 'tokio:work-56' panicked at src/expr/src/scalar/func/impls/interval.rs:48:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
   3: mz_expr::scalar::func::impls::interval::cast_interval_to_time
   4: <mz_expr::scalar::func::impls::interval::CastIntervalToTime as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/func/macros.rs:153:21
   5: <mz_expr::scalar::func::impls::interval::CastIntervalToTime as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/func.rs:4374:26
   6: <mz_expr::scalar::func::UnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/func/macros.rs:343:41
   7: <mz_expr::scalar::MirScalarExpr>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/mod.rs:1841:56
   8: <mz_expr::scalar::MirScalarExpr>::reduce::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/mod.rs:736:36
   9: <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/mod.rs:792:34
  10: stacker::maybe_grow::<(), <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  11: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}, ()>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/stack.rs:100:5
  12: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/visit.rs:711:9
  13: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/visit.rs:439:31
  14: <mz_expr::scalar::MirScalarExpr>::reduce
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/scalar/mod.rs:744:13
  15: <mz_transform::fold_constants::FoldConstants>::action::<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_repr::relation::RelationType>, <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}::{closure#0}>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/fold_constants.rs:194:21
  16: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/fold_constants.rs:53:13
  17: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/visit.rs:556:13
  18: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/stack.rs:191:33
  19: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  20: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/stack.rs:100:5
  21: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/stack.rs:191:19
  22: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/visit.rs:554:9
  23: <mz_expr::relation::MirRelationExpr as mz_expr::visit::Visit>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/expr/src/visit.rs:345:31
  24: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/fold_constants.rs:49:22
  25: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/lib.rs:360:13
  26: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/lib.rs:277:25
  27: <tracing::span::Span>::in_scope::<<mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}, core::result::Result<(), mz_transform::TransformError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1102:9
  28: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/lib.rs:275:17
  29: <mz_transform::Optimizer>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/lib.rs:660:13
  30: <mz_transform::Optimizer>::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/transform/src/lib.rs:623:32
  31: <mz_adapter::optimize::materialized_view::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::optimize::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/optimize/materialized_view.rs:167:24
  32: <tracing::span::Span>::in_scope::<<mz_adapter::optimize::materialized_view::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::optimize::{closure#0}, core::result::Result<mz_expr::relation::MirRelationExpr, mz_adapter::optimize::OptimizerError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1102:9
  33: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_expr::relation::MirRelationExpr>>::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/optimize/peek.rs:217:20
  34: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/optimize/peek.rs:208:9
  35: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/optimize/mod.rs:104:63
  36: <core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  37: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  38: std::panicking::try::<core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>, core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  39: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  40: mz_ore::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/panic.rs:78:19
  41: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::try_with::<mz_ore::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}, core::result::Result<core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  42: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::with::<mz_ore::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}, core::result::Result<core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  43: mz_ore::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::LocalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/ore/src/panic.rs:75:21
  44: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_sql::plan::expr::HirRelationExpr>>::catch_unwind_optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/optimize/mod.rs:104:15
  45: <mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:456:42
  46: <mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03cdac7a71513236a-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:463:35
  47: <tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  48: <tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  49: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  50: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  51: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  52: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  53: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  54: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  55: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  56: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  57: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  58: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  59: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  60: <tokio::runtime::task::raw::RawTask>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  61: <tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  62: <tokio::runtime::blocking::pool::Task>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  63: <tokio::runtime::blocking::pool::Inner>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  64: <tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
```

Found by the output consistency check in https://buildkite.com/materialize/nightlies/builds/6151#018d409c-ee61-42ca-836c-a26da6a9cacc

This is not a regression but an old panic, maybe introduced by https://github.com/MaterializeInc/materialize/pull/10749

ci-regexp: called `Option::unwrap()` on a `None` value

**Comment by nrainer-materialize** [comment] 2024-01-26 11:50
Closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/24684.

**Closed by nrainer-materialize** 2024-01-26 11:50 UTC
Labels: C-bug
