### ISSUE TITLE
testdrive: in-memory state of the catalog does not match its on-disk state

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#27196] opened 2024-05-21 15:36 UTC
### What version of Materialize are you using?

bb54d1c683af88c21f57f5884b9eeef64d2c4c1e

### What is the issue?

```
error: catalog inconsistency: catalog state

Caused by:
    the in-memory state of the catalog does not match its on-disk state:
    @@ -301795,101 +301795,100 @@
           "s0acffd0b-d4ab-46b9-8d03-21e9ad91af7f",
           "s0b421d9f-49de-49f7-bf64-c98c354a8230",
           "s0b69cfd9-34c0-4082-914f-38a47cc63181",
           "s0b6ef4bf-c67c-4429-83f3-9aa7b97e8f10",
           "s0bb3de90-bd8e-47e0-9ad4-34a8db94f076",
           "s0bd95b6d-a94e-45cb-a91d-eb2c46ec44da",
           "s0c439d74-4d7d-4c03-bc94-37d4eab16d83",
           "s0d620e25-fcdd-46de-8314-0ba120d73dec",
           "s0dcfc52a-445e-40ce-9260-a393cce2be48",
           "s0dee1743-a68b-46d0-a884-33a072a7d2c0",
```

was observed in https://buildkite.com/materialize/nightly/builds/7822#018f9858-74fc-4584-8779-210c5e6ab8a2.

ci-regexp: the in-memory state of the catalog does not match its on-disk state

**Comment by nrainer-materialize** [comment] 2024-05-21 15:36
See also: https://materializeinc.slack.com/archives/C02FWJ94HME/p1716281641799669

**Comment by sploiselle** [comment] 2024-05-21 15:56
@nrainer-materialize Do you know when this started occurring?

**Comment by nrainer-materialize** [comment] 2024-05-28 06:56
Adding a further occurrence: https://buildkite.com/materialize/nightly/builds/7898#018fbdba-f856-4636-b72c-60aac92b99b6

**Comment by def-** [comment] 2024-06-03 03:06
Another one: https://buildkite.com/materialize/nightly/builds/7940#_
This seems pretty important to me. @ParkMyCar Since this started failing on your PR first (https://github.com/MaterializeInc/materialize/pull/27169) and the check was implemented by you, would you mind taking a look?

**Comment by def-** [comment] 2024-06-03 03:10
Sorry, just found the previous discussion around this in https://materializeinc.slack.com/archives/C02FWJ94HME/p1716281641799669 Still seems important to me and like there is no clear cause, maybe we can add some more logging so that we get more information when this fails again in CI?

**Comment by jkosh44** [comment] 2024-06-03 17:18
For all the failures the issue is that the on disk catalog is missing one unfinalized shard that the in memory catalog contains.

**Comment by jkosh44** [comment] 2024-06-03 17:49
I don't see a pattern in the SQL commands that triggered the consistency checks that failed. However when looking through the logs of the failed tests, they all either end with

```
environmentd: 2024-05-20T20:07:51.308686Z  INFO coord::handle_message{kind="controller_ready"}: mz_storage_controller: triggering shard finalization due to dropped storage object
```
or
```
environmentd: 2024-05-31T18:28:18.314664Z  WARN mz_storage_client::storage_collections: error during background finalization of shard sffac4c6e-5806-4aa4-bd47-8d395aa1704d: FinalizationError { since: Antichain { elements: [0] }, upper: Antichain { elements: [] } }
```

My current thinking is that there's a race condition somewhere with some background task that finalizes shards.

**Comment by jkosh44** [comment] 2024-06-03 17:53
FWIW the following testdrive test trivially reproduces the problem in the opposite direction, that is the finalized shard appears on disk, but not in memory.

```
$ postgres-execute connection=postgres://mz_system:materialize@${testdrive.materialize-internal-sql-addr}
ALTER SYSTEM SET enable_storage_shard_finalization = off

> CREATE TABLE t (a INT);

> DROP TABLE t;
```

The reason is that setting `enable_storage_shard_finalization`, stops us from tracking unfinalized shards in memory.

**Comment by jkosh44** [comment] 2024-06-03 19:23
The following testdrive test exactly reproduces the error:

```
> CREATE TABLE t (a INT);

> DROP TABLE t;

$ postgres-execute connection=postgres://mz_system:materialize@${testdrive.materialize-internal-sql-addr}
ALTER SYSTEM SET enable_storage_shard_finalization = off

> SELECT mz_unsafe.mz_sleep(3)
<null>

```

I'm a bit skeptical that this is the actual issue, because as far as I can tell we never alter `enable_storage_shard_finalization` in the tests. So I will keep digging.

**Comment by jkosh44** [comment] 2024-06-03 22:11
As per my best understanding, this is the lifecycle of an unfinalized shards.

1. A user drops a storage collection.
2. The unfinalized shard is added to a catalog txn.
3. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn.
4. The unfinalized shard is persisted durably via committing the catalog txn.
5. The since of the storage collection is downgraded to the empty frontier.
6. The finalizable shard is added to `StorageCollectionsImp`.
7. A background task finalizes the shard.
8. A background task removes the finalizable shard from `StorageCollectionsImp`.
9. A background task inserts a finalized shard into `StorageCollectionsImp`.
10. The next time any DDL is ran and a catalog transaction is going to commit, the unfinalized shard is removed from the txn.
3. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn.
12. The unfinalized shard is removed durably via committing the catalog txn.
13. The next time a storage collection is created or dropped (possibly even from the DDL in step 10?), the finalized shard is removed from `StorageCollectionsImp`.

Two important notes are:
- How all these fields are initialized on startup are completely different and I have not looked into it yet.
- There is a server configuration parameter that changes the behavior of all the above steps (`enable_storage_shard_finalization`), and as shown above can clearly cause inconsistencies.

An observation here is that the catalog state is set from an uncommitted transactions. If the transaction aborts then hopefully the catalog state is reverted? Or hopefully everything panics? Otherwise that could explain the inconsistency.

**Comment by aljoscha** [comment] 2024-06-04 15:01
There is at least one other possible source of inconsistency that I know of:
- `prepare_state` adds finalizable shards to durable state: https://github.com/MaterializeInc/materialize/blob/main/src/storage-client/src/storage_collections.rs#L1256
- Finalizable shards are added to the in-memory list of finalizable shards without consulting durable state: https://github.com/MaterializeInc/materialize/blob/main/src/storage-client/src/storage_collections.rs#L1256

I don't like this at all, and it's something i wanted to fix once the dust around shard finalization has settled some more. But maybe now's a good time to do it. It _does_ require some elbow grease to get all the plumbing right.

**Comment by jkosh44** [comment] 2024-06-04 19:42
https://github.com/MaterializeInc/materialize/pull/27436 fixed the two repros that I mentioned above. I'm going to run Nightlies a bunch and see if I can repro the issue.

**Comment by jkosh44** [comment] 2024-06-04 20:31
> There is at least one other possible source of inconsistency that I know of:
> 
>     * `prepare_state` adds finalizable shards to durable state: https://github.com/MaterializeInc/materialize/blob/main/src/storage-client/src/storage_collections.rs#L1256
> 
>     * Finalizable shards are added to the in-memory list of finalizable shards without consulting durable state: https://github.com/MaterializeInc/materialize/blob/main/src/storage-client/src/storage_collections.rs#L2283
> 
> 
> I don't like this at all, and it's something i wanted to fix once the dust around shard finalization has settled some more. But maybe now's a good time to do it. It _does_ require some elbow grease to get all the plumbing right.
> 
> edit: fix links

Agreed, this should be fixed. Unfortunately for me, I don't think this could lead to the in-memory and durable catalog state diverging.

**Comment by jkosh44** [comment] 2024-06-06 14:00
After many attempts, it still repros: https://buildkite.com/materialize/nightly/builds/7999

**Comment by jkosh44** [comment] 2024-06-17 14:28
> As per my best understanding, this is the lifecycle of an unfinalized shards.
> 
>   1. A user drops a storage collection.
> 
>   2. The unfinalized shard is added to a catalog txn.
> 
>   3. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn.
> 
>   4. The unfinalized shard is persisted durably via committing the catalog txn.
> 
>   5. The since of the storage collection is downgraded to the empty frontier.
> 
>   6. The finalizable shard is added to `StorageCollectionsImp`.
> 
>   7. A background task finalizes the shard.
> 
>   8. A background task removes the finalizable shard from `StorageCollectionsImp`.
> 
>   9. A background task inserts a finalized shard into `StorageCollectionsImp`.
> 
>   10. The next time any DDL is ran and a catalog transaction is going to commit, the unfinalized shard is removed from the txn.
> 
>   11. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn.
> 
>   12. The unfinalized shard is removed durably via committing the catalog txn.
> 
>   13. The next time a storage collection is created or dropped (possibly even from the DDL in step 10?), the finalized shard is removed from `StorageCollectionsImp`.

I may have had a breakthrough this morning on what's happening. First, here are the steps that Testdrive takes to compare the the in-memory catalog to the on-disk catalog.

1. Send an HTTP request to Materialize to get the catalog contents.
2. Materialize responds with a serialized version of the catalog it has in memory, let's call this `Memory`.
3. Connect to persist.
4. Read in the current durable catalog contents that exist in persist, let's call this `Disk`.
5. Compare the contents of `Memory` to `Disk`.

Another important piece of information is that there are at least one background processes that cause the Coordinator to execute a catalog transaction on some periodic schedule. One example of this is updating the storage usage tables.

Below I will show an interleaving of the steps from the lifecycle of unfinalized shards, which I'll prefix with `S`, and the steps from a Testdrive catalog comparison, which I'll prefix with `T`, that can result in the failure that we're seeing.

S1. A user drops a storage collection, `c`.
S2. The unfinalized shard, `c`, is added to a catalog txn.
S3. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn. 
S4. `c` is persisted durably via committing the catalog txn.
S5. The since of the storage collection is downgraded to the empty frontier.
S6. `c` is added to `StorageCollectionsImp`.

T1. Send an HTTP request to Materialize to get the catalog contents.
T2. Materialize responds with a serialized version of the catalog it has in memory, let's call this `Memory`. Importantly, this contains the shard `c` in the list of unfinalized shards.

S7. A background task finalizes the shard `c`.
S8. A background task removes the finalizable shard `c` from `StorageCollectionsImp`.
S9. A background task inserts the finalized shard `c` into `StorageCollectionsImp`.
S10. The next time any DDL is ran and a catalog transaction is going to commit, the unfinalized shard `c` is removed from the txn.
S11. The unfinalized shards in the in-memory catalog state is set equal to the unfinalized shards in the catalog txn.
S12. The unfinalized shard `c` is removed durably via committing the catalog txn.

T3. Connect to persist.
T4. Read in the current durable catalog contents that exist in persist, let's call this `Disk`. Importantly, this will not contain the shard `c` in the list of unfinalized shards.
T5. Compare the contents of `Memory` to `Disk`, which now fails.


If this is correct, then we should be able to reproduce by introducing an artificial delay between steps T2 and T3, and by reducing the storage usage collection interval. Additionally, this means that it's just a testing issue and not an issue in production.

**Comment by jkosh44** [comment] 2024-06-17 15:14
In fact the issue does repro after applying the following diff to `main`

```
diff --git a/src/environmentd/src/bin/environmentd/main.rs b/src/environmentd/src/bin/environmentd/main.rs
index fe90ad0027..1373d2c11c 100644
--- a/src/environmentd/src/bin/environmentd/main.rs
+++ b/src/environmentd/src/bin/environmentd/main.rs
@@ -911,6 +911,7 @@ fn run(mut args: Args) -> Result<(), anyhow::Error> {
             persist_clients,
             metrics: Arc::new(mz_catalog::durable::Metrics::new(&metrics_registry)),
         };
+        args.storage_usage_collection_interval_sec = Duration::from_millis(500);
         listeners
             .serve(mz_environmentd::Config {
                 tls,
diff --git a/src/testdrive/src/action/consistency.rs b/src/testdrive/src/action/consistency.rs
index 417f5fdc27..55290626b0 100644
--- a/src/testdrive/src/action/consistency.rs
+++ b/src/testdrive/src/action/consistency.rs
@@ -174,6 +174,8 @@ async fn check_catalog_state(state: &State) -> Result<(), anyhow::Error> {
         return Ok(());
     };
 
+    tokio::time::sleep(Duration::from_secs(3)).await;
+
     // Load the on-disk catalog and dump its state.
     let maybe_disk_catalog = state
         .with_catalog_copy(system_parameter_defaults, |catalog| catalog.state().clone())
```

when running the following Testdrive snippet:

```
> CREATE SCHEMA s

> CREATE TABLE s.t1 (a INT);
> CREATE TABLE s.t2 (a INT);
> CREATE TABLE s.t3 (a INT);
> CREATE TABLE s.t4 (a INT);
> CREATE TABLE s.t5 (a INT);
> CREATE TABLE s.t6 (a INT);
> CREATE TABLE s.t7 (a INT);
> CREATE TABLE s.t8 (a INT);
> CREATE TABLE s.t9 (a INT);
> CREATE TABLE s.t10 (a INT);
> CREATE TABLE s.t11 (a INT);
> CREATE TABLE s.t12 (a INT);
> CREATE TABLE s.t13 (a INT);
> CREATE TABLE s.t14 (a INT);
> CREATE TABLE s.t15 (a INT);
> CREATE TABLE s.t16 (a INT);
> CREATE TABLE s.t17 (a INT);
> CREATE TABLE s.t18 (a INT);
> CREATE TABLE s.t19 (a INT);
> CREATE TABLE s.t20 (a INT);
> CREATE TABLE s.t21 (a INT);
> CREATE TABLE s.t22 (a INT);
> CREATE TABLE s.t23 (a INT);
> CREATE TABLE s.t24 (a INT);
> CREATE TABLE s.t25 (a INT);

> DROP SCHEMA s CASCADE

```

with the following error:

```
^^^ +++
error: catalog inconsistency: catalog state

Caused by:
    the in-memory state of the catalog does not match its on-disk state:
    @@ -310639,127 +310639,101 @@
           "s467": "s2f687fff-082f-4162-834b-2a5fbcf50be7",
           "s468": "s1abb5abb-e6ea-4860-88d3-b9ed957af175",
           "s469": "sa3bc7576-728a-40d1-a84c-ffcdaaa96ffc",
           "s470": "s3c08f6b4-faa8-4b0b-bf84-ebeb38f28940",
           "s471": "sd7c38458-1270-4ec4-9bda-4a302544cc7b",
           "s472": "s5455459d-fd06-4d20-902c-5676435191bc",
           "s473": "sfd39575c-40da-4951-ab20-94a332a5fe16",
           "s474": "scfe4bde0-0421-48bb-aa16-cfc38254c957",
           "s475": "s47359604-0ac2-4db9-b6ce-b51eb15eb87b",
           "s476": "s2b748804-a9dc-471d-a509-f888d6fb938d",
           "s477": "s4d2cce7f-7fcc-4016-913e-85809ef1d2d4",
           "s478": "scfe2d686-d32d-46f1-b0f7-653335d5c2c0",
           "s479": "s3d0fc0f7-5142-44ce-a551-13e08426317b",
           "s480": "s6db7d521-de2b-4f88-b83b-07e5838acb95",
           "s481": "s5932cce6-ad36-452e-aec3-cdf46403b9f0",
           "s482": "s5f2a0d9d-2dec-47b9-af19-c5275ae0ad4a",
           "s483": "s94c6497f-735a-4315-8384-c6413f8f2e07",
           "s484": "see9bc355-20d7-4755-a5d3-8abf2d684264",
           "s485": "s7348ec45-b8af-4b57-b287-bf25ffc30adf",
           "s486": "s06f80491-57fe-4c20-ae81-ba6e1c5f83a7",
           "s487": "sa066eb20-c71c-4e32-a430-987de95da7bb",
           "s488": "sa4ac83ec-6d12-47a5-bf9c-5b2834d0a4d5",
           "s489": "s4b2f6fb9-986d-40e7-bc7b-5b3886678778",
           "s490": "s494fc452-3876-49e8-8f7c-025c9ad2606b",
           "s491": "sdb7bcc3f-a6f2-4900-bc07-578e570eaee3",
           "s492": "sc5f2e7a5-ab62-49f9-913b-7ee82ac35eb9",
           "s493": "s0d7b28b9-af29-4b08-a0d4-0bca7a0b3ff2",
           "s494": "s259f3b61-ede4-4d30-99d9-e38d6a1131ec",
           "s495": "se93207c8-08ba-4421-af76-b5da6ed69084",
           "s496": "s33431169-0293-4243-a0de-c417ce45ada3",
           "s631": "sb4f02bba-f03a-46e5-a4dc-650ba7018702",
           "s633": "sa8ddb38d-4c67-4126-8f68-8e31dc4ff918",
           "s634": "sd973b1ca-212a-4477-ab66-93959e614a73",
           "s636": "s5f2991b7-45ff-4b81-abbb-949822c955ae",
           "s638": "s5293b4fe-32fa-468d-ac14-829dd24bb698",
           "s639": "sf70f0cca-31ab-4cb0-979c-c6c34eecd4dc",
           "s640": "s8b7fe9cc-39bc-40ab-a530-de0d09471014",
           "s651": "s29c1edd0-b523-4f0b-8f69-15611c2d2f93",
           "s652": "s455c5b40-64be-4a56-9c42-6cf317791c20",
           "s653": "s8602f789-9962-45c3-a82e-9ada3a9b61e3",
           "s654": "s47e7f7a9-b4b7-4e86-a684-aac6c8ce7618",
           "s662": "sf2393495-f35c-4814-8f73-0e872d2f911b",
           "s664": "s6880e7b0-c533-42f3-a3e9-3a9f96e831ff",
           "s665": "s4e753450-b4a2-4cca-8d8c-d005758ea1db",
           "s666": "sd5076c52-351c-44f9-bd3e-805476263b73",
           "s667": "s5e6d5e7d-489e-43cd-ba05-6b9c9118acfb",
           "s673": "s306da806-3266-488d-b947-8b6a59ffdf11",
           "s674": "sd6c457ea-c196-450d-8db4-8fc962d45dbd",
           "s712": "s33ac1aa5-3d45-4607-b98b-6f2b4c739097"
         },
    -    "unfinalized_shards": [
    -      "s079cff86-9654-4fe7-bc06-f9b05c1275bd",
    -      "s24276249-613b-45a4-b767-9fe07ba9d573",
    -      "s2498b588-3805-4c3b-9482-1f5dde965834",
    -      "s2f9a6d7a-78b6-4773-8ff7-46713e0e2009",
    -      "s311a4edb-0626-413b-a6db-b1e20a00420e",
    -      "s3f469b31-1c0b-4563-9f03-6b78f5cf96c4",
    -      "s5bec47b6-31f8-41da-a809-6256bb5bd754",
    -      "s658a726a-eb83-4410-a16f-9fce9bac6192",
    -      "s65bc24d0-3c33-43b2-a1d7-d6431ff4718e",
    -      "s76b3b009-e662-46f0-9c98-87cc68629981",
    -      "s79163414-6173-42cd-b0ae-2e776826adc6",
    -      "s7a530742-c9bc-4fc5-b39c-8447175df32e",
    -      "s7cf4d58a-320e-416f-94d4-0fde3c3318f1",
    -      "s83c8f951-b184-4873-8c4a-4e59e4d9ef44",
    -      "s9c651aef-7e8f-481f-b159-6dd4d56139ef",
    -      "saaa8be11-a672-42cd-9d89-99be07858d4a",
    -      "sbcfa31b3-325c-4e6d-bc80-62d8d4975379",
    -      "sc9c6d371-345d-47a3-9193-7718413c7572",
    -      "sda727406-fce5-47bd-8835-1312bd662b45",
    -      "sdd0dfdac-43c1-4bb2-a61b-a63b5b06c0b9",
    -      "se84de7d2-1479-4c16-a8e2-25d001cb5dbc",
    -      "se94a9110-f7a3-42e9-ae04-dc9cee5b7275",
    -      "sf5bd9d56-c2e5-430c-99a1-75a0aeba433a",
    -      "sf9a44ffd-cce6-43d7-9fe0-39b070b00417",
    -      "sfa3df589-00f7-4424-aa0b-6faaff9fb72a"
    -    ]
    +    "unfinalized_shards": []
       },
       "system_parameter_defaults": {
         "DateStyle": "ISO, MDY",
         "IntervalStyle": "postgres",
         "TimeZone": "UTC",
         "allow_real_time_recency": "on",
         "allow_user_sessions": "on",
         "allowed_cluster_replica_sizes": "",
         "application_name": "",
         "arrangement_exert_proportionality": "16",
         "client_encoding": "UTF8",
         "client_min_messages": "notice",
         "cluster": "quickstart",
         "cluster_always_use_disk": "on",
         "cluster_check_scheduling_policies_interval": "3 s",
         "cluster_enable_topology_spread": "on",
         "cluster_multi_process_replica_az_affinity_weight": "100",
         "cluster_replica": "",
         "cluster_security_context_enabled": "on",
         "cluster_soften_az_affinity": "off",
         "cluster_soften_az_affinity_weight": "100",
         "cluster_soften_replication_anti_affinity": "off",
         "cluster_soften_replication_anti_affinity_weight": "100",
         "cluster_topology_spread_ignore_non_singular_scale": "on",
         "cluster_topology_spread_max_skew": "1",
         "cluster_topology_spread_soft": "off",
         "compute_dataflow_max_inflight_bytes": "134217728",
         "compute_dataflow_max_inflight_bytes_cc": "",
         "compute_hydration_concurrency": "2",
         "compute_persist_sink_obey_read_only": "on",
         "coord_slow_message_warn_threshold": "30 s",
         "copy_to_s3_arrow_builder_buffer_ratio": "150",
         "copy_to_s3_multipart_part_size_bytes": "8388608",
         "copy_to_s3_parquet_row_group_file_ratio": "20",
         "crdb_connect_timeout": "5 s",
         "crdb_tcp_user_timeout": "30 s",
         "database": "materialize",
         "disk_cluster_replicas_default": "on",
         "enable_alter_set_cluster": "off",
         "enable_alter_swap": "on",
         "enable_binary_date_bin": "off",
         "enable_cardinality_estimates": "off",
         "enable_cluster_schedule_refresh": "on",
         "enable_columnation_lgalloc": "on",
         "enable_comment": "on",
         "enable_compute_chunked_stack": "on",
         "enable_connection_validation_syntax": "on",
         "enable_consolidate_after_union_negate": "on",
         "enable_copy_to_expr": "on",
         "enable_create_sink_denylist_with_options": "off",

Stack backtrace:
   0: anyhow::__private::format_err
   1: mz_testdrive::action::consistency::check_catalog_state::{closure#0}
   2: mz_testdrive::action::consistency::run_consistency_checks::{closure#0}
   3: mz_testdrive::run_line_reader::{closure#0}
   4: mz_testdrive::run_string::{closure#0}
   5: mz_testdrive::run_file::{closure#0}
   6: testdrive::main::{closure#0}
   7: <tracing::instrument::Instrumented<testdrive::main::{closure#0}> as core::future::future::Future>::poll
   8: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>::{closure#0}
   9: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>
  10: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>
  11: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>::{closure#0}
  12: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>::{closure#0}, ()>
  13: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>
  14: <tokio::runtime::runtime::Runtime>::block_on::<testdrive::main::{closure#0}>
  15: testdrive::main
  16: <fn() as core::ops::function::FnOnce<()>>::call_once
  17: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  18: std::rt::lang_start::<()>::{closure#0}
  19: std::rt::lang_start_internal
  20: std::rt::lang_start::<()>
  21: main
  22: <unknown>
  23: __libc_start_main
  24: _start
```

I'm not sure yet what the right fix is. We could of course just ignore `unfinalized_shards` in our catalog consistency check, but in theory the in-memory and durable copy should match when viewed at exactly the same time. If this error starts happening much more frequently, that would be a red flag that some new real issue might be happening.

**Comment by jkosh44** [comment] 2024-06-17 17:57
> I'm not sure yet what the right fix is. We could of course just ignore `unfinalized_shards` in our catalog consistency check, but in theory the in-memory and durable copy should match when viewed at exactly the same time. If this error starts happening much more frequently, that would be a red flag that some new real issue might be happening.

I've thought about this for a bit. I think the only two options are:

- Redesign `StorageMetadata`.
- Ignore `unfinalized_shards` in the Testdrive catalog consistency check.

I'm not prepared to redesign `StorageMetadata`, so I'm going to start ignoring `unfinalized_shards` in the Testdrive catalog consistency checks.

**Comment by aljoscha** [comment] 2024-06-18 08:06
Nice find! Taking a step back: shouldn't we always expect inconsistencies? Because we don't atomically pull the in-memory copy and the copy from persist. So there's always the possibility of changes sneaking in.

**Comment by jkosh44** [comment] 2024-06-18 14:00
> Nice find! Taking a step back: shouldn't we always expect inconsistencies? Because we don't atomically pull the in-memory copy and the copy from persist. So there's always the possibility of changes sneaking in.

That would be true for any field that may be updated by background processes. It just so happens that no other field is updated by a background process, so we shouldn't have to worry about this for other fields.

**Closed** 2024-06-18 19:43 UTC
Labels: C-bug, T-correctness, ci-flake
