### ISSUE TITLE
Decimals should be allowed to be used in `VALUES` statements where floats are expected.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4043] opened 2020-08-25 18:01 UTC
```
materialize=> create table t (a float);
CREATE TABLE
materialize=> insert into t values (1234.0);
ERROR:  expected type f64 for column a, found decimal(38, 1)
```

Works in postgres.

**Comment by cuongdo** [comment] 2020-08-26 10:38
@benesch how do you feel about this as a starter project?

**Comment by benesch** [comment] 2020-08-26 18:09
Too hard, I'm afraid. Plenty of unknowns here—I have no idea how
complicated the solution is going to be.

**Comment by benesch** [comment] 2020-10-06 14:19
Also, duplicate of #2852.

**Closed by benesch** 2020-10-06 14:19 UTC
Labels: C-bug

**Comment by ruchirK** [comment] 2020-10-26 23:51
Posting here even though the issue is closed - I ran into this today when trying to insert non-integer numbers into a table. In addition to the error Brennan ran into when the column type is `float`, I ran into similar errors when the column's type was `decimal`

```
materialize=> CREATE TABLE test(a NUMERIC);
CREATE TABLE
materialize=> INSERT INTO test VALUES(5.555);
ERROR:  expected type decimal(38, 0) for column a, found decimal(38, 3)
materialize=> INSERT INTO test VALUES(5.555::decimal);
INSERT 0 1
```

As far as I can tell, the only way to insert a non-integer number into a table right now is to explicitly cast it to the correct type. Is that accurate or am I misunderstanding something? And if that is the way it is for now - should I add a comment indicating that is the case in the docs?

**Comment by benesch** [comment] 2020-10-26 23:58
It’s only closed because it’s a duplicate of a more general problem! We
still would very much like to fix this.

Your analysis of the situation is correct. I think I’d rather invest energy
in fixing this though, rather than trying to explain the current buggy
behavior.

**Comment by ruchirK** [comment] 2020-10-27 00:07
Yup yup sorry I only meant I'm posting here instead of in the issue we left open because this has more specific context.

> I think I’d rather invest energy in fixing this though, rather than trying to explain the current buggy behavior.

I think that's fair if we can do a quick fix but your earlier comments made it seem like it might be time consuming fix? FWIW I did spend (perhaps embarrassingly) 30 or so minutes trying to find a combination that would work partially because the current create table / insert pages already have lists of restrictions so I erroneously assumed that those were the _only_ restrictions and that most other simple behavior would just be correct. I could see users getting tripped up in a similar way.

**Comment by benesch** [comment] 2020-11-03 14:28
Yep, totally understood. Priority has been bumped up accordingly: #4683.
