### ISSUE TITLE
Metabase can't render "interval" result type

### ISSUE THREAD

**Issue by antifuchs** [MaterializeInc/materialize#7188] opened 2021-06-25 14:19 UTC
### What version of Materialize are you using?

0.8.0 and before

### How did you install Materialize?

Cloud.

### What was the issue?

When connecting with metabase, running 

```sql
SELECT now() - '1 day'::interval;
```

renders an interval, but:

```sql
select now()-now();
```

results in the error `ERROR: unknown catalog item 'regproc'`. This works on the psql command line - a query result there renders in text correctly.

You can work around by using `select (now()-now())::text;` instead, but this is a thing that I'm pretty sure works with a real postgresql instance, so we should support it too.

### Is the issue reproducible? If so, please provide reproduction instructions.

I could repro (and be confused by) this issue on metabase connected to 0.7.x materialized's.

### Please attach any applicable log files.

n/a.

**Comment by benesch** [comment] 2021-08-19 03:13
Retroactive duplicate of #7790.

**Closed by benesch** 2021-08-19 03:13 UTC
Labels: C-bug, bugfix-day
