### ISSUE TITLE
count(*) on join overflows without error

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22234] opened 2023-10-06 14:19 UTC
### What version of Materialize are you using?

main

### What is the issue?

```
materialize=> create table t1 (c int);
CREATE TABLE
Time: 277.621 ms
materialize=> insert into t1 select generate_series(1, 1000000);
INSERT 0 1000000
Time: 1735.507 ms (00:01.736)
materialize=> select count(*) from t1;
  count
---------
 1000000
(1 row)

Time: 465.510 ms
materialize=> select count(*) from t1, t1 as t2;
     count
---------------
 1000000000000
(1 row)

Time: 390.299 ms
materialize=> select count(*) from t1, t1 as t2, t1 as t3;
        count
---------------------
 1000000000000000000
(1 row)

Time: 395.606 ms
materialize=> select count(*) from t1, t1 as t2, t1 as t3, t1 as t4;
        count
---------------------
 2003764205206896640
(1 row)

Time: 399.911 ms
```

The last result is wrong. When our calculation overflows and we can't represent the size, we should be returning an error instead of a wrong result. Proof via Python that this is the result of a 64bit uint overflow:
```
>>> (1000000**4)%(2**64)
2003764205206896640
```

Explain plan:
```
materialize=> explain select count(*) from t1, t1 as t2, t1 as t3, t1 as t4;
               Optimized Plan
---------------------------------------------
 Explained Query:                           +
   Return                                   +
     Union                                  +
       Get l1                               +
       Map (0)                              +
         Union                              +
           Negate                           +
             Project ()                     +
               Get l1                       +
           Constant                         +
             - ()                           +
   With                                     +
     cte l1 =                               +
       Reduce aggregates=[count(*)]         +
         CrossJoin type=delta               +
           Get l0                           +
           Get l0                           +
           Get l0                           +
           Get l0                           +
     cte l0 =                               +
       ArrangeBy keys=[[]]                  +
         Project ()                         +
           ReadStorage materialize.public.t1+

(1 row)

Time: 24.236 ms
```

**Comment by vmarcos** [comment] 2023-10-06 15:44
This is another way to trigger the behavior seen in https://github.com/MaterializeInc/materialize/issues/18738 and also in https://github.com/MaterializeInc/materialize/issues/18645#issuecomment-1722977609.

I'd suggest closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/18738. Please feel free to reopen if there is something about this repro that we'd like to address differently.

**Closed by vmarcos** 2023-10-06 15:44 UTC
Labels: C-bug, T-correctness
