### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:257:34

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17993] opened 2023-03-07 18:35 UTC
### What version of Materialize are you using?

v0.46.0-dev (534cdc4db)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> CREATE SOURCE tpch
    FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
    FOR ALL TABLES
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> CREATE SOURCE auction
    FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
    FOR ALL TABLES
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> CREATE SOURCE counter
    FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> select(select "counter" from counter limit 1) from lineitem where
    cast(nullif(case when cast(null as float4) >
                    (select 1)then cast(mz_uptime() as interval) else cast(
                        mz_uptime() as interval) end,
                (select "delay" from mz_internal.mz_worker_compute_delays))
             as interval) = case when
    EXISTS(select
           "l_returnflag" where(select "nspacl" from pg_namespace limit 1) <
           (select "brokers" from mz_kafka_connections)) then
    cast(nullif((select "duration" from mz_internal.mz_peek_durations),
                case when(select "argument_type_ids" from mz_functions) <=
                    (select "key" from mz_internal.mz_show_indexes)
                        then cast(null as interval) end)
             as interval) else cast(nullif((select "duration" from mz_internal
                                                .mz_peek_durations limit 1),
                                           case when(select
                                                     "argument_type_ids" from
                                                         mz_functions) <=
                                               (select "key" from mz_internal
                                                    .mz_show_indexes)
                                                   then cast(null as interval)
                                                       end) as interval) end;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

ci-regexp: Expression in join plan is not bound at time of use

### Relevant log output

```source
thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:257:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:1926:5
   5: core::option::Option<T>::expect
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:786:21
   6: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from::{{closure}}::{{closure}}
             at ./src/compute-client/src/plan/join/linear_join.rs:257:34
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:2438:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/map.rs:124:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:837:9
  11: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/vec/mod.rs:2856:17
  12: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/vec/spec_extend.rs:26:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/vec/mod.rs:2724:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:1860:9
  17: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from::{{closure}}
             at ./src/compute-client/src/plan/join/linear_join.rs:262:26
  18: core::option::Option<T>::unwrap_or_else
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:873:21
  19: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from
             at ./src/compute-client/src/plan/join/linear_join.rs:242:17
  20: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1222:46
  21: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  22: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  23: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  24: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  25: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  26: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  30: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  31: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  32: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  33: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  34: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  35: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  36: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  37: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  38: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  39: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  40: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  41: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  42: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  43: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  44: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  45: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  46: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  47: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  48: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  49: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  50: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  51: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  52: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  53: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  54: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  55: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1064:38
  56: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:952:38
  57: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  58: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  59: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./src/compute-client/src/plan/mod.rs:952:9
  60: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:935:9
  61: mz_compute_client::plan::Plan<T>::finalize_dataflow
             at ./src/compute-client/src/plan/mod.rs:1612:32
  62: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::finalize_dataflow
             at ./src/adapter/src/coord/dataflows.rs:265:9
  63: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator>::create_peek_plan::{{closure}}
             at ./src/adapter/src/coord/peek.rs:271:32
  64: core::option::Option<T>::map_or_else
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:1066:21
  65: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator>::create_peek_plan
             at ./src/adapter/src/coord/peek.rs:268:25
  66: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer.rs:2588:25
  67: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2380:29
  68: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2362:5
  69: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2266:21
  70: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2189:5
  71: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:315:60
  72: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:119:5
  73: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:504:78
  74: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:307:5
  75: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:304:61
  76: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:263:5
  77: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  78: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:68:21
  79: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  80: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  81: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  82: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  83: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  84: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  85: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  86: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  87: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  88: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  89: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```
Explain plan:
```
                                      Optimized Plan
-------------------------------------------------------------------------------------------
 Explained Query:                                                                         +
   Return                                                                                 +
     Project (#2)                                                                         +
       Join on=(#0 = #1) type=differential                                                +
         ArrangeBy keys=[[#0]]                                                            +
           Project (#1)                                                                   +
             Filter (#1) IS NOT NULL AND ((#0) IS NULL OR (false = (#0 = #1)))            +
               Map (mz_uptime())                                                          +
                 CrossJoin type=differential                                              +
                   ArrangeBy keys=[[]]                                                    +
                     Project ()                                                           +
                       Get materialize.public.lineitem                                    +
                   ArrangeBy keys=[[]]                                                    +
                     Union                                                                +
                       Get l2                                                             +
                       Map (null)                                                         +
                         Union                                                            +
                           Negate                                                         +
                             Distinct                                                     +
                               Project ()                                                 +
                                 Get l2                                                   +
                           Constant                                                       +
                             - ()                                                         +
         ArrangeBy keys=[[]]                                                              +
           Union                                                                          +
             Get l4                                                                       +
             Negate                                                                       +
               Distinct                                                                   +
                 Get l4                                                                   +
             Constant                                                                     +
               - ()                                                                       +
         ArrangeBy keys=[[]]                                                              +
           Union                                                                          +
             Get l5                                                                       +
             Negate                                                                       +
               Distinct                                                                   +
                 Get l5                                                                   +
             Constant                                                                     +
               - ()                                                                       +
         ArrangeBy keys=[[]]                                                              +
           TopK limit=1 monotonic=false                                                   +
             Project (#4)                                                                 +
               Map ((00:00:00.000001 * numeric_to_double((bigint_to_numeric(#1) / 1000))))+
                 Get mz_internal.mz_raw_peek_durations                                    +
         ArrangeBy keys=[[]]                                                              +
           Union                                                                          +
             Get l6                                                                       +
             Map (null)                                                                   +
               Union                                                                      +
                 Negate                                                                   +
                   Project ()                                                             +
                     Get l6                                                               +
                 Constant                                                                 +
                   - ()                                                                   +
   With                                                                                   +
     cte l6 =                                                                             +
       TopK limit=1 monotonic=false                                                       +
         Get materialize.public.counter                                                   +
     cte l5 =                                                                             +
       Union                                                                              +
         Get l1                                                                           +
         Project ()                                                                       +
           Filter (#0 > 1)                                                                +
             Reduce aggregates=[count(*)]                                                 +
               Get l1                                                                     +
     cte l4 =                                                                             +
       Union                                                                              +
         Get l3                                                                           +
         Project ()                                                                       +
           Filter (#0 > 1)                                                                +
             Reduce aggregates=[count(*)]                                                 +
               Get l3                                                                     +
     cte l3 =                                                                             +
       Project ()                                                                         +
         Get mz_catalog.mz_functions                                                      +
     cte l2 =                                                                             +
       Union                                                                              +
         Project (#6)                                                                     +
           Map ((00:00:00.000001 * numeric_to_double((bigint_to_numeric(#3) / 1000))))    +
             Get mz_internal.mz_raw_worker_compute_delays                                 +
         Map (error("more than one record produced in subquery"))                         +
           Project ()                                                                     +
             Filter (#0 > 1)                                                              +
               Reduce aggregates=[count(*)]                                               +
                 Project ()                                                               +
                   Get mz_internal.mz_raw_worker_compute_delays                           +
     cte l1 =                                                                             +
       Project ()                                                                         +
         Join on=(#1 = #3 AND #2 = #4) type=differential                                  +
           ArrangeBy keys=[[#1]]                                                          +
             Project (#0, #3, #4)                                                         +
               Get mz_catalog.mz_indexes                                                  +
           ArrangeBy keys=[[#0]]                                                          +
             Union                                                                        +
               Get l0                                                                     +
               Project (#0)                                                               +
                 Get mz_catalog.mz_sinks                                                  +
               Project (#0)                                                               +
                 Join on=(#1 = #2) type=differential                                      +
                   ArrangeBy keys=[[#1]]                                                  +
                     Project (#0, #3)                                                     +
                       Get mz_catalog.mz_indexes                                          +
                   ArrangeBy keys=[[#0]]                                                  +
                     Get l0                                                               +
               Project (#0)                                                               +
                 Get mz_catalog.mz_connections                                            +
               Project (#0)                                                               +
                 Get mz_catalog.mz_types                                                  +
               Project (#0)                                                               +
                 Get mz_catalog.mz_functions                                              +
               Project (#0)                                                               +
                 Get mz_catalog.mz_secrets                                                +
           ArrangeBy keys=[[#0]]                                                          +
             Project (#0)                                                                 +
               Get mz_catalog.mz_clusters                                                 +
     cte l0 =                                                                             +
       Union                                                                              +
         Project (#0)                                                                     +
           Get mz_catalog.mz_tables                                                       +
         Project (#0)                                                                     +
           Get mz_catalog.mz_sources                                                      +
         Project (#0)                                                                     +
           Get mz_catalog.mz_views                                                        +
         Project (#0)                                                                     +
           Get mz_catalog.mz_materialized_views                                           +
                                                                                          +
 Used Indexes:                                                                            +
   - mz_internal.mz_raw_peek_durations_u1_primary_idx                                     +
   - mz_internal.mz_raw_worker_compute_delays_u1_primary_idx                              +

(1 row)
```

**Comment by ggevay** [comment] 2023-03-09 16:11
There seem to be two bugs:
1. The optimizer pipeline for EXPLAINing is somehow behaving differently from the optimizer pipeline that runs for normal query execution. EXPLAIN should throw the exact same error (and then one would need to use EXPLAIN BROKEN). I don't know why this is.
2. The problem is that the `ColumnKnowledge` + `FoldConstants` that is in the same fixpoint loop with `JoinImplementation` invalidates the join plan. Before https://github.com/MaterializeInc/materialize/pull/17708, `JoinImplementation` would just throw away the old plan and come up with a new one, but it's not doing this now, because it sees we already have a join plan, it just doesn't realize it that it became invalid in the meantime.

We should definitely investigate 1., because it might potentially mislead us in many other situations as well, and we won't even know it.

Unfortunately, I can't rule it out that 2. can cause incorrect results in some cases rather than a crash, so we should work also on this now.

I'm not sure how to fix 2. I think I'm going to try to move `JoinImplementation` to after that fixpoint loop into its own fixpoint loop. Then we might lose some optimizations that can happen after `JoinImplementation`, but I don't have any other idea at the moment to fix this. I'm gonna run an slt rewrite now to see how much optimization would we lose. I have to admit that I don't understand what it is that those transform cannot do before `JoinImplementation` that they are able to do after it.

**Comment by ggevay** [comment] 2023-03-09 16:21
There seems to be more and more evidence that `JoinImplementation` should be part of the MIR-to-LIR lowering, rather than its own MIR transform. Moving it out from that fixpoint loop to somewhere after that fixpoint loop would be a first step of moving it into the lowering. So I'd say that unless this slt runs finds some very bad plan regressions, we should go ahead with this.

**Comment by ggevay** [comment] 2023-03-09 19:53
There are some plan regressions, but they are all minor: Some redundant predicates appeared in some filters. I have an idea for a not too complicated fix, I'll implement it tomorrow.

**Comment by ggevay** [comment] 2023-03-10 15:24
My fix is fixing only some of the plan regressions, but I don't know of any easy fix for the remaining ones, and the regressions are minor, so I'll go ahead and open a PR. For later, I opened an issue with an idea how to fix the `IS NOT NULL` regressions by making `ColumnKnowledge` smarter:
https://github.com/MaterializeInc/materialize/issues/18051
(This idea would also make the IS NOT NULL removals more robust in some other situations, not just for these regressions.)

**Comment by ggevay** [comment] 2023-03-11 13:10
I just realized there is a simple explanation for 1. from above, i.e., why the optimizer pipeline for EXPLAINing is behaving differently from the optimizer pipeline that runs for normal query execution: It's not a bug, it's simply that the `mz_uptime()` function [is resolved when running a one-off select, but not resolved in an EXPLAIN](https://github.com/MaterializeInc/materialize/issues/18048%23issuecomment-1464071475).

**Closed** 2023-03-16 13:47 UTC
Labels: C-bug, A-optimization, A-COMPUTE

**Comment by ggevay** [comment] 2023-03-16 17:11
Fixed by https://github.com/MaterializeInc/materialize/pull/18054

(The fix introduced some minor plan regressions, which should be fixed later by https://github.com/MaterializeInc/materialize/issues/18051)
