### ISSUE TITLE
librdkafka producer threads left behind after DROP SINK

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8573] opened 2021-10-07 07:11 UTC
### What version of Materialize are you using?

```
v0.9.6-dev (8c4d31411)
```

### What was the issue?

librdkafka threads are left behind after DROP SINK. This issue seems to be distinct from all the other bugs about kafka threads proliferating, as it is also reproducible with --workers 1 and with a bounded number of concurrently-existing topics. The sinks also need to be actively producing messages.

The issue is reproducible regardless of the reuse_topic setting.

All the threads left behind appear to be of the following two types:

```
Thread 404 (Thread 0x7f6dc36bf700 (LWP 1263306)):
#0  0x00007f6ead97caff in __GI___poll (fds=fds@entry=0x7f6e6969a098, nfds=2, timeout=1000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6ead999aa2 in __poll_chk (fds=fds@entry=0x7f6e6969a098, nfds=<optimized out>, timeout=<optimized out>, fdslen=fdslen@entry=16) at poll_chk.c:27
#2  0x0000562102b99712 in poll (__timeout=<optimized out>, __nfds=<optimized out>, __fds=0x7f6e6969a098) at /usr/include/x86_64-linux-gnu/bits/poll2.h:41
#3  rd_kafka_transport_poll (rktrans=0x7f6e6969a000, tmout=<optimized out>) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_transport.c:960
#4  0x0000562102b9977f in rd_kafka_transport_io_serve (rktrans=0x7f6e6969a000, timeout_ms=1000) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_transport.c:792
#5  0x0000562102b1660a in rd_kafka_broker_ops_io_serve (rkb=rkb@entry=0x7f6e6b6b1000, abs_timeout=21400986116309) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdtime.h:160
#6  0x0000562102b18207 in rd_kafka_broker_producer_serve (abs_timeout=21400986116309, rkb=0x7f6e6b6b1000) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_broker.c:3985
#7  rd_kafka_broker_serve (rkb=rkb@entry=0x7f6e6b6b1000, timeout_ms=<optimized out>, timeout_ms@entry=1000) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_broker.c:5078
#8  0x0000562102b1899d in rd_kafka_broker_thread_main (arg=0x7f6e6b6b1000) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_broker.c:5237
#9  0x00007f6eadbee6da in start_thread (arg=<optimized out>) at pthread_create.c:474
#10 0x00007f6ead989293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 403 (Thread 0x7f6dc38c0700 (LWP 1263305)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f6dc38bad40, clockid=<optimized out>, expected=0, futex_word=0x7f6e95dafad0) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7f6dc38bad40, clockid=<optimized out>, mutex=0x7f6e95dafa80, cond=0x7f6e95dafaa8) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x7f6e95dafaa8, mutex=0x7f6e95dafa80, abstime=0x7f6dc38bad40) at pthread_cond_wait.c:656
#3  0x00007f6eadbfbf2d in cnd_timedwait (cond=cond@entry=0x7f6e95dafaa8, mutex=mutex@entry=0x7f6e95dafa80, time_point=time_point@entry=0x7f6dc38bad40) at cnd_timedwait.c:25
#4  0x0000562102bdb097 in cnd_timedwait_abs (cnd=cnd@entry=0x7f6e95dafaa8, mtx=mtx@entry=0x7f6e95dafa80, tspec=tspec@entry=0x7f6dc38bad40) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/tinycthread_extra.c:103
#5  0x0000562102b6a6ef in rd_kafka_q_serve (rkq=0x7f6e95dafa80, timeout_ms=100, max_cnt=max_cnt@entry=0, cb_type=cb_type@entry=RD_KAFKA_Q_CB_CALLBACK, callback=callback@entry=0x562102af4aa0 <rd_kafka_poll_cb>, opaque=opaque@entry=0x0) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_queue.h:488
#6  0x0000562102af31b8 in rd_kafka_poll (rk=0x7f6e78618000, timeout_ms=<optimized out>) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka.c:3846
#7  0x0000562101940f53 in rdkafka::producer::base_producer::BaseProducer<C>::poll () at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/src/producer/base_producer.rs:298
#8  <rdkafka::producer::base_producer::ThreadedProducer<C> as rdkafka::config::FromClientConfigAndContext<C>>::from_config_and_context::{{closure}} () at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/src/producer/base_producer.rs:525
#9  std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125
#10 0x0000562101afb183 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481
#11 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347
#12 std::panicking::try::do_call () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401
#13 std::panicking::try () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365
#14 std::panic::catch_unwind () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434
#15 std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480
#16 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227
#17 0x00005621037acc47 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575
#18 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575
#19 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#20 0x00007f6eadbee609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f6ead989293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Pipe the attached workload [gh8573.sql.zip](https://github.com/MaterializeInc/materialize/files/7299638/gh8573.sql.zip)
through the psql client and let it run. The workload creates and drops sinks named s[1-10] and runs UPDATE against the base table so that the sink always has something to produce.

2. In a separate console observe a growing number of threads:

```
pstoev@Ubuntu-2004-focal-64-minimal:/proc/1253889/fd$ sudo gdb -p `pidof materialized` --batch --ex 'thread apply all bt' | grep 'Thread ' | wc
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/pstoev/ruchirK-fix-8315/target/release/materialized.
Use `info auto-load python-scripts [REGEXP]' to list them.
     57     345    3066
pstoev@Ubuntu-2004-focal-64-minimal:/proc/1253889/fd$ sudo gdb -p `pidof materialized` --batch --ex 'thread apply all bt' | grep 'Thread ' | wc
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/pstoev/ruchirK-fix-8315/target/release/materialized.
Use `info auto-load python-scripts [REGEXP]' to list them.
     92     555    4781
```

3. In the psql client, observe that there are never more than 10 sinks
```
materialize=> show sinks;
 name 
------
 s1
 s10
 s2
 s4
 s5
 s6
 s7
 s8
 s9
(9 rows)
```

There are no kafka sources in this workload.

**Comment by philip-stoev** [comment] 2022-02-23 13:47
The DROP SOURCE issue is a more recent problem so it has been given its own ticket #10843

**Comment by bkirwi** [comment] 2022-08-29 18:49
This might be mitigated by the fact that we now shut down the process when the sink is dropped. But still worth looking into!

**Comment by cjubb39** [comment] 2022-09-28 22:04
I ran what I hope was a similar test (since the syntax for creating sinks has changed) and didn't see a creep up in the number of threads while the sink was running.

I'm a little skeptical that the issue is actually gone and we actually shut down "properly" (because it appears to possibly be an rdkafka issue) but my inability to repro, our rewrite(s) of the sink in the past year, and Ben's point that we shut down the entire process when we drop a sink makes me want to close this out.

It's something we should be aware of if we one day combine multiple sinks onto a single storaged (but I'm not really sure how we're tracking things like that? @nmeagan11?)

**Closed** 2022-09-28 22:04 UTC
Labels: C-bug, A-sink, P2, A-STORAGE

**Comment by nmeagan11** [comment] 2022-09-29 18:45
> but I'm not really sure how we're tracking things like that?

For now, let's add it as a comment to #11503 for tracking and I'll parse it out during further planning.

**Comment by uce** [comment] 2022-10-04 19:12
@nmeagan11 I think it's actually better to leave the comment in https://github.com/MaterializeInc/cloud/issues/3642 since we're likely going to close out the Kafka sinks epic.
