### ISSUE TITLE
Wrong result with inner join, disjunction and workers > 1

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5774] opened 2021-02-16 12:08 UTC
### What version of Materialize are you using?

```
materialized v0.7.1-dev (f26c4dac1)
```

### What was the issue?

This is similar in outward appearances to #5622, but it does not require outer joins or multi-column indexes. Instead it seems to require a disjunction and multiple single-column indexes. The offending query is:

```
SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE c_acctbal  >=  1 OR o_orderDATE  > '1000-01-01'  AND c_custkey = 1;
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, pipe the attached script against ```-w 32``` :

```
cat q2.sql | psql -p 6875 -h 127.0.0.1 -U materialize | sort | uniq -c

...
    176     31
      1     62
...
```
In order words, 1 invocation of the query returned 2x rows the expected number. IF X=31 is the expected result, the anomalous result is either ```X+1```, ```2*X``` or ```2*X + 1```.

**Comment by philip-stoev** [comment] 2021-02-16 12:09
[5774.zip](https://github.com/MaterializeInc/materialize/files/5988421/5774.zip)

Attaching test case.

**Comment by frankmcsherry** [comment] 2021-02-16 19:49
Thanks! I'm going to take a look into this (and the other issues about join non-determinism) some time this week. I think it is mostly a matter of going in a dark room with no internet for a few hours.

**Comment by philip-stoev** [comment] 2021-02-18 10:41
#5794 unfortunately does not seem to fix this issue.

**Comment by frankmcsherry** [comment] 2021-02-18 12:09
Interesting. It could be unrelated then (I chased down the bug in the other issue, and haven't checked out what is going on here).

**Comment by frankmcsherry** [comment] 2021-02-18 12:31
I've seen the wrong answer now, but .. unfortunately it seems much less easy to reproduce than #5622. It is also likely unrelated because the explain plan indicates that we do not use a delta join plan:
```
materialize=> explain plan for SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE c_acctbal  >=  1 OR o_orderDATE  > '1000-01-01'  AND c_custkey = 1;
                         Optimized Plan                          
-----------------------------------------------------------------
 %0 =                                                           +
 | Get materialize.public.lineitem (u124)                       +
 | ArrangeBy (#0)                                               +
                                                                +
 %1 =                                                           +
 | Get materialize.public.orders (u121)                         +
 | ArrangeBy (#0)                                               +
                                                                +
 %2 =                                                           +
 | Get materialize.public.customer (u118)                       +
 | ArrangeBy (#0)                                               +
                                                                +
 %3 = Let l0 =                                                  +
 | Join %0 %1 %2 (= #0 #16) (= #17 #25)                         +
 | | implementation = Differential %0.(#0) %1.(#0) %2.(#0)      +
 | | demand = (#17, #20, #30)                                   +
 | Filter ((#30 >= 100dec) || ((#20 > 1000-01-01) && (#17 = 1)))+
 | Reduce group=()                                              +
 | | agg count(true)                                            +
                                                                +
 %4 =                                                           +
 | Get %3 (l0)                                                  +
 | Negate                                                       +
 | Project ()                                                   +
                                                                +
 %5 =                                                           +
 | Constant ()                                                  +
                                                                +
 %6 =                                                           +
 | Union %4 %5                                                  +
 | Map 0                                                        +
                                                                +
 %7 =                                                           +
 | Union %3 %6                                                  +
 
(1 row)
```

**Comment by frankmcsherry** [comment] 2021-02-18 12:39
@philip-stoev just checking something I noticed. I've only seen the repro twice now, and each time it has been only at the start of a run. As in, once the first result back, and once the second result back, but not (so far at least) later in the bulk of the 100+ query runs in the test file. Did you notice anything similar?

**Comment by frankmcsherry** [comment] 2021-02-18 13:21
@philip-stoev produced a minimized example, which repros most of the time for me with
```
cargo run --release -- -w64 --logging-granularity off
```
It is
```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE TABLE customer (
    c_custkey     integer
);
CREATE TABLE orders (
    o_orderkey       integer,
    o_custkey        integer NOT NULL,
    o_orderdate      DATE NOT NULL 
);
CREATE INDEX pk_orders_orderkey ON orders (o_orderkey);
CREATE TABLE lineitem (
    l_orderkey       integer NOT NULL
);
CREATE INDEX fk_lineitem_orderkey ON lineitem (l_orderkey ASC);

INSERT INTO "lineitem" VALUES (1);
INSERT INTO "orders" VALUES (1, 4, '1996-01-02'), (2, 8, '1996-12-01');
INSERT INTO "customer" VALUES (1), (4);

SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE  o_orderDATE  > '1000-01-01';
SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE  o_orderDATE  > '1000-01-01';
SELECT COUNT(*)
FROM lineitem
JOIN orders ON ( l_orderkey  = o_orderkey )
JOIN customer ON ( o_custkey = c_custkey  )
WHERE  o_orderDATE  > '1000-01-01';
```

**Comment by frankmcsherry** [comment] 2021-02-18 13:22
If you `SELECT *` the results, they look like
```
 l_orderkey | o_orderkey | o_custkey | o_orderdate | c_custkey 
------------+------------+-----------+-------------+-----------
          1 |          1 |         4 | 1996-01-02  |         4
          1 |          1 |         4 | 1996-01-02  |         4
(2 rows)

 l_orderkey | o_orderkey | o_custkey | o_orderdate | c_custkey 
------------+------------+-----------+-------------+-----------
          1 |          1 |         4 | 1996-01-02  |         4
(1 row)

 l_orderkey | o_orderkey | o_custkey | o_orderdate | c_custkey 
------------+------------+-----------+-------------+-----------
          1 |          1 |         4 | 1996-01-02  |         4
(1 row)
```
which seems like just straight up duplication (or perhaps a count being two rather than one).

Investigating!

**Comment by frankmcsherry** [comment] 2021-02-18 13:39
This also reproduces for me with just a single entry in `orders`, which makes it even more mysterious where the `2` comes from.
```
INSERT INTO "orders" VALUES (1, 4, '1996-01-02');
```

**Comment by frankmcsherry** [comment] 2021-02-18 13:41
The optimized plan, fwiw:
```
                      Optimized Plan                       
-----------------------------------------------------------
 %0 =                                                     +
 | Get materialize.public.lineitem (u363)                 +
 | ArrangeBy (#0)                                         +
                                                          +
 %1 =                                                     +
 | Get materialize.public.orders (u360)                   +
 | ArrangeBy (#0)                                         +
                                                          +
 %2 =                                                     +
 | Get materialize.public.customer (u358)                 +
 | ArrangeBy (#0)                                         +
                                                          +
 %3 =                                                     +
 | Join %0 %1 %2 (= #0 #1) (= #2 #4)                      +
 | | implementation = Differential %0.(#0) %1.(#0) %2.(#0)+
 | | demand = (#0, #2, #3)                                +
 | Filter (#3 > 1000-01-01)                               +
 | Project (#0, #0, #2, #3, #2)                           +
 
(1 row)

materialize=> 
```

**Comment by frankmcsherry** [comment] 2021-02-18 14:12
Status update (mainly through @philip-stoev): this reproduces with a single worker thread, on a very simple query.
```
materialize=> DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE TABLE customer (
    c_custkey     integer
);
CREATE TABLE orders (
    o_orderkey       integer,
    o_custkey        integer NOT NULL
);
CREATE INDEX pk_orders_orderkey ON orders (o_orderkey);
CREATE TABLE lineitem (
    l_orderkey       integer NOT NULL
);
CREATE INDEX fk_lineitem_orderkey ON lineitem (l_orderkey ASC);

INSERT INTO "lineitem" VALUES (1);
INSERT INTO "orders" VALUES (1, 4);
INSERT INTO "customer" VALUES (4);

SELECT * FROM lineitem, orders, customer WHERE l_orderkey  = o_orderkey AND o_custkey = c_custkey;
SELECT * FROM lineitem, orders, customer WHERE l_orderkey  = o_orderkey AND o_custkey = c_custkey;
SELECT * FROM lineitem, orders, customer WHERE l_orderkey  = o_orderkey AND o_custkey = c_custkey;
DROP SCHEMA
CREATE SCHEMA
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
INSERT 0 1
INSERT 0 1
INSERT 0 1
 l_orderkey | o_orderkey | o_custkey | c_custkey 
------------+------------+-----------+-----------
          1 |          1 |         4 |         4
          1 |          1 |         4 |         4
(2 rows)

 l_orderkey | o_orderkey | o_custkey | c_custkey 
------------+------------+-----------+-----------
          1 |          1 |         4 |         4
          1 |          1 |         4 |         4
(2 rows)

 l_orderkey | o_orderkey | o_custkey | c_custkey 
------------+------------+-----------+-----------
          1 |          1 |         4 |         4
(1 row)
```
Importantly, it seems to be related to being among the first few query executions. I don't see the error if run for longer. It shouldn't be that hard to chase down, but seems less likely to be a race condition in timely with only one worker.

**Comment by frankmcsherry** [comment] 2021-02-18 14:27
Current working theory: there is some logic glitch in the case of joining pre-arranged data (the faulty join is one that takes arrangements as both of its inputs) that only manifests very early in the life of an arrangement. The 3-way join is required in this case to force that implementation, as otherwise a delta join can be used.

**Comment by frankmcsherry** [comment] 2021-02-18 14:47
I'm getting close to the issue. It doesn't seem as much to be restricted to requiring two arrangement (you can remove the index on `lineitem` and the issue manifests). Rather, it seems to be an annoying detail about importing fast-forwarded arrangements.

We fast-forward arrangements on import so that, while they may have lots of times internal to them, we only want to see times "as of" some lower bound. All present times should be fast-forwarded to this time before being exposed to our logic, to avoid random noise in the output that could be incorrect (it should nontheless be correct once accumulated up to the lower bound, but times before that could .. go negative, be wrong, etc).

So, when we import arrangements we have a wrapper that advances all timestamps before presenting them outward. Unfortunately, that isn't good enough for joins that use shared arrangements, as to correctly avoid double-counting updates (e.g. responding to diffs on each input with a hit against each record) they slice the input arrangements by time. However, they only know about this wrt the original timestamps, as these are where the batch boundaries are. The batch boundaries likely don't make a clean cut at the user-chosen fast-forward time.

I'll ponder this a bit, but I think probably joins should be re-jiggered to line up on physical batching rather than logical time boundaries. Probably more lines to change than the previous timely fix.

**Comment by frankmcsherry** [comment] 2021-02-18 22:39
Quick status update here: I've found the issue, which is that DD's `join` gets confused by input arrangements that have been pre-physically merged. The issue was previously masked by a race that was not visibly wrong in most common scheduling patterns, but shows up more clearly with many workers. With some more invariant checking in place (`debug_assert`) it is pretty easy to catch `join` being confused and thinking that it can ask about the collection half-way through a range that "may have been" physically compacted (in reality it was not, and one method leaks that information out inappropriately).

**Comment by frankmcsherry** [comment] 2021-02-19 01:06
Well, https://github.com/TimelyDataflow/differential-dataflow/pull/307 fixes it for me locally. There is a write-up there about the issue, but essentially pre-compacted data going in to `join` resulted in enough weirdness that it made sense just to sort it out once and for all for now.

**Closed** 2021-02-24 11:54 UTC
Labels: C-bug
