### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'part upload task failed: task 8025228 was cancelled'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21744] opened 2023-09-14 13:47 UTC
### What version of Materialize are you using?

abde5a7618d56d39594c65230dde4c03d0419ffc

### What is the issue?

```
thread 'tokio-runtime-worker' panicked at 'part upload task failed: task 8025228 was cancelled', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e445cc3ea486f6c8-1/materialize/tests/src/persist-client/src/batch.rs:911:29
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <mz_persist_client::batch::BatchParts<mz_repr::timestamp::Timestamp>>::finish::{closure#0}::{closure#0}
   3: <mz_persist_client::batch::BatchParts<mz_repr::timestamp::Timestamp>>::finish::{closure#0}
   4: <mz_persist_client::batch::BatchBuilderInternal<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::finish::<mz_storage_types::sources::SourceData, ()>::{closure#0}::{closure#0}
   5: <mz_persist_client::batch::BatchBuilder<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::finish::{closure#0}
   6: <mz_persist_client::write::WriteHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::batch::<((mz_storage_types::sources::SourceData, ()), mz_repr::timestamp::Timestamp, i64), mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<mz_storage_client::client::Update>, <mz_storage_controller::persist_handles::PersistTableWriteWorker<_>>::new::{closure#1}::append_work<mz_repr::timestamp::Timestamp>::{closure#0}::{closure#0}>>::{closure#0}::{closure#0}
   7: <mz_persist_client::write::WriteHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::compare_and_append::<((mz_storage_types::sources::SourceData, ()), mz_repr::timestamp::Timestamp, i64), mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<mz_storage_client::client::Update>, <mz_storage_controller::persist_handles::PersistTableWriteWorker<_>>::new::{closure#1}::append_work<mz_repr::timestamp::Timestamp>::{closure#0}::{closure#0}>>::{closure#0}::{closure#0}
   8: <tracing::instrument::Instrumented<<mz_persist_client::write::WriteHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::compare_and_append<((mz_storage_types::sources::SourceData, ()), mz_repr::timestamp::Timestamp, i64), mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<mz_storage_client::client::Update>, <mz_storage_controller::persist_handles::PersistTableWriteWorker<_>>::new::{closure#1}::append_work<mz_repr::timestamp::Timestamp>::{closure#0}::{closure#0}>>::{closure#0}> as core::future::future::Future>::poll
   9: <futures_util::stream::futures_unordered::FuturesUnordered<<mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<_>>::new::{closure#1}::append_work<mz_repr::timestamp::Timestamp>::{closure#0}::{closure#1}> as futures_core::stream::Stream>::poll_next
  10: <mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<mz_repr::timestamp::Timestamp>>::new::{closure#1}
  11: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<<mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<mz_repr::timestamp::Timestamp>>::new::{closure#1}>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<<mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<mz_repr::timestamp::Timestamp>>::new::{closure#1}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}>
  12: <tokio::runtime::task::core::Core<<mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<mz_repr::timestamp::Timestamp>>::new::{closure#1}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
  13: <tokio::runtime::task::harness::Harness<<mz_storage_controller::persist_handles::PersistMonotonicWriteWorker<mz_repr::timestamp::Timestamp>>::new::{closure#1}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
  14: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
  15: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
  16: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::multi_thread::worker::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
  17: tokio::runtime::scheduler::multi_thread::worker::run
  18: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
  19: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
  20: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
  21: <tokio::runtime::blocking::pool::Inner>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in full SLT run: https://buildkite.com/materialize/sql-logic-tests/builds/5684#018a9376-79bd-4f05-a73b-8a8957ec1d56
I'm not sure yet if this is a flake or reproducible.

ci-regexp: part upload task failed: task .* was cancelled

**Comment by danhhz** [comment] 2023-09-14 14:11
@bkirwi I think this is the is_cancelled check that got removed in https://github.com/MaterializeInc/materialize/commit/be74489b23da2d15f0c899a2c53a222a81b3a189

**Comment by def-** [comment] 2023-09-14 17:51
This is unfortunately flaky, I was unable to reproduce it so far.

**Comment by ParkMyCar** [comment] 2023-09-20 21:25
I've been seeing this flake quite often now, here's an [example](https://buildkite.com/materialize/tests/builds/64123#018ab450-c21b-4de1-bee8-762131c2014f)

**Comment by danhhz** [comment] 2023-09-20 21:31
@bkirwi probably time to do something about this. not sure offhand what the fix is, but I'm pretty sure the issue is what I pointed out a few comments above

**Comment by jkosh44** [comment] 2023-09-20 22:56
Anecdotally, this happens almost every time I try to run a test locally.

**Comment by ggevay** [comment] 2023-09-21 13:27
Also happened here: https://buildkite.com/materialize/tests/builds/64164#018ab7c7-6348-4bb6-af54-9e7c33bea705

**Comment by jkosh44** [comment] 2023-09-21 14:03
> @bkirwi I think this is the is_cancelled check that got removed in [be74489](https://github.com/MaterializeInc/materialize/commit/be74489b23da2d15f0c899a2c53a222a81b3a189)

The following diff (which is a revert of that commit plus some conflict resolutions) causes the issue to go away completely

```
diff --git a/src/persist-client/src/batch.rs b/src/persist-client/src/batch.rs
index 541a980036..b52513abca 100644
--- a/src/persist-client/src/batch.rs
+++ b/src/persist-client/src/batch.rs
@@ -25,7 +25,7 @@ use mz_ore::cast::CastFrom;
 use mz_persist::indexed::columnar::{ColumnarRecords, ColumnarRecordsBuilder};
 use mz_persist::indexed::encoding::BlobTraceBatchPart;
 use mz_persist::location::{Atomicity, Blob};
-use mz_persist_types::stats::{trim_to_budget, truncate_bytes, TruncateBound, TRUNCATE_LEN};
+use mz_persist_types::stats::trim_to_budget;
 use mz_persist_types::{Codec, Codec64};
 use mz_proto::{RustType, TryFromProtoError};
 use mz_timely_util::order::Reverse;
@@ -410,7 +410,6 @@ where
             Arc::clone(&blob),
             isolated_runtime,
             &batch_write_metrics,
-            consolidate,
         );
         Self {
             lower,
@@ -732,10 +731,9 @@ pub(crate) struct BatchParts<T> {
     lower: Antichain<T>,
     blob: Arc<dyn Blob + Send + Sync>,
     isolated_runtime: Arc<IsolatedRuntime>,
-    writing_parts: VecDeque<JoinHandle<HollowBatchPart>>,
+    writing_parts: VecDeque<(PartialBatchKey, JoinHandle<(usize, Option<LazyPartStats>)>)>,
     finished_parts: Vec<HollowBatchPart>,
     batch_metrics: BatchWriteMetrics,
-    consolidated: bool,
 }
 
 impl<T: Timestamp + Codec64> BatchParts<T> {
@@ -748,7 +746,6 @@ impl<T: Timestamp + Codec64> BatchParts<T> {
         blob: Arc<dyn Blob + Send + Sync>,
         isolated_runtime: Arc<IsolatedRuntime>,
         batch_metrics: &BatchWriteMetrics,
-        consolidated: bool,
     ) -> Self {
         BatchParts {
             cfg,
@@ -761,7 +758,6 @@ impl<T: Timestamp + Codec64> BatchParts<T> {
             writing_parts: VecDeque::new(),
             finished_parts: Vec::new(),
             batch_metrics: batch_metrics.clone(),
-            consolidated,
         }
     }
 
@@ -784,7 +780,6 @@ impl<T: Timestamp + Codec64> BatchParts<T> {
         let stats_collection_enabled = self.cfg.stats_collection_enabled;
         let stats_budget = self.cfg.stats_budget;
         let schemas = schemas.clone();
-        let consolidated = self.consolidated;
         let untrimmable_columns = Arc::clone(&self.cfg.stats_untrimmable_columns);
 
         let write_span = debug_span!("batch::write_part", shard = %self.shard_id).or_current();
@@ -792,13 +787,6 @@ impl<T: Timestamp + Codec64> BatchParts<T> {
             || "batch::write_part",
             async move {
                 let goodbytes = updates.goodbytes();
-                let key_lower = if consolidated {
-                    updates.get(0).and_then(|((k, _), _, _)| {
-                        truncate_bytes(k, TRUNCATE_LEN, TruncateBound::Lower)
-                    })
-                } else {
-                    None
-                };
                 let batch = BlobTraceBatchPart {
                     desc,
                     updates: vec![updates],
@@ -872,45 +860,50 @@ impl<T: Timestamp + Codec64> BatchParts<T> {
                     }
                     stats
                 });
-
-                HollowBatchPart {
-                    key: partial_key,
-                    encoded_size_bytes: payload_len,
-                    // If we don't have an explicit bound, use the minimum key.
-                    key_lower: key_lower.unwrap_or_else(Vec::new),
-                    stats,
-                }
+                (payload_len, stats)
             }
             .instrument(write_span),
         );
-        self.writing_parts.push_back(handle);
+        self.writing_parts.push_back((partial_key, handle));
 
         while self.writing_parts.len() > self.cfg.batch_builder_max_outstanding_parts {
             batch_metrics.write_stalls.inc();
-            let handle = self
+            let (key, handle) = self
                 .writing_parts
                 .pop_front()
                 .expect("pop failed when len was just > some usize");
-            let part = match handle
+            let (encoded_size_bytes, stats) = match handle
                 .instrument(debug_span!("batch::max_outstanding"))
                 .await
             {
                 Ok(x) => x,
+                Err(err) if err.is_cancelled() => (0, None),
                 Err(err) => panic!("part upload task failed: {}", err),
             };
-            self.finished_parts.push(part);
+            self.finished_parts.push(HollowBatchPart {
+                key,
+                encoded_size_bytes,
+                key_lower: vec![],
+                stats,
+            });
         }
     }
 
     #[instrument(level = "debug", name = "batch::finish_upload", skip_all, fields(shard = %self.shard_id))]
     pub(crate) async fn finish(self) -> Vec<HollowBatchPart> {
         let mut parts = self.finished_parts;
-        for handle in self.writing_parts {
-            let part = match handle.await {
+        for (key, handle) in self.writing_parts {
+            let (encoded_size_bytes, stats) = match handle.await {
                 Ok(x) => x,
+                Err(err) if err.is_cancelled() => (0, None),
                 Err(err) => panic!("part upload task failed: {}", err),
             };
-            parts.push(part);
+            parts.push(HollowBatchPart {
+                key,
+                encoded_size_bytes,
+                key_lower: vec![],
+                stats,
+            });
         }
         parts
     }
```

**Comment by def-** [comment] 2023-09-22 11:44
This seems to be happening a lot more often now (not a release blocker though since this is already released, so was caught too late anyway). @bkirwi Any chance to get this fixed quickly?

**Comment by bkirwi** [comment] 2023-09-22 13:53
Sorry, I haven't been seeing notifications on this one for some reason. I'll look into it, though I've got a bunch of urgent stuff on deck so it may be a couple days.

**Comment by danhhz** [comment] 2023-09-22 15:08
@bkirwi Just FYI that this is happening pretty constantly on CI, so also very much falls into the urgent bucket

**Comment by bkirwi** [comment] 2023-09-26 16:37
I believe the recent issues are fixed by https://github.com/MaterializeInc/materialize/pull/21856/commits/e2c3b17e6c9b136090cd40646bbc9d96c4a6cb7d -- h/t @guswynn for coming up with a nice solution.

If folks are still running into this on a recent `main`, please flag it! Otherwise I will close this as fixed in a day or so.

**Comment by def-** [comment] 2023-09-27 07:03
There is a different panic on main now with e2c3b17: https://github.com/MaterializeInc/materialize/issues/21991

**Comment by bkirwi** [comment] 2023-09-29 18:18
The related issue is now also fixed.

SLT's weird task cancellation continues to be a ready source of bugs, but I'm not seeing this one in recent `main` either. Closing for now - though folks should feel to reopen if we see more task-upload failures.

**Closed by bkirwi** 2023-09-29 18:18 UTC
Labels: C-bug, ci-flake
