### ISSUE TITLE
storage: librdkafka: "Timed out FetchRequest in flight" after temporary network disruption, ingestion fails with no error in source

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7035] opened 2021-06-14 08:16 UTC
### What version of Materialize are you using?

```
v0.7.4-dev (b7aa10f26)
```

### What was the issue?

One of the Antithesis test runs produced the following error:

```
[  281553] [   279.402910] [service_materialized]   [I] 2018-01-28T16:02:33.083259Z  INFO librdkafka: librdkafka: REQTMOUT [thrd:cp-combined:9092/bootstrap]: cp-combined:9092/0: Timed out FetchRequest in flight (after 60815ms, timeout #0)    
[  281553] [   279.406238] [service_materialized]   [I] 2018-01-28T16:02:33.087082Z  WARN librdkafka: librdkafka: REQTMOUT [thrd:cp-combined:9092/bootstrap]: cp-combined:9092/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests    
[  281553] [   279.409425] [service_materialized]   [I] 2018-01-28T16:02:33.090463Z ERROR librdkafka: librdkafka: FAIL [thrd:cp-combined:9092/bootstrap]: cp-combined:9092/0: 1 request(s) timed out: disconnect (after 94423ms in state UP)    
[  281553] [   279.450421] [service_materialized]   [I] 2018-01-28T16:02:33.129197Z ERROR rdkafka::client: librdkafka: Global error: OperationTimedOut (Local: Timed out): cp-combined:9092/0: 1 request(s) timed out: disconnect (after 94423ms in state UP)    
```

The error implies that ```FetchRequest``` timed out after 60 seconds in flight. While it is true that Antithesis disrupted the network multiple times within that time period, their logging indicates that packets were being exchanged during the period:

```
[  108921] [   225.147057] [fault_injector]         [I] [133.317485s] Network Model - Packet summary: 446 packets: 372(83%) passed, 74(17%) dropped; average latency: 29.53ms
[  108969] [   225.577340] [fault_injector]         [I] [133.747767s] Network Model - Packet summary: 51 packets: 44(86%) passed, 7(14%) dropped; average latency: 34.57ms
[  109017] [   225.604965] [fault_injector]         [I] [133.775392s] Network Model - Packet summary: 9 packets: 8(89%) passed, 1(11%) dropped; average latency: 33.59ms
[  109065] [   226.159935] [fault_injector]         [I] [134.330362s] Network Model - Packet summary: 100 packets: 97(97%) passed, 3(3%) dropped; average latency: 31.07ms
[  109113] [   227.763822] [fault_injector]         [I] [135.934249s] Network Model - Packet summary: 226 packets: 214(95%) passed, 12(5%) dropped; average latency: 205.06ms
[  109161] [   228.468049] [fault_injector]         [I] [136.638476s] Network Model - Packet summary: 85 packets: 78(92%) passed, 7(8%) dropped; average latency: 80.26ms
[  109209] [   230.680555] [fault_injector]         [I] [138.850982s] Network Model - Packet summary: 432 packets: 409(95%) passed, 23(5%) dropped; average latency: 34.68ms
[  109257] [   230.730092] [fault_injector]         [I] [138.900519s] Network Model - Packet summary: 0 packets: 0(0%) passed, 0(0%) dropped; average latency: 0.00ms
[  109305] [   231.589178] [fault_injector]         [I] [139.759605s] Network Model - Packet summary: 50 packets: 0(0%) passed, 50(100%) dropped; average latency: 0.00ms
[  109353] [   233.424540] [fault_injector]         [I] [141.594967s] Network Model - Packet summary: 12 packets: 0(0%) passed, 12(100%) dropped; average latency: 0.00ms
[  109401] [   233.906168] [fault_injector]         [I] [142.076595s] Network Model - Packet summary: 3 packets: 0(0%) passed, 3(100%) dropped; average latency: 0.00ms
[  280257] [   233.973108] [fault_injector]         [I] [142.143535s] Network Model - Packet summary: 0 packets: 0(0%) passed, 0(0%) dropped; average latency: 0.00ms
[  280305] [   235.830488] [fault_injector]         [I] [144.000915s] Network Model - Packet summary: 34 packets: 18(53%) passed, 16(47%) dropped; average latency: 135.56ms
[  280353] [   238.040541] [fault_injector]         [I] [146.210968s] Network Model - Packet summary: 75 packets: 66(88%) passed, 9(12%) dropped; average latency: 34.88ms
[  280401] [   238.483849] [fault_injector]         [I] [146.654277s] Network Model - Packet summary: 70 packets: 67(96%) passed, 3(4%) dropped; average latency: 32.31ms
[  280449] [   239.106386] [fault_injector]         [I] [147.276813s] Network Model - Packet summary: 78 packets: 73(94%) passed, 5(6%) dropped; average latency: 34.41ms
[  280497] [   241.456054] [fault_injector]         [I] [149.626481s] Network Model - Packet summary: 452 packets: 433(96%) passed, 19(4%) dropped; average latency: 31.36ms
[  280545] [   247.540184] [fault_injector]         [I] [155.710612s] Network Model - Packet summary: 1030 packets: 978(95%) passed, 52(5%) dropped; average latency: 81.29ms
[  280593] [   247.543844] [fault_injector]         [I] [155.714272s] Network Model - Packet summary: 0 packets: 0(0%) passed, 0(0%) dropped; average latency: 0.00ms
[  280641] [   248.061530] [fault_injector]         [I] [156.231957s] Network Model - Packet summary: 138 packets: 135(98%) passed, 3(2%) dropped; average latency: 26.92ms
[  280689] [   248.312493] [fault_injector]         [I] [156.482920s] Network Model - Packet summary: 109 packets: 105(96%) passed, 4(4%) dropped; average latency: 29.77ms
[  280737] [   249.259315] [fault_injector]         [I] [157.429742s] Network Model - Packet summary: 138 packets: 130(94%) passed, 8(6%) dropped; average latency: 188.87ms
[  280785] [   250.752805] [fault_injector]         [I] [158.923232s] Network Model - Packet summary: 334 packets: 306(92%) passed, 28(8%) dropped; average latency: 31.56ms
[  280833] [   254.494509] [fault_injector]         [I] [162.664936s] Network Model - Packet summary: 416 packets: 343(82%) passed, 73(18%) dropped; average latency: 32.85ms
[  280881] [   255.709430] [fault_injector]         [I] [163.879858s] Network Model - Packet summary: 268 packets: 255(95%) passed, 13(5%) dropped; average latency: 28.91ms
[  280929] [   255.858740] [fault_injector]         [I] [164.029167s] Network Model - Packet summary: 18 packets: 17(94%) passed, 1(6%) dropped; average latency: 20.36ms
[  280977] [   256.318824] [fault_injector]         [I] [164.489252s] Network Model - Packet summary: 152 packets: 144(95%) passed, 8(5%) dropped; average latency: 33.11ms
[  281025] [   258.799411] [fault_injector]         [I] [166.969838s] Network Model - Packet summary: 482 packets: 463(96%) passed, 19(4%) dropped; average latency: 75.23ms
[  281073] [   260.406985] [fault_injector]         [I] [168.577412s] Network Model - Packet summary: 365 packets: 349(96%) passed, 16(4%) dropped; average latency: 35.42ms
[  281121] [   263.811516] [fault_injector]         [I] [171.981943s] Network Model - Packet summary: 838 packets: 808(96%) passed, 30(4%) dropped; average latency: 31.91ms
[  281169] [   263.938259] [fault_injector]         [I] [172.108686s] Network Model - Packet summary: 49 packets: 47(96%) passed, 2(4%) dropped; average latency: 25.77ms
[  281217] [   268.847971] [fault_injector]         [I] [177.018398s] Network Model - Packet summary: 1086 packets: 988(91%) passed, 98(9%) dropped; average latency: 31.47ms
[  281265] [   270.536509] [fault_injector]         [I] [178.706936s] Network Model - Packet summary: 267 packets: 249(93%) passed, 18(7%) dropped; average latency: 146.11ms
[  281313] [   270.770560] [fault_injector]         [I] [178.940987s] Network Model - Packet summary: 109 packets: 106(97%) passed, 3(3%) dropped; average latency: 32.19ms
[  281361] [   275.654284] [fault_injector]         [I] [183.824711s] Network Model - Packet summary: 421 packets: 305(72%) passed, 116(28%) dropped; average latency: 170.40ms
[  281409] [   275.881002] [fault_injector]         [I] [184.051429s] Network Model - Packet summary: 8 packets: 7(88%) passed, 1(12%) dropped; average latency: 41.21ms
[  281457] [   276.070933] [fault_injector]         [I] [184.241360s] Network Model - Packet summary: 13 packets: 13(100%) passed, 0(0%) dropped; average latency: 43.75ms
[  281505] [   278.001168] [fault_injector]         [I] [186.171595s] Network Model - Packet summary: 211 packets: 192(91%) passed, 19(9%) dropped; average latency: 79.54ms
````

So it seems that there were ample opportunities for the communication to take place. Apart from a 3-second period with 0% packets passed, the rest of the time there was traffic.

So either Antitheis' reporting is incorrect (or I am reading it incorrectly) and the network was borked throughout the period, or the failure and retry logic in librdkafka went astray and signaled a timeout where progress could have been made.

Furthermore, the source does not error out. It returns an incomplete output instead.

### Is the issue reproducible? If so, please provide reproduction instructions.

This only happened once and only within Antithesis' environment.

### Please attach any applicable log files.

The complete log from all the participating containers including the log lines from Antithesis indicating the times of the variosu network disruptions is attached here.

[kafka-avro-upsert-sources.td 471 1_non-matching rows expected .log](https://github.com/MaterializeInc/materialize/files/6646647/kafka-avro-upsert-sources.td.471.1_non-matching.rows.expected.log)

**Comment by aljoscha** [comment] 2021-08-02 12:15
I think this is pretty serious, if we can't pick up consumption after network outages. It's very hard to debug if we can't reproduce it, though.

**Comment by philip-stoev** [comment] 2021-08-02 12:30
@aljoscha  one thing I can do is bump the verbosity level of librdkafka to the max and then have Antithesis rerun their thing.

I will also see if I can reproduce this locally with firewall tricks and such.

**Comment by benesch** [comment] 2024-01-28 00:53
> This only happened once and only within Antithesis' environment.

Closing as we no longer use Antithesis.

**Closed by benesch** 2024-01-28 00:52 UTC
Labels: C-bug, T-antithesis, A-STORAGE
