### ISSUE TITLE
CREATE SINK creates a topic+schema that can not be read back with CREATE SOURCE - column specified more than once

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#22815] opened 2023-10-31 11:52 UTC
### What version of Materialize are you using?

 v0.76.0-dev (5e5e491c0)

### What is the issue?

This testdrive sequence:

```
$ postgres-execute connection=postgres://mz_system:materialize@${testdrive.materialize-internal-sql-addr}
ALTER SYSTEM SET enable_table_keys = true;

> CREATE TABLE sink_table (f1 INTEGER PRIMARY KEY);
> INSERT INTO sink_table VALUES (1);

> CREATE SINK sink_table_sink1 FROM sink_table
  INTO KAFKA CONNECTION kafka_conn (TOPIC 'sink-table-sink1')
  KEY (f1)
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE UPSERT

> CREATE SOURCE sink_table_view1
  FROM KAFKA CONNECTION kafka_conn (TOPIC 'sink-table-sink1')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE UPSERT
```

Produces this error:

```
ERROR:  column "f1" specified more than once
```

The column `f1` is present both in the key schema and the value schema created by `CREATE SINK`:

```
curl -s "http://localhost:8081/subjects/sink-table-sink1-key/versions/1" 
{"subject":"sink-table-sink1-key","version":1,"id":2,"schema":"{\"type\":\"record\",\"name\":\"row\",\"fields\":[{\"name\":\"f1\",\"type\":\"int\"}]}"}
curl -s "http://localhost:8081/subjects/sink-table-sink1-value/versions/1" 
{"subject":"sink-table-sink1-value","version":1,"id":1,"schema":"{\"type\":\"record\",\"name\":\"envelope\",\"fields\":[{\"name\":\"f1\",\"type\":\"int\"}
```

and there is no option to either `CREATE SINK` or `CREATE SOURCE` to fix this situation.

**Comment by sthm** [comment] 2023-12-15 08:14
Duplicate of #20112

**Closed by sthm** 2023-12-15 08:14 UTC
Labels: C-bug
