### ISSUE TITLE
TAIL producing delete rows for rows inserted within the same progress marker

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5827] opened 2021-02-20 17:26 UTC
I'm seeing an issue with TAIL where rows are being inserted and deleted within
the same progress marker. I would expect that these rows would be compacted
away. I don't have the raw rows returned by materialize, nor
`mz_logical_timestamp` information, but this issue reproduces fairly often, so
if we want that, I can rerun with some extra debugging information.

```
ERROR: Attempting to remove row never inserted
CURRENT ROWS:
[['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 0, 87918723657],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 1, 88378166287],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 2, 93832885896],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 3, 95815830734],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 4, 94845705605],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 5, 91626816076],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 6, 95265671773],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 7, 93699611011]]

ROWS TO DELETE:
[['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 0, 87918723657],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 1, 88378166287],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 2, 93832885896],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 3, 95815830734],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 4, 94845705605],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 5, 91626816076],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 6, 95265671773],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 7, 93699611011],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 0, 87922620224],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 1, 88382099516],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 2, 93836489961],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 3, 95819119324],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 4, 94848773774],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 5, 91630524826],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 6, 95269165531],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 7, 93703013332]]

ROWS TO INSERT:
[['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 0, 87922620224],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 1, 88382099516],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 2, 93836489961],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 3, 95819119324],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 4, 94848773774],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 5, 91630524826],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 6, 95269165531],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 7, 93703013332],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 0, 87928900943],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 1, 88387777814],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 2, 93842492802],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 3, 95823714892],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 4, 94853878398],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 5, 91636412411],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 6, 95274856406],
 ['a7139bef-5bd4-4e58-8aed-fd13ffba7670', 7, 93708463137]]
```

Here is the materialized view that I am running with:

```sql
CREATE SOURCE time_per_worker_v0
FROM KAFKA BROKER 'localhost:9093'
TOPIC 'dev.mtrlz.time_per_worker.v0'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'
ENVELOPE NONE;

CREATE MATERIALIZED IF NOT EXISTS VIEW time_per_worker AS
    SELECT mz_cluster_id, mz_scheduling_worker_id, mz_scheduling_elapsed_ns
    FROM time_per_worker_v0
    WHERE mz_logical_timestamp = (SELECT max(mz_logical_timestamp) FROM time_per_worker_v0);
```

Here is the Avro schema that I'm running with:

```json
{
    "name": "value",
    "type" : "record",
    "namespace": "dev.mtrlz.time_per_worker.v0",
    "fields": [
        {"name": "mz_cluster_id",  "type": "string"},
        {"name": "mz_logical_timestamp",  "type": "double"},
        {"name": "mz_scheduling_worker_id",  "type": "int"},
        {"name": "mz_scheduling_elapsed_ns", "type": "long"}
    ]
}
```

@mjibson, since you've been looking at TAIL recently, it this behavior that you would expect?

**Comment by mjibson** [comment] 2021-02-22 17:12
I have no idea. I only worked on the part of TAIL that occurred after the set of rows is determined. This might be a better question for @umanwizard who I think recently changed some of the sink semantics.

**Comment by umanwizard** [comment] 2021-02-22 17:47
This sounds like a bug for sure, one of us should take a look

**Comment by cirego** [comment] 2021-02-22 23:11
Thanks for taking a look!

**Comment by frankmcsherry** [comment] 2021-03-02 11:12
Having a reproduction for this would help! Is that easy to do?

**Comment by cirego** [comment] 2021-03-02 16:34
I was hitting this consistently when developing #5913, at least until I worked around it by applying deletes before inserts. Let me see if it's simple to push a branch that reproduces the issue easily under mzcompose.

**Comment by cirego** [comment] 2021-03-02 17:12
> I was hitting this consistently when developing #5913, at least until I worked around it by applying deletes before inserts. Let me see if it's simple to push a branch that reproduces the issue easily under mzcompose.

Unfortunately, it's not reproducing as easily as it was before. I've been running `mzbench` for 30 minutes and still haven't hit this problem with TAIL.

**Comment by cirego** [comment] 2021-03-02 17:15
> > I was hitting this consistently when developing #5913, at least until I worked around it by applying deletes before inserts. Let me see if it's simple to push a branch that reproduces the issue easily under mzcompose.
> 
> Unfortunately, it's not reproducing as easily as it was before. I've been running `mzbench` for 30 minutes and still haven't hit this problem with TAIL.

These are the steps I'm running to try and reproduce.

1. Run `./bin/mzbench avro-upsert v0.7.0` in one window
2. Run `docker logs --follow avro-upsert_perf-dash-web_1` in another window, waiting for a crash.

I've pushed the code for this repro attempt as #5955.

**Comment by cirego** [comment] 2021-03-05 20:28
I'm closing #5955, as it has drifted quite a bit. Does anyone still want to try and reproduce using `mzbench`?

**Comment by ruchirK** [comment] 2021-05-26 16:06
Hey @philip-stoev any updates on trying to reproduce this issue?

**Comment by philip-stoev** [comment] 2021-05-26 16:12
Sorry, no, I have been buried.

**Comment by ruchirK** [comment] 2021-05-26 16:12
No worries!

**Comment by philip-stoev** [comment] 2021-05-27 07:34
I was unable to reproduce this with a simple psql test using base tables.

I was also not able to reproduce this with a concurrent randomized workload (again over base tables, but using the ```EXCEPT ALL``` trick to simulate deletions). I captured a TAIL output of 84K lines and used this command line:

```
cat output | awk '{$2=""; print $0}' | sort | uniq -c   | grep -v '1 1'
```

to fish for any rows that appear twice within a single timestamp. Unfortunately, no anomalies were found.

It may be that this is specific to Kafka sources, hence my inability to reproduce it. I will need to revisit this again at a later time.

**Comment by umanwizard** [comment] 2021-06-02 16:01
Since we haven't been able to reproduce, let's close the issue -- feel free to reopen if it happens again.

**Closed by umanwizard** 2021-06-02 16:01 UTC
Labels: G-external integrations, Top Priority
