### ISSUE TITLE
testing: test against more/newer versions of PG for sources

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#18537] opened 2023-03-31 17:36 UTC
### Feature request

We currently test PG sources against PG 10 (at least in `pg-cdc`); it would be great if we used a more current version than this (preferably 15). However, I think testing against a suite of versions would also be very useful, albeit more challenging given their different levels of support for different features.

**Comment by benesch** [comment] 2024-02-23 04:47
Closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/6825.

**Closed by benesch** 2024-02-23 04:47 UTC
Labels: C-feature, T-testing, A-STORAGE
