### ISSUE TITLE
pg-cdc: tokio_postgres performs many small reads on the socket, CPU maxed out when replicating

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6836] opened 2021-05-24 10:59 UTC
### What version of Materialize are you using?

```
v0.7.4-dev (f76e9cd37)
```

### What was the issue?

tokio_postgres appears to be doing a lot of very small reads from the Postgres socket:

```
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\202N\353\350\34\275\321\3242\270\260\202`\20\250/g\324\240\233`\300\361\272\32"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\203 \302\355<(\337\6\227\345\324u\177 \230\327\240d\252\344\360`g$\10"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\204\225\324&\177)\262\353\311\354zI\221\\2\215\231[\5\3P-1\24R"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\205\301\35\301\300rJ\260\207\350\202 \315@\16\307_\322\24I\20\3\250j\231"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\206\307\376\2252\25\314b\5~\302\266\365\20\243nx4$\316\315G\240\320\327"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
[pid 1061791] recvfrom(12, "k\261\372{\360\316e\207\310\213r\330#\235`y\0007\332\235Q\221\257.|G\311\24H\21\321\272"..., 80, 0, NULL, NULL) = 80
[pid 1061791] recvfrom(12, "\27\3\3\0P", 5, 0, NULL, NULL) = 5
```

and so socket operations dominate the execution time:

```
+    7.49%     0.05%  tokio:work-14    [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+    7.38%     0.09%  tokio:work-14    [kernel.kallsyms]   [k] do_syscall_64
+    7.35%     0.05%  tokio:work-12    [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+    7.29%     0.04%  tokio:work-7     [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+    7.23%     0.09%  tokio:work-12    [kernel.kallsyms]   [k] do_syscall_64
+    7.18%     0.10%  tokio:work-7     [kernel.kallsyms]   [k] do_syscall_64
+    5.64%     0.03%  tokio:work-3     [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+    5.56%     0.08%  tokio:work-3     [kernel.kallsyms]   [k] do_syscall_64
+    3.91%     0.04%  tokio:work-12    libpthread-2.27.so  [.] __libc_recv
+    3.86%     0.04%  tokio:work-14    libpthread-2.27.so  [.] __libc_recv
+    3.75%     0.04%  tokio:work-7     libpthread-2.27.so  [.] __libc_recv
+    3.54%     0.03%  tokio:work-12    [kernel.kallsyms]   [k] __x64_sys_recvfrom
+    3.50%     0.04%  tokio:work-12    [kernel.kallsyms]   [k] __sys_recvfrom
+    3.48%     0.02%  tokio:work-14    [kernel.kallsyms]   [k] __x64_sys_recvfrom
+    3.44%     0.04%  tokio:work-14    [kernel.kallsyms]   [k] __sys_recvfrom
+    3.39%     0.02%  tokio:work-7     [kernel.kallsyms]   [k] __x64_sys_recvfrom
+    3.35%     0.04%  tokio:work-7     [kernel.kallsyms]   [k] __sys_recvfrom
+    3.33%     0.01%  tokio:work-12    [kernel.kallsyms]   [k] sock_recvmsg
+    3.25%     0.01%  tokio:work-14    [kernel.kallsyms]   [k] sock_recvmsg
+    3.25%     0.02%  tokio:work-12    [kernel.kallsyms]   [k] inet_recvmsg
+    3.22%     0.18%  tokio:work-12    [kernel.kallsyms]   [k] tcp_recvmsg
+    3.18%     0.01%  tokio:work-7     [kernel.kallsyms]   [k] sock_recvmsg
+    3.17%     0.01%  tokio:work-14    [kernel.kallsyms]   [k] inet_recvmsg
+    3.15%     0.19%  tokio:work-14    [kernel.kallsyms]   [k] tcp_recvmsg
+    3.12%     0.03%  tokio:work-3     libpthread-2.27.so  [.] __libc_recv
+    3.09%     0.01%  tokio:work-7     [kernel.kallsyms]   [k] inet_recvmsg
+    3.07%     0.19%  tokio:work-7     [kernel.kallsyms]   [k] tcp_recvmsg
+    2.80%     0.02%  tokio:work-3     [kernel.kallsyms]   [k] __x64_sys_recvfrom
+    2.76%     0.03%  tokio:work-3     [kernel.kallsyms]   [k] __sys_recvfrom
```

As @petrosagg observed, tokio_postgres provides an API that can transfer the burden of buffer management to the caller.

https://docs.rs/tokio-postgres/0.7.2/tokio_postgres/config/struct.Config.html#method.connect_raw

### Is the issue reproducible? If so, please provide reproduction instructions.

Use test case from https://github.com/MaterializeInc/materialize/issues/6827, with ```strace``` to see the syscalls and ```perf record -p XXX sleep 60; perf report ``` to see the CPU usage.

**Comment by petrosagg** [comment] 2021-05-24 13:54
Recording the current state:

After further investigation this doesn't seem to be coming from the connection to postgres. I set up an isolated test of the library where I tested queries, simple queries, copy outs, and reading a replication slot and in all cases the strace showed reads happening with a 8KB buffer, similar to the official client.

We need to look closer into the trace to find the corresponding `connect` syscall of the offending file descriptor to understand what's going on

**Comment by philip-stoev** [comment] 2021-05-24 13:58
Ok let me try to reproduce it again and provide the required information. Nothing besides replication was happening at the time -- there were no queries running on the Mz side.

**Comment by petrosagg** [comment] 2021-05-24 14:47
Turns out it was an issue with the postgres library when used with a TLS connector. The issue is fixed in this PR upstream https://github.com/sfackler/rust-postgres/pull/777

**Closed** 2021-05-24 19:14 UTC
Labels: A-source, C-bug, D-good second issue, G-external integrations
