### ISSUE TITLE
load-generator-key-value.td is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#27786] opened 2024-06-21 05:59 UTC
### Buildkite link

https://buildkite.com/materialize/test/builds/84292

### Relevant log output

```source
^^^ +++
load-generator-key-value.td:157:1: error: non-matching rows: expected:
[["up_with_update", "true", "true", "48", "48", "true", "16"]]
got:
[["up_with_update", "false", "true", "48", "48", "true", "16"]]
Poor diff:
+ up_with_update false true 48 48 true 16
- up_with_update true true 48 48 true 16

     |
  14 | $ postgres-execute c ... [rest of line truncated for security]
 156 | # Higher offsets than before, as we produce more values.
 157 | > SELECT
     | ^
importer.proto:2:1: warning: Import empty.proto is unused.
```

### Additional thoughts

Further occurrences:
* https://buildkite.com/materialize/test/builds/84299
* https://buildkite.com/materialize/nightly/builds/8174
* https://buildkite.com/materialize/nightly/builds/8123
* https://buildkite.com/materialize/nightly/builds/8115

**Comment by def-** [comment] 2024-06-24 05:21
Duplicate of https://github.com/MaterializeInc/materialize/issues/27397

**Closed by def-** 2024-06-24 05:21 UTC
Labels: C-bug, ci-flake
