### ISSUE TITLE
peristence: INSERTs allowed to proceed even though they can not be persisted

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7926] opened 2021-08-19 11:12 UTC
### What version of Materialize are you using?

```
v0.9.1-dev (ed424518a)
```

### What was the issue?

One is allowed to issue `INSERT` statements against Mz and they will be acknowledged even if the data can not be persisted. This goes against the concept that the database client should receive an acknowledgement only after the data has been persisted to durable storage.

If the data could not be persisted, an error should have been returned to the DML statement or , at the very least, at transaction commit  (which for autocommit statements amounts to the same thing from the viewpoint of the user)

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Start Materialize
2. Create a table
2. remove the `persist` directory
3. Insert some data. Observe that even though the log begins to report:
```
2021-08-19T11:09:30.193597Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:30.193645Z ERROR coord::coord: failed to seal persisted stream to ts 1629371370194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
```

the insert succeeded when it should not have.

### Please attach any applicable log files.
```
materialized v0.9.1-dev (ed424518a) listening on 0.0.0.0:6875...
2021-08-19T11:09:24.675975Z  INFO coord::catalog: create table materialize.public.t1 (u1)    
2021-08-19T11:09:24.676023Z  INFO coord::catalog: create index materialize.public.t1_primary_idx (u2)    
2021-08-19T11:09:30.193597Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:30.193645Z ERROR coord::coord: failed to seal persisted stream to ts 1629371370194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:31.193900Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:31.193924Z ERROR coord::coord: failed to seal persisted stream to ts 1629371371194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:32.194194Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:32.194214Z ERROR coord::coord: failed to seal persisted stream to ts 1629371372195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:33.193711Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:33.193728Z ERROR coord::coord: failed to seal persisted stream to ts 1629371373194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:33.993384Z  WARN persist::indexed::runtime: error running step: String("failed to append to future: No such file or directory (os error 2)")    
2021-08-19T11:09:33.993405Z ERROR coord::coord: failed to seal persisted stream to ts 1629371373994: failed to append to future: No such file or directory (os error 2)    
2021-08-19T11:09:34.193877Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:34.193884Z ERROR coord::coord: failed to seal persisted stream to ts 1629371374194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:35.194301Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:35.194323Z ERROR coord::coord: failed to seal persisted stream to ts 1629371375195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:36.193767Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:36.193775Z ERROR coord::coord: failed to seal persisted stream to ts 1629371376194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:37.194148Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
2021-08-19T11:09:37.194167Z ERROR coord::coord: failed to seal persisted stream to ts 1629371377195: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:38.193573Z ERROR coord::coord: failed to seal persisted stream to ts 1629371378194: failed to commit metadata after appending to future: No such file or directory (os error 2)    
2021-08-19T11:09:38.193568Z  WARN persist::indexed::runtime: error running step: String("failed to commit metadata after appending to future: No such file or directory (os error 2)")    
```

**Comment by ruchirK** [comment] 2021-08-19 15:56
I think I have a candidate fix for this. basically, we need to be better about plumbing the error from the write response to the user and I think theres a way to do this with a few line change to coord.

(this solves the part about the write succeeding even though it should error, selects still hang)

**Comment by ruchirK** [comment] 2021-08-19 18:09
My candidate fix was incorrect, but the basic idea is sound. When a user issues a write, the persistence crate returns a future that can be awaited to get the correct response. The coordinator's state machine does indeed await the write when it commits the transaction, but it returns from insert when it enqueues the write as a transaction op.

More specifically, in the coordinator we go through the state machine till we get to `sequence_insert` which enqueues the write as an operation that will happen when the transaction is committed, and then immediately returns success. At a later point, the coordinator sends out a `Command::Commit` that takes us to `sequence_end_transaction` where we actually do the write and receive the appropriate response, but by then we’ve already responded to the insert. There's an existing todo in the code to thread the future output back to the user somehow.

cc: @mjibson

**Comment by ruchirK** [comment] 2021-08-19 18:20
Also, if you do these repro steps on a dev build we crash because we fail some invariants that the persistence crate is asserting on in dev mode. I'm personally happy with that behavior but want to make sure others agree with that.

**Comment by mjibson** [comment] 2021-08-19 19:24
Dan and I took pains to try to make commit produce an error in this case. I'm curious why that's not happening.

**Comment by ruchirK** [comment] 2021-08-19 20:52
Matt and I looked into this offline and confirmed that this works correctly when you specify an explicit txn, and only does not work correctly when you specify an implicit txn. Matt I'm going to assign this one to you as you're going to own the followup of figuring out what postgres does in this case (where an insert fails at commit time) and how to implement that in mz.

sidenote: I found this diff

```
index e3974678c..330dfdffc 100644
--- a/src/persist/src/indexed/mod.rs
+++ b/src/persist/src/indexed/mod.rs
@@ -560,8 +561,8 @@ impl<U: Buffer, L: Blob> Indexed<U, L> {
         updates: Vec<(Id, Vec<((Vec<u8>, Vec<u8>), u64, isize)>)>,
         res: FutureHandle<SeqNo>,
     ) {
-        let resp = self.validate_write(&updates);
-
+        //let resp = self.validate_write(&updates);
+        let resp = Err("writes never work".into());
         if resp.is_ok() {
             self.pending_writes.extend(updates);
         }
```

extremely useful in debugging this issue (basically make every write an error instead of manually having to remove the files)

**Closed** 2021-08-24 18:49 UTC
Labels: C-bug, A-persistence, T-correctness
