### ISSUE TITLE
Output inconsistencies (data-flow rendering vs. constant folding)

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#19511] opened 2023-05-26 07:37 UTC
### What version of Materialize are you using?

v0.55.0 (448db5f3c)

### What is the issue?

The outcome of queries produces different results with different evaluation modes (data-flow rendering vs. constant folding).

CC @vmarcos

### Snippets trimmed down to minimal required code

Summary: The functions `sum`, `avg`, `stddev_samp`, `stddev_pop` produce inconsistent results when working on very large values or very small, decimal values.

#### 1) sum with max value

* Data-flow rendering: `-1.0141204801825835e+31`
* Constant folding: `1e+39`

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, double_val DOUBLE);
INSERT INTO t_dfr_vert VALUES (3, 999999999999999999999999999999999999999::DOUBLE);
INSERT INTO t_dfr_vert VALUES (8, 0.500000000000000000000000000000000000001::DOUBLE);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_vert (row_index, double_val)
 AS SELECT 3, 999999999999999999999999999999999999999::DOUBLE
    UNION SELECT 8, 0.500000000000000000000000000000000000001::DOUBLE;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  sum(double_val)
FROM
  t_dfr_vert
WHERE row_index IN (8, 3);
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  sum(double_val)
FROM
  v_ctf_vert
WHERE row_index IN (8, 3);
```

</details>

#### 2) avg with max value

* Data-flow rendering: `-5.070602400912918e+30`
* Constant folding: `5e+38`
* Remarks: This is probably a consecutive fault of the `SUM` fault.

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, double_val DOUBLE);
INSERT INTO t_dfr_vert VALUES (3, 999999999999999999999999999999999999999::DOUBLE);
INSERT INTO t_dfr_vert VALUES (8, 0.500000000000000000000000000000000000001::DOUBLE);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_vert (row_index, double_val)
 AS SELECT 3, 999999999999999999999999999999999999999::DOUBLE
    UNION SELECT 8, 0.500000000000000000000000000000000000001::DOUBLE;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  avg(double_val)
FROM
  t_dfr_vert
WHERE row_index IN (8, 3);
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  avg(double_val)
FROM
  v_ctf_vert
WHERE row_index IN (8, 3);
```

</details>

#### 3) stddev_samp with large decimal value

* Data-flow rendering: `ERROR:  Evaluation error: cannot take square root of a negative number`
* Constant folding: `1.414213562373095e+31`
* Remarks: This is potentially a consecutive fault of the `SUM` fault.

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, decimal_39_8_val DECIMAL(39,8));
INSERT INTO t_dfr_vert VALUES (3, 9999999999999999999999999999999.99999999::DECIMAL(39,8));
INSERT INTO t_dfr_vert VALUES (4, -9999999999999999999999999999999.99999999::DECIMAL(39,8));
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_vert (row_index, decimal_39_8_val)
 AS SELECT 3, 9999999999999999999999999999999.99999999::DECIMAL(39,8)
    UNION SELECT 4, -9999999999999999999999999999999.99999999::DECIMAL(39,8);
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  stddev_samp(decimal_39_8_val)
FROM
  t_dfr_vert
WHERE row_index IN (3, 4);
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  stddev_samp(decimal_39_8_val)
FROM
  v_ctf_vert
WHERE row_index IN (3, 4);

```
</details>

#### 4) stddev_pop with large value

* Data-flow rendering: `Evaluation error: cannot take square root of a negative number`
* Constant folding: `4.611686018427388e+18`
* Remarks: This is likely related to `stddev_samp`.

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, int8_val INT8);
INSERT INTO t_dfr_vert VALUES (5, 0::INT8);
INSERT INTO t_dfr_vert VALUES (7, 9223372036854775807::INT8);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_vert (row_index, int8_val)
 AS SELECT 5, 0::INT8
    UNION SELECT 7, 9223372036854775807::INT8;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  stddev_pop(int8_val)
FROM
  t_dfr_vert
WHERE row_index IN (5, 7);
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  stddev_pop(int8_val)
FROM
  v_ctf_vert
WHERE row_index IN (5, 7);

```
</details>

#### 5) avg with tiny value

* Data-flow rendering: `0`
* Constant folding: `1e-39`

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_horiz;
CREATE TABLE t_dfr_horiz (double_tiny DOUBLE);
INSERT INTO t_dfr_horiz VALUES (0.000000000000000000000000000000000000001::DOUBLE);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_horiz (double_tiny)
 AS SELECT 0.000000000000000000000000000000000000001::DOUBLE;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  avg(double_tiny)
FROM
  t_dfr_horiz;
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  avg(double_tiny)
FROM
  v_ctf_horiz;

```
</details>

#### 6) stddev_samp with values with small decimals

* Data-flow rendering: `0.00017263348892818244`
* Constant folding: `0.0`

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, decimal_39_8_val DECIMAL(39,8));
INSERT INTO t_dfr_vert VALUES (6, 1.00000001::DECIMAL(39,8));
INSERT INTO t_dfr_vert VALUES (8, 0.99999999::DECIMAL(39,8));
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_vert (row_index, decimal_39_8_val)
 AS SELECT 6, 1.00000001::DECIMAL(39,8)
    UNION SELECT 8, 0.99999999::DECIMAL(39,8);
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  stddev_pop(decimal_39_8_val)
FROM
  t_dfr_vert
WHERE row_index IN (8, 6);
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  stddev_pop(decimal_39_8_val)
FROM
  v_ctf_vert
WHERE row_index IN (8, 6);
-- ------------------------------

```
</details>

#### 7) avg with very small values

* Data-flow rendering: `0.0`
* Constant folding: `1e-39`

<details>
  <summary>SQL</summary>

```
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_horiz;
CREATE TABLE t_dfr_horiz (double_tiny DOUBLE);
INSERT INTO t_dfr_horiz VALUES (0.000000000000000000000000000000000000001::DOUBLE);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_horiz (double_tiny)
 AS SELECT 0.000000000000000000000000000000000000001::DOUBLE;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  avg(double_tiny)
FROM
  t_dfr_horiz;
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  avg(double_tiny)
FROM
  v_ctf_horiz;
-- ------------------------------

```
</details>

#### 8) sum with very small values

* Data-flow rendering: `0.0`
* Constant folding: `1e-39`

<details>
  <summary>SQL</summary>

```
-- ------------------------------
-- Setup for evaluation strategy 'Dataflow rendering':
DROP TABLE IF EXISTS t_dfr_horiz;
CREATE TABLE t_dfr_horiz (double_tiny DOUBLE);
INSERT INTO t_dfr_horiz VALUES (0.000000000000000000000000000000000000001::DOUBLE);
-- ------------------------------
-- Setup for evaluation strategy 'Constant folding':
CREATE OR REPLACE VIEW v_ctf_horiz (double_tiny)
 AS SELECT 0.000000000000000000000000000000000000001::DOUBLE;
-- ------------------------------
-- Query using evaluation strategy 'Dataflow rendering':
SELECT
  sum(double_tiny)
FROM
  t_dfr_horiz;
-- ------------------------------
-- Query using evaluation strategy 'Constant folding':
SELECT
  sum(double_tiny)
FROM
  v_ctf_horiz;
-- ------------------------------

```
</details>

### Other

These issues were identified with the [output consistency testing checks](https://github.com/MaterializeInc/materialize/pull/19443). When the issues are fixed, please remove them from the ignore list in [inconsistency_ignore_filter.py](https://github.com/MaterializeInc/materialize/blob/057851684c4d7d1c4f115eeda084b1202f76d63a/misc/python/materialize/output_consistency/ignore_filter/inconsistency_ignore_filter.py)

**Comment by vmarcos** [comment] 2023-05-26 11:35
The cases where the underlying data types are `DOUBLE` look to me like instances of #15186. For other data types, we should check if type promotion is getting us (potentially incorrectly) into floating point types (e.g., in `mz_avg_promotion`).

**Comment by vmarcos** [comment] 2023-05-26 11:37
@teskje The following patch seems to fix **stddev_pop with large value** locally for me:
```diff
diff --git a/src/pgrepr-consts/src/oid.rs b/src/pgrepr-consts/src/oid.rs
index 87e7784f6b..0abed88d33 100644
--- a/src/pgrepr-consts/src/oid.rs
+++ b/src/pgrepr-consts/src/oid.rs
@@ -123,6 +123,7 @@ pub const FUNC_MZ_AVG_PROMOTION_DECIMAL_OID: u32 = 16_402;
 pub const FUNC_MZ_AVG_PROMOTION_F32_OID: u32 = 16_403;
 pub const FUNC_MZ_AVG_PROMOTION_F64_OID: u32 = 16_404;
 pub const FUNC_MZ_AVG_PROMOTION_I32_OID: u32 = 16_405;
+pub const FUNC_MZ_AVG_PROMOTION_I64_OID: u32 = 16_406;
 pub const FUNC_MZ_ENVIRONMENT_ID_OID: u32 = 16_407;
 pub const FUNC_MZ_LOGICAL_TIMESTAMP_OID: u32 = 16_409;
 pub const FUNC_MZ_RENDER_TYPMOD_OID: u32 = 16_410;
diff --git a/src/sql/src/func.rs b/src/sql/src/func.rs
index 3ef45d0218..6dbd7ec0ef 100644
--- a/src/sql/src/func.rs
+++ b/src/sql/src/func.rs
@@ -3079,6 +3079,11 @@ pub static MZ_INTERNAL_BUILTINS: Lazy<BTreeMap<&'static str, Func>> = Lazy::new(
                     ecx, CastContext::Explicit, e, &ScalarType::Numeric {max_scale: None},
                 )
             }) => Numeric, oid::FUNC_MZ_AVG_PROMOTION_I32_OID;
+            params!(Int64) => Operation::unary(|ecx, e| {
+                typeconv::plan_cast(
+                    ecx, CastContext::Explicit, e, &ScalarType::Numeric {max_scale: None},
+                )
+            }) => Numeric, oid::FUNC_MZ_AVG_PROMOTION_I64_OID;
             params!(UInt16) => Operation::unary(|ecx, e| {
                 typeconv::plan_cast(
                     ecx, CastContext::Explicit, e, &ScalarType::Numeric {max_scale: None},
```

**Comment by vmarcos** [comment] 2023-05-26 12:25
With the patch, we produce the following output for **3) stddev_samp with large decimal value**:
```sql
DROP TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
CREATE VIEW
ERROR:  Evaluation error: value out of range: overflow
ERROR:  value out of range: overflow
```
PostgreSQL, on the other hand, produces:
```sql
DROP TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
CREATE VIEW
                    stddev_samp                    
---------------------------------------------------
 14142135623730950488016887242096.9807856825766181
(1 row)

                    stddev_samp                    
---------------------------------------------------
 14142135623730950488016887242096.9807856825766181
(1 row)
```
My conjecture here is that we are probably busting through our precision when squaring due to the algorithm we use for standard deviation, a potential improvement to which is tracked by https://github.com/MaterializeInc/materialize/issues/1240.

**Comment by vmarcos** [comment] 2023-06-01 09:19
After investigation, the incorrect behavior pointed out in this issue should be fixed by a solution to both #19577 and #15186. I am thus closing this as a duplicate of these two issues. Please reopen if you find conflicting evidence.

**Closed by vmarcos** 2023-06-01 09:19 UTC
Labels: C-bug, T-correctness, A-COMPUTE

**Comment by nrainer-materialize** [comment] 2023-06-05 07:38
Just for the sake of completeness: This also affects `var_samp` and `var_pop`.
This will also be fixed by the referenced tickets since the root cause is supposed to be the same.

**Comment by vmarcos** [comment] 2023-06-05 09:15
> `AVG` and `STDDEV*` functions promote integer and decimal types to floating-point, not numeric #19577

Good point, I edited #19577 to make sure that we will not forget to check these too!
