### ISSUE TITLE
storage: consumer commit error: NoOffset (Local: No offset stored) not reflected in source status

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17443] opened 2023-01-31 09:19 UTC
### What version of Materialize are you using?

v0.43.0-dev (6d091d73f)

### How did you install Materialize?

Docker image

### What is the issue?

Attempting to read data from the Confluent Cloud repeatedly gave me this error in the log:

```
cluster-u3-replica-5: 2023-01-31T09:17:30.133199Z ERROR mz_storage::source::source_reader_pipeline: timely-2 source(u31) failed to commit offsets: resume_upper={(1..+inf, 0), (0, 14), (1, 0)} e=Consumer commit error: NoOffset (Local: No offset stored)
```

I will investigate whether the error is legitimate or not separately. This ticket is about the fact that the source is still reported as running even though no data is being ingested . Since this is an `ERROR`-level message in the logs, I was expecting this to be reflected in the source status.

Instead, the status table has the following state:

```
materialize=> select * from mz_internal.mz_source_status_history order by occurred_at;
        occurred_at         | source_id |  status  | error | details 
----------------------------+-----------+----------+-------+---------
 2023-01-31 09:00:30.887+00 | u23       | starting |       | 
 2023-01-31 09:00:31.69+00  | u23       | running  |       | 
```

@bkirwi FYI

There is limited information about what the `NoOffset` is supposed to mean. One commenter on one github ticket even says it is supposed to be treated as success(?)

**Comment by philip-stoev** [comment] 2023-01-31 10:14
huh actually this error is dumped 3K times during a normal testdrive run:

```
philip@materialize:~/Documents$ grep NoOffset 'services (10).txt' 2>&1 | wc
   2835   69036  796033
```

**Comment by aljoscha** [comment] 2023-01-31 10:32
@guswynn could you please take a look at this? :pray:

**Comment by aljoscha** [comment] 2023-01-31 11:44
Duplicate of https://github.com/MaterializeInc/materialize/issues/16692

**Closed by aljoscha** 2023-01-31 11:44 UTC
Labels: C-bug, A-STORAGE
