### ISSUE TITLE
CREATE SOURCE FORMAT CSV: Specifying tab separator doesn't seem to work

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#2368] opened 2020-03-20 14:31 UTC
```
materialize=> create source names from file '/Users/arjun/play/names.basics.tsv' format csv with 6 columns delimited by '\t';
ERROR:  Parse error:
create source names from file '/Users/arjun/play/names.basics.tsv' format csv with 6 columns delimited by '\t';
                                                                                                              ^
Expected one-character string, found: ;
```

**Comment by rjnn** [comment] 2020-03-20 14:44
Meanwhile CTRL+v and then pressing tab to insert an actual tab character between the single quotes did work, thanks for the suggestion offline @umanwizard!

**Comment by umanwizard** [comment] 2020-03-20 14:48
Dupe of #1734

**Closed by umanwizard** 2020-03-20 14:48 UTC
Labels: C-bug
