### ISSUE TITLE
persist: unexpected missing blob

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#14043] opened 2022-08-03 21:00 UTC
### What version of Materialize are you using?

38bb6db06bba2d9f5174cdcd2b058b819105da72

### How did you install Materialize?

Built from source

### What is the issue?

The following seems to fairly reliably reproduce an unexpectedly missing blob on main:

```
cargo build -p mz-persist-client --example persistcli --release && java -Djava.awt.headless=true -jar /path/to/maelstrom.jar test -w txn-list-append --bin ./target/release/examples/persistcli --rate=200 --time-limit=60 --node-count=1 --concurrency=2 --log-stderr -- maelstrom --blob-uri='mem://' --consensus-uri='mem://'
```

When it happens, the following shows up in the logs and we process no further maelstrom requests

```
INFO [2022-08-03 13:43:35,453] n0 stderr - maelstrom.process 2022-08-03T20:43:35.453772Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 4ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,460] n0 stderr - maelstrom.process 2022-08-03T20:43:35.460651Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 8ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,470] n0 stderr - maelstrom.process 2022-08-03T20:43:35.470745Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 16ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,487] n0 stderr - maelstrom.process 2022-08-03T20:43:35.486913Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 32ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,521] n0 stderr - maelstrom.process 2022-08-03T20:43:35.521037Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 64ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,592] n0 stderr - maelstrom.process 2022-08-03T20:43:35.592219Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 128ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,728] n0 stderr - maelstrom.process 2022-08-03T20:43:35.728330Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 256ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:35,983] n0 stderr - maelstrom.process 2022-08-03T20:43:35.983530Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 512ms: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:36,489] n0 stderr - maelstrom.process 2022-08-03T20:43:36.488766Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 1.024s: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:37,477] n0 stderr - maelstrom.process 2022-08-03T20:43:37.477734Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 2.048s: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
INFO [2022-08-03 13:43:39,452] n0 stderr - maelstrom.process 2022-08-03T20:43:39.452856Z  INFO mz_persist_client::read: unexpected missing blob, trying again in 4.096s: w637085b5-decb-447c-83c3-419c960520c3/p2e786cde-7a34-4a60-876d-cf9825df8942
```

My initial suspicion was that Maelstrom wasn't holding on to some SeqNo capability correctly, which allowed GC to delete something we were still using. So, I tried commenting out GC entirely and it still repro's (though maybe less frequently). I think that means this could exist in prod.

**Comment by pH14** [comment] 2022-08-08 12:09
Hmm I tried running this locally, and it's a bummer that the Maelstrom test can reproduce the bug, but doesn't signal any errors when it runs. I wonder if we want to change the behavior of https://github.com/MaterializeInc/materialize/blob/19c9736241017477be9d996d45d44e6a7b8a8e07/src/persist-client/src/read.rs#L843-L865 and panic if we fail to read a batch part from a linearizable blob store

**Comment by pH14** [comment] 2022-08-22 11:31
We're still seeing these errors on prod, reopening to track the investigation

**Comment by pH14** [comment] 2022-09-01 20:42
I think we've got this one figured out! We have an alert for when the log line shows up, and since https://github.com/MaterializeInc/materialize/pull/14332 was merged we've only seen the bug crop up during compaction, which is easily recoverable, and have not seen it happen to a reader where it would indicate something has gone very awry. I feel comfortable closing this one out

**Closed by pH14** 2022-09-01 20:42 UTC
Labels: C-bug, P2, A-STORAGE
