### ISSUE TITLE
storage/source/postgres: investigate why extracting txns might be slow

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#26813] opened 2024-04-26 01:47 UTC
We had a user with a 30-second `wal_sender_tiimeout` hit that timeout when extracting some not-incredibly-large txns. @benesch [describes the issue here](https://github.com/MaterializeInc/materialize/issues/26813#issuecomment-2100824842).

---

_Note: this is the original issue description, which was mistaken; we use a multi-stage stream and `extract_transaction` does not pull items from the replication log directly._

While [extracting transactions](https://github.com/MaterializeInc/materialize/blob/72d3b09bc006b5f871bdcd92377f6d5e63d75a8c/src/storage/src/source/postgres/replication.rs#L592), we ignore [`ReplicationMessage::PrimaryKeepAlive`](https://github.com/MaterializeInc/materialize/blob/72d3b09bc006b5f871bdcd92377f6d5e63d75a8c/src/storage/src/source/postgres/replication.rs#L615), irrespective of their status.

A downside of this implementation is that if the time it takes to extract a transaction exceeds the server's [`wal_sender_timeout`](https://www.postgresql.org/docs/current/runtime-config-replication.html), the server will terminate the source's connection. If the latency is due to an exceptionally large transaction (e.g. processing it as quickly as we can deterministically exceeds the `wal_sender_timeout`), the source might never be able to successfully ingest the transaction. In this case, the source will enter a cycle of:

1. Trying to ingest the large txn.
2. Exceeding `wal_sender_timeout` and having its connection closed.
3. Having its dataflow rescheduled.

cc @petrosagg

**Comment by benesch** [comment] 2024-04-26 02:36
Thanks for filing, @sploiselle! Gentle plea to stitch these into the storage mega tracker, or toss on the triage column of the storage team board if you're short on time.

One other idea to consider here: ...can we just run `SET wal_sender_timeout = '10min'` in the session that establishes the replication stream? It seems like maybe that's under our control. Would need to test, but if it works... that would give us quite a bit of headroom and wouldn't require any complicated refactoring.

**Comment by petrosagg** [comment] 2024-05-07 07:37
Keepalives are handled in `raw_stream` regardless of whether we are extracting a transaction or not and we always send back replies in a timely manner or if we are requested to do so. https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/source/postgres/replication.rs#L548-L561

Unless I'm missing something this can be closed

**Comment by sploiselle** [comment] 2024-05-07 19:29
@petrosagg You're saying that these ignored keepalives ([link](https://github.com/MaterializeInc/materialize/blob/72d3b09bc006b5f871bdcd92377f6d5e63d75a8c/src/storage/src/source/postgres/replication.rs#L615)) are also seen [here](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/source/postgres/replication.rs#L548-L561)?

**Comment by petrosagg** [comment] 2024-05-08 13:17
@sploiselle yes. the input to `extract_transaction` is the stream produced by `raw_stream` which will handle keepalives as it pases events along

**Comment by benesch** [comment] 2024-05-08 15:17
I think there is still something to fix here! This issue came out of debugging a customer problem, in which we conclusively saw a Postgres source get stuck because transactions were taking longer than the default `wal_sender_timeout` (60s) to decode.

> we always send back replies in a timely manner or if we are requested to do so.

The raw stream is only advanced as quickly as `extract_transaction` allows, though. If PostgreSQL emits tons and tons of data records in a txn and then requests a keepalive, we'll only see the keepalive once we've processed all those messages from the transaction.

I'm not entirely sure what went wrong with the customer problem, as we're lacking metrics/logs that give us visibility into the number of messages processed inside of a transaction. The transaction sizes were measured in dozens of megabytes ([link](https://materializeinc.slack.com/archives/C03REC5MEKU/p1714088606850949?thread_ts=1714070439.625529&cid=C03REC5MEKU))—nothing that _should_ require a full minute to process.

Gut take, but it feels like this is a recent regression. Possibly related to https://github.com/MaterializeInc/materialize/pull/26267? Feels like maybe something pathological going on with operator scheduling.

----

In any world, still bullish on a quick fix of setting `wal_sender_timeout = '10m'`, to give ourselves some more headroom.

**Comment by sploiselle** [comment] 2024-05-08 17:03
@petrosagg ty for clarifying––my misunderstanding. I had thought that `extract_transaction` removed the items from the PG stream directly, but I see that they instead pull values out of `raw_stream`'s  output.

@benesch We do now set `wal_sender_timeout = '60s'` and haven't bumped into the issue again.

**Comment by benesch** [comment] 2024-05-09 01:22
> We do now set `wal_sender_timeout = '60s'` and haven't bumped into the issue again.

Oh! I missed https://github.com/MaterializeInc/materialize/pull/26818 go past. That’s great.

Looks like we’re just setting the WAL sender timeout to the default of 60s though. That was the number that gave the customer trouble. Should we consider bumping to 5m or 10m by default?

**Comment by sploiselle** [comment] 2024-05-09 01:25
They had their value set to 30s, which is what gave them trouble. I suggest we increase iff this bites them again.

**Comment by benesch** [comment] 2024-05-09 01:32
Ah, you’re so right. I misremembered. Ok, I feel good about our current situation. Feels like we can kick this one into the backlog as a p2 and only worry about it if we see it again in the wild.

**Comment by benesch** [comment] 2024-05-09 10:21
Oho, brilliant! This perfectly explains why the customer was running into trouble. Since we hardcode the `FEEDBACK_INTERVAL` to 30s, we need the `wal_sender_timeout` to be 30s plus a little slop. So when the customer set their `wal_sender_timeout` to 30s, we wouldn't be sending the eager feedback messages in time. 

I think we can basically close this out. Two thoughts:

  * I think we should add a comment in the code indicating that `wal_sender_timeout` must always be greater than `FEEDBACK_INTERVAL` plus a healthy fudge factor.
  * Do we want to consider wiring up `FEEDBACK_INTERVAL` to a LD flag for good measure? Not strictly necessary, but it might be a nice lever to have in the future if we have a customer who can't tolerate a `wal_sender_timeout` of 60s for some reason.

**Comment by petrosagg** [comment] 2024-05-09 10:53
> We had a user with a 30-second

oh duh, I glossed over the first sentence of this issue! Yes that must be what happened.

> I think we should add a comment in the code indicating

Afaik we don't have a reason to have an opinion on the `wal_sender_timeout`. Our current strategy of picking half of that as the feedback interval has worked very well for anyone having that value set to 60 seconds. I put up a PR that reverts https://github.com/MaterializeInc/materialize/pull/26818 and instead adaptively picks the feedback interval based on whatever the db administrator has set `wal_sender_timeout` to.

https://github.com/MaterializeInc/materialize/pull/27005

**Closed** 2024-05-09 15:14 UTC
Labels: C-refactoring, A-STORAGE
