### ISSUE TITLE
Error while querying unmaterialized view based on Postgres source

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#11232] opened 2022-03-15 13:22 UTC
### What version of Materialize are you using?

v0.22.1-dev (aa2362140)

### How did you install Materialize?

Built from source

### What was the issue?

If I try to query (with a `SELECT * FROM view`) an unmaterialized view based on a Postgres source that has no active materializations, the query either:
- hangs seemingly forever
- fails with an error similar to `ERROR:  Source error: u58/23: failed during initialization, must be dropped and recreated: db error: ERROR: replication slot "materialize_db8a808de40047c4834b631150b880cd" already exists`
- returns zero rows

The "returns zero rows" behavior is the rarest outcome, and I only managed to reproduce it for the first queries soon after the `materialized` starts.

The error tends to happen if you run a `SELECT` immediately after cancelling a hanging `SELECT`.

### How to reproduce

1. Create a new Postgres table and subscription
2. Insert a single record in the table above (optional)
3. Create a Postgres source based on the subscription above
4. Run `CREATE VIEWS FROM SOURCE source_name;`
5. Repeatedly query the view created for the table directly (e.g. if the table is called `mztx` on Postgres, run `SELECT * FROM mztx`)

### Relevant log output
Every time the select doesn't fail, I get a similar line in the logs:
```source
2022-03-15T13:16:02.150943Z  INFO mz_dataflow::source::postgres: replication snapshot for source u58/23 succeeded
```
```

**Comment by andrioni** [comment] 2022-03-15 13:23
cc @petrosagg @frankmcsherry @philip-stoev

**Comment by guswynn** [comment] 2022-03-15 16:56
The "returns 0 rows" outcome is _probably_ the same as https://github.com/MaterializeInc/materialize/issues/11072
where, on a fresh source, we have no timestamp bindings to drive the short-lived instance to actually obtain data before the `SELECT` finishes

As for the other bugs, they _might_ be specific to postgres, but caused by the way that the `PostgresSourceReader` works, @nharring-adjacent might know more about how replication slots work

**Comment by nharring-adjacent** [comment] 2022-03-15 17:26
I would be interested to see if this behavior changed with either of the Postgres source changes I merged recently (https://github.com/MaterializeInc/materialize/pull/10721 around PostgresSourceReader itself and https://github.com/MaterializeInc/materialize/pull/11083 which refactored `CREATE VIEWS FROM SOURCE` for Postgres sources.)

**Comment by elindsey** [comment] 2022-05-09 21:50
Merging this into https://github.com/MaterializeInc/materialize/issues/11048

**Closed by elindsey** 2022-05-09 21:50 UTC
Labels: C-bug, T-correctness
