### ISSUE TITLE
error: executing query failed: db error: ERROR: Evaluation error: internal error: Invalid data in source, saw net-zero records for key ("C") with non-zero accumulation in accumulable aggregate

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27453] opened 2024-06-05 02:16 UTC
### What version of Materialize are you using?

4c9c744a16

### What is the issue?

```
17:1: error: executing query failed: db error: ERROR: Evaluation error: internal error: Invalid data in source, saw net-zero records for key ("C") with non-zero accumulation in accumulable aggregate: ERROR: Evaluation error: internal error: Invalid data in source, saw net-zero records for key ("C") with non-zero accumulation in accumulable aggregate
```
Seen in https://buildkite.com/materialize/nightly/builds/7972#018fe44e-9799-4390-971b-cf7caa2502f0, seems flaky.

The error location itself was last touched in https://github.com/MaterializeInc/materialize/pull/18772 in August.

ci-regexp: Invalid data in source, saw net-zero records for key

**Comment by teskje** [comment] 2024-06-05 09:19
@def- Considering that this happens in the same CI run that also had a bunch of `Mismatched aggregates for key in ReduceCollation` errors, and all of them are connected with selecting from a MySQL source, I'm inclined to believe that his is the same issue as https://github.com/MaterializeInc/materialize/issues/27455, caused by invalid data in sources. Is there a reason to believe it's something else?

**Comment by def-** [comment] 2024-06-05 12:25
The other tests were with toggling txn-wal+mysql, while this one was just with mysql, but maybe that was just a coincidence and they are indeed indicative of the same root cause.

**Comment by teskje** [comment] 2024-06-07 12:38
https://github.com/MaterializeInc/materialize/issues/27455 has turned out to not be related to txn-wal, so I'm optimistically closing this. Feel free to reopen should the issue reoccur even with the fix for https://github.com/MaterializeInc/materialize/issues/27455.

**Closed by teskje** 2024-06-07 12:38 UTC
Labels: C-bug, A-compute, ci-flake
