### ISSUE TITLE
Difficulties using TAIL from a NodeJS backend

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#7160] opened 2021-06-24 18:01 UTC
I encountered the following issues trying to build a realtime application based on `TAIL`:

* `TAIL` outputs rows that can have conflicting names if the target view contains columns named `timestamp`, `diff`, or `progressed`
Timestamp in particular is a pretty common name. Libraries that auto convert rows into hashmaps (like node-postgres) will only keep one of the two. While it is possible to use alternative APIs and access the row as an array, it's cumbersome.
**Proposal:** We could choose less likely names for the system columns like `mz_timestamp`, `mz_diff`, and `mz_progressed`

* My application was listening on the `TAIL` stream and was reconstructing the collection according to the diffs. I wanted to only release well-formed collections to the rest of the application so the receiving code needed to know when a timestamp is complete. `TAIL` doesn't provide a consistent mechanism for that, even when you do `WITH (PROGRESS)`. The timestamps progress if you get a row where it has `progressed=true` OR if you receive a row with a timestamp higher than the previous row. This also implies that data might be buffered on the materialize side to make this happen.
**Proposal**: Always send progress messages when a timestamp closes and don't hold back any row data, at least in the `WITH (PROGRESS)` mode

* The diff field is declared as a `i64` which makes the javascript client to provide it as a string since JS only has 64bit floats.
**Proposal:** Make the diff field `i32`. It's extremely unlikely that any system will produce a single row with cardinality over 2 billion

**Comment by benesch** [comment] 2021-06-25 07:19
Point 1 is https://github.com/MaterializeInc/materialize/issues/5908, and the proposal you suggest here is the one agreed upon by everyone!

cc @mjibson for thoughts on point 2.

Re point 3: I'm really loathe on the Materialize side to do anything to work around JS's numeric woes. We had this problem at Cockroach too, and, well, folks who use PostgreSQL seriously from JS are used to dealing with this, and usually have some workarounds. JS is slowly getting a `BigInt` type that may one day be supported by node-pg: https://github.com/brianc/node-pg-types/issues/78. In the meantime you can use [`pg.defaults.parseInt8()`](https://github.com/brianc/node-postgres/blob/4b229275cfe41ca17b7d69bd39f91ada0068a5d0/packages/pg/lib/defaults.js#L78) to YOLO it if you're sure you'll never see an int8 that exceeds the maximum safe integer.

**Comment by petrosagg** [comment] 2021-06-25 10:05
oh, great about #5908! amazing that we ended up in an identical proposal

re point 3: If the rule is "we don't cut corners because of JS", then I fully agree with it and I will argue that this change does not violate it. The argument that `i64` is excessive for the diff field I think stands on its own regardless of the minor JS inconvenience that made me realize it. I also saw that `repr::Diff`is defined as `isize` in the code, is that on purpose?

In my demo I did the even YOLOer thing of using `==` instead of `===` to let JS do its type coercion abominations :P

**Comment by philip-stoev** [comment] 2021-06-25 11:09
Every time a 32-bit has been used for anything internal to the database system it has overflowed and had to be changed to a 32-bit integer. record IDs, message IDs, anything , always. I suggest we keep this a 64-bit thing.

If you have a source with 2 billion NULLs in it, you can potentially get a diff with such a large value if you are very unlucky.

**Comment by petrosagg** [comment] 2021-06-25 11:11
Alright, I'm convinced. I withdraw point 3 :)

**Comment by mjibson** [comment] 2021-06-25 17:18
I *thought* that `progress=true` produced periodic messages even if there were no rows. There's no code that buffers in the "after dataflow" side. We even specifically care about the case where there's no rows and thus just a progress event https://github.com/MaterializeInc/materialize/blob/4d68d9eed8bc78421631c374324429827e282f8f/src/dataflow/src/sink/tail.rs#L77. So I'm not sure what's going on there? It might be a dataflow-side thing which I don't know about.

**Comment by benesch** [comment] 2021-06-28 01:42
Adding to To Do in both SQL and Coordinator and Sources and Sinks so we don't lose track of this. There's definitely something strange here. @petrosagg, would you be able to provide repro instructions for the missing progress messages?

**Comment by mjibson** [comment] 2021-06-28 16:18
This is easily reproducible though:

```materialize=> create table t (i int);
CREATE TABLE
materialize=> copy (tail t with (progress=true)) to stdout;
```

has no output, when I would expect it to. It perhaps did at one point and this regressed.

**Comment by mjibson** [comment] 2021-06-29 17:56
I was not able to produce empty progress messages for any version since this was released in 0.5.2 so I assume I misremember having them ever. We just wrote the code such that they might exist, but they never did.

**Comment by mjibson** [comment] 2021-06-29 18:11
I've opened https://github.com/MaterializeInc/materialize/issues/7257 to track the empty progress messages.

**Comment by benesch** [comment] 2021-06-29 18:51
Ok, sounds like #7257 covers it then!

**Closed by benesch** 2021-06-29 18:51 UTC
Labels: C-feature
