### ISSUE TITLE
CREATE SOURCE dbt macro

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#7074] opened 2021-06-16 16:03 UTC
details forthcoming, [requested by a user](https://docs.google.com/document/d/1PZg6P0XAOHM0tuKxhXUAcmMeaq87fizPT-l-38SM9Ew/edit#bookmark=id.xh9u6usgvpap) (internal doc). unknown priority

if we're adding CREATE SOURCE, we should consider adding CREATE SINK as well.

**Comment by nmeagan11** [comment] 2021-06-18 19:18
Updated with priority P2 as there have been a couple user requests for this feature.

**Comment by benesch** [comment] 2021-06-18 20:48
Have we gotten clarity on what exactly users are asking for?

**Comment by awang** [comment] 2021-06-21 14:02
@nmeagan11 can you add details?

**Comment by awang** [comment] 2021-06-21 17:06
i think these 2 issues might have more details:  https://github.com/MaterializeInc/materialize/issues/6788 and https://github.com/MaterializeInc/materialize/issues/6249

**Comment by benesch** [comment] 2021-06-21 17:10
Oops, sorry, did not mean to press the "close" button here!

**Comment by nmeagan11** [comment] 2021-06-21 17:59
@awang #6249 is a duplicate of this ticket, so I will close this out. 

@benesch There are more details in #6249, but to answer your question, our dbt adaptor is limited on what Materialize statements it supports, as we have not implemented all of the macros. There are now use cases where users want their dbt models to include creating Materialize sources.

**Closed by nmeagan11** 2021-06-21 17:59 UTC
Labels: C-feature, P2
