### ISSUE TITLE
S3 sources - drop/recreate of s3 source and dependent view shows differing row counts from before recreate

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#8023] opened 2021-08-24 14:10 UTC
Testing on 0.8.3, download binaries. 

Sequence of events - 

1. Create s3 source with sqs notifications. Create materialized view.
2. Load data into bucket
3. Check count
4. Load finishes.
5. check count 
6. Drop and recreate source
7. Check count. I see this count is > than count from step 5.

Attached zip file allows for recreating the scenario.

[demonstration.zip](https://github.com/MaterializeInc/materialize/files/7039801/demonstration.zip)

**Comment by frankmcsherry** [comment] 2021-08-24 14:17
Do you know which count of the three is the correct count?

**Comment by quodlibetor** [comment] 2021-08-24 16:07
Something surprising about this is that we are in fact downloading objects correctly, looking at the materialized.log file (after massaging and filtering) we end up with a record that looks like the following. Note in particular that source_id's are alternating here, I've just sorted the lines after moving the source_id to the end of the line. With the exception of one trailing u33/30 from probably a previous run, this looks like exactly what I would expect:

```text
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_48_875898.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_48_875898.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_52_246409.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_52_246409.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_55_482660.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_55_482660.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_58_684721.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_58_684721.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_12_41969.json   source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_12_41969.json   source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_15_316154.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_15_316154.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_18_651167.json  source_id=u33/30
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_18_651167.json  source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_18_651167.json  source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_2_47330.json    source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_2_47330.json    source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_5_339844.json   source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_5_339844.json   source_id=u40/40
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_8_833797.json   source_id=u40/39
successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_8_833797.json   source_id=u40/40
```

confirmed by actually machine counting:

```console
$ uniq -c /tmp/tmp.log | sort -n
   2 successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_48_875898.json
   2 successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_52_246409.json
   2 successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_55_482660.json
   2 successfully downloaded s3mztest2/2021/8/24/15/43/mock_data_58_684721.json
   2 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_12_41969.json
   2 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_15_316154.json
   2 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_2_47330.json
   2 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_5_339844.json
   2 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_8_833797.json
   3 successfully downloaded s3mztest2/2021/8/24/15/44/mock_data_18_651167.json
```

So the actual S3 object discovery appears to be the same in both cases. The objects also all appear to be the same size, and to have the same amount of data getting sent to dataflow (all related logs are "sent 489 chunks to reader").

I need to investigate more, there aren't any obvious bugs in the logs, unfortunately.

**Comment by quodlibetor** [comment] 2021-08-24 16:34
Okay we figured it out, the observed behavior is #7423. In detail, steps to reproduce are:

* create an s3 bucket, but put no data in it
* create two views that depend on the same *unmaterialized* SQS-dependent source
* start putting objects in the bucket

These two views will end up receiving different subsets of the data, because each view must read and delete messages from SQS in order to make forward progress through the SQS queue. On the second view instantiation the data already exists, and so the bucket scan for each view can just read the data successfully.

Until we fix this, it is possible to work around the multiple views being dependent on the same SQS queue losing data by either:

* using a materialized source
* creating different sources for each downstream view which each depend on a unique SQS queue, and using AWS SNS to fork S3 event notifications into each of the SQS queues.

**Comment by quodlibetor** [comment] 2021-08-25 13:29
I'm going to close this as a dupe of 7423.

**Closed by quodlibetor** 2021-08-25 13:29 UTC
Labels: C-bug
