### ISSUE TITLE
Materialized views forget ordering

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#15065] opened 2022-09-29 09:24 UTC
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

The effect of an `ORDER BY` clause is lost when reading the output of a `SELECT` through a materialized view:

```
materialize=> select a from (values (1), (2), (3), (4), (5)) t(a) order by a desc;
 a
---
 5
 4
 3
 2
 1
(5 rows)

materialize=> create materialized view mv as select a from (values (1), (2), (3), (4), (5)) t(
a) order by a desc;
CREATE MATERIALIZED VIEW
materialize=> select * from mv;
 a
---
 1
 2
 3
 4
 5
(5 rows)
```

**Comment by uce** [comment] 2022-09-29 09:29
This is a duplicate of #724. That ticket also links other duplicates.

cc @ggnall For UX awareness

**Closed by uce** 2022-09-29 09:29 UTC
Labels: C-bug, A-COMPUTE, A-ADAPTER
