### ISSUE TITLE
environmentd OOM'ing/growing memory utilization

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#15354] opened 2022-10-12 14:22 UTC
### What version of Materialize are you using?

/

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The environment of a prospect is experiencing memory issues. The issue is vague and mostly serves to anchor related information.
* environmentd, storage, compute memory utilization increasing with no workload
* Profiling `environmentd` shows `ActiveReplicationState::handle_comand` as one place where allocations happen.
* Little more is known

Context: https://materializeinc.slack.com/archives/C0403RW9NAZ/p1665408594282749

### Related tasks

* [x] #15531
* [x] #15704
* [ ] #15828
* [x] #15831
* [x] #15847
* [x] #15930
* [x] #15952
* [x] #16326

**Comment by lluki** [comment] 2022-10-20 08:18
Yesterday (on v0.28.0) we saw some environments that a continuously growing memory usage on environmentd. One theory was that leaking peek commands is the cause (see #15531), however the memory growth we saw was too fast to be caused by this bug.
I just had a look at that environment (us-east-1-staging, `2841`) again and with v0.28.3 deployed, `envd` now has a stable (or very slow growing) memory consumption. It seems plausible to me that v0.28.3 + fixing #15531 fixes this issue.

**Comment by vmarcos** [comment] 2022-10-26 14:06
This [discussion](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1666790066832059) may be relevant for another potential source of leaking memory in management of `collections` in an `Instance`.

**Comment by lluki** [comment] 2022-11-24 14:49
I re-ran the [metadata stress ](https://github.com/lluki/mat-meta-stresstes) test on the latest main `v0.32-dev`  bcf6fc5d0e02d39b18da1b62d884760d35f4a4fe. The situation has improved but memory consumption of computed and environmentd are still clearly growing. 

This is the situation while hammering environmentd with create + drop table, materialized views etc. There are no more than 20 objects alive at any point in time.
![mem-growth](https://user-images.githubusercontent.com/2659045/203811191-acbf9f53-45e7-48e7-8e29-a7d8c8ca6dad.png)

**Comment by teskje** [comment] 2023-01-09 08:54
As far as I am aware, we are currently not experiencing memory leaks caused by compute. The only sub-task still open on this ticket is https://github.com/MaterializeInc/materialize/issues/15828, which is independently assigned to the storage team and project. So I'm closing this issue, as there is nothing to do for the compute team here.

**Closed by teskje** 2023-01-09 08:54 UTC
Labels: C-bug, A-stability, A-COMPUTE
