### ISSUE TITLE
DDL statements become very slow during CRDB upgrades

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#17651] opened 2023-02-13 16:52 UTC
*Follow up from incident 38 (https://github.com/MaterializeInc/cloud/issues/5504).*

### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

We recently observed DDL statements temporarily become very slow (> 1 minute for creating views). This coincided with rolling upgrades being performed on our CRDB clusters, so it is likely that the latter caused the slowdown. We should investigate if the issue lies on our side or CRDB's.

Relevant discussion: [Slack](https://materializeinc.slack.com/archives/CM7ATT65S/p1676304831721299) and [Slack](https://materializeinc.slack.com/archives/C04Q25C35L0).

**Comment by benesch** [comment] 2023-02-14 15:55
As mentioned on Slack: I think it'd be great to throw the QA team at this, and see if they can reproduce in a local mzcompose or kind test. It may require running a multi-node Cockroach cluster and doing a graceful (one-at-a-time) restart. If we can reproduce this in a test, it will be _much_ easier to find and fix the problem in Materialize (vs having to deploy to staging and .. somehow triggering a graceful restart of the staging Cockroach cluster).

**Comment by philip-stoev** [comment] 2023-02-15 10:22
Test case in https://github.com/MaterializeInc/materialize/issues/17680 , apologies for opening a new ticket.

**Comment by benesch** [comment] 2023-02-16 03:53
Closing as a (retroactive) duplicate of #17680.

**Closed by benesch** 2023-02-16 03:53 UTC
Labels: C-bug, A-STORAGE, A-ADAPTER
