### ISSUE TITLE
regression:  thread 'timely:work-3' panicked at 'failed to correctly cast channel', communication/src/allocator/process.rs:144:13

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17310] opened 2023-01-24 07:51 UTC
### What version of Materialize are you using?

v0.41.0

### How did you install Materialize?

Docker image

### What is the issue?

The `DataflowsLarge` Zippy scenario in the Release Qualification Test has panicked as follows

https://buildkite.com/materialize/release-qualification/builds/68#0185dec4-a52d-4a50-a0dc-faa83a3e6da2

This panic has not been seen in many months.

The command that is being run is:

```
cd test/zippy
./mzcompose run default --scenario=DataflowsLarge --actions=100000
```
on a `c6a.12xlarge` machine. The test failed in 38 min.

### Relevant log output

```source
zippy-storaged-1         | thread 'timely:work-3' panicked at 'failed to correctly cast channel', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/communication/src/allocator/process.rs:144:13
zippy-storaged-1         | stack backtrace:
zippy-storaged-1         | 2023-01-23T15:38:43.366935Z  INFO mz_compute::server: Timely already initialized; re-using.
zippy-storaged-1         |    0: rust_begin_unwind
zippy-storaged-1         |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
zippy-storaged-1         |    1: core::panicking::panic_fmt
zippy-storaged-1         |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
zippy-storaged-1         |    2: core::panicking::panic_display
zippy-storaged-1         |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139:5
zippy-storaged-1         |    3: core::panicking::panic_str
zippy-storaged-1         |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123:5
zippy-storaged-1         |    4: core::option::expect_failed
zippy-storaged-1         |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879:5
zippy-storaged-1         |    5: <timely_communication::allocator::process::Process as timely_communication::allocator::Allocate>::allocate::<(usize, usize, alloc::vec::Vec<((timely::progress::Location, core::time::Duration), i64)>)>
zippy-storaged-1         |    6: <timely_communication::allocator::generic::Generic>::allocate::<(usize, usize, alloc::vec::Vec<((timely::progress::Location, core::time::Duration), i64)>)>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/communication/src/allocator/generic.rs:54:36
zippy-storaged-1         |    7: <timely_communication::allocator::generic::Generic as timely_communication::allocator::Allocate>::allocate::<(usize, usize, alloc::vec::Vec<((timely::progress::Location, core::time::Duration), i64)>)>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/communication/src/allocator/generic.rs:91:9
zippy-storaged-1         |    8: <timely::worker::Worker<timely_communication::allocator::generic::Generic> as timely::worker::AsWorker>::allocate::<(usize, usize, alloc::vec::Vec<((timely::progress::Location, core::time::Duration), i64)>)>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/worker.rs:239:9
zippy-storaged-1         |    9: <timely::progress::broadcast::Progcaster<core::time::Duration>>::new::<timely::worker::Worker<timely_communication::allocator::generic::Generic>>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/progress/broadcast.rs:37:33
zippy-storaged-1         |   10: <timely::progress::subgraph::SubgraphBuilder<(), core::time::Duration>>::build::<timely::worker::Worker<timely_communication::allocator::generic::Generic>>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/progress/subgraph.rs:184:26
zippy-storaged-1         |   11: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::dataflow_core::<core::time::Duration, (), <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::dataflow<core::time::Duration, (), <timely::synchronization::sequence::Sequencer<mz_storage::internal_control::InternalStorageCommand>>::preloaded<timely_communication::allocator::generic::Generic>::{closure#0}>::{closure#0}, alloc::boxed::Box<()>>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/worker.rs:642:28
zippy-storaged-1         |   12: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::dataflow::<core::time::Duration, (), <timely::synchronization::sequence::Sequencer<mz_storage::internal_control::InternalStorageCommand>>::preloaded<timely_communication::allocator::generic::Generic>::{closure#0}>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/worker.rs:566:9
zippy-storaged-1         |   13: <timely::synchronization::sequence::Sequencer<mz_storage::internal_control::InternalStorageCommand>>::preloaded::<timely_communication::allocator::generic::Generic>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/synchronization/sequence.rs:113:9
zippy-storaged-1         |   14: <timely::synchronization::sequence::Sequencer<mz_storage::internal_control::InternalStorageCommand>>::new::<timely_communication::allocator::generic::Generic>
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/synchronization/sequence.rs:92:9
zippy-storaged-1         |   15: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::setup_command_sequencer
zippy-storaged-1         |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0af0baf26b9b4e847-1/materialize/tests/src/storage/src/internal_control.rs:69:9
zippy-storaged-1         |   16: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
zippy-storaged-1         |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0af0baf26b9b4e847-1/materialize/tests/src/storage/src/storage_state.rs:301:33
zippy-storaged-1         |   17: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
zippy-storaged-1         |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0af0baf26b9b4e847-1/materialize/tests/src/storage/src/storage_state.rs:288:33
zippy-storaged-1         |   18: mz_storage::server::serve::{closure#1}
zippy-storaged-1         |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0af0baf26b9b4e847-1/materialize/tests/src/storage/src/server.rs:87:9
zippy-storaged-1         |   19: timely::execute::execute::<(), mz_storage::server::serve::{closure#1}>::{closure#1}
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/timely/src/execute.rs:287:22
zippy-storaged-1         |   20: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute<(), mz_storage::server::serve::{closure#1}>::{closure#1}>::{closure#0}
zippy-storaged-1         |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/faf5eb6/communication/src/initialize.rs:316:33
zippy-storaged-1         | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by aljoscha** [comment] 2023-01-24 09:07
I have a suspicion that this is caused by the bug that was fixed in https://github.com/MaterializeInc/materialize/pull/17268. The commit in question doesn't have that fix, but the most recent release and `main` should have it. I'm running tests on a `ci-large` instance with the fix, to see if it reproduces.

**Comment by aljoscha** [comment] 2023-01-25 13:14
Closing this as fixed by #17268. Which was confirmed by re-running release qualification tests.

**Closed by aljoscha** 2023-01-25 13:14 UTC
Labels: C-bug, release-blocker
