### ISSUE TITLE
environmentd stops downgrading since on read handles if computed restarts

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#14261] opened 2022-08-16 15:09 UTC
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

If `computed` restarts, `environmentd` will stop sending `PersistWorkerCmd::Downgrade` calls to its read handles for the introspection shards. This can be easily reproduced locally:

1. Run `./bin/environmentd`
2. `pkill -f computed`
3. The metrics on `environmentd` (localhost:6878/metrics) and for `computed` (localhost:2102/metrics) will show that  `mz_persist_shard_upper` continues to grow, but `mz_persist_shard_since` _does not_ advance for any of the shards `computed` is writing to

This causes persist state to grow without bound which becomes very problematic for Cockroach

**Comment by antiguru** [comment] 2022-08-16 16:25
I can reproduce the issue but haven't determined the cause for it. It seems best if someone from the persist team provides some guidance on how the `since` information flows through the system.

**Comment by frankmcsherry** [comment] 2022-08-16 16:39
I think we should be able to observe (or not observe) the storage controller call `persist_read_handles.downgrade()` in response to `update_read_capabilities`. If that is happening, it could be a `persist` issue, but my first guess would be that this isn't happening for some crazy reason. If that *is* happening, .. idk it could be a read lease held by the failed `computed` that takes 15 minutes to get sorted out?

**Comment by antiguru** [comment] 2022-08-17 08:22
It could be we're retracting a timestamp twice:
```
environmentd: 2022-08-17T08:20:23.805309Z DEBUG set_read_policy:update_read_capabilities: mz_compute_client::controller: updates: System(346) -> ChangeBatch { updates: [(1660724422775, -1), (1660724423000, 1)], clean: 2 }
environmentd: 2022-08-17T08:20:23.805361Z DEBUG set_read_policy:update_read_capabilities: mz_compute_client::controller:         with changes: ChangeBatch { updates: [(1660724422775, -1), (1660724423000, 1)], clean: 0 }
[kill computed]
environmentd: 2022-08-17T08:20:32.826683Z DEBUG set_read_policy:update_read_capabilities: mz_compute_client::controller: updates: System(346) -> ChangeBatch { updates: [(1660724431775, -1), (1660724432000, 1)], clean: 2 }
environmentd: 2022-08-17T08:20:32.826749Z DEBUG set_read_policy:update_read_capabilities: mz_compute_client::controller:         with changes: ChangeBatch { updates: [(1660724431775, -1), (1660724432000, 1)], clean: 0 }
```

**Comment by lluki** [comment] 2022-08-18 09:31
I can reproduce the issue and I verified that we do set the read policy correctly on restart. 

So what is actually different on restart? My best theory right now is that we call `.create_collections` ([in coord.rs](https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/coord.rs#L385-L391))  with already existing collections. I thought this is safe, but maybe it's not? Or it causes some interference with the `set_read_policy` that follows?

**Comment by pH14** [comment] 2022-08-19 15:58
I walked through this one some more, and what I'm finding is that after `computed` restarts, we no longer generate a new read capability for the storage collection.

Prior to restarting, `computed` will send its `FrontierUppers` change batches of `[(ts_a, -1), (ts_b, +1)]`. After restarting, it resumes with `[(0, -1), (ts_c, +1)]` where `ts_c > ts_b` and never retracts `ts_b`. 

This causes the call to `generate_new_capability_for_collection` to generate updates of `[(ts_b, -1), (ts_b, +1)]` in perpetuity, which freezes the read capability at a point in time prior to the `computed` restart.  https://github.com/MaterializeInc/materialize/blob/2671c07d9ff20a498c890a2a61e861f57d4c1fde/src/storage/src/controller.rs#L1070-L1076

@antiguru is it possible we're missing something in the `computed` rehydration logic to allow the process to resume its frontier from where it left off?

**Comment by aljoscha** [comment] 2022-08-19 16:45
You can add some logging to see where exactly this happens, see [1]. With this, you will get a log like the following which shows that the frontier update diffs don't line up, which makes it stuck. `computed` is sending updates as if it is assuming that the compute controller is starting from scratch, but it already has a different view of the frontier so the diffs don't make sense to it:

```
environmentd: 2022-08-19T15:54:14.271588Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(0, -1), (1660924455000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:15.244524Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924455000, -1), (1660924456000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:16.245119Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924456000, -1), (1660924457000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:17.252982Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924457000, -1), (1660924458000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:18.261664Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924458000, -1), (1660924459000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:19.284549Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924459000, -1), (1660924460000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:20.277409Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924460000, -1), (1660924461000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:21.283380Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924461000, -1), (1660924462000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:22.290703Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924462000, -1), (1660924463000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:23.299208Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924463000, -1), (1660924464000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:24.310703Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924464000, -1), (1660924465000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:25.315216Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924465000, -1), (1660924466000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:26.321508Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924466000, -1), (1660924467000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:27.331887Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924467000, -1), (1660924468000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:28.344841Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924468000, -1), (1660924469000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:29.345160Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924469000, -1), (1660924470000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:30.353048Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924470000, -1), (1660924471000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:31.362757Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924471000, -1), (1660924472000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:32.367911Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924472000, -1), (1660924473000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:33.379449Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924473000, -1), (1660924474000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:34.382746Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924474000, -1), (1660924475000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:35.388973Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924475000, -1), (1660924476000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:36.395323Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924476000, -1), (1660924477000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:37.402212Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924477000, -1), (1660924478000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:38.416890Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924478000, -1), (1660924479000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:39.417813Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924479000, -1), (1660924480000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:40.424773Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924480000, -1), (1660924481000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:41.442138Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924481000, -1), (1660924482000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:42.440139Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924482000, -1), (1660924483000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:43.460216Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924483000, -1), (1660924484000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:44.073012Z ERROR mz_orchestrator_process: compute-cluster-1-replica-1 exited: Ok(ExitStatus(unix_wait_status(15))); relaunching in 5s
environmentd: 2022-08-19T15:54:44.073376Z  WARN mz_compute_client::controller::replicated: replica task for 1 failed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2022-08-19T15:54:44.073790Z  INFO mz_compute_client::controller::replicated: starting replica task for 1
environmentd: 2022-08-19T15:54:44.077879Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 125ms: transport error
environmentd: 2022-08-19T15:54:44.202450Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 250ms: transport error
environmentd: 2022-08-19T15:54:44.455670Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 500ms: transport error
environmentd: 2022-08-19T15:54:44.956785Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 1s: transport error
environmentd: 2022-08-19T15:54:45.957739Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 2s: transport error
environmentd: 2022-08-19T15:54:47.960139Z  WARN mz_compute_client::controller::replicated: error connecting to replica 1, retrying in 4s: transport error
environmentd: 2022-08-19T15:54:49.075299Z  INFO mz_orchestrator_process: Launching compute-cluster-1-replica-1: --controller-listen-addr=127.0.0.1:2100 --internal-http-listen-addr=127.0.0.1:2102 --workers=1 --opentelemetry-resource=instance_id=1 --opentelemetry-resource=replica_id=1 localhost:2101 --process=0 --opentelemetry-resource=replica_index=0 --log-filter=info --log-prefix=compute-cluster-1-replica-1 --pid-file-location=/Users/aljoscha/Dev/rust/materialize/mzdata/compute-cluster-1-replica-1-0.pid --secrets-reader=process --secrets-reader-process-dir=/Users/aljoscha/Dev/rust/materialize/mzdata/secrets...
compute-cluster-1-replica-1: 2022-08-19T15:54:49.104297Z  INFO computed: about to bind to 127.0.0.1:2100
compute-cluster-1-replica-1: 2022-08-19T15:54:49.104381Z  INFO computed: serving internal HTTP server on 127.0.0.1:2102
compute-cluster-1-replica-1: 2022-08-19T15:54:49.108994Z  INFO mz_compute::communication: initialization complete worker=0
compute-cluster-1-replica-1: 2022-08-19T15:54:49.113017Z  INFO mz_service::grpc: Starting to listen on 127.0.0.1:2100
compute-cluster-1-replica-1: 2022-08-19T15:54:51.963759Z  INFO mz_service::grpc: GrpcServer: remote client connected
environmentd: 2022-08-19T15:54:51.965169Z  INFO mz_service::grpc: GrpcClient localhost:2100: connected
compute-cluster-1-replica-1: 2022-08-19T15:54:52.002663Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
environmentd: 2022-08-19T15:54:52.035069Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(0, -1), (1660924492000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:52.083061Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924492000, -1), (1660924493000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:54.004962Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924493000, -1), (1660924494000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:55.006497Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924494000, -1), (1660924495000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:56.023917Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924495000, -1), (1660924497000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:57.026971Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924497000, -1), (1660924498000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:58.036401Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924498000, -1), (1660924499000, 1)], clean: 2 }
environmentd: 2022-08-19T15:54:59.040755Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924499000, -1), (1660924500000, 1)], clean: 2 }
environmentd: 2022-08-19T15:55:00.045511Z  INFO mz_compute_client::controller: s349: ChangeBatch { updates: [(1660924500000, -1), (1660924501000, 1)], clean: 2 }
```

[1] [0001-print-frontier-updates-for-s349.patch.txt](https://github.com/MaterializeInc/materialize/files/9383888/0001-print-frontier-updates-for-s349.patch.txt)

**Comment by frankmcsherry** [comment] 2022-08-19 17:03
fwiw, the above is expected behavior. When `computed` restarts, the controller also restarts tracking each of its frontiers from [`0`].

**Comment by frankmcsherry** [comment] 2022-08-19 17:53
The issue appears to be that the introspection shards, which are written to by individual replicas, do not participate in the active replication logic, and have only ever echod their upper information out (as the active replication machinery does nothing for them, and is potentially confusing as replicas have nothing to say about the shards of other replicas).

The `upper`s of non-introspection collections seem fine, and resume cleanly across restarts.

I judge this as correctly assigned to @antiguru for further triage. Two candidate solutions are:
1. Record reported frontier information in 
```rust
    persisted_logs: BTreeMap<LogVariant, (GlobalId, CollectionMetadata)>,
```
2. Have each of these shards participate in active replication, but just with "slow" other replicas.

It feels like the correct long term solution is for the storage controller to own `upper` advancement for storage collections.

**Closed** 2022-08-23 10:19 UTC
Labels: C-bug, P1, C-triage
