### ISSUE TITLE
ci: cluster smoke test: panicked at 'cannot serve requested as_of:

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#12885] opened 2022-06-05 02:09 UTC
The "cluster smoke test" in CI very occasionally flakes. The issue occurs at the step where it kills one replica in a two-replica cluster and expects the cluster to still be healthy. When the test flakes, the replica that is expected to still be healthy has failed like so:

```
thread 'timely:work-0' panicked at 'cannot serve requested as_of: Since(Antichain { elements: [1654385320489] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e2a3fad493b0a1ef-1/materialize/tests/src/storage/src/source/persist_source.rs:61:24
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1035:23
   4: mz_storage::source::persist_source::persist_source::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
   7: mz_storage::source::persist_source::persist_source::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e2a3fad493b0a1ef-1/materialize/tests/src/storage/src/source/persist_source.rs:139:47
   8: mz_storage::source::util::source::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e2a3fad493b0a1ef-1/materialize/tests/src/storage/src/source/util.rs:97:45
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
  10: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  11: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:684:30
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:344:26
  14: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:310:17
  15: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:684:30
  16: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:344:26
  17: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:310:17
  18: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:754:57
  19: core::option::Option<T>::map
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:912:29
  20: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:754:26
  21: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:396:38
  22: mz_compute::server::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e2a3fad493b0a1ef-1/materialize/tests/src/compute/src/server.rs:172:13
  23: mz_compute::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e2a3fad493b0a1ef-1/materialize/tests/src/compute/src/server.rs:114:13
  24: timely::execute::execute_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/execute.rs:388:22
  25: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I've only been able to reproduce this once, by running the cluster test in a loop repeatedly for an hour.

cc @petrosagg @danhhz can you triage?

**Comment by philip-stoev** [comment] 2022-06-06 08:06
I can reproduce this readily (as in, right away) on my Hetzner machine. Let me know if SSH access is needed.

**Comment by danhhz** [comment] 2022-06-06 15:02
as far as I can tell, persist is doing the right thing here. this is a panic in storage code in response to a `Result::Err` coming out of persist that indicates a snapshot or listen was requested at an as_of frontier that has already lost historical detail. feels like debugging needs to start with how storage ended up requesting an `as_of` that's lagged behind the shard `since`

I need to get up to speed on storage code at some point, but I haven't yet. @petrosagg or @aljoscha are presumably the likely candidates for digging into this

**Comment by frankmcsherry** [comment] 2022-06-16 14:26
Per @andrioni this seems to happen in a multi-replica case, where one *does* expect this error to happen (https://github.com/MaterializeInc/materialize/issues/12576). What is a bit surprising is that this results in test failure, as opposed to the slower replica crashing and restarting. The only thing that comes to mind without looking closer is that there is some where situation where both replicas end up "behind" on a view, probably each one of two different views, and they each fail to start back up.

Probably good for COMPUTE to look at this and identify what is happening, ensure enough tracing is in place that we can observe this in the future, and then shake out the right way to prevent all the toe stepping. Unless the theory above is totally wrong, ofc.

**Comment by teskje** [comment] 2022-06-20 08:41
I can reproduce this reliably on my local machine.

This is the test code:

```python
c.up("materialized")
c.wait_for_materialized()

# 1. Create a remote cluster and verify that tests pass.
c.up("computed_1")
c.up("computed_2")
c.sql("DROP CLUSTER IF EXISTS cluster1 CASCADE;")
c.sql(
    "CREATE CLUSTER cluster1 REPLICAS (replica1 (REMOTE ['computed_1:2100', 'computed_2:2100']));"
)
c.run("testdrive", *glob)

# 2. Add a replica to that remote cluster and verify that tests still pass.
c.up("computed_3")
c.up("computed_4")
c.sql(
    "CREATE CLUSTER REPLICA cluster1.replica2 REMOTE ['computed_3:2100', 'computed_4:2100']"
)
c.run("testdrive", *glob)

# 3. Kill one of the nodes in the first replica of the compute cluster and
# verify that tests still pass.
c.kill("computed_1")
c.run("testdrive", *glob)

# 4. Leave only replica 2 up and verify that tests still pass.
c.sql("DROP CLUSTER REPLICA cluster1.replica1")
c.run("testdrive", *glob)
```

In step 2, when `replica2` is spawned and the testdrive is run, this is when it crashes for me with the `cannot serve requested as_of` error reported above. Then in step 3, we also kill `replica1`, so now there is no replica left anymore to serve queries and the test hangs forever.

AFAICT from looking at persist trace logs and print debugging, the crash of `replica2` is indeed caused by #12576. I see that `replica1` drops its read capability for a storage collection, and then `replica2` tries to read the same collection at the time of this read capability.

> What is a bit surprising is that this results in test failure, as opposed to the slower replica crashing and restarting.

The test uses remote replicas, not managed ones. Since they are not managed by the orchestrator, there is nothing that would feel responsible for restarting them, right?

**Comment by benesch** [comment] 2022-06-20 19:17
> The test uses remote replicas, not managed ones. Since they are not managed by the orchestrator, there is nothing that would feel responsible for restarting them, right?

That's right! I imagine this is desirable behavior, @philip-stoev? Otherwise we wouldn't have noticed this issue. If we _di_ want automatic restarts, though, it'd be easy enough to wire up [Docker restart policies](https://docs.docker.com/engine/reference/run/#restart-policies---restart).

**Comment by philip-stoev** [comment] 2022-07-22 07:18
@frankmcsherry This panic just happened on a test that only uses 1 replica - 

https://buildkite.com/materialize/nightlies/builds/1024#018224b5-45cd-4306-bf36-4bb57a7b1a65

On the call yesterday you mentioned that this panic is acceptable in multi-replica cases. What about single-replica situations?

**Comment by frankmcsherry** [comment] 2022-07-22 10:16
Very surprising!

**Comment by antiguru** [comment] 2022-07-25 11:53
I'm observing this error the second time today. All I did was
```
bin/environmentd --release --reset
# Hit Ctrl+C
bin/environmentd --release
```

This leaves the replica in a crash-loop which it apparently cannot recover from. It doesn't reproduce every time, so I can't give more specific instructions.

```
environmentd: 2022-07-25T11:53:04.278825Z  INFO mz_orchestrator_process: Launching compute-cluster-1-replica-106: --controller-listen-addr=127.0.0.1:2103 --internal-http-listen-addr=127.0.0.1:2105 --workers=8 --opentelemetry-resource=instance_id=1 --opentelemetry-resource=replica_id=106 localhost:2104 --process=0 --opentelemetry-resource=replica_index=0 --log-filter=info --log-prefix=compute-cluster-1-replica-106 --pid-file-location=/home/moritz/dev/repos/materialize/mzdata/compute-cluster-1-replica-106-0.pid --secrets-reader=process --secrets-reader-process-dir=/home/moritz/dev/repos/materialize/mzdata/secrets...
compute-cluster-1-replica-106: 2022-07-25T11:53:04.299528Z  INFO computed: about to bind to 127.0.0.1:2103
compute-cluster-1-replica-106: 2022-07-25T11:53:04.299555Z  INFO computed: serving internal HTTP server on 127.0.0.1:2105
worker 0:       initialization complete
compute-cluster-1-replica-106: 2022-07-25T11:53:04.303625Z  INFO mz_service::grpc: Starting to listen on 127.0.0.1:2103
compute-cluster-1-replica-106: 2022-07-25T11:53:07.161176Z  INFO mz_service::grpc: GrpcServer: remote client connected
environmentd: 2022-07-25T11:53:07.161421Z  INFO mz_service::grpc: GrpcClient localhost:2103: connected
compute-cluster-1-replica-106: 2022-07-25T11:53:07.171183Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping
thread 'timely:work-0' panicked at 'cannot serve requested as_of: Since(Antichain { elements: [1658745527000] })', /home/moritz/dev/repos/materialize/src/storage/src/source/persist_source.rs:69:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
environmentd: 2022-07-25T11:53:07.567131Z  WARN mz_compute_client::controller::replicated: replica task for 106 failed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2022-07-25T11:53:07.567136Z ERROR mz_orchestrator_process: compute-cluster-1-replica-106 exited: Ok(ExitStatus(unix_wait_status(6))); relaunching in 5s
environmentd: 2022-07-25T11:53:07.567162Z  INFO mz_compute_client::controller::replicated: starting replica task for 106
environmentd: 2022-07-25T11:53:07.567600Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 125ms: transport error
environmentd: 2022-07-25T11:53:07.693375Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 250ms: transport error
environmentd: 2022-07-25T11:53:07.944390Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 500ms: transport error
environmentd: 2022-07-25T11:53:08.445852Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 1s: transport error
environmentd: 2022-07-25T11:53:09.447880Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 2s: transport error
compute-cluster-1-replica-2: 2022-07-25T11:53:10.021744Z  INFO mz_persist_client::r#impl::machine: snapshot sfa2b004e-dba8-43d6-98ac-9931f773c6fc as of Antichain { elements: [0] } not yet available for upper Antichain { elements: [0] } retrying in 16s
environmentd: 2022-07-25T11:53:11.449195Z  WARN mz_compute_client::controller::replicated: error connecting to replica 106, retrying in 4s: transport error
```

**Comment by teskje** [comment] 2022-07-25 11:56
@antiguru This looks like what was reported [here](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1658489569228959). Can you try if this goes away with https://github.com/MaterializeInc/materialize/pull/13795?

**Comment by antiguru** [comment] 2022-07-29 11:13
I can't reproduce the error anymore, neither the way I was able to repro earlier this week or using the instructions provided by @teskje. @philip-stoev, can you still reproduce the problem?

I checked if I could find the problem in CI in the last few days, but I didn't see it.

**Comment by philip-stoev** [comment] 2022-07-29 11:56
It last happened here https://buildkite.com/materialize/nightlies/builds/1033#0182351f-af15-4a60-a40b-4e3d97315b13, so a couple of days ago.

The following test was running:
```
cd test/platform-checks
./mzcompose run default --scenario=RestartComputed
```

**Comment by antiguru** [comment] 2022-08-31 09:57
The same problem seems to affect `storaged` itself, for example in https://buildkite.com/materialize/tests/builds/40526#0182ec1b-6d2d-4f99-94f2-72c72fcfa983:

```
platform-checks-materialized-1      | thread 'timely:work-0' panicked at 'cannot serve requested as_of: Since(Antichain { elements: [1661818787001] })', src/storage/src/source/persist_source.rs:126:24
platform-checks-materialized-1      | stack backtrace:
platform-checks-materialized-1      |    0: rust_begin_unwind
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
platform-checks-materialized-1      |    1: core::panicking::panic_fmt
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
platform-checks-materialized-1      |    2: core::result::unwrap_failed
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
platform-checks-materialized-1      |    3: core::result::Result<T,E>::expect
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
platform-checks-materialized-1      |    4: mz_storage::source::persist_source::persist_source_core::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
platform-checks-materialized-1      |    5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |    6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
platform-checks-materialized-1      |    7: mz_storage::source::persist_source::persist_source_core::{{closure}}::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f3a1f3243d4e622d-1/materialize/tests/src/storage/src/source/persist_source.rs:174:47
platform-checks-materialized-1      |    8: mz_storage::source::util::source::{{closure}}::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f3a1f3243d4e622d-1/materialize/tests/src/storage/src/source/util.rs:103:17
platform-checks-materialized-1      |    9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
platform-checks-materialized-1      |   10: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
platform-checks-materialized-1      |   11: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
platform-checks-materialized-1      |   12: timely::progress::subgraph::PerOperatorState<T>::schedule
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
platform-checks-materialized-1      |   13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
platform-checks-materialized-1      |   14: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
platform-checks-materialized-1      |   15: timely::progress::subgraph::PerOperatorState<T>::schedule
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
platform-checks-materialized-1      |   16: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
platform-checks-materialized-1      |   17: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
platform-checks-materialized-1      |   18: timely::worker::Wrapper::step::{{closure}}
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:57
platform-checks-materialized-1      |   19: core::option::Option<T>::map
platform-checks-materialized-1      |              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:929:29
platform-checks-materialized-1      |   20: timely::worker::Wrapper::step
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:26
platform-checks-materialized-1      |   21: timely::worker::Worker<A>::step_or_park
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:396:38
platform-checks-materialized-1      |   22: mz_storage::storage_state::Worker<A>::run_client
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f3a1f3243d4e622d-1/materialize/tests/src/storage/src/storage_state.rs:135:17
platform-checks-materialized-1      |   23: mz_storage::storage_state::Worker<A>::run
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f3a1f3243d4e622d-1/materialize/tests/src/storage/src/storage_state.rs:111:33
platform-checks-materialized-1      |   24: mz_storage::protocol::server::serve::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f3a1f3243d4e622d-1/materialize/tests/src/storage/src/protocol/server.rs:94:9
platform-checks-materialized-1      |   25: timely::execute::execute::{{closure}}
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/execute.rs:287:22
platform-checks-materialized-1      |   26: timely_communication::initialize::initialize_from::{{closure}}
platform-checks-materialized-1      |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/communication/src/initialize.rs:316:33
```

**Comment by philip-stoev** [comment] 2022-09-07 10:41
Happened again in Buildkite : https://buildkite.com/materialize/tests/builds/40603#0182f14c-5cd1-4962-9736-9f6de897957f

**Comment by aljoscha** [comment] 2022-09-09 14:56
I enriched the error message in #14735. Please report any new occurrences of this.

**Comment by aljoscha** [comment] 2022-09-19 17:12
I think the `storaged` failure might have been fixed by https://github.com/MaterializeInc/materialize/pull/14785.

**Comment by cjubb39** [comment] 2022-09-19 17:14
^ please give a shout if this error pops up again on anything that includes the PR aljoscha mentioned!

**Closed** 2022-09-28 17:36 UTC
Labels: P1, A-COMPUTE, ci-flake

**Comment by teskje** [comment] 2022-09-29 07:33
I merged a fix for the issue where the since frontier of storage collection was not correctly held back for slow replicas in a multi-replica setting. My hope is that this resolves all remaining instances of the "cannot serve requested as_of" we were still seeing in CI. Please scream if you observe that not to be the case!

**Comment by benesch** [comment] 2022-09-29 20:08
Thanks _very_ much, @teskje! So good to finally get this one closed!
