### ISSUE TITLE
Schema Registry: Cache Failure Results

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#4181] opened 2020-09-10 18:10 UTC
Materialize will output some complaint of "NaN value not matching the schema in the json", particularly when evolving the schema.  This may cause Materialize to hammer Schema Registry.

If there's some issue with the schema we will just retry on every message instead of caching the failure result

**Comment by umanwizard** [comment] 2020-09-10 18:28
dupe of #4180

**Closed by umanwizard** 2020-09-10 18:28 UTC
Labels: C-bug
