### ISSUE TITLE
Joining logs does not work when Materialize is under heavy load

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4147] opened 2020-09-03 16:04 UTC
When Materialize is under heavy load and has slowed down dramatically, it is natural to want to run some [diagnostic queries](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/diagnostic-queries.md) or query a logging view such as `mz_records_per_dataflow_global `.

However, running diagnostic queries or querying a logging view with an underlying join often returns `"Timestamp ({}) is not valid for all inputs: {:?}"`. It is especially inconvenient that it becomes harder to get information from internal logs right when you really want to know what's behind a performance problem.

Notes:
1. This has also been observed to sporadically happen when Materialize is not under heavy load.
2. There is a workaround, albeit quite an inconvenient one, in that one can query the logging sources (each query may take minutes on end) and then manually stitch the information together. 

Prospect requests:
1. Can the error message in this case be improved so that a user would be better informed how to work around this problem?
2. Can system logs have a separate, longer, compaction window to reduce the chances of the error happening while keeping user data quite compact?

**Comment by ruchirK** [comment] 2020-09-03 16:13
This is likely exacerbated by the fact that system logs currently have a hardcoded logical compaction window of 1s

```
 286                 CatalogItem::Index(_) => {
 287                     if BUILTINS.logs().any(|log| log.index_id == *id) {
 288                         // Indexes on logging views are special, as they are
 289                         // already installed in the dataflow plane via
 290                         // `SequencedCommand::EnableLogging`. Just teach the
 291                         // coordinator of their existence, without creating a
 292                         // dataflow for the index.
 293                         //
 294                         // TODO(benesch): why is this hardcoded to 1000?
 295                         // Should it not be the same logical compaction window
 296                         // that everything else uses?
 297                         coord
 298                             .indexes
 299                             .insert(*id, Frontiers::new(coord.num_timely_workers, Some(1_000)));
```

in src/coord/src/coord.rs

**Comment by frankmcsherry** [comment] 2020-09-03 20:04
> There is a workaround, albeit quite an inconvenient one, in that one can query the logging sources (each query may take minutes on end) and then manually stitch the information together.

I think another work around is creating a materialized view for the `select` and then querying that. The issue is roughly that the views are out of sync, and one needs to wait for the others to catch up. Materializing a dataflow should do that. Also worth fixing the issue, but "out of sync sources" is a thing that we'll have to solve generally.

**Comment by benesch** [comment] 2020-10-08 18:03
Duplicate of #3983.

**Closed by benesch** 2020-10-08 18:03 UTC
Labels: C-bug, T-UX, T-beta-customer-priority, T-performance
