### ISSUE TITLE
Staging environment has CPU leak (in persist GC?)

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#19892] opened 2023-06-13 06:04 UTC
@RobinClowers's staging environment's `environmentd` pod has been slowly leaking CPU over the past few days:

<img width="1656" alt="image" src="https://github.com/MaterializeInc/materialize/assets/882976/6af57f46-8831-4ca5-9fa4-0c762d770240">

Org ID: 9e57afd1-45e2-45bb-8a11-2d224bd3d427
pprof: https://pprof.me/94d746a

The pprof linked above points at persist GC, so tagging in @danhhz and co.

The actual _symptom_ in this environment is that about once a minute the coordinator takes ~12s to respond to a `SELECT mz_version()` query. My theory is that persist GC is starving out a Tokio task for 12s spinning hot on ... something ... that causes all other work on that Tokio task to cease until the hot loop subsides.

**Comment by benesch** [comment] 2023-06-13 06:05
Persist GC dashboards mirror the CPU usage:



![Image](https://github.com/MaterializeInc/materialize/assets/882976/2d347125-83fa-48b3-8e89-746f2fe03a38)

**Comment by danhhz** [comment] 2023-06-13 14:19
Seems a lot like the bit we left unfixed in #17214, which has popped up from time to time since then but always fixed itself before it got bad enough that we needed to do anything about it. I'll poke at it

**Comment by benesch** [comment] 2023-06-13 14:44
@pH14 had the same take and is also poking at it a bit on Slack, just in case you hadn't seen! https://materializeinc.slack.com/archives/C02FWJ94HME/p1686664669817499?thread_ts=1686589988.099459&cid=C02FWJ94HME

**Comment by danhhz** [comment] 2023-06-13 14:59
yeah, just saw!

possible that the way this fixes itself is we roll the env, so I think we should try that to confirm as a mitigation or not

there's a small-ish piece of compaction 2.0 that can be pulled out and that i believe will fix 17214 for good. i've been holding off on it because other things have been higher priority and so far, no one has noticed this when it happened. might be time to time to go ahead and do that. (i thought i filed an issue for this small-ish piece but not finding it right now. i'll either dig it up or file one)

**Comment by danhhz** [comment] 2023-06-13 15:17
restarted. might take 15m (for leases to expire) plus a bit after to settle out. i'll check back in then

**Comment by RobinClowers** [comment] 2023-06-13 15:23
Do we understand what about my env caused this large shard? Does it have to do with the fact that I had a source that couldn't connect somehow? Or maybe having a postgres source that had very little data that didn't update over time?

**Comment by danhhz** [comment] 2023-06-13 18:16
@pH14 fixed this by running the persistcli force-compaction tool on the shard. given that we already have a tracking issue for the underlying bug and the problem is resolved, i'm going to go ahead and close this as a...

dup of #17214

<img width="925" alt="image" src="https://github.com/MaterializeInc/materialize/assets/52528/29a2bf37-d534-4ee1-9a39-c77b6b69dca9">

<img width="920" alt="image" src="https://github.com/MaterializeInc/materialize/assets/52528/17c0a2da-aa54-419b-b9b1-dd9a32bce077">

**Closed by danhhz** 2023-06-13 18:16 UTC
