### ISSUE TITLE
Cannot ORDER BY column not in the selection list

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#2804] opened 2020-04-28 14:59 UTC
When writing the following query:
`mz> create materialized view c as SELECT count(*) FROM orderline GROUP BY ol_w_id, ol_d_id ORDER BY ol_w_id, ol_d_id`

We get the following error:
`column "ol_w_id" does not exist` (even though show columns from table confirms it does)

In fact, the issue is on the ORDER BY, and disappears when we remove the ORDER BY clause.

**Comment by nacrooks** [comment] 2020-04-28 15:00
I'm not sure if the issue is that we do not support ORDER BY on installed materialized views (@frankmcsherry mentioned a while back that we don't?) or another issue, but either way the error message is pretty misleading

**Comment by frankmcsherry** [comment] 2020-04-28 16:09
The issue here is that the `ORDER BY` is applied to the selected columns, but there is only `count(*)` there. You probably want
```
SELECT ol_w_id, ol_d_id, count(*) 
FROM orderline 
GROUP BY ol_w_id, ol_d_id 
ORDER BY ol_w_id, ol_d_id
```
I agree that the error message doesn't helpfully lead you to this. I'm not sure what the investment is there to provide better tooling around query parsing. @benesch might be able to say whether improved name resolution would better identify the problem here.

**Comment by justinj** [comment] 2020-04-28 17:08
That's a bug though, right? PG allows you to order by columns not projected by the select:
```
postgres=# create table xyz (x int, y int, z int);
CREATE TABLE
postgres=# select count(*) from xyz group by y, z;
 count
-------
(0 rows)

postgres=# select count(*) from xyz group by y, z order by y, z;
 count
-------
(0 rows)
```

**Comment by justinj** [comment] 2020-05-20 16:46
I'm going to rename this issue since I think this is an actual bug.

**Comment by justinj** [comment] 2020-05-20 16:48
Simpler repro:

```sql
CREATE TABLE x (a int);
```

Materialize:
```sql
materialize=> select a+1 from x order by a;
ERROR:  column "a" does not exist
```

PG:
```sql
postgres=# select a+1 from x order by a;
 ?column?
----------
        2
        3
        4
(3 rows)
```

**Comment by wangandi** [comment] 2020-05-29 17:41
Is this a duplicate of #696?

**Comment by justinj** [comment] 2020-05-29 17:44
Looks like it!

**Closed by justinj** 2020-05-29 17:44 UTC
Labels: C-bug, T-UX
