### ISSUE TITLE
Debezium sources with upsert semantics

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5709] opened 2021-02-10 15:46 UTC
There seem to be two related classes of thing that people mean when they ask for debezium/upsert sources:

(1) If the data is perturbed, we shouldn't get confusing negative multiplicity errors. That is; we should just ignore the `before` field and use the `after` field to inform us of the current value.

(2) Key-based compaction of Debezium sources should be possible.

I think for (2), it would be enough to retain the set of keys, rather than the full rows as we do for "raw" (i.e., non-Debezium) upsert sources. The logic would be as follows:

1. When a record of the form `{"k": "foo", "v": {"before": "v1", "after": "v2"}}` is received, we check the set of keys. If there is none, this _was_ an update, but is now an insert (due to key-based compaction). Thus, emit `(("foo", "v2"), +1)`.
2. If on the other hand we _have_ seen the key, then we need to use the `before` field to retract its previous value and insert the new one; therefore, we emit `(("foo", "v1"), -1); (("foo", "v2"), +1)`.

If, however, we want to use this feature to work around misordered and duplicated Debezium data (use-case "(1)" at the beginning of this post), we would need to store the full set of keys and values (as we do for "raw" upsert sources now), because in general we can't trust the "before" field to be accurate.

**Comment by ruchirK** [comment] 2021-02-10 19:07
We had a conversation in a weekly sync that basically echoed the writeup-here but just to reiterate, there's two potential flavors of upsert we could potentially do

1. "key-only-upsert" -- we keep the set of keys materialized in memory. use the absence / existence of a key to determine whether we use the before field or not
2. "traditional upsert: we keep keys and values materialized in memory and only look at the after field.

I believe both approaches let us handle key-based compaction and time based compaction, but (1) is cheaper than (2) from a memory / compute POV and (2) is resilient to glitches in data. if the data in the topic "eventually" converges to the correct value then this will too.

**Comment by ruchirK** [comment] 2021-02-15 16:21
A note -- I think there's maybe more room for solutions in "resilient to glitches" than I thought.

key-only-upsert could store along with the key, a 64 bit fingerprint of the most recently inserted value. then when we get a new before / after we could compare the before's fingerprint to the fingerprint we had stored -- if they don't match we might have a problem. IIUC this approach wouldn't really have false positives (because the hash function should give us the same hash for the same thing twice), but we might have false negatives (because two different things might yield the same hash). I haven't thought hard about hash function collision probabilities yet, but I think for a best effort thing we can afford to be fairly tolerant?

**Comment by benesch** [comment] 2021-02-18 19:21
I think it would work in the sense that as long as you didn't care about having extremely inconsistent data, we'd be able to show you _something_.

**Comment by frankmcsherry** [comment] 2021-02-19 13:35
This could be a fine thing to test out "source orthogonality lite" with. Users can today just use it as a debezium source, push it through a threshold operator, and then .. idk "do a topk by offset" (but I think we don't present the offset for DBZ; oh well). 

Like, imo they should at least be able to try:
``` 
CREATE SOURCE my_dbz_w_errors = ...;

CREATE VIEW inserts AS
SELECT * FROM my_dbz_w_errors
EXCEPT ALL
SELECT * FROM my_dbz_retractions;

CREATE VIEW deletes AS
SELECT * FROM my_dbz_retractions
EXCEPT ALL
SELECT * FROM my_dbz_w_errors;
```
This does a thing where it pushes potentially negated records through a `RelationExpr::Threshold`, and shows both the positive and negative elements as `inserts` and `deletes`. They can use the `inserts` and potentially consult the `deletes` to see what is messed up.

If the problem is actually "Debezium sources w/o retractions but please do upsert logic for me" this doesn't solve that problem, but it could help them deal with "lol idk what data are there but please make it make sense".

**Comment by ruchirK** [comment] 2021-02-19 13:55
I'm trying to wrap my head around this

1. I'm not sure why EXCEPT ALL becomes a threshold but I think I can ignore that for now

2. if they got

(before: none, after (x, y))
(before: (x, y), after (x, z))

would inserts have

((x, y), 1) and deletes have ((x, z), 1) and deletes have

((x, y), 1) -- is that the right idea?

**Comment by frankmcsherry** [comment] 2021-02-19 14:20
1. `a EXCEPT ALL b` is planned as `b.negate().concat(a).threshold()`.
2. inserts would have `(x,z)` and deletes would be empty, in my take on this example data.

**Comment by quodlibetor** [comment] 2021-03-10 22:31
I have been looking at this for awhile and trying to think through and experiment with the both fastest and best way to make progress, and I think I've got a plan.

First, some context for folks who've had internal discussions around this: we've discussed adding adding a `KeyUpsert` or `DebeziumUpsert` variant to our [`SourceEnvelope`](https://github.com/MaterializeInc/materialize/blob/e0d118fde96e47ec9509d8bf94697978a3818ee1/src/dataflow-types/src/types.rs#L522-L528) enum.

However, that doesn't particularly affect the implementation: we specifically need to decide whether to move the decoding logic out of the [existing upsert function](https://github.com/MaterializeInc/materialize/blob/947e8a1b1239660bdd7f52d2290b7cebf997e498/src/dataflow/src/render/upsert.rs#L36) or inject something into that function that causes it to behave differently.

Complicating the decision is the place that upsert sits with relation to the ongoing source orthogonality work. Upsert operates on a timely stream, and Debezium decoding also operates on a timely stream, but unfortunately their stream formats are incompatible.

This is visible in the code as [a branch](https://github.com/MaterializeInc/materialize/blob/c2b1d36b954ed590f0867db68a8a03914c24953c/src/dataflow/src/render/sources.rs#L202-L233).

* Both Debezium decoding and Upsert processing:
  * Take a stream that includes kafka keys and kafka values
  * Emit a stream that does not include the kafka keys
* But they differ in how they emit retractions, and in the format of their outputs:
  * upsert processing [emits retractions literally](https://github.com/MaterializeInc/materialize/blob/c2b1d36b954ed590f0867db68a8a03914c24953c/src/dataflow/src/render/upsert.rs#L197-L202)
  * Debezium processing on the other hand internally basically ignores the debezium format and
    emits rows that just contain the `before`/`after` values [in a single row](https://github.com/MaterializeInc/materialize/blob/c2b1d36b954ed590f0867db68a8a03914c24953c/src/interchange/src/avro/envelope_debezium.rs#L53).

    It then depends on [some planned dataflow commands](https://github.com/MaterializeInc/materialize/blob/c2b1d36b954ed590f0867db68a8a03914c24953c/src/sql/src/plan/statement/ddl.rs#L326) which get executed [a bit later in import_source](https://github.com/MaterializeInc/materialize/blob/c2b1d36b954ed590f0867db68a8a03914c24953c/src/dataflow/src/render/sources.rs#L337-L338)

---

Moving on to the specific proposal, I think it makes sense to make the following
modifications:

* For the key-based-compaction part we add an `UpsertMode::{Value,Debezium}` parameter to
  `SourceEnvelope::Upsert` such that it becomes `SourceEnvelope::Upsert(DataEncoding,
  UpsertMode)`.
* To teach upsert about Debezium I think that the easiest thing to do is to modify
   [`DecoderState::decode_upsert_value`](https://github.com/MaterializeInc/materialize/blob/947e8a1b1239660bdd7f52d2290b7cebf997e498/src/dataflow/src/decode/mod.rs#L121-L129)
  method to return an `Option<insert>`/`Option<retract>` pair (all the existing methods would
  unconditionally return `None` for the retraction). But it might make sense to just teach upsert
  about the embedded before/after row format. This latter option feels slightly more orthogonal, but might require a larger refactor of other upsert sources making it worse for the short term.

  The upsert operator would then be modified to emit rows that match the Debezium envelope row
  format (with embedded before/after structs).
* Planning is modified to allow the combination of debezium and upsert, but otherwise gets to be
  pretty ignorant of these changes.

**Comment by quodlibetor** [comment] 2021-03-11 15:04
That's a good poitn, thanks Ruchir. If trying to parameterize the upsert code gets too hairy I might do that.

**Comment by umanwizard** [comment] 2021-03-11 22:16
Your plan makes sense to me. Sanity check: we expect that if someone is running this, they should be able to turn off Dbz deduplication completely, right? (Because even if there is duplication, the _latest_ value in Kafka will still be correct)

**Comment by umanwizard** [comment] 2021-03-17 22:26
@quodlibetor ^ can you confirm the above?

**Comment by quodlibetor** [comment] 2021-05-13 17:11
> we expect that if someone is running this, they should be able to turn off Dbz deduplication completely, right? (Because even if there is duplication, the latest value in Kafka will still be correct)

Yes, we've verified that this is true.

Closing this because it's done via #6210 #6301 #6301

**Closed by quodlibetor** 2021-05-13 17:11 UTC
Labels: C-feature
