### ISSUE TITLE
"Cluster smoke test" is flaky

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#14598] opened 2022-09-02 18:56 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/40811#0182ff3d-2c85-43ba-b1a3-561ecff5a967

### Relevant log output

```source
pg-snapshot-resumption/03-while-storaged-down.td	1s
> SELECT COUNT(*) FROM t1;
 
pg-snapshot-resumption/03-while-storaged-down.td:10:1: error: deadline has elapsed
     |
   9 |
  10 | > SELECT COUNT(*) FROM t1;
     | ^
!!! Error Report	0s
1 errors were encountered during execution
```

### Additional thoughts

Appears to be a timeout. Always seems to present the same way.

Other examples:
* https://buildkite.com/materialize/tests/builds/40779#0182fbb4-a126-4dd6-a1fb-0e959dd7997a
* https://buildkite.com/materialize/tests/builds/40718#0182f879-da4a-4826-b722-0620fff10058
* https://buildkite.com/materialize/tests/builds/40830#018300f2-7ec1-4354-9443-64017f9cd97f
* https://buildkite.com/materialize/tests/builds/41025#01831568-1ddd-48bb-b65e-540704c91579

Possibly related to #14590.

**Comment by aljoscha** [comment] 2022-09-07 12:08
Probably same as https://github.com/MaterializeInc/materialize/issues/14533?

**Comment by aljoscha** [comment] 2022-09-08 12:43
Closing as duplicate of #14533

**Closed by aljoscha** 2022-09-08 12:43 UTC
Labels: C-bug, P2, ci-flake
