### ISSUE TITLE
data-ingest: thread 'timely:send-0' panicked at 'failed to send MergeQueue: "SendError(..)"'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22027] opened 2023-09-28 07:20 UTC
### What version of Materialize are you using?

d44111b700

### What is the issue?

```
data-ingest-materialized-1     | thread 'timely:send-0' panicked at 'failed to send MergeQueue: "SendError(..)"', /cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/communication/src/allocator/zero_copy/tcp.rs:146:31
data-ingest-materialized-1     | stack backtrace:
data-ingest-materialized-1     | cluster-u3-replica-u3: 2023-09-27T23:46:16.279323Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(true), enable_arrangement_size_logging: Some(true), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), consensus_connection_pool_ttl: Some(300s), consensus_connection_pool_ttl_stagger: Some(6s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 1.2s, multiplier: 2, clamp: 100ms }), reader_lease_duration: Some(900s), sink_minimum_batch_updates: Some(128), storage_sink_minimum_batch_updates: Some(100), stats_audit_percent: Some(100), stats_collection_enabled: Some(true), stats_filter_enabled: Some(true), stats_budget_bytes: Some(1024), stats_untrimmable_columns: Some(UntrimmableColumns { equals: ["err", "ts", "receivedat", "createdat"], prefixes: ["last_"], suffixes: ["timestamp", "time", "_at", "_tstamp"] }), pubsub_client_enabled: Some(true), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128), feature_flags: {"persist_streaming_compaction_enabled": true, "persist_streaming_snapshot_and_fetch_enabled": true} }, tracing: TracingParameters { log_filter: Some(info), opentelemetry_filter: Some(off) }, grpc_client: GrpcClientParameters { connect_timeout: Some(5s), http2_keep_alive_interval: Some(3s), http2_keep_alive_timeout: Some(5s) } }
data-ingest-materialized-1     | ********************************* WARNING ********************************
```
Seen in https://buildkite.com/materialize/nightlies/builds/4428#018ad8fc-8244-4984-a96b-3ec218f0b597
I'm rerunning to see if this is flaky or a regression (Edit: Appears to be a flake, not a regression). I'm worried about the lack of backtraces, the code location is https://github.com/TimelyDataflow/timely-dataflow/blob/b990faba8ea59ec2a7450809215145f3e940234a/communication/src/allocator/zero_copy/tcp.rs#L146

ci-regexp: panicked at 'failed to send MergeQueue: "SendError\(\.\.\)"'

**Comment by antiguru** [comment] 2023-09-28 13:33
From the logs:
`data-ingest-materialized-1     | cluster-u1-replica-u1: 2023-09-27T23:46:16.278881Z  WARN mz_cluster::communication: failed to initialize network: Resource temporarily unavailable (os error 11) process=1`

Duplicate of #20513.

**Closed by antiguru** 2023-09-28 13:33 UTC
Labels: C-bug, ci-flake
