### ISSUE TITLE
environmentd startup time depends on number or size of tables

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15380] opened 2022-10-13 06:03 UTC
### What version of Materialize are you using?

environmentd v0.27.0-alpha.24.post (0467d025c)

### How did you install Materialize?

Docker image

### What is the issue?

The Nightly "Zippy User Tables" has started to time out waiting for Materialize to restart towards the end of the test. Turns out that environment startup time (as measured until it starts listening to its SQL TCP socket) increases progressively as the test goes by and more data is inserted , until it becomes longer than 1 minute.

https://buildkite.com/materialize/nightlies/builds/1230#0183cbf7-47a1-4c03-8f0a-bf1f493240d4

In the absence of a distributed environmentd, a longer startup time puts an upper bound on the maximum uptime we can achieve in the cloud. According to @benesch environmentd startup time should not be influenced by the number or size of tables.

I am attaching two environmentd logs - the one from the first environmentd startup in the test and the one from the last. It is obvious that much more stuff is happening prior to opening the SQL TCP socket and that that stuff takes much longer.
[first.txt](https://github.com/MaterializeInc/materialize/files/9771244/first.txt)
[last.txt](https://github.com/MaterializeInc/materialize/files/9771243/last.txt)

**Comment by benesch** [comment] 2022-10-14 05:13
Thanks for filing, @philip-stoev! Added to the umbrella issue in #15379 too.

**Comment by jkosh44** [comment] 2022-10-17 15:44
One possibility is that this extra time is due to fencing tables during startup. During bootstrapping the Coord will fence out all tables by updating their `upper`s. Though this is just a guess, some actual perf benchmarking should tell us if this is true or not.

**Comment by jkosh44** [comment] 2022-10-26 20:52
After some inspiration from @mjibson I was able to reproduce this pretty significantly locally. After creating 773 tables, Materialize took close to 6 minutes to start up.

Attached is a full log of startup.
[startup.txt](https://github.com/MaterializeInc/materialize/files/9873609/startup.txt)

Here are some highlights:

- In between the log line `mz_adapter::coord: coordinator init: opening catalog` and `open: mz_adapter::catalog: create table materialize.public.t0 (u1)` took roughly 2 minutes. Something at the start of `catalog::Open` is taking a long time.
- We seem to have some duplicate logs. For every table we produce two identical log lines of the format: `create table materialize.public.t<i> (u<j>)`. I'm not sure if we are duplicating work or just duplicating log lines.
- Inbetween the log line `open: mz_adapter::catalog: create table materialize.public.t772 (u773)` and `open: mz_adapter::catalog: create table materialize.public.t0 (u1)` took roughly 2 minutes. So there's something else in `catalog::Open` that's taking a long time.
- Each call to `mz_adapter::coord: coordinator init: installing table <GID>` takes roughly 1/5 of a second. While this is not that slow, it adds up for all tables to take a significant amount of time. In contrast installing all other objects (sources, funcs, types, etc) is almost instantaneous.

**Comment by jkosh44** [comment] 2022-10-26 21:09
I think I just figured it out, I re-started my local instance with 773 tables after adding a bunch of logs to `catalog::Open`.
This function, although it has absolutely no effect, takes about 4 minutes to run and is responsible for the duplicate `create table materialize.public.t<i> (u<j>)` logs: https://github.com/MaterializeInc/materialize/blob/88a0a20b0bcdcd2f312e2638bbb7096ed8fef1a4/src/adapter/src/catalog/migrate.rs#L40-L60

**Comment by jkosh44** [comment] 2022-10-26 21:19
If I just comment out the contents of `migrate()` the startup time speeds up to 3 minutes, and nearly all of that time is spent in `installing table <GID>`. Attached is the logs of startup with `migrate()` removed, with some logs I added locally.
[startup_speedup.txt](https://github.com/MaterializeInc/materialize/files/9873826/startup_speedup.txt)

**Comment by guswynn** [comment] 2022-10-26 21:30
it looks `rewrite_items` unconditionally updates EVERY item even if it hasnt changed: https://github.com/MaterializeInc/materialize/blob/main/src/adapter/src/catalog/migrate.rs#L35 (and we call `rewrite_items` TWICE

**Comment by jkosh44** [comment] 2022-10-27 13:20
I did some more benchmarking of `migrate`. Almost the entire 4 minutes is spent inside of `rewrite_items`, it's called twice (as indicated above) and takes 2 minutes each time.

**Comment by jkosh44** [comment] 2022-10-27 13:33
Here is a breakdown of how long everything takes within `migrate`:
```
Loading items took: 2.686914ms.
Parsing took: 67.92133ms.
Transformations took: 211.828µs
Serialization took: 38.697383ms.
Updating items in transaction took: 128.516017429s
```
Not only is every item unconditionally updated as @guswynn pointed out, but a single call to update is O(n) in the number of items. Meaning that each `rewrite_items` will be O(n^2). I think the fix here is
1) Only update items that have changed.
2) Batch updates together.

**Comment by benesch** [comment] 2022-10-27 13:35
I like the sound of (2) more than (1). There are quite plausibly migrations we need to write that touch all items; I'd love for `environmentd` not to get massively slower on the weeks that we have to do those migrations vs. the weeks that we don't.

**Comment by jkosh44** [comment] 2022-10-27 14:04
Here is a breakdown of how long everything takes within `migrate` when batching item updates:
```
Loading items took: 2.742938ms.
Parsing took: 39.968273ms.
Transformations took: 69.893µs
Serialization took: 25.169463ms.
Updating items in transaction took: 150.271048ms
```

I'll have a PR open shortly.

**Comment by benesch** [comment] 2022-11-01 03:34
> but on the cloud with CRDB this transaction becomes very long.

It should be very easy to test this in cloud, if you want to validate! Not sure if the log lines you added are mergeable and /or merged, but if they are not, you can deploy an instrumented build to staging and measure there.

**Comment by ggnall** [comment] 2022-12-08 20:59
Closing this and adding a feature for consistent improved performance: https://github.com/MaterializeInc/materialize/issues/16531

**Closed by ggnall** 2022-12-08 20:59 UTC
Labels: C-bug, A-ADAPTER

**Comment by benesch** [comment] 2022-12-12 05:08
That's a great idea. Thanks, @ggnall!

**Comment by ggnall** [comment] 2022-12-12 15:17
credit to @mjibson! as part of his work on https://github.com/MaterializeInc/materialize/issues/16531
