### ISSUE TITLE
environmentd OoM in product-limits' Indexes scenario

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28236] opened 2024-07-15 11:39 UTC
### What version of Materialize are you using?

510ca1dbc3

### What is the issue?

Happens reliably since https://github.com/MaterializeInc/materialize/compare/261f0febce...510ca1dbc3: https://buildkite.com/materialize/nightly/builds/8532#0190a958-2d66-49e9-9acd-96594303ded9
```
2024-07-13 00:08:44 UTC	> SELECT f69 FROM t;
2024-07-13 00:08:44 UTC	rows match; continuing at ts 1720829324.6607249
2024-07-13 00:08:44 UTC	> SELECT f70 FROM t;
2024-07-13 00:10:44 UTC	rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 21s
2024-07-13 00:10:44 UTC	1153:1: error: preparing query failed: connection closed
2024-07-13 00:10:44 UTC	     |
2024-07-13 00:10:44 UTC	   6 | $ postgres-connect n ... [rest of line truncated for security]
2024-07-13 00:10:44 UTC	   7 | $ postgres-execute c ... [rest of line truncated for security]
2024-07-13 00:10:44 UTC	  11 | $ postgres-execute c ... [rest of line truncated for security]
2024-07-13 00:10:44 UTC	1152 | 69
2024-07-13 00:10:44 UTC	1153 | > SELECT f70 FROM t;
2024-07-13 00:10:44 UTC	     | ^
```
@jkosh44 Two of your changes look potentially responsible: #28208 and to a lesser degree #28210

Is this an expected regression?

ci-regexp: Memory cgroup out of memory
ci-apply-to: Product limits

**Comment by jkosh44** [comment] 2024-07-15 14:11
> Happens reliably since https://github.com/MaterializeInc/materialize/compare/261f0febce...510ca1dbc3
...
> @jkosh44 Two of your changes look potentially responsible: https://github.com/MaterializeInc/materialize/pull/28208 and to a lesser degree https://github.com/MaterializeInc/materialize/pull/28210

I re-ran Nightlies for #28208 (`ef798e33b4`) and #28210 (`388b0ef913`):

- `ef798e33b4`: https://buildkite.com/materialize/nightly/builds/8553
- `388b0ef913`: https://buildkite.com/materialize/nightly/builds/8552

Both jobs failed with OOM errors. Since, `388b0ef913` is older I think it's safe to say that it was not introduced by `ef798e33b4`.

**Comment by def-** [comment] 2024-07-15 14:17
> Both jobs failed with OOM errors. Since, 388b0ef913 is older I think it's safe to say that it was not introduced by ef798e33b4.

I'm also trying against the parent of ef798e33b4 to verify that: https://buildkite.com/materialize/nightly/builds/8560

**Comment by jkosh44** [comment] 2024-07-15 14:20
I started builds for the remaining commits in the range you specified:

- `b7414d366c`: https://buildkite.com/materialize/nightly/builds/8561
- `1e524ca338`: https://buildkite.com/materialize/nightly/builds/8559
- `b1fc0fa1f5`: https://buildkite.com/materialize/nightly/builds/8558

As well as the commit immediately before that range (`261f0febce`): https://buildkite.com/materialize/nightly/builds/8562

**Comment by jkosh44** [comment] 2024-07-15 15:15
This repro'd in `1e524ca338`, so I think it's safe to say that it was not introduced by `ef798e33b4`. This means that it was not introduced into v0.108.X. So while it's a release blocker for v0.109.X, v0.108.X is safe.

**Comment by jkosh44** [comment] 2024-07-15 19:09
Duplicate of https://github.com/MaterializeInc/materialize/issues/28217.

There are so many error logs, that the logs themselves cause an OOM.

**Closed by jkosh44** 2024-07-15 19:09 UTC
Labels: C-bug, release-blocker, A-ADAPTER
