### ISSUE TITLE
Sink Overview Page

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#28617] opened 2024-07-29 21:22 UTC
Link to the Notion Epic: https://www.notion.so/Sink-Overview-Page-1715140341e344a28ef2157029f91022

**Comment by chaas** [comment] 2024-07-29 21:26
Duplicate of https://github.com/MaterializeInc/console/issues/2423

**Closed by chaas** 2024-07-29 21:26 UTC
