### ISSUE TITLE
support multiplying intervals by integers

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#4163] opened 2020-09-07 14:56 UTC
In Postgres:

```
arjun=# select interval '1 minute' * 4;
 ?column? 
----------
 00:04:00
(1 row)
```

In materialize:
```
materialize=> select interval '1 minute' * 4;
ERROR:  no overload for interval * i32: arguments cannot be implicitly cast to any implementation's parameters; try providing explicit casts
```

**Comment by benesch** [comment] 2020-09-08 14:04
Duplicate of #3518.

**Closed by benesch** 2020-09-08 14:04 UTC
Labels: C-bug
