### ISSUE TITLE
sql: lint options

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#5367] opened 2021-01-18 19:30 UTC
It's easy for users to typo option values and encounter unexpected and unhelpful errors (e.g. #5133). We should have a step that ensures that all options got consumed and error if there are any unused options, giving the user a hint to check option names.

**Comment by benesch** [comment] 2021-01-20 06:06
Yep! But duplicate of #3562.

**Closed by benesch** 2021-01-20 06:06 UTC
Labels: C-feature, T-UX, U-community
