### ISSUE TITLE
Support pg_class

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#4326] opened 2020-09-29 15:28 UTC
Required for https://github.com/MaterializeInc/materialize/issues/4289#issuecomment-698110478

**Comment by benesch** [comment] 2020-09-30 04:07
Two quick followups from #4332!

  * Indexes have their own names, distinct from the table they're on! `SELECT * FROM pg_class` in Postgres, for example, will show index names as distinct from the relations on which the index is built.

  Looks like `mz_indexes` is missing a `name` field, but that should be pretty easy to add.  

  * relnamespace looks like it should be an OID rather than a string. That should be an easy fix though!

**Comment by benesch** [comment] 2020-09-30 04:52
Whoops, nerdsniped myself! https://github.com/MaterializeInc/materialize/pull/4340

**Comment by benesch** [comment] 2020-10-09 02:48
Duplicate of #4280.

**Closed by benesch** 2020-10-09 02:48 UTC
Labels: A-integration, A-sql, C-feature
