### ISSUE TITLE
Incorrect output to Kafka sink when calculating count

### ISSUE THREAD

**Issue by maver1ck** [MaterializeInc/materialize#4212] opened 2020-09-14 19:15 UTC
### What version of Materialize are you using?

v0.4.2

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [X] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

When created Kafka sink on materialized view output for simple count creates 2 messages instead of one.
Sample:
```
{"before":{"row":{"count":7}},"after":null}
{"before":null,"after":{"row":{"count":8}}}
```

It should be:
```
{"before":{"row":{"count":7}},"after":{"row":{"count":8}}}
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Create Kafka topic 
```
kafka-avro-console-producer \                                                                    
         --broker-list localhost:9092 --topic test \
         --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
```
Create Source, View and Sink:
```
CREATE SOURCE test
FROM KAFKA BROKER 'localhost:9092' TOPIC 'test'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081';

CREATE MATERIALIZED VIEW test_count1 AS select count(f1) from test;

CREATE SINK test_sink
FROM test_count1
INTO KAFKA BROKER 'localhost' TOPIC 'test-sink'
FORMAT AVRO USING
    CONFLUENT SCHEMA REGISTRY 'http://localhost:8081';
```

Check output of kafka consumer
```
 kafka-avro-console-consumer --topic test-sink-u7-1600109623-15327300333849980626 --bootstrap-server localhost:909
2 --from-beginning
{"before":{"row":{"count":7}},"after":null}
{"before":null,"after":{"row":{"count":8}}}
```

**Comment by benesch** [comment] 2020-09-16 05:27
I think this is actually working as intended. Internally we represent an update as a delete followed by an insert, which is what you're seeing here. Agreed it's a bit unexpected though; we've got some changes to the output format in the works.

@ruchirK can you double-check that this is expected?

**Comment by ruchirK** [comment] 2020-09-16 12:19
Yes, this is entirely as expected. @maver1ck for a bit more context, differential dataflow, the underlying compute engine that we've built Materialize on, represents updates as triples of 

```
(data, timestamp, diff)
```
(where `diff` denotes how many copies of `data` were added to / removed from a collection at `timestamp`)
so in the case above, we have something like

```
(7, ts, -1)
(8, ts, +1)
```

and each of these gets translated to a avro message. Other than being unexpected, is having the update split into a delete and insert problematic for what you are trying to do?

**Comment by maver1ck** [comment] 2020-09-22 16:52
The only thing problematic is this split.
I was assuming I would get one record with both before and after fields filled.
This is how debezium is performing operations and materialize copied their message format.

**Comment by ruchirK** [comment] 2020-09-22 20:43
100% agree that it's not the exact same as Debezium here. That's partly because the underlying compute engine is used for more than just OLTP use cases, and so it's hard to match up what came "before" with what came "after".  What are you trying to do with sinks at the moment that is hard to accomplish with updates split into separate inserts and deletes? If you can give us a little bit more context on why this is painful, we can definitely try to help!

**Comment by ruchirK** [comment] 2020-09-28 14:40
I'm going to close this issue @maver1ck but feel free to reopen / open another one if you have further questions!

**Closed by ruchirK** 2020-09-28 14:40 UTC
Labels: A-sink, C-bug
