### ISSUE TITLE
Wrong comparison for intervals

### ISSUE THREAD

**Issue by neverchanje** [MaterializeInc/materialize#14163] opened 2022-08-10 07:26 UTC
### What version of Materialize are you using?

v0.26.4

### How did you install Materialize?

Homebrew tap

### What is the issue?

```
materialize=> select interval '26 hours' < interval '1 day';
 ?column?
----------
 t
(1 row)
```

Somehow Materialize thinks 'days' is always larger than 'hours'. 

```
postgres=# select interval '26 hours' < interval '1 day';
 ?column?
----------
 f
(1 row)
```

**Comment by benesch** [comment] 2022-08-10 07:31
Thanks for the report, @neverchanje! Unfortunately this is a known issue. Closing as a duplicate of #10854.

**Closed by benesch** 2022-08-10 07:31 UTC
Labels: C-bug, A-sql, A-ADAPTER, C-triage

**Comment by jkosh44** [comment] 2022-08-10 13:30
@neverchanje In the meantime you can use `justify_interval` to get the expected behavior (https://materialize.com/docs/sql/functions/justify-interval/)
```
materialize=> select justify_interval(interval '26 hours') < justify_interval(interval '1 day');
 ?column? 
----------
 f
(1 row)
```
