### ISSUE TITLE
compute: Restarting environmentd can cause unexpected re-hydrations

### ISSUE THREAD

**Issue by ParkMyCar** [MaterializeInc/materialize#26155] opened 2024-03-20 13:33 UTC
### What version of Materialize are you using?

v0.92.0

### What is the issue?

Recently we had to restart an instance of `environmentd`, this caused a few (but not all) `clusterd`s to restart, requiring dataflows to rehydrate. Interestingly I didn't observe any downtime from k9s, i.e. the pods themselves didn't restart, so this seems more like a compute issue than a cloud issue.

We would like to solve this because restarting `environmentd` can already be disruptive to the customer, but should only last ~1 minute. Re-hydrating dataflows on the other hand can take almost arbitrarily long and thus is _much_ more disruptive.

See more discussion around the referenced instance [here in Slack](https://materializeinc.slack.com/archives/C06Q94A843D/p1710859044755659).

**Comment by teskje** [comment] 2024-03-20 16:16
There is one issue that's readily reproducible locally, although it's hard to say if this is the same one that motivated this ticket. When you start a default Materialize instance, then restart envd without restarting the clusters, reconciliation fails for the following system indexes:

* `mz_sink_statuses_ind`
* `mz_source_statuses_ind`
* `mz_object_transitive_dependencies_ind`

Notably these are all indexes reading from "retained metrics objects", i.e., collections with an increased compaction window, but they themselves are not.

What happens is that during as-of bootstrapping for a collection we try to choose an as-of that is advanced to the `least_valid_write` of the collection's inputs. Here is the rationale from the code:

```
        // For compute reconciliation to recognize that an existing dataflow can be reused, we want
        // to advance the `as_of` far enough that it is beyond the `as_of`s of all dataflows that
        // might still be installed on replicas, but ideally not much farther as that would just
        // increase the wait time until the index becomes readable, and would also prevent warmup.
        // We advance the `as_of` to `least_valid_write` - 1. (`least_valid_write` is the meet of
        // the `upper`s of all dependencies.) This works because we know that no replica could have
        // produced output at `least_valid_write`, so their write frontiers can't be later. Also,
        // subtracting 1 is still ok, because we can assume that the compaction window is at least
        // 1.
```

This rationale is not entirely correct. In particular, this part is wrong: "This works because we know that no replica could have produced output at `least_valid_write`". It would be correct if we could assume that frontiers of dependencies never regress, and that is true for storage dependencies (whose frontiers are persisted), but not for index dependencies. Index frontiers can regress during an environmentd restart because there is nothing that remembers what the index frontiers were before the restart.

Frontiers of "retained metrics" indexes are virtually guaranteed to regress across restarts. As-of bootstrapping will initialize them to, roughly, `least_valid_write - 30 days`. Assuming that the frontier of the index was somewhere close to the current time before the restart, that's a regression by 30 days. Non-"retained metrics" indexes have their frontiers regressed as well, but only by one second, so chances are that reconciliation still works out in most cases.

I think it should be possible to fix reconciliation by changing as-of bootstrapping to not use `least_valid_write` but instead use the least valid write time of (transitive) storage dependencies only. That way the statement cited above becomes true. I'm just not entirely sure this doesn't break things in other places yet.

**Comment by teskje** [comment] 2024-03-28 14:35
Closing this issue under the optimistic assumption that it the described reconciliation failure was caused by the bug fixed in #26239.

**Comment by teskje** [comment] 2024-04-09 08:23
Hard to say if this is the same as what motivated this issue, but there is one problem with reconciliation that readily reproduces locally.

**Comment by teskje** [comment] 2024-04-09 08:24
Re-opening because more reconciliation failures were reported [in Slack](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1712544194835509). They are caused by dataflows containing different transient `GlobalId`s after bootstrapping, which makes the plan equality check fail.

**Closed** 2024-04-10 17:29 UTC
Labels: C-bug, A-COMPUTE
