### ISSUE TITLE
Keyless indexes are possible

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#4951] opened 2020-12-05 00:13 UTC
I'm not sure whether this is intended or desirable, but we can create keyless indexes in Materialize.
```
materialize=> create table blah(a int, b int);
CREATE TABLE
materialize=> create index blah_keyless_index on blah();
CREATE INDEX
```

In psql trying to create a keyless index results in a syntax error:
```
andiwang=# create index keyless on blah();
ERROR:  syntax error at or near ")"
LINE 1: create index keyless on blah();
```

A pro of having keyless indexes is that it currently makes cross join plans better. See: https://github.com/MaterializeInc/materialize/issues/1487#issuecomment-739083405
A con of having keyless indexes is that keyless indexes would live on only one worker. Thus, it would be terrible if a user accidentally created a keyless index on any view/source with a nontrivial number of rows. 

If it is determined that allowing keyless indexes is not a bug, then it is a bug that keyless indexes don't show up when you do `SHOW INDEX`. 
```
materialize=> show indexes in blah;
 on_name |     key_name     | seq_in_index | column_name | expression | nullable 
---------+------------------+--------------+-------------+------------+----------
 blah    | blah_primary_idx |            1 | a           |            | t
 blah    | blah_primary_idx |            2 | b           |            | t
(2 rows)
```
Clearly the keyless index actually exists because it affects plans and dropping the keyless index does not result in an error. But it does not show up in `SHOW INDEX` because currently we have one row in the result for each index column, and a keyless index has no columns.

**Comment by wangandi** [comment] 2021-06-09 18:01
> I believe SHOW INDEXES predates having arrays and lists and such, which might be a better way to communicate the same information (and support indexes on zero columns).

Am I understanding you correctly when I think:
* You're not making a statement as to whether or not you believe the ability to create keyless indexes is a bug.
* You believe regardless of whether or not the ability to create keyless indexes is a bug, we should change the interface for keyless indexes to use arrays/lists.

**Comment by frankmcsherry** [comment] 2021-06-09 18:02
Ah, I should have said that yes. I read it and thought "that's not a bug" and then saw the final bit about us not reporting them and thought "that is a bug!".

**Comment by antiguru** [comment] 2023-09-07 15:12
@ggevay Is this still an issue?

**Comment by ggevay** [comment] 2023-09-07 15:52
Ah thanks a lot; I vaguely remembered that we have an issue like this, but couldn't find it when working on this 2 days ago. 

Fortunately, it's not an issue anymore:
```
materialize=> create table t(a int, b int);

create index bad on t();
CREATE TABLE
NOTICE:  Empty index key. The index will be completely skewed to one worker thread, which can lead to performance problems.
HINT:  CREATE DEFAULT INDEX is almost always better than an index with an empty key. (Except for cross joins with big inputs, which are better to avoid anyway.)
CREATE INDEX
materialize=> show indexes;
 name | on | cluster | key 
------+----+---------+-----
 bad  | t  | default | {}
(1 row)

materialize=> \gdesc
 Column  |  Type  
---------+--------
 on      | text
 name    | text
 key     | text[]
 cluster | text
(4 rows)
```
So:
- [I recently added a notice for empty index keys](https://github.com/MaterializeInc/materialize/pull/21593), so users shouldn't be able to unknowingly introduce a performance problem with this anymore. 
- It seems somebody solved the "not turning up in `SHOW INDEXES`" part of this issue by doing exactly what [Frank recommended above](https://github.com/MaterializeInc/materialize/issues/4951#issuecomment-857911154).

We might still consider disallowing it completely. But I think we shouldn't do that, because an index with an empty key might be useful for some big cross joins: the `key` column is now an `array`. 

Closing the issue now as solved. Feel free to reopen if somebody thinks we should completely disallow this.

**Closed by ggevay** 2023-09-07 15:52 UTC
Labels: C-bug, A-sql, A-optimization
