### ISSUE TITLE
CREATE CLUSTER REPLICA ... AVAILABILITY ZONE is not obeyed 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14170] opened 2022-08-10 14:35 UTC
### What version of Materialize are you using?

v0.26.1-dev (86c6f75d2)

### How did you install Materialize?

Docker image

### What is the issue?

Running this:

```
CREATE CLUSTER antiaffinity_cluster1 REPLICAS ();
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica1 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica2 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica3 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
```

does not cause 3 replicas to be placed in a single availability zone. Instead, it produces the following K8s error:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  107s (x3 over 7m6s)  default-scheduler  0/4 nodes are available: 1 node(s) didn't match pod anti-affinity rules, 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 1 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling.
```

**Comment by philip-stoev** [comment] 2022-08-10 14:37
Assigning to @uce as I am not sure which team belongs to. The functionality lives in environmentd, in the K8s orchestrator, but is used by the cloud team.

**Comment by brennanvincent** [comment] 2022-08-31 20:38
@philip-stoev , how are you running your environment? In the `kind` setup in the cloud repo I do not have AZs like `kind-worker3` etc.

```
~ ❯❯❯ psql "postgres://brennan%40materialize.com:$(<~/staging.mzpass)@127.0.0.1:32022/materialize"
psql (14.5 (Ubuntu 14.5-1), server 9.5.0)
Type "help" for help.

materialize=> CREATE CLUSTER antiaffinity_cluster1 REPLICAS ();
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica1 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica2 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica3 SIZE '1' , AVAILABILITY ZONE 'kind-worker3';
CREATE CONNECTION
ERROR:  unknown cluster replica availability zone kind-worker3
HINT:  Valid availability zones are: kind
ERROR:  unknown cluster replica availability zone kind-worker3
HINT:  Valid availability zones are: kind
ERROR:  unknown cluster replica availability zone kind-worker3
HINT:  Valid availability zones are: kind
materialize=> 
```

**Comment by uce** [comment] 2022-09-25 18:28
I've moved this to the compute board and removed the triage label. @philip-stoev Brennan's example indicates that it works as expected? Can you confirm or provide a clearer example?

**Comment by teskje** [comment] 2023-02-08 15:16
Assigned to @philip-stoev to double-check.

**Comment by philip-stoev** [comment] 2023-02-21 08:52
@umanwizard it is not the kind setup in the cloud repo, it is the kind setup in the main repo , test/cloudtest/setup.sh . There the nodes are tagged as being each in a different availability zone.

The issue is reproducible as follows:

```
cd test/cloudtest
./setup.sh
./pytest -k test_wait

# Get the port to connect to
kubectl describe service/environmentd
psql -h 127.0.0.1 -p 32049 -u materialize

# Run

 CREATE CLUSTER antiaffinity_cluster1 REPLICAS ();
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica1 SIZE '1' , AVAILABILITY ZONE 'cloudtest-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica2 SIZE '1' , AVAILABILITY ZONE 'cloudtest-worker3';
CREATE CLUSTER REPLICA antiaffinity_cluster1.antiaffinity_replica3 SIZE '1' , AVAILABILITY ZONE 'cloudtest-worker3';

# Examine newly-created pods:

kubectl describe pod/cluster-u2-replica-6-0
```

and you will get:

```
  Warning  FailedScheduling  73s   default-scheduler  0/4 nodes are available: 1 node(s) didn't match pod anti-affinity rules, 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 1 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling.
```

**Comment by teskje** [comment] 2023-02-21 12:05
This works as expected in cloud. I tested this by creating three replicas in 'euw1-az1'. All three of them were scheduled on nodes in the 'eu-west-1c' availability zone, which is what 'euw1-az1' maps to in our staging account. So it seems like this is an issue with our kind setup.

**Comment by teskje** [comment] 2023-02-21 12:31
I tested this in kind now. Some observations:
* The first replica does in fact get scheduled on the correct node. The other two fail to be scheduled.
* The error message includes "1 node(s) didn't match pod anti-affinity rules".

So the issue is that we have an anti-affinity rule that prevents replicas of the same cluster from being scheduled on the same node: https://github.com/MaterializeInc/materialize/blob/d6371fdc5d9adeb960ddc16a31b032926f063f52/src/controller/src/clusters.rs#L468-L475.

Based on this I'd say this works as intended.

**Comment by philip-stoev** [comment] 2023-02-21 12:46
So how does this work on the cloud ten? Ideally the `CREATE` statement should have failed at purification time if it is expected that it would fail later. Anyway, more of a cosmetic issue so feel free to close it or stick it in some backlog.

**Comment by teskje** [comment] 2023-02-21 12:56
> So how does this work on the cloud ten?

In the cloud we have enough (i.e. more than three) nodes in each AZ, so each replica pod can be scheduled according to all affinity and anti-affinity rules. Each pod gets scheduled on a different node.

> Ideally the CREATE statement should have failed at purification time if it is expected that it would fail later. 

I'm not sure if k8s gives us an API to check beforehand whether a given pod spec will be successfully scheduled or not. Probably trying to do such a check would also introduce race conditions. What if you have one free node left and try to create two replicas at the same time? They might both pass the pre-check, but k8s would only be able to successfully schedule one of them.

Apart from that, it's possible to add nodes after the fact. The orchestrator could, when it realizes that there are not enough nodes in a given AZ to schedule a new pod, dynamically allocate another node in that AZ, thus making the scheduling succeed. We might even be doing that on cloud right now. Having a pre-check would prevent this kind of dynamic upscaling.

**Comment by umanwizard** [comment] 2023-02-21 14:34
Yes, in cloud we dynamically add new nodes if there are not enough, using
the Kubernetes Cluster Autoscaler.

**Comment by umanwizard** [comment] 2023-02-21 14:36
I think this can be closed if it's purely due to the kind setup not supporting autoscaling. I think we all agree that it is working in production. Feel free to reopen if that is not the case.

**Closed by umanwizard** 2023-02-21 14:36 UTC
Labels: C-bug, A-ADAPTER
