### ISSUE TITLE
test_pg_views_forbidden_types is flaky

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#17366] opened 2023-01-26 17:51 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/49008#0185ef10-9d0f-4ddd-a245-f023873ce19c

### Relevant log output

```source
thread 'catalog::builtin::tests::test_pg_views_forbidden_types' panicked at 'called `Result::unwrap()` on an `Err` value: StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(EXX000), message: "internal error: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1674753799.099895237,1. Read timestamp: 1674753799.099895237,2 Previous Deadline: 1674754043.251270841,0.", detail: Some("stack trace:\ngithub.com/cockroachdb/cockroach/pkg/kv/txn.go:775: UpdateDeadline()\ngithub.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:220: maybeUpdateDeadline()\ngithub.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:145: MaybeUpdateDeadline()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:274: execStmtInOpenState()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129: func1()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2382: execWithProfiling()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:128: execStmt()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1920: func1()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1924: execCmd()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1846: run()\ngithub.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:828: ServeConn()\ngithub.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728: func1()\nGOROOT/src/runtime/asm_amd64.s:1594: goexit()\n"), hint: Some("You have encountered an unexpected error.\n\nPlease check the public issue tracker to check whether this problem is\nalready tracked. If you cannot find it there, please report the error\nwith details by creating a new issue.\n\nIf you would rather not post publicly, please contact us directly\nusing the support form.\n\nWe appreciate your feedback.\n"), position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("txn.go"), line: Some(775), routine: Some("UpdateDeadline") }) }) }', src/adapter/src/catalog.rs:3286:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: <core::result::Result<(), mz_stash::StashError>>::unwrap
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
   4: <mz_adapter::catalog::Catalog>::with_debug::<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}::{closure#0}, core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}::{closure#0}::{closure#0}>, ()>::{closure#0}
             at ./src/catalog.rs:3281:9
   5: <core::future::from_generator::GenFuture<<mz_adapter::catalog::Catalog>::with_debug<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}::{closure#0}, core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}::{closure#0}::{closure#0}>, ()>::{closure#0}> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   6: mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}
             at ./src/catalog/builtin.rs:3510:9
   7: <core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   8: <core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/future.rs:124:9
   9: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:541:57
  10: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:102:5
  11: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:68:5
  12: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:541:25
  13: <tokio::runtime::scheduler::current_thread::Context>::enter::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:350:19
  14: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:540:36
  15: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}, core::option::Option<()>>::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:615:57
  16: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::current_thread::Context>>::set::<<tokio::runtime::scheduler::current_thread::CoreGuard>::enter<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}, core::option::Option<()>>::{closure#0}, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core>, core::option::Option<()>)>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/macros/scoped_tls.rs:61:9
  17: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>::{closure#0}, core::option::Option<()>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:615:27
  18: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:530:19
  19: <tokio::runtime::scheduler::current_thread::CurrentThread>::block_on::<core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/current_thread.rs:154:24
  20: <tokio::runtime::runtime::Runtime>::block_on::<core::future::from_generator::GenFuture<mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/runtime.rs:282:47
  21: mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types
             at ./src/catalog/builtin.rs:3455:9
  22: mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0}
             at ./src/catalog/builtin.rs:3454:11
  23: <mz_adapter::catalog::builtin::tests::test_pg_views_forbidden_types::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

I'm not convinced that the specific test is at all relevant to the bug since it seems like it's a CockroachDB error.

**Comment by benesch** [comment] 2023-01-26 22:35
That issue was closed as a duplicate of https://github.com/cockroachdb/cockroach/issues/76727. The good news is that this is high on their priority list to fix.

**Comment by def-** [comment] 2023-05-16 11:21
Also seen in test_auth_base, so still occurring for us even though https://github.com/cockroachdb/cockroach/issues/76727 is fixed: https://buildkite.com/materialize/tests/builds/55631#01882421-2e67-4e1b-b79d-0218f0133c57
```
[2023-05-16T10:43:19Z] thread 'test_auth_base' panicked at 'called `Result::unwrap()` on an `Err` value: stash error: postgres: db error: ERROR: internal error: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1684233792.810883844,1. Read timestamp: 1684233792.810883844,2 Previous Deadline: 1684233792.810883844,1.
[2023-05-16T10:43:19Z] DETAIL: stack trace:
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/kv/txn.go:775: UpdateDeadline()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:220: maybeUpdateDeadline()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:186: getResult()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:108: getByName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:496: func6()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:523: getNonVirtualDescriptorID()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:328: getDescriptorByName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:53: GetObjectByName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/table.go:53: getTableByName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/table.go:44: GetImmutableTableByName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:75: Get()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:247: SynthesizePrivilegeDescriptor()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilege/vtable_privilege.go:48: GetPrivilegeDescriptor()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table_desc.go:654: GetPrivilegeDescriptor()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/authorization.go:244: getOwnerOfPrivilegeObject()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:626: getOwnerName()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2878: 1()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2427: func1()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2610: func1()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2626: forEachTableDescWithTableLookupInternalFromDescriptors()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2548: forEachTableDescWithTableLookupInternal()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2493: forEachTableDescWithTableLookup()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2421: forEachTableDesc()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2873: func235()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:613: 1()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127: func3()
[2023-05-16T10:43:19Z] github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489: func2()
[2023-05-16T10:43:19Z] GOROOT/src/runtime/asm_amd64.s:1594: goexit()
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] HINT: You have encountered an unexpected error.
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] Please check the public issue tracker to check whether this problem is
[2023-05-16T10:43:19Z] already tracked. If you cannot find it there, please report the error
[2023-05-16T10:43:19Z] with details by creating a new issue.
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] If you would rather not post publicly, please contact us directly
[2023-05-16T10:43:19Z] using the support form.
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] We appreciate your feedback.
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] 
[2023-05-16T10:43:19Z] Stack backtrace:
[2023-05-16T10:43:19Z]    0: <core::result::Result<mz_environmentd::Server, anyhow::Error> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, mz_stash::StashError>>>::from_residual
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:2107:27
[2023-05-16T10:43:19Z]    1: mz_environmentd::serve::{closure#0}::{closure#0}
[2023-05-16T10:43:19Z]              at ./src/lib.rs:235:17
[2023-05-16T10:43:19Z]    2: <tracing::instrument::Instrumented<mz_environmentd::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
[2023-05-16T10:43:19Z]    3: mz_environmentd::serve::{closure#0}
[2023-05-16T10:43:19Z]              at ./src/lib.rs:230:1
[2023-05-16T10:43:19Z]    4: <tokio::runtime::park::CachedParkThread>::block_on::<mz_environmentd::serve::{closure#0}>::{closure#0}
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
[2023-05-16T10:43:19Z]    5: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<mz_environmentd::serve::{closure#0}>::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
[2023-05-16T10:43:19Z]       tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<mz_environmentd::serve::{closure#0}>::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
[2023-05-16T10:43:19Z]       <tokio::runtime::park::CachedParkThread>::block_on::<mz_environmentd::serve::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
[2023-05-16T10:43:19Z]    6: <tokio::runtime::context::BlockingRegionGuard>::block_on::<mz_environmentd::serve::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
[2023-05-16T10:43:19Z]    7: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<mz_environmentd::serve::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
[2023-05-16T10:43:19Z]    8: <tokio::runtime::runtime::Runtime>::block_on::<mz_environmentd::serve::{closure#0}>
[2023-05-16T10:43:19Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:304:45
[2023-05-16T10:43:19Z]    9: auth::util::start_server
[2023-05-16T10:43:19Z]              at ./tests/util.rs:360:17
[2023-05-16T10:43:19Z]   10: auth::test_auth_base
[2023-05-16T10:43:19Z]              at ./tests/auth.rs:985:18
[2023-05-16T10:43:19Z]   11: auth::test_auth_base::{closure#0}
[2023-05-16T10:43:19Z]              at ./tests/auth.rs:876:21
[2023-05-16T10:43:19Z]   12: <auth::test_auth_base::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z]   13: core::ops::function::FnOnce::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z]       test::__rust_begin_short_backtrace
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:656:18
[2023-05-16T10:43:19Z]   14: test::run_test::{{closure}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:647:30
[2023-05-16T10:43:19Z]       core::ops::function::FnOnce::call_once{{vtable.shim}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z]   15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
[2023-05-16T10:43:19Z]       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
[2023-05-16T10:43:19Z]       std::panicking::try::do_call
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
[2023-05-16T10:43:19Z]       std::panicking::try
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
[2023-05-16T10:43:19Z]       std::panic::catch_unwind
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
[2023-05-16T10:43:19Z]       test::run_test_in_process
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:679:27
[2023-05-16T10:43:19Z]       test::run_test::run_test_inner::{{closure}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:573:39
[2023-05-16T10:43:19Z]   16: test::run_test::run_test_inner::{{closure}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/test/src/lib.rs:600:37
[2023-05-16T10:43:19Z]       std::sys_common::backtrace::__rust_begin_short_backtrace
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
[2023-05-16T10:43:19Z]   17: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:558:17
[2023-05-16T10:43:19Z]       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
[2023-05-16T10:43:19Z]       std::panicking::try::do_call
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
[2023-05-16T10:43:19Z]       std::panicking::try
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
[2023-05-16T10:43:19Z]       std::panic::catch_unwind
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
[2023-05-16T10:43:19Z]       std::thread::Builder::spawn_unchecked_::{{closure}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:557:30
[2023-05-16T10:43:19Z]       core::ops::function::FnOnce::call_once{{vtable.shim}}
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z]   18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
[2023-05-16T10:43:19Z]       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
[2023-05-16T10:43:19Z]       std::sys::unix::thread::Thread::new::thread_start
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
[2023-05-16T10:43:19Z]   19: <unknown>
[2023-05-16T10:43:19Z]   20: __clone', src/environmentd/tests/auth.rs:985:45
[2023-05-16T10:43:19Z] stack backtrace:
[2023-05-16T10:43:19Z]    0: rust_begin_unwind
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-05-16T10:43:19Z]    1: core::panicking::panic_fmt
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-05-16T10:43:19Z]    2: core::result::unwrap_failed
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
[2023-05-16T10:43:19Z]    3: <core::result::Result<auth::util::Server, anyhow::Error>>::unwrap
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
[2023-05-16T10:43:19Z]    4: auth::test_auth_base
[2023-05-16T10:43:19Z]              at ./tests/auth.rs:985:18
[2023-05-16T10:43:19Z]    5: auth::test_auth_base::{closure#0}
[2023-05-16T10:43:19Z]              at ./tests/auth.rs:876:21
[2023-05-16T10:43:19Z]    6: <auth::test_auth_base::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z]    7: core::ops::function::FnOnce::call_once
[2023-05-16T10:43:19Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-16T10:43:19Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I'll try bumping our cockroach version for testing: https://github.com/MaterializeInc/materialize/pull/19308

**Closed** 2023-05-16 11:57 UTC
Labels: C-bug, C-triage, ci-flake
