### ISSUE TITLE
[SQLsmith] ERROR:  Unsupported temporal predicate. Note: `mz_now()` must be directly compared to a mz_timestamp-castable expression. Expression found: (mz_now() < mz_now())

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18048] opened 2023-03-10 12:29 UTC
### What version of Materialize are you using?

v0.46.0-dev (7394158)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> EXPLAIN SELECT FROM (SELECT FROM mz_internal.mz_arrangement_sharing_internal AS ref_4) AS subq_8 WHERE mz_catalog.mz_now() < mz_catalog.mz_now();
ERROR:  Unsupported temporal predicate. Note: `mz_now()` must be directly compared to a mz_timestamp-castable expression. Expression found: (mz_now() < mz_now())
```
Might be related to https://github.com/MaterializeInc/materialize/issues/18045 since it also features temporal predicates and only happens within `explain`. Cc @aalexandrov @ggevay

ci-regexp: Unsupported temporal predicate
ci-regexp: OneShot plan has temporal constraints

**Comment by frankmcsherry** [comment] 2023-03-10 12:48
I think this is not a bug: it is reporting an error in the query. We do not support this comparison. Or am I misunderstanding something?

**Comment by def-** [comment] 2023-03-10 13:38
Without the `explain` the query runs fine though, is that expected?
```
materialize=> SELECT FROM (SELECT FROM mz_internal.mz_arrangement_sharing_internal AS ref_4) AS subq_8 WHERE mz_catalog.mz_now() < mz_catalog.mz_now();
--
(0 rows)
```

**Comment by def-** [comment] 2023-03-10 15:12
Similar:
```
materialize=> explain select
  "subq_0"."c2" as c0
from
  (select
        "ref_0"."worker_id" as c0,
        "ref_0"."time" as c1,
        "ref_0"."id" as c2,
        "ref_0"."time" as c3,
        "ref_0"."time" as c4
      from
        mz_internal.mz_active_peeks as ref_0
      where ((numrange(0,0) < numrange(0,0))
          or (cast(null as uint2) < cast(null as uint2)))
        or ("ref_0"."id" > cast(null as uuid))) as subq_0
where "subq_0"."c1" >= cast(coalesce(mz_catalog.mz_now(),
    cast(null as mz_timestamp)) as mz_timestamp);;
ERROR:  OneShot plan has temporal constraints
```

**Comment by frankmcsherry** [comment] 2023-03-10 16:38
When run as a `SELECT` query we install the current timestamp and run it. When we create a dataflow we need certain properties to hold. When we `EXPLAIN` it looks like we do the latter, I suppose on the principle that we want to show you what might happen if you create a dataflow.

I can imagine there is an issue to open about whether we should have `EXPLAIN DATAFLOW` or `EXPLAIN NOT DATAFLOW` or .. idk how we should distinguish these things. It will become a larger issue when we start to land optimizations for the `SELECT` cases that do not apply for general dataflows. @antiguru

**Comment by ggevay** [comment] 2023-03-11 13:12
Ohh, yes, we should definitely  have an issue for "EXPLAIN DATAFLOW or EXPLAIN NOT DATAFLOW" (if we don't have already). [I got confused by the same thing just a few days ago.](https://github.com/MaterializeInc/materialize/issues/17993#issuecomment-1464909378)

**Comment by aalexandrov** [comment] 2023-03-13 09:38
I've filed #18089 to track this.

**Comment by ggevay** [comment] 2023-03-13 10:11
Closing, because
- The original error msg indicates a problem with the query, not with the system.
- The different EXPLAIN behavior is tracked [here](https://github.com/MaterializeInc/materialize/issues/18089).

**Closed by ggevay** 2023-03-13 10:11 UTC
Labels: C-bug
