### ISSUE TITLE
TAIL stalls when adding a new replica to a cluster

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#14729] opened 2022-09-08 23:16 UTC
### What version of Materialize are you using?

 v0.27.0-alpha.20 (9db27abd5)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

In one tab, run tail over a materialized or indexed view being computed on some cluster foo. In another tab, add another replica to cluster foo. In the first tab, you will see the output of tail stop until the create replica command in tab two returns. It appears to be blocking environmentd from returning results in another session.

**Comment by uce** [comment] 2022-09-25 18:36
@teskje Is the described behavior expected?

**Comment by teskje** [comment] 2022-09-26 08:00
I would say it is expected from an implementation point of view, but definitely confusing to the user.

AFAICT, this happens because in adapter's sequencer (which must be single-threaded, to ensure consistency guarantees) we call the compute controller's `add_replica_to_instance`, which blocks until the new replica service is registered with K8S. So as long as we are waiting for K8S to return, adapter cannot handle other command and presumably also not tail responses. (cc @jkosh44 to confirm)

There are probably several ways to solve this. One I can think about is that once we have compute command durability, we might be able to decouple the recording of commands from their execution, i.e. have a separate compute controller thread that continually reads new recorded commands and apply them. Then in adapter's sequencer, calls to the compute controller would only have to wait until the respective compute command was durably recorded.

**Comment by uce** [comment] 2022-09-26 10:45
Thanks for the context, Jan. Let's keep this in the compute backlog. It's seems like a nice-to-have improvement to me that we can work on soonish. My assumption here is that adding/removing replicas should be a low frequency op. @sjwiesman does that sound good to you?

@jkosh44 @chaas We can also move this to the adapter backlog if you think that's a better fit. Compute would be looking at this through the command durability lens, but ya'll might have a different preference.

**Comment by jkosh44** [comment] 2022-09-26 13:30
I can confirm that `add_replica_to_instance` is called on the main Coord thread, which will block the coord until it is complete. We have an issue https://github.com/MaterializeInc/materialize/issues/13300 to move certain commands off of the main thread, which this can be included in. 

The general pattern we take in similar scenarios in the adapter is to wait in a background task and then send a message to the main thread when the waiting is done. That could be another solution if we prefer to handle this on the adapter side.

**Comment by sjwiesman** [comment] 2022-09-26 15:58
That makes sense to me! I would not characterize this as mission critical, but I’d like to push for it being done at some point. The easiest way to demonstrate adding replicas without downtime is while running a tail and it’s just a small annoyance that output appears to stall

**Comment by teskje** [comment] 2022-10-04 16:47
I took fresh traces and it turns out that the time spend waiting in the compute controller is negligible. What actually takes time is creating the storage collections for the introspection sources:

![Screen Shot 2022-10-04 at 18 43 00](https://user-images.githubusercontent.com/4521314/193878388-17c3e13b-d480-4109-b1ad-640c0f249ce6.png)

Inside `create_collections`, we are waiting for stash transaction to complete:

![Screen Shot 2022-10-04 at 18 43 25](https://user-images.githubusercontent.com/4521314/193878569-0808aa9b-1168-4025-9fcb-04ae214b5dd3.png)

This makes it very likely that implementing https://github.com/MaterializeInc/materialize/issues/15074 would fix this bug.

**Comment by teskje** [comment] 2022-10-07 13:20
After batching stash transactions, the trace looks better but still not great:

![Screen Shot 2022-10-07 at 15 14 54](https://user-images.githubusercontent.com/4521314/194563040-1b45084e-82df-40b6-8162-7dd510ca5274.png)

We are still spending a significant amount of time opening the persist shards one by one. I'm not sure if we can get any easy wins here as well. AFAIK, persist doesn't offer an API to open multiple shards at the same time, and I'm not sure how easy it would be to add that.

**Comment by mjibson** [comment] 2022-10-12 18:46
I've moved assignment of this issue to the adapter team, because the create replica work happens in the main coord thread and blocks all other coord messages until it's complete. We would like to move it to its own thread, but that's difficult due to interactions with the compute and storage controllers, which won't be accessible from the other thread. I think the surfaces team should investigate this and figure out if we have API requests for storage or compute (like being able to await a future in a separate thread).

**Comment by chaas** [comment] 2022-10-12 20:59
Tracking ticket for request for compute to change the replica creation API #15368

**Comment by jkosh44** [comment] 2022-12-01 17:18
@teskje It looks like `add_replica_to_instance` does not return a `oneshot`. Instead is no longer async and instead will start an async task to do all the work and return immediately. Is this the correct understanding? If that's the case then we can close this issue because adding a replica will no longer block the main Coordinator thread.

**Comment by teskje** [comment] 2022-12-01 17:26
> It looks like add_replica_to_instance does not return a oneshot. Instead is no longer async and instead will start an async task to do all the work and return immediately. Is this the correct understanding?

Yes this is correct.

> If that's the case then we can close this issue because adding a replica will no longer block the main Coordinator thread.

The compute controller won't block the coordinator anymore when adding a replica, but the storage controller still does, when it has to `create_collections` (see the trace screenshot above). This is not noticeable right now, because we disabled the persisted introspection sources, so I assume there are no storage collections to be created together with a replica. However, when/if we enable the persisted introspection collections again.

**Comment by benesch** [comment] 2022-12-02 04:40
> Next steps for us would be to think about how we can create collections off the main coord thread.

Might be worth punting this over to @petrosagg or @aljoscha! I think there are quite a few subtleties, because the persist state is needed to initialize the collection state, and I'm not sure what happens if we defer that work.

**Comment by teskje** [comment] 2024-07-12 11:28
The specific issue reported here has been resolved by removing the persisted introspection sources, making it so that adding a replica doesn't cause the creation of storage collections anymore. The more general issue of `create_collections` being called on the coordinator's main thread still exists though. I've created https://github.com/MaterializeInc/materialize/issues/28198 to track it, so I think we can close this one.

**Closed by teskje** 2024-07-12 11:28 UTC
Labels: C-bug, A-storage, A-ADAPTER, A-controller
