### ISSUE TITLE
Setting the database to a nonexistent one succeeds (but subsequent queries fail)

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#15866] opened 2022-11-03 14:12 UTC
### What version of Materialize are you using?

 v0.30.1 (85b85f6d1)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
materialize=> show databases;
    name     
-------------
 materialize
(1 row)

materialize=> set database = chumblespuzz;
SET

materialize=> show tables;
ERROR:  unknown schema 'public'
```

**Comment by ggnall** [comment] 2022-11-03 18:24
- This also happens with Clusters.
- There was a reason that @benesch thinks this needs to work this way. Surfaces can't remember so any info helpful!
- One way we could work around this (if we can't error on SET for whatever reason) to allow the operation but send a NOTICE. 

cc: @mjibson  @chaas

**Comment by ggnall** [comment] 2022-11-03 18:25
Related: https://github.com/MaterializeInc/materialize/issues/12926#issuecomment-1147546797

**Comment by aldeka** [comment] 2022-11-03 18:26
How terrible would it be to refuse to set something nonexistent so long as you have at least one DB?

**Comment by benesch** [comment] 2022-11-03 18:29
Going to close this as a duplicate of https://github.com/MaterializeInc/materialize/issues/12926 to avoid forking the discussion. I'll copy the comments over.

**Closed by benesch** 2022-11-03 18:29 UTC
Labels: C-bug, C-triage
