### ISSUE TITLE
Robust communication between Coordinator and STORAGE/COMPUTE

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#13291] opened 2022-06-27 14:26 UTC
### Feature request

Currently all communication from the Coordinator to STORAGE and COMPUTE is called with `unwrap()`. This means that if STORAGE or COMPUTE is not available, then the Coordinator will crash. Additionally, the Coordinator will enter a crash loop until they become responsive since communication to STORAGE and COMPUTE is required during the startup process.

While this is technically correct, it is not a good user experience. One potential solution is to return an error to the user and roll back the current operation. Another might be to sit and wait for STORAGE/COMPUTE to become available.

Part of #13204

**Comment by ggnall** [comment] 2022-11-11 22:54
Dupe of https://github.com/MaterializeInc/materialize/issues/13306.

**Closed by ggnall** 2022-11-11 22:54 UTC
Labels: C-feature, A-coordinator, A-ADAPTER
