### ISSUE TITLE
Trailing comma in list of columns confuses our parsing and gives a useless error message

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#2517] opened 2020-04-01 19:50 UTC
```
materialize=> create materialized view v as values (DATE '2007-02-01');
CREATE VIEW
materialize=> select column1, from v;
ERROR:  column "column1" does not exist
materialize=> select column1 from v;
  column1   
------------
 2007-02-01
(1 row)

```

**Comment by benesch** [comment] 2020-04-01 20:00
I think this is mostly a duplicate of https://github.com/MaterializeInc/materialize/issues/1643.

**Comment by benesch** [comment] 2020-04-01 20:00
I agree this super sucks.

**Comment by umanwizard** [comment] 2020-04-01 21:05
For prioritization purposes: note that for one of our external partners, this is one of the very first issues that they hit.

**Closed** 2020-05-04 21:37 UTC
Labels: C-bug
