### ISSUE TITLE
cluster: panic: called `Result::unwrap()` on an `Err` value: IdentifierMissing(User(414))

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11568] opened 2022-04-04 08:49 UTC
### What version of Materialize are you using?

 v0.25.1-dev (f5e3e40be)

### How did you install Materialize?

Docker image

### What was the issue?

In Nightly cluster:

https://buildkite.com/materialize/nightlies/builds/780#3eefb59d-7662-4efe-a877-a626c1d5afbc

### Relevant log output

```source
materialized_1         | 2022-04-03T11:38:34.929501Z ERROR panic: called `Result::unwrap()` on an `Err` value: IdentifierMissing(User(414))
materialized_1         | thread: coordinator
materialized_1         | location: src/coord/src/coord.rs:3496:60
materialized_1         | version: 0.25.1-dev (f5e3e40bed6beb7ace7fc2c5c447c805485925c9)
materialized_1         | backtrace:
materialized_1         |    0: materialized::handle_panic
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:956:21
materialized_1         |    1: core::ops::function::Fn::call
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:70:5
materialized_1         |    2: std::panicking::rust_panic_with_hook
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
materialized_1         |    3: std::panicking::begin_panic_handler::{{closure}}
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
materialized_1         |    4: std::sys_common::backtrace::__rust_end_short_backtrace
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
materialized_1         |    5: rust_begin_unwind
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
materialized_1         |    6: core::panicking::panic_fmt
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
materialized_1         |    7: core::result::unwrap_failed
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
materialized_1         |    8: core::result::Result<T,E>::unwrap
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
materialized_1         |       mz_coord::coord::Coordinator::least_valid_read
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:3496:36
materialized_1         |    9: mz_coord::coord::Coordinator::determine_timestamp
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:3570:21
materialized_1         |   10: mz_coord::coord::Coordinator::sequence_peek::{{closure}}
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:3219:37
materialized_1         |   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
materialized_1         |       mz_coord::coord::Coordinator::sequence_plan::{{closure}}
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:1786:63
materialized_1         |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
materialized_1         |       mz_coord::coord::Coordinator::handle_execute::{{closure}}
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:1552:66
materialized_1         |       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
materialized_1         |       mz_coord::coord::Coordinator::message_command::{{closure}}
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:1112:62
materialized_1         |   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
materialized_1         |       mz_coord::coord::Coordinator::serve::{{closure}}
materialized_1         |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09e54328af9d53fa2-1/materialize/tests/src/coord/src/coord.rs:725:67
materialized_1         |   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
materialized_1         |       tokio::park::thread::CachedParkThread::block_on::{{closure}}
materialized_1         |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
materialized_1         |       tokio::coop::with_budget::{{closure}}
materialized_1         |              at cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
materialized_1         |       std::thread::local::LocalKey<T>::try_with
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
materialized_1         |       std::thread::local::LocalKey<T>::with
materialized_1         |              at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
materialized_1         |       tokio::coop::with_budget
```

**Comment by frankmcsherry** [comment] 2022-04-04 11:14
Hi! What sort of triage has been done? It looks like this is a `coord.rs` crash, and while I can help with that it may be unrelated to optimization/dataflow.

**Comment by philip-stoev** [comment] 2022-04-04 11:27
For the lack of a better category, I am putting all cluster-related stuff in Optimization+Dataflow. Feel free to move it as appropriate.

**Comment by frankmcsherry** [comment] 2022-04-04 11:33
This is a similar presentation as the issue fixed by https://github.com/MaterializeInc/materialize/pull/11563 does the issue reproduce consistently?

**Comment by antiguru** [comment] 2022-04-04 15:08
This issue is 100% reproducible, make your life easier with the following patch:
```diff
diff --git a/test/cluster/mzcompose.py b/test/cluster/mzcompose.py
index f9de71475..f1eed097c 100644
--- a/test/cluster/mzcompose.py
+++ b/test/cluster/mzcompose.py
@@ -80,7 +80,7 @@ def workflow_nightly(c: Composition) -> None:
         ],
         cwd=Path(__file__).parent.parent,
     ).split()
-    test_cluster(c, *files)
+    test_cluster(c, *["testdrive/github-8241.td"])


 def test_cluster(c: Composition, *glob: str) -> None:
@@ -91,6 +91,7 @@ def test_cluster(c: Composition, *glob: str) -> None:
     # Create a remote cluster and verify that tests pass.
     c.up("dataflowd_compute_1")
     c.up("dataflowd_compute_2")
+    c.sql("DROP CLUSTER IF EXISTS c CASCADE")
     c.sql(
         "CREATE CLUSTER c REMOTE replica1 ('dataflowd_compute_1:6876', 'dataflowd_compute_2:6876');"
     )
```

And then run:
```
(cd test/cluster; ./mzcompose run nightly)
```

Here's a log with tracing turned on: [gh_11568.log](https://github.com/MaterializeInc/materialize/files/8410882/gh_11568.log)

**Comment by antiguru** [comment] 2022-04-04 15:35
Some additional logs from `least_valid_read`:
```
materialized_1         | 2022-04-04T15:34:19.501382Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {} }, instance: 1
materialized_1         | 2022-04-04T15:34:19.501626Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {} }, instance: 1
materialized_1         | 2022-04-04T15:34:22.064968Z  INFO mz_coord::catalog: create cluster c
materialized_1         | 2022-04-04T15:34:22.968279Z  INFO mz_dataflow_types::client::tcp: Reconnected to dataflowd_compute_1:6876
materialized_1         | 2022-04-04T15:34:22.968393Z  INFO mz_dataflow_types::client::tcp: Reconnected to dataflowd_compute_2:6876
materialized_1         | 2022-04-04T15:34:22.968419Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica "replica1"
materialized_1         | 2022-04-04T15:34:25.746264Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.746493Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.782617Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {System(4009)}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.782999Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {System(4009)}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.806126Z  INFO mz_coord::catalog: create database materialize
materialized_1         | 2022-04-04T15:34:25.806144Z  INFO mz_coord::catalog: create schema 1.public
materialized_1         | 2022-04-04T15:34:25.825825Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {System(4037)}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.826040Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {System(4037)}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:25.848726Z  INFO mz_coord::catalog: create table 1.6.t1 (u1)
materialized_1         | 2022-04-04T15:34:25.933825Z DEBUG hyper::proto::h1::io: parsed 2 headers
materialized_1         | 2022-04-04T15:34:25.933842Z DEBUG hyper::proto::h1::conn: incoming body is empty
materialized_1         | 2022-04-04T15:34:25.934117Z DEBUG hyper::proto::h1::io: flushed 301 bytes
materialized_1         | 2022-04-04T15:34:25.934965Z DEBUG hyper::proto::h1::conn: read eof
materialized_1         | 2022-04-04T15:34:25.954834Z  INFO mz_coord::catalog: create index 1.6.i1 (u2)
materialized_1         | 2022-04-04T15:34:25.973625Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {User(1)}, compute_ids: {} }, instance: 2
materialized_1         | 2022-04-04T15:34:26.874697Z DEBUG hyper::proto::h1::io: parsed 2 headers
materialized_1         | 2022-04-04T15:34:26.874713Z DEBUG hyper::proto::h1::conn: incoming body is empty
materialized_1         | 2022-04-04T15:34:26.874891Z DEBUG hyper::proto::h1::io: flushed 317 bytes
materialized_1         | 2022-04-04T15:34:26.875305Z DEBUG hyper::proto::h1::conn: read eof
materialized_1         | 2022-04-04T15:34:26.894971Z  INFO mz_coord::catalog: create view 1.6.v1 (u3)
materialized_1         | 2022-04-04T15:34:26.957898Z DEBUG hyper::proto::h1::io: parsed 2 headers
materialized_1         | 2022-04-04T15:34:26.957910Z DEBUG hyper::proto::h1::conn: incoming body is empty
materialized_1         | 2022-04-04T15:34:26.958073Z DEBUG hyper::proto::h1::io: flushed 333 bytes
materialized_1         | 2022-04-04T15:34:26.958563Z DEBUG hyper::proto::h1::conn: read eof
materialized_1         | 2022-04-04T15:34:26.959229Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {User(2)} }, instance: 2
materialized_1         | 2022-04-04T15:34:26.959407Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {}, compute_ids: {User(2)} }, instance: 2
materialized_1         | 2022-04-04T15:34:26.961618Z DEBUG mz_coord::coord: least_valid_read id_bundle: CollectionIdBundle { storage_ids: {User(1)}, compute_ids: {User(2)} }, instance: 1
materialized_1         | 2022-04-04T15:34:28.307316Z ERROR panic: called `Result::unwrap()` on an `Err` value: IdentifierMissing(User(2))
```

**Comment by benesch** [comment] 2022-04-04 16:18
Weirdly it doesn't reproduce without a transaction!

**Comment by benesch** [comment] 2022-04-04 16:21
Ah, ok, it's because various things are scoped to the cluster that happens to be active when the transaction starts, and various things are not. I'm going to launch a discussion in #eng-platform.

**Comment by benesch** [comment] 2022-04-04 16:46
Assigning to you, @mjibson!

From an in-person discussion with @frankmcsherry, we think we should move to ban multi-cluster transactions. That way, if we later decide to support multi-cluster transactions, it's a feature to add them. If we go in the other direction, it would be a breaking change if we later decide we want to ban them.

Work items:

  * Write the code to ensure that `SET cluster` is not valid in a transaction. Alternatively, `SET cluster` is not valid in a transaction _except_ at the very beginning, like `SET isolation_level`. 
  * Change `timedomain_for` to accept a `compute_instance_id`, and restrict the returned ID bundle to just the indexes on the provided compute instance.
  * Write a testdrive script that verifies that multi-cluster transactions are banned.

**Comment by mjibson** [comment] 2022-04-04 21:13
Why do we need to prevent changing the CLUSTER variable? I think it'll complain gracefully if you do that.

**Comment by benesch** [comment] 2022-04-04 21:54
Oh will it? You could totally be right. Excellent!

**Closed** 2022-04-04 23:36 UTC
Labels: C-bug, A-platform, M-platform-blocker
