### ISSUE TITLE
 thread 'test_auth_base_disable_tls' panicked at 'assertion failed: `(left == right)`  ... stash and persist result variant do not match. stash:

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23169] opened 2023-11-13 23:06 UTC
### What version of Materialize are you using?

5294484c371d

### What is the issue?

Seen in cargo test in https://buildkite.com/materialize/tests/builds/68627#018bcad1-2d9c-461d-9a28-b34fb92586b9
```
thread 'test_auth_base_disable_tls' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`: stash and persist result variant do not match. stash: Err(Durable(MiscStash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E40001), message: "restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn ...', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-053f1155bd6f38b45-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:125:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<bool, bool>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:228:5
   4: <mz_catalog::durable::impls::shadow::OpenableShadowCatalogState<mz_catalog::durable::impls::stash::OpenableConnection, mz_catalog::durable::impls::persist::PersistHandle> as mz_catalog::durable::OpenableDurableCatalogState>::open::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-053f1155bd6f38b45-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:125:9
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<alloc::boxed::Box<dyn mz_catalog::durable::DurableCatalogState>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
   6: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./src/lib.rs:480:14
   7: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./src/lib.rs:339:5
   9: <mz_environmentd::test_util::Listeners>::serve::{closure#4}
             at ./src/test_util.rs:524:18
  10: <tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  11: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  12: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  13: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  14: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  15: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  16: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  17: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  18: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  19: <tokio::runtime::runtime::Runtime>::block_on::<<mz_environmentd::test_util::Listeners>::serve::{closure#4}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  20: <mz_environmentd::test_util::Listeners>::serve
             at ./src/test_util.rs:460:21
  21: mz_environmentd::test_util::start_server
             at ./src/test_util.rs:539:5
  22: auth::test_auth_base_disable_tls::test_impl
             at ./tests/auth.rs:1064:18
  23: auth::test_auth_base_disable_tls
             at ./tests/auth.rs:1058:1
  24: auth::test_auth_base_disable_tls::{closure#0}
             at ./tests/auth.rs:1058:1
  25: <auth::test_auth_base_disable_tls::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```
Full log: https://gist.github.com/def-/14194cb20e278f171ce26742c495478c
Related to shadow catalog.

ci-regexp: thread 'test_auth_.*' panicked at 'assertion failed: `(left == right)`

**Comment by jkosh44** [comment] 2023-11-14 18:29
This is a duplicate of https://github.com/MaterializeInc/materialize/issues/21882. It's just that the test name and error message format has changed since then.

**Closed by jkosh44** 2023-11-14 18:29 UTC
Labels: C-bug
