### ISSUE TITLE
Cannot select more than one batch using pg-query-stream

### ISSUE THREAD

**Issue by haggholm** [MaterializeInc/materialize#24059] opened 2023-12-21 05:54 UTC
### What version of Materialize are you using?

v0.79.1 (38a21b1a6)

### What is the issue?

When attempting to stream data in a Node.JS application using [pg-query-stream](https://www.npmjs.com/package/pg-query-stream) (or using the [pg-cursor](https://www.npmjs.com/package/pg-cursor) package directly), it only retrieves the first page's worth of data from Materialize. This works fine against Postgres, including RDS and various other variations like Greenplum, but not Materialize. A trivial sample application is made available at https://github.com/haggholm/materialize-pg-query-stream/blob/master/index.js for convenience.

**Comment by benesch** [comment] 2023-12-22 05:14
Thank you for the ready-built reproduction, @haggholm! I was able to reproduce the issue myself immediately. I ran the following against a local Materialize with tracing enabled and immediately observed the hang:

```js
$ MATERIALIZE_QUERY="SELECT generate_series(1, 100)" node index.js 
got row 1: { generate_series: 1 }
got row 2: { generate_series: 2 }
got row 3: { generate_series: 3 }
got row 4: { generate_series: 4 }
got row 5: { generate_series: 5 }
got row 6: { generate_series: 6 }
got row 7: { generate_series: 7 }
got row 8: { generate_series: 8 }
got row 9: { generate_series: 9 }
got row 10: { generate_series: 10 }

```

And here's the trace from Materialize:

```
environmentd: 2023-12-22T04:58:09.218147Z TRACE handle_connection:run: mz_pgwire::codec: cid=1 send=ReadyForQuery(Idle)
environmentd: 2023-12-22T04:58:09.220320Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Parse { name: "", sql: "SELECT generate_series(1, 100)", param_types: [] }
environmentd: 2023-12-22T04:58:09.221704Z TRACE handle_connection:run:run:advance_ready:parse:send: mz_pgwire::codec: cid=1 send=ParseComplete
environmentd: 2023-12-22T04:58:09.221844Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Bind { portal_name: "C_1", statement_name: "", param_formats: [], raw_params: [], result_formats: [] }
environmentd: 2023-12-22T04:58:09.222247Z TRACE handle_connection:run:run:advance_ready:bind:send: mz_pgwire::codec: cid=1 send=BindComplete
environmentd: 2023-12-22T04:58:09.222407Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=DescribePortal { name: "C_1" }
environmentd: 2023-12-22T04:58:09.222472Z TRACE handle_connection:run:run:advance_ready:describe_portal:send: mz_pgwire::codec: cid=1 send=RowDescription([FieldDescription { name: ColumnName("generate_series"), table_id: 0, column_id: 0, type_oid: 23, type_len: 4, type_mod: -1, format: Text }])
environmentd: 2023-12-22T04:58:09.222564Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Flush
environmentd: 2023-12-22T04:58:09.222673Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Execute { portal_name: "C_1", max_rows: 10 }
environmentd: 2023-12-22T04:58:09.230817Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(1))])
environmentd: 2023-12-22T04:58:09.230884Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(2))])
environmentd: 2023-12-22T04:58:09.230930Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(3))])
environmentd: 2023-12-22T04:58:09.230959Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(4))])
environmentd: 2023-12-22T04:58:09.230986Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(5))])
environmentd: 2023-12-22T04:58:09.231180Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(6))])
environmentd: 2023-12-22T04:58:09.231225Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(7))])
environmentd: 2023-12-22T04:58:09.231258Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(8))])
environmentd: 2023-12-22T04:58:09.231361Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(9))])
environmentd: 2023-12-22T04:58:09.231393Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send_all:send: mz_pgwire::codec: cid=1 send=DataRow([Some(Int4(10))])
environmentd: 2023-12-22T04:58:09.231430Z TRACE handle_connection:run:run:advance_ready:execute:send_execute_response:sending_rows_immediate:send_rows:send: mz_pgwire::codec: cid=1 send=PortalSuspended
environmentd: 2023-12-22T04:58:09.242503Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Flush
environmentd: 2023-12-22T04:58:09.247309Z TRACE handle_connection:run:run:advance_ready: mz_pgwire::codec: cid=1 recv=Execute { portal_name: "C_1", max_rows: 10 }
environmentd: 2023-12-22T04:58:09.247385Z DEBUG handle_connection:run:run:advance_ready:execute:error: mz_pgwire::protocol: cid=1 error code=34000 message=portal "C_1" does not exist
environmentd: 2023-12-22T04:58:09.247410Z TRACE handle_connection:run:run:advance_ready:execute:error:send: mz_pgwire::codec: cid=1 send=ErrorResponse(ErrorResponse { severity: Error, code: SqlState(E34000), message: "portal \"C_1\" does not exist", detail: None, hint: None, position: None })
environmentd: 2023-12-22T04:58:09.247496Z TRACE handle_connection:run:run: mz_pgwire::codec: cid=1 recv=Flush
```

pg-query-stream successfully establishes a portal for the query and fetches the first ten rows from it in one batch, but when it goes back for the second batch, the portal it had established is gone, and so Materialize rejects the request in an error. There might be a bug in pg-query-stream here, because I'd expect it to report that error. Regardless, it looks like we're at variance with PostgreSQL here, and apparently intentionally so. We've got a test case that explicitly checks that portal go missing like this: https://github.com/MaterializeInc/materialize/blob/246f0f22b4c2fa7ec1aedeba41bbd671a93c1065/test/pgtest-mz/portals.pt#L1-L19. 

This test was introduced in https://github.com/MaterializeInc/materialize/pull/15255. 

I'll need to dig a little bit deeper to know what the right fix is here, but I'm hopeful that we can match PostgreSQL's semantics for portals without losing the single-statement optimizations that motivated #15255.

cc @jkosh44 @mjibson

**Comment by benesch** [comment] 2023-12-22 16:51
I pushed up @haggholm's reproduction as an mzcompose test case in https://github.com/MaterializeInc/materialize/pull/24093. Fixing the bug is still TODO, but I think it should be relatively straightforward, though the resulting code will be ugly.

**Comment by benesch** [comment] 2023-12-23 22:24
I updated #24093 with a bug fix as well. Hoping we can get this merged by December 28 for release on Jan 4.

**Closed** 2023-12-26 14:53 UTC
Labels: C-bug
