### ISSUE TITLE
"Cluster Isolation Test" is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25761] opened 2024-03-05 10:27 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/77547#018e0e12-a601-4d8f-9396-d7ff56f3701b

### Relevant log output

```source
> SELECT * FROM source1
rows match; continuing at ts 1709633452.9336944
> CREATE SINK sink1 FROM v1mat
INTO KAFKA CONNECTION kafka_conn (TOPIC 'sink1')
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
ENVELOPE DEBEZIUM
rows match; continuing at ts 1709633453.1167142
Verifying results in Kafka topic sink1
89:1: error: record 0 did not match
expected:
Record {
    headers: [],
    key: None,
    value: Some(
        {
            (
                "before",
                Union {
                    index: 0,
                    inner: Null,
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
            (
                "after",
                Union {
                    index: 1,
                    inner: {
                        (
                            "c1",
                            Long(3),
                        ),
                    },
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
        },
    ),
}
actual:
Record {
    headers: [],
    key: None,
    value: Some(
        {
            (
                "before",
                Union {
                    index: 0,
                    inner: Null,
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
            (
                "after",
                Union {
                    index: 1,
                    inner: {
                        (
                            "c1",
                            Long(2),
                        ),
                    },
                    n_variants: 2,
                    null_variant: Some(
                        0,
                    ),
                },
            ),
        },
    ),
}
     |
  69 |     URL '${testdrive ... [rest of line truncated for security]
  88 |
  89 | $ kafka-verify-data format=avro sink=materialize.public.sink1 sort-messages=true
```

**Comment by def-** [comment] 2024-03-05 10:39
Duplicate of https://github.com/MaterializeInc/materialize/issues/25479

**Closed by def-** 2024-03-05 10:39 UTC
Labels: C-bug, ci-flake
