### ISSUE TITLE
Cargo test is flaky, Short Zippy and Cloudtest panic with no errors

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#20034] opened 2023-06-19 21:09 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/57948

### Relevant log output

```source
FAIL [  54.813s]                                  mz-stash upgrade::v18_to_v19::tests::smoke_test

--- STDOUT:                                               mz-stash upgrade::v18_to_v19::tests::smoke_test ---

running 1 test
2023-06-19T17:08:24.743032Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:24.976412Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: intent on key /NamespaceTable/30/1/100/300/"collections"/4/1): "sql txn" meta={id=470c7677 key=/Table/3/1/384/2/1 pri=0.01752651 epo=0 ts=1687194503.939618251,1 min=1687194502.929438156,0 seq=20} lock=true stat=PENDING rts=1687194502.929438156,0 wto=false gul=1687194503.429438156,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:27.154772Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:28.133246Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/318/2/1): "sql txn" meta={id=3c2badbb key=/Table/3/1/404/2/1 pri=0.00705277 epo=0 ts=1687194505.198973737,1 min=1687194504.979066306,0 seq=20} lock=true stat=PENDING rts=1687194504.979066306,0 wto=false gul=1687194505.479066306,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:31.374915Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:31.513882Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1): "sql txn" meta={id=d848e43a key=/Table/3/1/437/2/1 pri=0.03037597 epo=0 ts=1687194508.779792502,1 min=1687194508.136423526,0 seq=20} lock=true stat=PENDING rts=1687194508.136423526,0 wto=false gul=1687194508.636423526,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:36.732722Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:37.540714Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1): "sql txn" meta={id=0181d204 key=/Table/3/1/498/2/1 pri=0.00226148 epo=0 ts=1687194513.736927824,2 min=1687194511.516346964,0 seq=20} lock=true stat=PENDING rts=1687194511.516346964,0 wto=false gul=1687194512.016346964,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:46.910907Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:47.513474Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1): "sql txn" meta={id=77e8eb68 key=/Table/3/1/531/2/1 pri=0.01728940 epo=0 ts=1687194523.914289352,2 min=1687194517.543225064,0 seq=20} lock=true stat=PENDING rts=1687194517.543225064,0 wto=false gul=1687194518.043225064,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:53.746320Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:53.759061Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1): "sql txn" meta={id=5f073d13 key=/Table/3/1/580/2/1 pri=0.01543402 epo=0 ts=1687194530.749326271,2 min=1687194527.515811991,0 seq=20} lock=true stat=PENDING rts=1687194527.515811991,0 wto=false gul=1687194528.015811991,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
2023-06-19T17:08:53.931072Z  INFO tokio_postgres::connection: NOTICE: using sequential values in a primary key does not perform as well as using random UUIDs. See https://www.cockroachlabs.com/docs/v23.1/serial.html    
2023-06-19T17:08:53.942863Z  WARN mz_stash::postgres: initial stash connection error, retrying: stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/614/2/1): "sql txn" meta={id=a3e92e1b key=/Table/3/1/632/2/1 pri=0.02015112 epo=0 ts=1687194533.832098173,1 min=1687194533.761562697,0 seq=20} lock=true stat=PENDING rts=1687194533.761562697,0 wto=false gul=1687194534.261562697,0
HINT: See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable
test upgrade::v18_to_v19::tests::smoke_test ... FAILED

failures:

failures:
    upgrade::v18_to_v19::tests::smoke_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 6 filtered out; finished in 54.76s


--- STDERR:                                               mz-stash upgrade::v18_to_v19::tests::smoke_test ---
thread 'upgrade::v18_to_v19::tests::smoke_test' panicked at 'unable to open debug stash: StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E40001), message: "restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/614/2/1): \"sql txn\" meta={id=a3e92e1b key=/Table/3/1/632/2/1 pri=0.02015112 epo=0 ts=1687194533.832098173,1 min=1687194533.761562697,0 seq=20} lock=true stat=PENDING rts=1687194533.761562697,0 wto=false gul=1687194534.261562697,0", detail: None, hint: Some("See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable"), position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }) }', src/stash/src/postgres.rs:1481:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: <core::result::Result<mz_stash::postgres::Stash, mz_stash::StashError>>::expect
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: <mz_stash::postgres::DebugStashFactory>::open_debug::{closure#0}
             at ./src/postgres.rs:1479:9
   5: mz_stash::upgrade::v18_to_v19::tests::smoke_test::{closure#0}::test_impl::{closure#0}
             at ./src/upgrade/v18_to_v19.rs:204:45
   6: mz_stash::upgrade::v18_to_v19::tests::smoke_test::{closure#0}
             at ./src/upgrade/v18_to_v19.rs:199:5
   7: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
   8: <core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
   9: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:541:57
  10: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  12: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:541:25
  13: <tokio::runtime::scheduler::current_thread::Context>::enter::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:350:19
  14: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:540:36
  15: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:615:57
  16: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::current_thread::Context>>::set::<<tokio::runtime::scheduler::current_thread::CoreGuard>::enter<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core>, core::option::Option<()>)>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  17: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:615:27
  18: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:530:19
  19: <tokio::runtime::scheduler::current_thread::CurrentThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/current_thread.rs:154:24
  20: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:302:47
  21: mz_stash::upgrade::v18_to_v19::tests::smoke_test
             at ./src/upgrade/v18_to_v19.rs:199:5
  22: mz_stash::upgrade::v18_to_v19::tests::smoke_test::{closure#0}
             at ./src/upgrade/v18_to_v19.rs:199:5
  23: <mz_stash::upgrade::v18_to_v19::tests::smoke_test::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

I was a bit surprised that Cloudtest and Short Zippy did not fail even though panics were observed. Is this intentional?

I rebased my PR on main on June 16, so the commit ameliorating the problem with Cargo test (14ec9e5f06110aadcdf5d9a2d7a337df4c25aaac) should have been picked up...

**Comment by def-** [comment] 2023-06-20 09:21
@ParkMyCar "unable to open debug stash" is still happening, sounds like https://github.com/MaterializeInc/materialize/commit/14ec9e5f06110aadcdf5d9a2d7a337df4c25aaac didn't fix it fully.

**Comment by uce** [comment] 2023-06-20 09:23
@chaas @ParkMyCar Added to the surfaces project, because of the "unable to open debug stash" issue. Dennis is looking into why the tests pass although there are panics.

**Comment by def-** [comment] 2023-06-20 10:24
I just noticed that https://github.com/MaterializeInc/materialize/issues/19931#issuecomment-1593550798 is still open and @ParkMyCar had an explanation, so I'd consider this to be a duplicate of it (and a CRDB bug).

> I was a bit surprised that Cloudtest and Short Zippy did not fail even though panics were observed. Is this intentional?

I opened https://github.com/MaterializeInc/materialize/issues/20040 to keep track of this, seems unintentional to me.

**Closed** 2023-06-20 10:25 UTC
Labels: C-bug, ci-flake
