### ISSUE TITLE
S3 sources don't respect HTTP Proxy setting

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#6118] opened 2021-03-17 14:59 UTC
They don't respect the HTTP proxy environment variable.

This user is able to work around it for testing, but it's definitely blocking them from moving to production. [Link to private chat](https://materializecommunity.slack.com/archives/G0168U7190F/p1615809476027800)

**Comment by benesch** [comment] 2021-03-17 15:13
Duplicate of #6096.

**Closed by benesch** 2021-03-17 15:13 UTC
Labels: C-feature
