### ISSUE TITLE
internal transform error: fixpoint looped too many times with USING

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16076] opened 2022-11-15 11:00 UTC
### What version of Materialize are you using?

 v0.32.0-dev (95eeb37cb)

### How did you install Materialize?

Docker image

### What is the issue?

This query:

```
CREATE TABLE table_f2_f3 (f2 INTEGER, f3 INTEGER);
CREATE TABLE table_f3_f4 (f3 INTEGER, f4 INTEGER);
CREATE TABLE table_f3_f4_f5 (f3 INTEGER, f4 INTEGER, f5 INTEGER);
CREATE TABLE table_f4_f5 (f4 INTEGER, f5 INTEGER);
CREATE TABLE table_f5_f6 (f5 INTEGER, f6 INTEGER);

EXPLAIN SELECT *
  FROM table_f2_f3 , (
  	(table_f3_f4 AS a2 JOIN table_f3_f4_f5 AS a3 USING (f3, f4))
  	JOIN (table_f4_f5 AS a4 JOIN table_f5_f6 USING (f5))
  	USING (f4, f5)
  )
 WHERE f5 <= f5
   AND f4 = f6;
```

produces the output below. I tried removing the `USING` clauses but they seem to be required to reproduce.

### Relevant log output

```source
ERROR:  internal transform error: fixpoint looped too many times Fixpoint {
    transforms: [
        JoinImplementation {
            recursion_guard: RecursionGuard {
                depth: RefCell {
                    value: 0,
                },
                limit: 2048,
            },
        },
        ColumnKnowledge {
            recursion_guard: RecursionGuard {
                depth: RefCell {
                    value: 0,
                },
                limit: 2048,
            },
        },
        FoldConstants {
            limit: Some(
                10000,
            ),
        },
        Demand {
            recursion_guard: RecursionGuard {
                depth: RefCell {
                    value: 0,
                },
                limit: 2048,
            },
        },
        LiteralLifting {
            recursion_guard: RecursionGuard {
                depth: RefCell {
                    value: 0,
                },
                limit: 2048,
            },
        },
    ],
    limit: 100,
}; transformed relation: %0 =
| Get ? (u119)
| ArrangeBy ()

%1 =
| Get ? (u120)
| Filter (#0) IS NOT NULL, (#1) IS NOT NULL
| ArrangeBy (#0, #1)

%2 =
| Get ? (u121)
| Filter (#0) IS NOT NULL, (#1) IS NOT NULL, (#2 <= #2)
| ArrangeBy (#1, #2)

%3 =
| Get ? (u122)
| Filter (#0) IS NOT NULL, (#1 <= #1)
| ArrangeBy (#0, #1)

%4 =
| Get ? (u123)
| Filter (#1) IS NOT NULL, (#0 <= #0)

%5 =
| Join %0 %1 %2 %3 %4 (= #2 #4) (= #3 #5 #7 #10) (= #6 #8 #9)
| | implementation = Differential %4 %2.(#1, #2) %3.(#0, #1) %1.(#0, #1) %0.()
| Project (#0, #1, #3, #6, #2, #3)
```

**Comment by ggevay** [comment] 2022-11-18 14:29
Interestingly, it's not happening on the current main. I did a git bisection, and the commit that fixes (?) it is fe893350ee97e4381bf2050ab238d5166f9e6d56. But I'll still debug what was happening, because it's also possible that that commit just masks a still existing bug for this specific query.

**Comment by ggevay** [comment] 2022-11-18 15:36
This one is very tricky. fe89335 fixes it for most cases, but probably not all. The problem is that JoinImplementation can oscillate in the following way:
1. JoinImplementation looks at the ArrangeBys on the inputs (and several other input characteristics), and decides for some join order.
2. implement_arrangements (part of JoinImplementation) changes which inputs have what ArrangeBys.
3. Next run of JoinImplementation looks at the new set of ArrangeBys, and decides for a different join order.
4. implement_arrangements changes which inputs have what ArrangeBys. It might be that the new set of ArrangeBys are the same as before step 1, in which case we are in an infinite loop.

The query in the issue description oscillates between the following two states:
```
optimize/global/physical/fixpoint/0098
Project (#0, #1, #3, #6, #2, #3) // { arity: 6 }
  Join on=(#2 = #4 AND eq(#3, #5, #7, #10) AND eq(#6, #8, #9)) type=differential // { arity: 11 }
    implementation
      %4:table_f5_f6 » %2:table_f3_f4_f5[#1, #2]KKAf » %3:table_f4_f5[#0, #1]KKAf » %1:table_f3_f4[#0, #1]KKAf » %0:table_f2_f3[×]Af
    ArrangeBy keys=[[]] // { arity: 2 }
      Get materialize.public.table_f2_f3 // { arity: 2 }
    ArrangeBy keys=[[#0, #1]] // { arity: 2 }
      Filter (#0) IS NOT NULL AND (#1) IS NOT NULL // { arity: 2 }
        Get materialize.public.table_f3_f4 // { arity: 2 }
    ArrangeBy keys=[[#1, #2]] // { arity: 3 }
      Filter (#0) IS NOT NULL AND (#1) IS NOT NULL AND (#2 <= #2) // { arity: 3 }
        Get materialize.public.table_f3_f4_f5 // { arity: 3 }
    ArrangeBy keys=[[#0, #1]] // { arity: 2 }
      Filter (#0) IS NOT NULL AND (#1 <= #1) // { arity: 2 }
        Get materialize.public.table_f4_f5 // { arity: 2 }
    Filter (#1) IS NOT NULL AND (#0 <= #0) // { arity: 2 }
      Get materialize.public.table_f5_f6 // { arity: 2 }
```
```
optimize/global/physical/fixpoint/0099
Project (#0, #1, #3, #6, #2, #3) // { arity: 6 }
  Join on=(#2 = #4 AND eq(#3, #5, #7, #10) AND eq(#6, #8, #9)) type=differential // { arity: 11 }
    implementation
      %3:table_f4_f5 » %2:table_f3_f4_f5[#1, #2]KKAf » %1:table_f3_f4[#0, #1]KKAf » %4:table_f5_f6[#0, #1]KKf » %0:table_f2_f3[×]Af
    ArrangeBy keys=[[]] // { arity: 2 }
      Get materialize.public.table_f2_f3 // { arity: 2 }
    ArrangeBy keys=[[#0, #1]] // { arity: 2 }
      Filter (#0) IS NOT NULL AND (#1) IS NOT NULL // { arity: 2 }
        Get materialize.public.table_f3_f4 // { arity: 2 }
    ArrangeBy keys=[[#1, #2]] // { arity: 3 }
      Filter (#0) IS NOT NULL AND (#1) IS NOT NULL AND (#2 <= #2) // { arity: 3 }
        Get materialize.public.table_f3_f4_f5 // { arity: 3 }
    ArrangeBy keys=[[#0, #1]] // { arity: 2 }
      Filter (#0) IS NOT NULL AND (#1 <= #1) // { arity: 2 }
        Get materialize.public.table_f4_f5 // { arity: 2 }
    ArrangeBy keys=[[#0, #1]] // { arity: 2 }
      Filter (#1) IS NOT NULL AND (#0 <= #0) // { arity: 2 }
        Get materialize.public.table_f5_f6 // { arity: 2 }
```

Before fe89335, the first join input usually didn't end up with an ArrangeBy. Nowadays maybe it's more rare that we are removing an ArrangeBy, so maybe the bug should happen more rarely. But it seems to me that 100% ruling it out is super hard. For example, https://github.com/MaterializeInc/materialize/blob/fe893350ee97e4381bf2050ab238d5166f9e6d56/src/transform/src/join_implementation.rs#L580 might remove an ArrangeBy if the key is wrong. This might happen if one run of JoinImplementation reaches an input from one edge on the join graph, and puts an ArrangeBy on some keys, but then the next run puts it as the starting input, and wants to (outward) traverse a different edge of the join graph, in which case it can't use the previous ArrangeBy.

So instead of thinking through a gazillion cases in which ArrangeBys can be changed around by JoinImplementation, I would propose the following short-cut fix:
-  The main reason (maybe the only good reason?) we are currently running JoinImplementation multiple times is that sometimes we want to re-plan a differential join as a delta join when we see what ArrangeBys appeared after we decided for a differential join.
- I don't see a good reason to re-plan a diffferential join as a different differential join due to ArrangeBys having changed. Same for re-planning a delta join as a different delta join. In fact, it might even be counter-productive:
  - We are looking at ArrangeBys to try to find an order where we are not creating new arrangements.
  - However, if we get happy from seeing an ArrangeBy that was inserted by a previous run of JoinImplementation, that might actually be a false signal, since we are probably gonna be newly creating that arrangement.   
- Therefore, I'd say JoinImplementation should just check at the end whether it would be re-planning a differential as a different differential, or re-planning a delta as a different delta, and just not change the join node at all in these cases.

@frankmcsherry, What do you think?

**Comment by frankmcsherry** [comment] 2022-11-22 11:09
> @frankmcsherry, What do you think?

I think in the past we had it increase the available arrangements monotonically, which would prevent the oscillation. Doing that seems fine to me. We could remove them later in LIR planning, where we (aim to) do other arrangement pruning.

**Comment by ggevay** [comment] 2022-12-10 18:28
I'm still investigating what would be the best solution here, but want to record a disturbing observation that I just found after 2 hours of debugging: I thought the only reason why JoinImplementation is in a fixpoint loop is because sometimes we want to improve the join plan based on new ArrangeBys introduced by JoinImplementation, but it turns out that if we don't run to fixpoint then we can end up with an invalid join plan that later crashes the lowering. The reason for this is that the `implement_arrangements` call mutates the inputs and thus it invalidates the join order that we just came up with right before the `implement_arrangements` call. Specifically, if it lifts away a Project, then input arities change, which means that the column indexes in the join plan become invalid. If we run `JoinImplementation` to fixpoint then this weirdness cannot cause a crash, because if there is ever a run of `JoinImplementation` that doesn't change the inputs, then the _next_ run of `JoinImplementation` will come up with a plan that won't get invalidated.

**Comment by ggevay** [comment] 2022-12-12 20:12
> I think in the past we had it increase the available arrangements monotonically, which would prevent the oscillation. Doing that seems fine to me. We could remove them later in LIR planning, where we (aim to) do other arrangement pruning.

The problem is that this would cause the "Used indexes" part of EXPLAIN to be wrong. Although, this might be only a temporary issue, as we are probably going to change the "Used indexes" part of EXPLAIN to be based on LIR, see https://github.com/MaterializeInc/materialize/issues/16598

**Comment by ggevay** [comment] 2023-03-01 17:55
Fixed by https://github.com/MaterializeInc/materialize/pull/17708

**Closed by ggevay** 2023-03-01 17:55 UTC
Labels: C-bug, needs-discussion, A-optimization, A-COMPUTE, T-stability
