### ISSUE TITLE
Enable CREATE TABLE AS select_statement

### ISSUE THREAD

**Issue by joacoc** [MaterializeInc/materialize#11401] opened 2022-03-25 22:25 UTC
### Feature request

This behavior is currently supported in `materialized views` or `views` but not in tables.

`CREATE TABLE table AS SELECT * FROM ..`

The current alternative is to create the table and using:

`INSERT INTO table SELECT * FROM ...`

But the structure to create the table needs to be known beforehand.

This is also a limitation for integration with technologies like Cube.js who uses this type of query to create intermediate tables rather than views/materialized views.

**Comment by morsapaes** [comment] 2022-12-23 14:09
Duplicate of #5266.

**Closed by morsapaes** 2022-12-23 14:09 UTC
Labels: C-feature
