### ISSUE TITLE
thread 'coordinator' panicked at src/catalog/src/durable/impls/stash.rs:1201:13: global timestamp must always go up

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25075] opened 2024-02-08 16:06 UTC
### What version of Materialize are you using?

a190d69c46

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/6355#018d88b3-6ae3-46d6-abc2-812d1f6f061c I'm retrying to see if it's a flake.

```
thread 'coordinator' panicked at src/catalog/src/durable/impls/stash.rs:1201:13:
global timestamp must always go up
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <mz_catalog::durable::impls::stash::Connection as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/stash.rs:1201:13
   3: <mz_catalog::durable::impls::stash::Connection as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/stash.rs:1186:5
   4: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<core::option::Option<mz_storage_types::controller::PersistTxnTablesImpl>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
   5: <futures_util::future::maybe_done::MaybeDone<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<core::option::Option<mz_storage_types::controller::PersistTxnTablesImpl>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   6: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>>, core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
   7: <mz_catalog::durable::impls::shadow::ShadowCatalogState as mz_catalog::durable::DurableCatalogState>::set_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:579:9
   8: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
   9: <mz_adapter::catalog::Catalog>::persist_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/catalog.rs:806:14
  10: <mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence as mz_adapter::coord::catalog_oracle::TimestampPersistence<mz_repr::timestamp::Timestamp>>::persist_timestamp::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:277:14
  11: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::memory::error::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  12: <mz_adapter::coord::catalog_oracle::CatalogTimestampOracle<mz_repr::timestamp::Timestamp, mz_ore::now::NowFn>>::maybe_allocate_new_timestamps::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:206:18
  13: <mz_adapter::coord::catalog_oracle::CatalogTimestampOracle<mz_repr::timestamp::Timestamp, mz_ore::now::NowFn>>::new::<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/catalog_oracle.rs:186:58
  14: <mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time::<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord/timeline.rs:305:26
  15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<&mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  18: tokio::runtime::coop::budget::<core::task::poll::Poll<&mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  21: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>::{closure#0}, &mut mz_adapter::coord::timeline::TimelineState<mz_repr::timestamp::Timestamp>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  23: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::ensure_timeline_state_with_initial_time<mz_adapter::coord::catalog_oracle::CatalogTimestampPersistence>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  24: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-061aa9d6a6c96a023-1/materialize/tests/src/adapter/src/coord.rs:2901:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
ci-regexp: global timestamp must always go up

**Comment by jkosh44** [comment] 2024-02-08 16:10
CC @aljoscha

This happened in the Launch Darkly test? My guess is that the timestamp oracle flag was flipped from shared to non-shared and that somehow caused a regression in the timestamp. Does that sound possible @aljoscha?

**Comment by def-** [comment] 2024-02-08 16:10
Correct.

**Comment by def-** [comment] 2024-02-08 16:46
Also now seen in platform-checks when toggling the timestamp oracle, so @jkosh44's hunch sounds correct: https://buildkite.com/materialize/nightlies/builds/6358#018d8916-ed31-41eb-a2b7-fd4c4dde89ba

**Comment by jkosh44** [comment] 2024-02-08 16:49
I'm going to re-assign this to @aljoscha since he's working on the timestamp oracle. I'm pretty sure that we've flipped everyone in staging and prod over to the shareable timestamp oracle and we don't plan on ever switching it back, so this may be a non-issue now.

**Comment by aljoscha** [comment] 2024-02-09 10:55
@def- This is likely because I changed the default from Catalog to Postgres. Could that be messing with the expectations of the test. If we want to fix it, maybe we need to be explicit about configuring `timestamp_oracle=Catalog` now in some of the test setup? I pushed up a PR for investigating.

**Comment by aljoscha** [comment] 2024-02-09 11:44
@jkosh44 The problem is that this bit of logic that I added is now potentially advancing the boot_ts a bit further: https://github.com/MaterializeInc/materialize/blob/65944d0508842b9ef153a4f9524192a9b2bb8258/src/adapter/src/catalog/open.rs#L273

Which then does a `set_timestamp` here:
https://github.com/MaterializeInc/materialize/blob/65944d0508842b9ef153a4f9524192a9b2bb8258/src/adapter/src/catalog/open.rs#L280

However, we then later initialize the Catalog oracle with the previously fetched "initial oracle timestamps", which are lower than the `boot_ts`.

You can see all this in the logs when you search for `1707477994677`, the offending timestamp.

This got introduced because the `previous_ts`, which is used to derive the `boot_ts` is now potentially more advanced because it also takes the Postgres oracle into account, as of my change. We can see in the logs that the pg timestamp is ~5 seconds further along than the catalog oracle timestamp:
```
launchdarkly-materialized-1  | environmentd: 2024-02-09T11:26:34.596147Z  INFO adapter::serve: mz_adapter::coord: current timestamps from the catalog-backed timestamp oracle: EpochMilliseconds -> 1707477981321
launchdarkly-materialized-1  | environmentd: 2024-02-09T11:26:34.615570Z  INFO adapter::serve: mz_adapter::coord: current timestamps from the postgres-backed timestamp oracle: "M" -> 1707477985887
launchdarkly-materialized-1  | environmentd: 2024-02-09T11:26:34.615598Z  INFO adapter::serve: mz_adapter::coord: initial oracle timestamps: EpochMilliseconds: 1707477985887
```

I _think_ this would be fixed by advancing the "initial oracle timestamps" to the `boot_ts`. But I don't know if I like that, plus I think the problem is exacerbated by `catalog_oracle::monotonic_now` wanting to advance the `boot_ts` by a full 5 seconds here, which we also don't need anymore once we remove the Catalog oracle.

**Comment by jkosh44** [comment] 2024-02-09 15:28
> However, we then later initialize the Catalog oracle with the previously fetched "initial oracle timestamps", which are lower than the boot_ts.

Where does this happen?

**Closed** 2024-02-12 18:26 UTC
Labels: C-bug
