### ISSUE TITLE
parallel-workload: halting process: dataflow creation cannot fail: SinceViolation(User(267))

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24130] opened 2023-12-28 12:13 UTC
### What version of Materialize are you using?

2831ad5e72

### What is the issue?

This happened on my PR https://github.com/MaterializeInc/materialize/pull/24111 and I believe is related to the additional jitter it introduces to CRDB and S3 connections: https://buildkite.com/materialize/nightlies/builds/5737#018cb02e-a134-4995-b2fb-6fa34b578c43
```
environmentd: 2023-12-28T11:51:08.515466Z  WARN mz_adapter::util: halting process: dataflow creation cannot fail: SinceViolation(User(267))
```

The envd shutdown happens during a webhook POST:
```
[worker_20] POST http://localhost:6976/api/webhook/db-pw-1703763121-1/s-2/wh-9 Headers: ih1: b'"M9xmtkXKOJZIRfTs1jJV999MmBb3ea9sVd7KWhHPamb4UKsZCN2PuTuaJdy6rBxoSWDevaeOqgauPCdSTPQ9jNYWgOj5oThGZGvB"', x-event-type: b'"YiOmBh43DmtioybOJExLwCmfRWQmIdEgzR83UGAkO0ZXH8EPZ4m4j8QPOlwwH9JKBHsAW2PQVMEXj0EEUuPle4CDvTpikynCAuvz"', ih4: b'"iisX2S5Y78Ph80EuhCiWVxm45W6mzidNaw16TWJIjeW381yw56mdB9D3gSC6Wr0GalC2BljJsoUvogobmTCbhTLUXmRKxuhPECWK"', x-mz-api-key: b'"UKxy5583ueUzuUPGikRxR8L6R7Ncqc93311FW7zuK3ScVoExAXhC24dGZPezYegVG4ffcfc9ce1afyif9UJ8yCwz5QkZmhQM5mwk"', ih2: b'"nY6lx8Iwnu1p07aypZpCZHJsUrGgCrpffUFZTy5spiFAaSi647xbxbYXXQTzXuNYizmq6dKtH5sAJiYoEbZeIvjd9XKrRPHy4mve"', ih0: b'"PBC6R9Zu4aZdpZwv8vtl5E2k95swVS01DoyWDgvAJf6m6vcNf9PvGVlt2bBNlmupmYhPJJBjcdpDJlizCZk4667CNSMoVveZy7pr"', signature: b'"A1D44kpVp52fTAI3VIC9tegsvGt2BfbpfjUwEKgab3NTl5Zq6aJQHAwRWjDDzoLMod5bJ7d22RHVBHYqKv8xLzzd6QSyFUqQ0fT3"', ih3: b'"9KloyPmK2WM2RfWl8zoW1zF2ZLHk4trWVfg9DC3glDJAl8rNcXQlauaBMuBaNQ7R0Jj4GMq8c6u6yDhN5YogTwZiwp1u8AStGoZQ"' Body: b'WS5ILtJB2RbTdjlEn9via5vobLHKiLJY0eYCJjnnL2IGyAIHNbFRfKKMA4dBGjpTfjb1BJ3ilIsrTYeAWQz4yXfqfuOZtxsKIXcz'
```
What seems suspicious is that this happened immediately after worker_22 is dropping the source concurrently:
```
[worker_22] DROP SOURCE "db-pw-1703763121-1"."s-2"."wh-9";
```
What normally happens then is to get back a 404 error, which would be expected and ignored. Because of the added network jitter envd might still believe that the source exists, start creating the dataflow, which then fails because it was dropped in the meantime.

This `dataflow creation cannot fail` was added in https://github.com/MaterializeInc/materialize/pull/22263 CC @aalexandrov 

All queries: [parallel-workload-queries.log](https://github.com/MaterializeInc/materialize/files/13786327/parallel-workload-queries.log)

This might be reproducible on the PR code state with
```bash
git checkout 2831ad5e727d3645dcf37a1527a455897ef6263c
while true; do bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --seed=1703763121 --threads=32 --runtime=1500 --complexity=ddl --scenario=regression || break; done
```
I'll try that locally to see if I can reproduce it.

ci-regexp: dataflow creation cannot fail: SinceViolation
ci-regexp: cannot fail to create dataflows: SinceViolation
ci-regexp: cannot fail to peek: SinceViolation

**Comment by ParkMyCar** [comment] 2024-01-05 19:08
Dug into this a bit, and I don't think it's related to webhooks. As far as I can tell POSTing to a webhook at the same time that environmentd halts is just a coincidence.

It looks like when trying to create a dataflow (maybe a subscribe?) a dependent object `u267`, which is the materialize view `db-pw-1703763121-0.s-0.v-52`, has a `SinceViolation`. Given the failure started happening when we introduced jitter to S3 and CRDB, it seems like maybe a timestamp we picked is no longer valid, because of the jitter?

Going to move this over to @aalexandrov from compute

**Comment by aalexandrov** [comment] 2024-01-08 13:52
#22263 was just reorganizing code. This particular `unwrap_or_terminate` which asserts that a `ship_dataflow` will never fail is also something that the code had before that PR. I don't have enough expertise in the timestamp selection process to resolve this, moving to @teskje for further triaging and re-assignment.

**Comment by teskje** [comment] 2024-01-10 09:04
I didn't manage to reproduce this, but there is a chance that the bug fixed in https://github.com/MaterializeInc/materialize/pull/24298 could lead to this panic. So let's see if it reoccurs after that PR has been merged.

**Comment by philip-stoev** [comment] 2024-01-22 07:17
This issue is now affecting numerous workloads in the CI pipeline https://buildkite.com/materialize/nightlies/builds/6082

**Comment by philip-stoev** [comment] 2024-01-22 07:20
How this can be both a `WARN` and a `halting process` ?

**Comment by teskje** [comment] 2024-01-22 08:50
A "halt" is different from a panic in that it is expected to sometimes happen, so we only `WARN` about it. We shouldn't do that for this error though. Fixed in https://github.com/MaterializeInc/materialize/pull/24516.

**Comment by def-** [comment] 2024-01-24 22:32
Also seen in cargo test in https://buildkite.com/materialize/tests/builds/73884#018d3caf-e2e8-4830-82f0-8040b03eb640
```
--- STDERR:              mz-environmentd::server test_closing_connection_for_insert_select ---
NOTICE:  connected to Materialize v0.85.0-dev
  Org ID: 4306552b-24c2-4227-9032-c229a4406c60
  Region: local/az1
  User: materialize
  Cluster: quickstart
  Database: materialize
  Schema: public

Issue a SQL query to get started. Need help?
  View documentation: https://materialize.com/s/docs
  Join our Slack community: https://materialize.com/s/chat
    
thread 'coordinator' panicked at src/adapter/src/util.rs:283:23:
cannot fail to create dataflows: SinceViolation(System(746))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <core::result::Result<(), mz_compute_client::controller::error::DataflowCreationError> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/util.rs:283:23
   3: <mz_adapter::coord::Coordinator>::implement_peek_plan::{closure#0}::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/peek.rs:559:17
   4: <mz_adapter::coord::Coordinator>::implement_peek_plan::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/peek.rs:438:5
   5: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:844:14
   6: <mz_adapter::coord::Coordinator>::peek_stage_finish::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:760:5
   7: <mz_adapter::coord::Coordinator>::execute_peek_stage::{closure#0}::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:176:71
   8: <mz_adapter::coord::Coordinator>::execute_peek_stage::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:125:5
   9: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord/message_handler.rs:158:67
  10: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  11: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  12: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord.rs:2539:48
  13: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  14: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  16: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  17: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  18: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  19: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  20: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  21: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  22: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  23: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a92a6dba844ddc3e-1/materialize/tests/src/adapter/src/coord.rs:2940:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by def-** [comment] 2024-01-25 08:45
This started happening so frequently between https://github.com/MaterializeInc/materialize/compare/b615c89de9...759d388b33
Two compute-related PRs landed in this time: https://github.com/MaterializeInc/materialize/pull/24569 (@aalexandrov ) and https://github.com/MaterializeInc/materialize/pull/24631 (@teskje ). At the moment this makes CI very hard to use, so a quick fix would be much appreciated!

**Comment by teskje** [comment] 2024-01-25 09:03
I'm pretty confident that https://github.com/MaterializeInc/materialize/pull/24631 is not the cause, since it changes nothing related to timestamp selection. https://github.com/MaterializeInc/materialize/pull/24569 contains a change that we previously had to revert because it caused `SinceViolation` errors, so that is more suspicious.

**Comment by aalexandrov** [comment] 2024-01-25 09:28
@def- I opened #24677, but I suggest triggering some extra runs on the failing tests with https://trigger-ci.dev.materialize.com/ before we merge this.

**Comment by def-** [comment] 2024-01-25 09:58
The nightly run did catch it, but we had this failure before, so it was considered a "known issue". But with your PR it is occurring much more commonly.

**Comment by def-** [comment] 2024-01-25 11:16
This is now also commonly happening in staging in v0.85.0-dev

**Comment by nrainer-materialize** [comment] 2024-01-26 08:41
I have a repro in https://github.com/MaterializeInc/materialize/pull/24648, which repeatedly runs a workflow with DDL statements with 16 concurrent connections. The workflow consists of creating a table with a few integer columns, inserting 100 rows, creating a trivial mv on it, selecting star from the mv, and dropping the table with cascade.

**Comment by teskje** [comment] 2024-01-26 09:38
@nrainer-materialize Is that PR based off a recent enough version of main to include https://github.com/MaterializeInc/materialize/pull/24677?

**Comment by nrainer-materialize** [comment] 2024-01-26 09:44
> @nrainer-materialize Is that PR based off a recent enough version of main to include #24677?

No, it does not include merge commit https://github.com/MaterializeInc/materialize/commit/86ead0ad46b47560c290da435e0be98e7a7044a5. I will rebase my branch.

**Comment by teskje** [comment] 2024-02-18 11:12
According to Sentry this has not occurred since v0.85.0, so I'm closing this issue. It's possible that we did not fix the original root cause of this, in which case I'd prefer opening a new issue when/if the panic reoccurs, so we don't get confused trying to handle different bugs in the same ticket.

**Closed by teskje** 2024-02-18 11:12 UTC
Labels: C-bug, ci-flake
