### ISSUE TITLE
test: Speed up `mz-adapter catalog::tests::test_builtin_migration`

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#22146] opened 2023-10-03 20:31 UTC
Follow-up from: https://github.com/MaterializeInc/materialize/issues/21891

The `mz-adapter catalog::tests::test_builtin_migration` test is very slow. the last measured run was 114.583s. Much of this slowness is due to slow startup time since each test case needs to open a fresh catalog.

We should speed this test up.

**Comment by chaas** [comment] 2024-09-18 18:19
Duplicate of #28722

**Closed by chaas** 2024-09-18 18:19 UTC
Labels: C-refactoring
