### ISSUE TITLE
Postgres: restarting postgres causes the Pg source to error out with File IO: connection closed

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6599] opened 2021-04-28 13:50 UTC
### What version of Materialize are you using?

```
f96b7e23620bfcb727514dd2d9319f298c881173
```

### What was the issue?

A mzcompose-based test that kills postgres and restarts it reports that the postgresql source does not recover.

This only happens if:
- the test does KILL + restart
- the volume of data inserted on the pg side is 2 M records. The issue does not happen with 200K records.

### Is the issue reproducible? If so, please provide reproduction instructions.

Please clone the ```philip-stoev:gh6599-test``` branch and run:
```
cd test/pg-cdc-failures
./mzcompose down -v ; ./mzcompose run pg-cdc-failures-restart-pg
```

and you will get:

```
> SELECT COUNT(*) = 2000000 FROM t1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
02-after-restart.td:13:1: error: executing query failed: db error: ERROR: Source error: File IO: connection closed
     |
  12 | 
  13 | > SELECT COUNT(*) = 2000000 FROM t1;
     | ^
ERROR: 1
Failed! giving up: testdrive-svc --no-reset 02-after-restart.td
```

**Comment by petrosagg** [comment] 2021-05-13 12:22
So I thought I was fixing this issue with #6743 but after looking more closely to the error you got ("connection closed") it is actually expected behaviour. The reason this needed a ton of rows to be in the table to trigger was that you were racing with the intitial table sync process that does not have an easy way of recovering from these kind of errors (lest buffering everything in RAM/disk).

The limitation is described in more detail here https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20210412_postgres_sources.md#initial-sync-resume-logic

In order to fix this issue the source would have to buffer all the data of the database somewhere just in case the connection drops. Since the writing of the design doc above I have come up with an alternative strategy which I think should be the final implementation:

1. Start the initial table sync and every row that is received will be 1) emitted into the dataflow and 2) stored in a temporary file on disk
2. In the happy path, the initial sync finishes with no error and the temporary files can be deleted. In the case of a connection error the buffered rows on disk are re-read and used to issue retractions for all rows sent in the dataflow so far. Then the process starts anew

@awang given this only happens during the initila phase do you still think it's a top priority?

**Comment by philip-stoev** [comment] 2021-05-17 11:36
After discussion with @petrosagg, I think it is OK if this error is not handled during the initial sync. The user has the opportunity to drop and restart the source. There is no opportunity for this error to show up in the middle of operations, long after the source has been created.

However, the error is very not informative and does not provide any information as to the correct course of action. There is nothing in the server log and the SQL error is simply "Source error: File IO: connection closed". It does not even way which source this is about.

Something like this would be more appropriate "Source X failed during initialization: File IO: connection closed. Drop and recreate the source to try again" or something along those lines.

**Comment by JLDLaughlin** [comment] 2021-05-20 19:29
So, I should have done this earlier, but I am unable to reproduce the error that you've shared locally! Here's what I see:
```
Running test 1 time(s) ...
Run 1 ...
Executing queries against PostgreSQL server at postgres://postgres:postgres@postgres...
>> INSERT INTO t1 SELECT a1.f1 * a2.f1 * a3.f1 * a4.f1 * a5.f1 FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
> SELECT COUNT(*) = 2000000 FROM t1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
02-after-restart.td:13:1: error: executing query failed: db error: ERROR: At least one input has no complete timestamps yet: [User(2)]
     |
  12 |
  13 | > SELECT COUNT(*) = 2000000 FROM t1;
     | ^
Failed! giving up: testdrive-svc --no-reset 02-after-restart.td
```

**Comment by JLDLaughlin** [comment] 2021-05-20 19:50
Ah! I applied your test commit to `main` and was able to recreate the error:
```
==> 02-after-restart.td
Running test 1 time(s) ...
Run 1 ...
Executing queries against PostgreSQL server at postgres://postgres:postgres@postgres...
>> INSERT INTO t1 SELECT a1.f1 * a2.f1 * a3.f1 * a4.f1 * a5.f1 FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5, ten AS a6;
> SELECT COUNT(*) = 2000000 FROM t1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 1s
02-after-restart.td:13:1: error: executing query failed: db error: ERROR: Source error: materialize.public.t1: failed during initialization, must be dropped and recreated: connection closed
     |
  12 |
  13 | > SELECT COUNT(*) = 2000000 FROM t1;
     | ^
1 errors were encountered during execution
files involved: 02-after-restart.td
```

**Comment by JLDLaughlin** [comment] 2021-06-02 20:49
Fixed by https://github.com/MaterializeInc/materialize/pull/6799!

**Closed by JLDLaughlin** 2021-06-02 20:49 UTC
Labels: A-source, C-bug, G-external integrations, Top Priority
