### ISSUE TITLE
platform-checks workflow-default is flaky

### ISSUE THREAD

**Issue by mgree** [MaterializeInc/materialize#19868] opened 2023-06-12 17:10 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/57429#_

### Relevant log output

```source
[2023-06-12T16:31:59Z] $ docker compose exec -T testdrive testdrive --kafka-addr=kafka:9092 --schema-registry-url=http://schema-registry:8081 --materialize-url=postgres://materialize@materialized:6875 --materialize-internal-url=postgres://materialize@materialized:6877 --aws-endpoint=http://localstack:4566 --no-reset --default-timeout=300s --seed=1 --var=replicas=1 --var=default-replica-size=4-4 --var=default-storage-size=4-1
[2023-06-12T16:31:59Z] > SELECT * FROM debezium_view1;
[2023-06-12T16:36:59Z] rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
[2023-06-12T16:36:59Z] 2:1: error: non-matching rows: expected:
[2023-06-12T16:36:59Z] [["A", "5", "16000"], ["B", "5", "16000"], ["C", "5", "16000"], ["D", "4", "16000"], ["E", "3", "16000"], ["F", "2", "16000"]]
[2023-06-12T16:36:59Z] got:
[2023-06-12T16:36:59Z] [["A", "1", "16000"], ["B", "1", "16000"]]
[2023-06-12T16:36:59Z] Poor diff:
[2023-06-12T16:36:59Z] + A 1 16000
[2023-06-12T16:36:59Z] - A 5 16000
[2023-06-12T16:36:59Z] + B 1 16000
[2023-06-12T16:36:59Z] - B 5 16000
[2023-06-12T16:36:59Z] - C 5 16000
[2023-06-12T16:36:59Z] - D 4 16000
[2023-06-12T16:36:59Z] - E 3 16000
[2023-06-12T16:36:59Z] - F 2 16000
[2023-06-12T16:36:59Z]
[2023-06-12T16:36:59Z]      |
[2023-06-12T16:36:59Z]    1 |
[2023-06-12T16:36:59Z]    2 | > SELECT * FROM debezium_view1;
[2023-06-12T16:36:59Z]      | ^
!!! Error Report
[2023-06-12T16:36:59Z] 1 errors were encountered during execution
[2023-06-12T16:36:59Z] files involved: -
[2023-06-12T16:36:59Z] mzcompose: test case workflow-default failed: running docker compose failed (exit status 1)
[2023-06-12T16:36:59Z] ==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
[2023-06-12T16:36:59Z] 202 {"id":"12e28bb9-4486-467f-9ef5-635f1827c485","run_id":"97b358fa-df3e-450b-b0d1-62170c1ccd33","queued":1,"skipped":0,"errors":[],"run_url":"https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/97b358fa-df3e-450b-b0d1-62170c1ccd33"}
[2023-06-12T16:36:59Z] mzcompose: error: at least one test case failed
[2023-06-12T16:37:00Z] 🚨 Error: The command exited with status 1
```
```


### Additional thoughts

[Works on retry](https://buildkite.com/materialize/tests/builds/57429#0188b08d-0b17-4db7-baf8-89e2b2ffbef0).

**Comment by def-** [comment] 2023-06-13 08:38
Previously happened here: https://github.com/MaterializeInc/materialize/issues/18329

**Comment by uce** [comment] 2023-06-13 08:39
We kill and restart Postgres. Debezium is sometimes unable to handle those restarts and gives up. We need to handle this better on the testing infrastructure side.

**Comment by def-** [comment] 2023-06-13 08:40
@sploiselle Do you think this could be part of the issue, and not fully fixed by https://github.com/MaterializeInc/materialize/pull/18769 ?

**Comment by sploiselle** [comment] 2023-06-13 11:00
@def- That fix was for the PG source; this error is in a Kafka source, ingesting PG through Debezium. Convoluted, I know. Un/fortunately, not something related to https://github.com/MaterializeInc/materialize/pull/18769 whatsoever.

**Comment by antiguru** [comment] 2023-07-21 09:34
Duplicate of #20391

**Closed by antiguru** 2023-07-21 09:34 UTC
Labels: C-bug, ci-flake
