### ISSUE TITLE
docs: document 'negative multiplicity error' in debezium docs

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#5526] opened 2021-02-01 01:29 UTC
This error isn't very self-explanatory; a longer treatment is required when discussing envelopes. In particular, if we documented this here, then searching 'negative multiplicity' in the docs search bar would result in this showing up.

**Comment by rjnn** [comment] 2021-02-01 03:52
In particular, log compaction with envelope debezium breaks with this bug, so this should be documented as explicitly not supported.

**Comment by morsapaes** [comment] 2022-06-29 09:00
Has this ever been reported outside of #2313? It sounds like an edge case that is caused by malformed (or, not in the form Materialize expects) change events at the source. We're explicit about what Materialize expects in the [Debezium envelope documentation](https://github.com/MaterializeInc/materialize/issues/2313), so I wouldn't make this a specific thing we call out. 

Closing this as I work through our documentation backlog, but feel free to re-open if you have strong feelings about it, @rjnn!

**Closed by morsapaes** 2022-06-29 09:00 UTC
Labels: C-feature, A-docs
