### ISSUE TITLE
Transactions spanning more than one timestamp could cause issues for materialize

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#1445] opened 2020-01-06 19:23 UTC
Currently, consistency guarantees may not hold for a given timestamp if topics are fed from Debezium, since Debezium does not guarantee that events that were part of the same transaction will have the same timestamp.

**Comment by awang** [comment] 2020-05-27 13:55
duplicate of https://github.com/MaterializeInc/materialize/issues/1979?

**Closed by awang** 2020-05-27 13:55 UTC
Labels: C-bug
