### ISSUE TITLE
Fast SQL logic tests is flaky (panicked at 'no entry found for key')

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#15747] opened 2022-10-27 17:50 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/44124#01841a71-4744-4dbb-9f43-dc564f6ecf27

### Relevant log output

```source
'coordinator' panicked at 'no entry found for key', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6c9ab957d72d4b-1/materialize/tests/src/compute-client/src/controller/instance.rs:332:24
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::park::thread::CachedParkThread::block_on
   8: tokio::runtime::handle::Handle::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

Possibly related to https://github.com/MaterializeInc/materialize/issues/15735 https://github.com/MaterializeInc/materialize/issues/10799

**Comment by teskje** [comment] 2022-10-28 07:57
Closing as I'm pretty sure this was caused by #15735 and fixed by https://github.com/MaterializeInc/materialize/pull/15737.

**Closed by teskje** 2022-10-28 07:57 UTC
Labels: C-bug, C-triage, ci-flake
