### ISSUE TITLE
AS OF NOW() on non-materialized sources may return incomplete/non-linearizable results

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10587] opened 2022-02-10 13:07 UTC
### What version of Materialize are you using?

v0.20.1-dev (d6329387a)

### How did you install Materialize?

Docker image

### What was the issue?

There are several distinct ways/anomalies in which `AS OF NOW()` can return unexpected results when applied against a non-materialized source. Those do not happen with materialized sources.

1. `AS OF NOW()` may return a partially-ingested view of the source before returning a complete view:
```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now             | count 
----------------------------+-------
 2022-02-10 12:59:03.374+00 | 28900
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now            | count  
---------------------------+--------
 2022-02-10 12:59:04.72+00 | 100000
```

2. `AS OF NOW()` may return an error after having returned without an error previously:

```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now            | count  
---------------------------+--------
 2022-02-10 12:59:04.72+00 | 100000
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
ERROR:  Timestamp (1644497944988) is not valid for all inputs: [Antichain { elements: [1644497944999] }]
```

3. `AS OF NOW()` **may repeatedly return one record less than expected**  and fluctuate between a complete result and a "complete minus one record" result:
```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now             | count 
----------------------------+-------
 2022-02-10 12:58:15.972+00 | 99999 <- HERE
(1 row)
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now             | count 
----------------------------+-------
 2022-02-10 12:58:16.977+00 | 99999 <- AND HERE
```

To reproduce:

1. Populate a bunch of topics:
```
$ set keyschema={"type": "record", "name": "Key", "fields": [ { "name": "f1", "type": "long" } ] }

$ set schema={"type" : "record", "name" : "test", "fields": [ { "name": "f2", "type": "long" } ] }

$ set count=100000


$ kafka-create-topic topic=multi-topic-0

$ kafka-ingest format=avro topic=multi-topic-0 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-1

$ kafka-ingest format=avro topic=multi-topic-1 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-2

$ kafka-ingest format=avro topic=multi-topic-2 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-cr ate-topic topic=multi-topic-3

$ kafka-ingest format=avro topic=multi-topic-3 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-4

$ kafka-ingest format=avro topic=multi-topic-4 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-5

$ kafka-ingest format=avro topic=multi-topic-5 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-6

$ kafka-ingest format=avro topic=multi-topic-6 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-7

$ kafka-ingest format=avro topic=multi-topic-7 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-8

$ kafka-ingest format=avro topic=multi-topic-8 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-9

$ kafka-ingest format=avro topic=multi-topic-9 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-10

$ kafka-ingest format=avro topic=multi-topic-10 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-11

$ kafka-ingest format=avro topic=multi-topic-11 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-12

$ kafka-ingest format=avro topic=multi-topic-12 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-13

$ kafka-ingest format=avro topic=multi-topic-13 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-14

$ kafka-ingest format=avro topic=multi-topic-14 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-15

$ kafka-ingest format=avro topic=multi-topic-15 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }
```
2. Run the queries below using the psql client against Mz with `--workers 1` , making sure the name of nonce in the `CREATE SOURCE` statements has been updated to reflect the nonce that testdrive used to create the topics. Note that the queries examine only source `s0`, the other sources and the materialized view I assume just put pressure on the timely scheduler:
```

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE  SOURCE s0 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-0-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s1 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-1-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s2 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-2-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s3 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-3-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s4 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-4-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s5 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-5-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s6 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-6-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s7 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-7-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s8 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-8-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s9 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-9-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s10 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-10-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s11 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-11-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s12 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-12-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s13 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-13-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s14 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-14-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;
CREATE  SOURCE s15 FROM KAFKA BROKER 'localhost:9092' TOPIC 'testdrive-multi-topic-15-1489697404' FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081/' ENVELOPE NONE;

CREATE MATERIALIZED VIEW v1 AS SELECT SUM(f1) AS f1 FROM (SELECT COUNT(*) AS f1 FROM s0 UNION ALL SELECT COUNT(*) AS f1 FROM s1 UNION ALL SELECT COUNT(*) AS f1 FROM s2 UNION ALL SELECT COUNT(*) AS f1 FROM s3 UNION ALL SELECT COUNT(*) AS f1 FROM s4 UNION ALL SELECT COUNT(*) AS f1 FROM s5 UNION ALL SELECT COUNT(*) AS f1 FROM s6 UNION ALL SELECT COUNT(*) AS f1 FROM s7 UNION ALL SELECT COUNT(*) AS f1 FROM s8 UNION ALL SELECT COUNT(*) AS f1 FROM s9 UNION ALL SELECT COUNT(*) AS f1 FROM s10 UNION ALL SELECT COUNT(*) AS f1 FROM s11 UNION ALL SELECT COUNT(*) AS f1 FROM s12 UNION ALL SELECT COUNT(*) AS f1 FROM s13 UNION ALL SELECT COUNT(*) AS f1 FROM s14 UNION ALL SELECT COUNT(*) AS f1 FROM s15);

\timing on
SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);

SELECT now(), count(*) FROM s0 AS OF NOW();
SELECT mz_internal.mz_sleep(0.1);
```

**Comment by frankmcsherry** [comment] 2022-02-10 13:22
Some quick takes from me on the three symptoms:

1. This is "in spec" at the moment. I wish that it were not. We do have the ability to ensure that `CREATE SOURCE` observes the maximum offset at time of creation and timestamps it then, as part of our linearizability guarantees. There is a related issue I can track down about our timestamping discipline here.
2. This is "in spec" at the moment, but we should be able to fix it. Imo the coordinator should probably not compact things past `now()` rendering them invalid at the moment. Afaict, the only way to get the "is not valid for all inputs" is to have a query that prescribes a query time, and unfortunately if inputs have been compacted past that time we cannot pick a new time to catch up to (without violating the `AS OF` constraint). But we can prevent the coordinator from compacting past `now()`.
3. Looks buggy for sure. If you hadn't said "fluctuates" I would have said "in spec, unfortunately" but if it goes *down* ever there is a very clear issue there.

I think we should fix all three, just trying to provide my take on what we need to chase down (e.g. product definition, specific bugs, specific code).

**Comment by philip-stoev** [comment] 2022-02-10 13:26
I can reproduce Item No 3  against main and other revisions, e.g. `v0.19.1-dev (6532f492a)`. But I can not reproduce against v0.19.0 .

Items No 1 and No 2 are reproducible with v0.19.0

> Looks buggy for sure. If you hadn't said "fluctuates" I would have said "in spec, unfortunately" but if it goes down ever there is a very clear issue there.

Yes, it goes up and down , so goes from 99999 to 100000 and back: 

```
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now             | count  
----------------------------+--------
 2022-02-10 13:20:33.523+00 | 100000
...
materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now             | count 
----------------------------+-------
 2022-02-10 13:20:34.648+00 | 99999
```

**Comment by frankmcsherry** [comment] 2022-02-10 13:41
@ruchirK does it seem right to you that (3.) is a violation of source timestamping durability? If we read 100,000 records from a source, then read the source again, we should (I think) expect to see the 100,000 again, because the timestamp bindings should be durable. If not durability, maybe compaction, etc., but it seems to be a thing that is out of spec with how we MZ is spec'd to behave today, right?

**Comment by philip-stoev** [comment] 2022-02-10 15:08
Mz runs with default settings. For no 1, it can take up to 3 select queries
for the result to start showing all records. For no 3, once all records
appear, the result always fluctuates between N and N - 1

**Comment by ruchirK** [comment] 2022-02-10 23:17
I transcribed philips repro instructions into the following testdrive snippet:

```
$ set keyschema={"type": "record", "name": "Key", "fields": [ { "name": "f1", "type": "long" } ] }

$ set schema={"type" : "record", "name" : "test", "fields": [ { "name": "f2", "type": "long" } ] }

$ set count=100000


$ kafka-create-topic topic=multi-topic-0

$ kafka-ingest format=avro topic=multi-topic-0 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-1

$ kafka-ingest format=avro topic=multi-topic-1 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-2

$ kafka-ingest format=avro topic=multi-topic-2 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-3

$ kafka-ingest format=avro topic=multi-topic-3 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-4

$ kafka-ingest format=avro topic=multi-topic-4 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-5

$ kafka-ingest format=avro topic=multi-topic-5 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-6

$ kafka-ingest format=avro topic=multi-topic-6 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-7

$ kafka-ingest format=avro topic=multi-topic-7 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-8

$ kafka-ingest format=avro topic=multi-topic-8 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-9

$ kafka-ingest format=avro topic=multi-topic-9 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-10

$ kafka-ingest format=avro topic=multi-topic-10 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-11

$ kafka-ingest format=avro topic=multi-topic-11 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-12

$ kafka-ingest format=avro topic=multi-topic-12 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-13

$ kafka-ingest format=avro topic=multi-topic-13 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-14

$ kafka-ingest format=avro topic=multi-topic-14 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

$ kafka-create-topic topic=multi-topic-15

$ kafka-ingest format=avro topic=multi-topic-15 schema=${schema} publish=true repeat=${count}
{"f2": ${kafka-ingest.iteration} }

> CREATE SOURCE s0 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-0-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s1 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s2 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-2-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s3 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-3-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s4 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-4-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s5 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-5-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s6 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-6-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s7 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-7-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s8 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-8-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s9 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-9-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s10 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-10-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s11 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-11-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s12 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-12-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s13 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-13-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s14 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-14-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE SOURCE s15 FROM KAFKA BROKER '${testdrive.kafka-addr}'
  TOPIC 'testdrive-multi-topic-15-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}' ENVELOPE NONE;

> CREATE MATERIALIZED VIEW v1 AS
  SELECT SUM(f1) AS f1 FROM
  (SELECT
    COUNT(*) AS f1 FROM s0
      UNION ALL SELECT COUNT(*) AS f1 FROM s1
      UNION ALL SELECT COUNT(*) AS f1 FROM s2
      UNION ALL SELECT COUNT(*) AS f1 FROM s3
      UNION ALL SELECT COUNT(*) AS f1 FROM s4
      UNION ALL SELECT COUNT(*) AS f1 FROM s5
      UNION ALL SELECT COUNT(*) AS f1 FROM s6
      UNION ALL SELECT COUNT(*) AS f1 FROM s7
      UNION ALL SELECT COUNT(*) AS f1 FROM s8
      UNION ALL SELECT COUNT(*) AS f1 FROM s9
      UNION ALL SELECT COUNT(*) AS f1 FROM s10
      UNION ALL SELECT COUNT(*) AS f1 FROM s11
      UNION ALL SELECT COUNT(*) AS f1 FROM s12
      UNION ALL SELECT COUNT(*) AS f1 FROM s13
      UNION ALL SELECT COUNT(*) AS f1 FROM s14
      UNION ALL SELECT COUNT(*) AS f1 FROM s15);
 ```
 
 which is easier to run. Once that's set up I queried with:
 
 ```
 materialize=> SELECT now(), count(*) FROM s0 AS OF NOW();
            now            | count
---------------------------+-------
 2022-02-10 22:57:37.35+00 | 99999
(1 row)
```

On my laptop, in dev mode with 1 worker and default settings (also tried with timestamp frequency=100ms)
 
 I observe the following - in relation to Philip's observed anomalies:
 
 1. I don't observe partial results, other than that I always got 99999 instead of 100k
 2. I did observe timestamp errors occaisonally
 3. I didn't observe any fluctuation. It was always 99999, even across restarts
 
 I can retry in release mode and also can try on a linux box

**Comment by ruchirK** [comment] 2022-02-10 23:19
scratch that. re: 1 I just observed partial results that took a few tries to get to 99999

**Comment by philip-stoev** [comment] 2022-02-11 07:11
> It doesn't reproduce with timestamp-frequency=100ms (it always returns 99999 with that setting)

Constantly returning 99999 would also be an indication of the bug.

**Comment by ruchirK** [comment] 2022-02-11 10:09
I'm going to give more rapid updates as I have a few hours to debug this in the morning and thats all.

I can still observe this with the logical compaction window dialed up to "5s" rather than the default "1s", and when I do so the bindings in sqlite look ... sane? 

```
sqlite> select json_extract(sid, '$.User') as id, pid, timestamp, offset from timestamps where id = 1;
1|0|1644573690000|100000
1|0|1644573691000|100000
1|0|1644573692000|100000
1|0|1644573693000|100000
1|0|1644573694000|100000
1|0|1644573695000|100000
sqlite>
```

they seem to advance and be compacted as one would expect. Once the system has reached its "return 99999 or 100000 state" I only observe bindings at offset 1000000 across all sources which seems to indicate that whatever transient issue we're running into only manifests in the in-memory data and doesn't cause whats written out to sqlite to change? (I'm trying to gather as much info as I can without recompiling because my recompilation times are terrible rn)

**Comment by ruchirK** [comment] 2022-02-11 10:14
When I bump the partition count on s0 (and only s0 to avoid muddling this test by increasing the work the source operators do by 4x), I observe the system returning 99996 or 1000000k which is good for my own sanity

```
materialize=> select mz_logical_timestamp(), count(*) from s0 as of now();
 mz_logical_timestamp | count
----------------------+--------
        1644574381170 | 100000
(1 row)

materialize=> select mz_logical_timestamp(), count(*) from s0 as of now();
 mz_logical_timestamp | count
----------------------+-------
        1644574382999 | 99996
(1 row)

materialize=> select mz_logical_timestamp(), count(*) from s0 as of now();
 mz_logical_timestamp | count
----------------------+--------
        1644574386309 | 100000
(1 row)
```

**Comment by frankmcsherry** [comment] 2022-02-11 10:18
> ...  I only observe bindings at offset 1000000 across all sources ...

This seems tot imply that .. if this still manifests after a restart, there is no longer a distinction between that last record and all the others, and that it must be a "strictness of inequality" comparison error somewhere.

**Comment by ruchirK** [comment] 2022-02-11 10:25
If I tweak the query to look ever so slightly in the future the error seems to go away

```
materialize=> select mz_logical_timestamp(), count(*) from s11 as of now() + interval '2 seconds';
 mz_logical_timestamp | count
----------------------+--------
        1644574887257 | 100000
(1 row)
```


(I'm testing with `s11` instead of `s0` because `s0` is now 4-part, but the issue is equally applicable to all sources in the test)

I reran this query about 50 times and never observed the glitch, whereas I can consistently observe the glitch say 1 in ten queries otherwise

**Comment by ruchirK** [comment] 2022-02-11 10:40
Ok. I feel like I have the sketch of a theory here. It seems like:

if we have a binding like (time1, offset1)

and are asked for a time < time1, we return after reading all of the records at offsets < offset1 and if we are asked for a time >= time1, we return after reading all of the records <= offset1 

or something like that. On the spectrum between "wild guess" and "the round earth theory" this is way closer to "wild guess"

**Comment by ruchirK** [comment] 2022-02-11 10:43
but whats weird or at least incomplete about this idea is that, there's never a moment where `offset1` is "bound", because we would need to observe an offset > offset1 in the bindings which we don't in sqlite.

**Comment by ruchirK** [comment] 2022-02-11 10:46
I'm going to repeat all of the observations I just made against v0.19.0 to get a sense of what, changed about whats stored in sqlite / how the system behaves other than the fact that we can't reproduce the glitch

**Comment by ruchirK** [comment] 2022-02-11 11:09
Ok! @frankmcsherry I think you're totally right. In v0.19.0: the sqlite catalog looks like

```
ubuntu@ip-10-1-25-27:~/materialize$ sudo sqlite3 /var/lib/docker/volumes/testdrive_mzdata/_data/catalog
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from timestamps;
{"User":2}|0|1644577751000|100001
{"User":2}|0|1644577752000|100001
sqlite>
```

**Comment by ruchirK** [comment] 2022-02-11 11:11
I had to create a sink on s1 in order to observe whats gets put in sqlite

**Comment by ruchirK** [comment] 2022-02-11 11:38
Frank's changes in https://github.com/MaterializeInc/materialize/pull/10606 seem to fix - I'm no longer able to observe the issue and the contents in sqlite match what was in v0.19.0

**Comment by nmeagan11** [comment] 2022-02-28 21:30
Is this issue resolved? If so, we should close it.

**Comment by ruchirK** [comment] 2022-02-28 21:45
I wanted to leave the issue open to track the work of adding a regression test for this: #10667 does so, but I'm not sure if its flaky, and got sidetracked by other stuff

**Comment by benesch** [comment] 2022-03-12 02:57
Item 3 is resolved. Items 1 and 2 are not!

**Comment by frankmcsherry** [comment] 2022-03-12 11:17
Should we break the issues out into specific feature requests? I think (1.) is https://github.com/MaterializeInc/materialize/issues/11048 and (2.) as an as-yet undescribed property of how timestamp selection should work (described only by "we should fix it as long at it does this").

**Comment by benesch** [comment] 2022-03-12 16:08
> Should we break the issues out into specific feature requests? I think (1.) is #11048 and (2.) as an as-yet undescribed property of how timestamp selection should work (described only by "we should fix it as long at it does this").

Yes, that sounds right to me. So, closing, because;

1. Item one is covered by #11048.
2. Item two is covered by the newly-filed #11188.
3. Item three is fixed.

@philip-stoev, holler if you disagree, but the new issues are both filed with the same "T-correctness" theme, so I figure this is a no-op from your perspective.

**Closed by benesch** 2022-03-12 16:08 UTC
Labels: C-bug, T-correctness, A-source
