### ISSUE TITLE
test_old_storage_usage_records_are_reaped_on_restart is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25204] opened 2024-02-13 17:56 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/75556#018da301-8e8d-4168-afc0-ae77a65151a0

### Relevant log output

```source
thread 'test_old_storage_usage_records_are_reaped_on_restart' panicked at src/environmentd/tests/server.rs:1446:9:
Records were not reaped!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: server::test_old_storage_usage_records_are_reaped_on_restart::test_impl
             at ./tests/server.rs:1446:9
   3: server::test_old_storage_usage_records_are_reaped_on_restart
             at ./tests/server.rs:1363:1
   4: server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0}
             at ./tests/server.rs:1363:1
   5: <server::test_old_storage_usage_records_are_reaped_on_restart::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jkosh44** [comment] 2024-02-13 18:15
Duplicate of https://github.com/MaterializeInc/materialize/issues/25193

**Closed by jkosh44** 2024-02-13 18:15 UTC
Labels: C-bug, ci-flake
