### ISSUE TITLE
Avro reader crash in read header/resolve schemas

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#2505] opened 2020-04-01 14:22 UTC
```
  thread: tokio-runtime-worker
 message: called `Option::unwrap()` on a `None` value
    0: materialized::handle_panic
              at src/materialized/bin/materialized.rs:296
    1: core::ops::function::Fn::call
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:72
    2: std::panicking::rust_panic_with_hook
              at src/libstd/panicking.rs:476
    3: rust_begin_unwind
              at src/libstd/panicking.rs:380
    4: core::panicking::panic_fmt
              at src/libcore/panicking.rs:85
    5: core::panicking::panic
              at src/libcore/panicking.rs:52
    6: core::option::Option<T>::unwrap
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
    7: core::ops::function::FnMut::call_mut
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ops/function.rs:154
    8: core::iter::adapters::map_fold::{{closure}}
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:772
    9: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1900
   10: core::iter::traits::iterator::Iterator::try_fold
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1776
   11: core::iter::traits::iterator::Iterator::fold
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1903
   12: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:812
   13: core::iter::traits::iterator::Iterator::for_each
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:655
   14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:2054
   15: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:2034
   16: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1919
   17: core::iter::traits::iterator::Iterator::collect
              at rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1558
   18: avro::schema::resolve_schemas
              at src/avro/schema.rs:66
   19: avro::reader::Block<R>::read_header::{{closure}}
              at Users/bwm/github/materialize/src/avro/reader.rs:118
..
   28: dataflow::render::build_dataflow::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/dataflow/render/mod.rs:176
..
   31: dataflow::source::file::read_file_task::{{closure}}
              at src/dataflow/source/file.rs:216
```

**Comment by benesch** [comment] 2020-04-02 05:17
Are there additional reproduction instructions for this?

**Comment by ruchirK** [comment] 2020-04-02 13:02
I wonder if this is related to #2443

**Comment by umanwizard** [comment] 2020-04-02 16:16
@quodlibetor do you have an example schema?

**Comment by umanwizard** [comment] 2020-04-09 15:28
@quodlibetor I don't think this is the same issue as the one you sent me earlier. Can you check if this is still reproducible? (Hopefully it's been fixed by other fixes)

**Comment by umanwizard** [comment] 2021-05-19 18:17
Closing due to lack of repro

**Closed** 2021-05-19 18:17 UTC
Labels: C-bug
