### ISSUE TITLE
Boolean comparison breaks autorouting

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#26738] opened 2024-04-19 20:18 UTC
### What version of Materialize are you using?

v0.96.2

### What is the issue?

For whatever reason, this autoroutes to mz_introspection: 

```sql
SELECT mz_is_superuser();
```

But this does not. 

```sql
SELECT mz_is_superuser() IS FALSE;
```

I didn't dig into this, and is likely not urgent, but documenting for later.

**Comment by benesch** [comment] 2024-04-20 17:12
This is working as designed, I'm afraid. I agree it's somewhat hard to explain, but autorouting only kicks in for "cheap" queries, and our definition of "cheap" is "100% guaranteed to be executable without involving the compute layer". `mz_is_superuser()` is unmaterializable, and so we can execute entirely it in the adapter, but `SELECT mz_is_superuser() IS FALSE` involves calling the `IS FALSE` operator, which lives in compute, and therefore we aren't certain that it is "cheap." (Obviously in this case it's a bit silly, as `IS FALSE` is obviously cheap, but with something like `generate_series(1, 1000)` it becomes clearer. Whether that's cheap our not depends on how large the series is, and that threshold moves around over time, and we don't want autorouting to depend on what the optimizer's current threshold for "cheap" is.)

https://github.com/MaterializeInc/materialize/blob/603721eea933365dfd62a9791673db039430c8a8/src/sql/src/plan/expr.rs#L1883-L1891

**Comment by chaas** [comment] 2024-09-06 15:11
Given @benesch 's statement above, I'm closing this issue. It doesn't seem like there's anything we can do here since autorouting is working as intended. @sjwiesman , feel free to reopen if you have a suggestion for a better UX here.

**Closed by chaas** 2024-09-06 15:11 UTC
Labels: A-ADAPTER
