### ISSUE TITLE
cluster:  thread 'thread 'timely:work-1timely:work-0' panicked at '' panicked at 'index out of bounds: the len is 1 but the index is 1index out of bounds: the len is 1 but the index is 1'

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11341] opened 2022-03-22 07:08 UTC
### What version of Materialize are you using?

ce309d9

### How did you install Materialize?

Docker image

### What was the issue?

Even with the fix for #11278 , the clustered Nightly run contines to crash heavily

https://buildkite.com/materialize/nightlies/builds/736#16b0a834-1a9b-4657-993e-d95b968d6669

### Relevant log output

```source
dataflowd_2_1                    | thread 'thread 'timely:work-1timely:work-0' panicked at '' panicked at 'index out of bounds: the len is 1 but the index is 1index out of bounds: the len is 1 but the index is 1', ', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/timely/src/progress/reachability.rs/cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/timely/src/progress/reachability.rs::621621::3333
dataflowd_2_1                    | 
dataflowd_2_1                    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dataflowd_2_1                    | thread 'main' panicked at 'worker command receiver should not drop first: "SendError(..)"', src/dataflow-types/src/client.rs:931:18
dataflowd_2_1                    | thread 'timely:recv-0' panicked at 'MergeQueue poisoned.', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/communication/src/allocator/zero_copy/bytes_exchange.rs:55:48
dataflowd_2_1                    | thread 'timely:send-0' panicked at 'MergeQueue poisoned.', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/communication/src/allocator/zero_copy/bytes_exchange.rs:96:48
dataflowd_2_1                    | thread 'main' panicked at 'Worker panic: Any { .. }', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/communication/src/initialize.rs:354:26
dataflowd_2_1                    | stack backtrace:
dataflowd_2_1                    |    0:     0x55589b5f16dc - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
dataflowd_2_1                    |    1:     0x55589b5f16dc - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
dataflowd_2_1                    |    2:     0x55589b5f16dc - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
dataflowd_2_1                    |    3:     0x55589b5f16dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
dataflowd_2_1                    |    4:     0x55589b61a15c - core::fmt::write::h753c7571fa063ecb
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
dataflowd_2_1                    |    5:     0x55589b5e8dc3 - std::io::Write::write_fmt::h2815c0519c99ba09
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
dataflowd_2_1                    |    6:     0x55589b5f4012 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
dataflowd_2_1                    |    7:     0x55589b5f4012 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
dataflowd_2_1                    |    8:     0x55589b5f4012 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
dataflowd_2_1                    |    9:     0x55589b5f3bf5 - std::panicking::default_hook::hda898f8d3ad1a5ae
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
dataflowd_2_1                    |   10:     0x55589b5f4763 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
dataflowd_2_1                    |   11:     0x55589b5f4480 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
dataflowd_2_1                    |   12:     0x55589b5f1b84 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
dataflowd_2_1                    |   13:     0x55589b5f41b9 - rust_begin_unwind
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
dataflowd_2_1                    |   14:     0x55589b6176d1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
dataflowd_2_1                    |   15:     0x55589b617983 - core::result::unwrap_failed::ha0327e3803285d6e
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
dataflowd_2_1                    |   16:     0x5558990bdb58 - core::result::Result<T,E>::expect::hf99d3aeb6850713f
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:975:23
dataflowd_2_1                    |   17:     0x5558990bdb58 - <timely_communication::initialize::WorkerGuards<T> as core::ops::drop::Drop>::drop::h1a9d66b640f42c5a
dataflowd_2_1                    |                                at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6f50573/communication/src/initialize.rs:354:13
dataflowd_2_1                    |   18:     0x55589933c7c0 - core::ptr::drop_in_place<timely_communication::initialize::WorkerGuards<()>>::h9a860f60041be2fa
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ptr/mod.rs:188:1
dataflowd_2_1                    |   19:     0x55589933c7c0 - core::ptr::drop_in_place<mz_dataflow::server::Server>::h1df27af48f9e4e35
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ptr/mod.rs:188:1
dataflowd_2_1                    |   20:     0x55589934b475 - dataflowd::run::{{closure}}::h1cede3e98c155776
dataflowd_2_1                    |                                at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0b06334729038b593-1/materialize/tests/src/dataflowd/src/bin/dataflowd.rs:259:1
dataflowd_2_1                    |   21:     0x5558993c62e9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9248215025c9b02d
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
dataflowd_2_1                    |   22:     0x5558993c62e9 - dataflowd::main::{{closure}}::ha5f3f312dd1d9e49
dataflowd_2_1                    |                                at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0b06334729038b593-1/materialize/tests/src/dataflowd/src/bin/dataflowd.rs:101:53
dataflowd_2_1                    |   23:     0x5558993c62e9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfa1e4ac720850a35
dataflowd_2_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
dataflowd_2_1                    |   24:     0x555899196198 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::hed070010227c5322
dataflowd_2_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
dataflowd_2_1                    |   25:     0x555899196198 - tokio::coop::with_budget::{{closure}}::h2c11f29f2c646604
dataflowd_2_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
dataflowd_2_1                    |   26:     0x555899196198 - std::thread::local::LocalKey<T>::try_with::h3da426aae199b912


materialized_1                   | [2m2022-03-21T11:36:23.038688Z[0m [32m INFO[0m [2mmz_coord::catalog[0m[2m:[0m drop index materialize.public.avro_types_uuid_primary_idx (u43)
dataflowd_1_1                    |   25:     0x56146d3022e9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfa1e4ac720850a35
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
dataflowd_1_1                    |   26:     0x56146d0d2198 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::hed070010227c5322
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
dataflowd_1_1                    |   27:     0x56146d0d2198 - tokio::coop::with_budget::{{closure}}::h2c11f29f2c646604
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
dataflowd_1_1                    |   28:     0x56146d0d2198 - std::thread::local::LocalKey<T>::try_with::h3da426aae199b912
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
dataflowd_1_1                    |   29:     0x56146d0d2198 - std::thread::local::LocalKey<T>::with::hc360e21ef67c0a27
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
dataflowd_1_1                    |   30:     0x56146d0d2198 - tokio::coop::with_budget::h5b2be2d7c3aac9fc
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
dataflowd_1_1                    |   31:     0x56146d0d2198 - tokio::coop::budget::h98d92ed30e38666e
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
dataflowd_1_1                    |   32:     0x56146d0d2198 - tokio::park::thread::CachedParkThread::block_on::hfba3359ec12e7093
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
dataflowd_1_1                    |   33:     0x56146d5dbd10 - tokio::runtime::enter::Enter::block_on::h83a73b5224d71f1b
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
dataflowd_1_1                    |   34:     0x56146d5dbd10 - tokio::runtime::thread_pool::ThreadPool::block_on::h2d3dc2ca3d447b93
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
dataflowd_1_1                    |   35:     0x56146d5dbd10 - tokio::runtime::Runtime::block_on::h03b4de7cae3d86e2
dataflowd_1_1                    |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
dataflowd_1_1                    |   36:     0x56146d0a0a39 - dataflowd::main::h7ba6d1f6f6213e0b
dataflowd_1_1                    |                                at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0b06334729038b593-1/materialize/tests/src/dataflowd/src/bin/dataflowd.rs:101:5
dataflowd_1_1                    |   37:     0x56146d258c53 - core::ops::function::FnOnce::call_once::h3c4ea477d946c1f6
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
dataflowd_1_1                    |   38:     0x56146d258c53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h399995fddf30d05a
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
dataflowd_1_1                    |   39:     0x56146d51ead9 - std::rt::lang_start::{{closure}}::hc447ca4f1c0b2e65
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:145:18
dataflowd_1_1                    |   40:     0x56146f52cd90 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
dataflowd_1_1                    |   41:     0x56146f52cd90 - std::panicking::try::do_call::h1e21ba261ba489ec
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
dataflowd_1_1                    |   42:     0x56146f52cd90 - std::panicking::try::h6afd48af8b6c96ac
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
dataflowd_1_1                    |   43:     0x56146f52cd90 - std::panic::catch_unwind::h85dd95e0bab7fb60
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
dataflowd_1_1                    |   44:     0x56146f52cd90 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
dataflowd_1_1                    |   45:     0x56146f52cd90 - std::panicking::try::do_call::h6b0ad65979f3077a
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
dataflowd_1_1                    |   46:     0x56146f52cd90 - std::panicking::try::h010108d314169ac6
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
dataflowd_1_1                    |   47:     0x56146f52cd90 - std::panic::catch_unwind::hff397f912b1535c2
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
dataflowd_1_1                    |   48:     0x56146f52cd90 - std::rt::lang_start_internal::h52e73755f77c7dd9
dataflowd_1_1                    |                                at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
dataflowd_1_1                    |   49:     0x56146d267568 - main
dataflowd_1_1                    |   50:     0x7f1bcffec0b3 - __libc_start_main
dataflowd_1_1                    |   51:     0x56146ca9a029 - <unknown>
dataflowd_1_1                    |                                at /scratch/.build/src/glibc-2.12.1/csu/../sysdeps/x86_64/elf/start.S:103
dataflowd_1_1                    | thread panicked while panicking. aborting.
```

**Comment by frankmcsherry** [comment] 2022-03-29 14:40
I would be super helpful to learn if this is the storage process or the compute process (it bisects the code into "source set-up" and "view maintenance". Do you happen to know?

**Comment by umanwizard** [comment] 2022-03-29 14:50
I’ll take a look at this

**Comment by umanwizard** [comment] 2022-03-29 20:35
Per the conversation on Slack [here](https://materializeinc.slack.com/archives/C032PHMQVGQ/p1648576443979479) , this has only been seen once.

It's plausible that the root cause is dataflows having been created with different topologies on different workers, though it's not immediately clear how that could happen in Materialize.

**Comment by umanwizard** [comment] 2022-03-30 19:18
De-prioritizing this as discussed in the optimization/dataflow meeting, since it's only ever been observed twice (once by Moritz anecdotally, and once here). It's interesting to note that when Moritz observed this issue, it was on a non-distributed `materialized` binary.

Let's keep the issue open in case we see it again in the future.

@antiguru suggested that if this crops up again, one thing to look at would be whether Timely correctly handles dataflows that are created with some delay (e.g. imagine if the dataflow is created on worker 0, then a second later on worker 1 ; is the logic in Timely to buffer the messages from worker 0 to avoid confusing worker 1 bug-free?)

**Comment by antiguru** [comment] 2022-09-15 13:31
Closing issue since the problem since hasn't been observed again and we changed this code significantly. Feel free to re-open should it happen again.

**Closed by antiguru** 2022-09-15 13:31 UTC
Labels: C-bug, A-dataflow
