### ISSUE TITLE
regression: panicked at 'Table write failed: `write.upper` set to value that signals we have lost leadership'

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15949] opened 2022-11-08 06:54 UTC
### What version of Materialize are you using?

250e4ef

### How did you install Materialize?

Docker image

### What is the issue?

The test that restarts the postgres backend caused environmentd to panic as follows

https://buildkite.com/materialize/nightlies/builds/1339#018454a8-9a52-486a-99e2-5c560baba211

### Relevant log output

```source
platform-checks-materialized-1      | thread 'tokio:work-1' panicked at 'Table write failed: `write.upper` set to value that signals we have lost leadership', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2195:57
platform-checks-materialized-1      | stack backtrace:
platform-checks-materialized-1      |    0: rust_begin_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
platform-checks-materialized-1      |    1: core::panicking::panic_fmt
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
platform-checks-materialized-1      |    2: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}::append_work::{{closure}}::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2195:57
platform-checks-materialized-1      |    3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |    4: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
platform-checks-materialized-1      |    5: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/collect.rs:50:26
platform-checks-materialized-1      |    6: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}::append_work::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2213:41
platform-checks-materialized-1      |    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |    8: mz_storage_client::controller::persist_write_handles::PersistWorker<T>::new::{{closure}}
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e3e4ce48c30621d3-1/materialize/tests/src/storage-client/src/controller.rs:2229:106
platform-checks-materialized-1      |    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
platform-checks-materialized-1      |   10: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
platform-checks-materialized-1      |   11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
platform-checks-materialized-1      |   12: tokio::runtime::task::core::CoreStage<T>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
platform-checks-materialized-1      |   13: tokio::runtime::task::harness::poll_future::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
platform-checks-materialized-1      |   14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
platform-checks-materialized-1      |   15: std::panicking::try::do_call
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
platform-checks-materialized-1      |   16: std::panicking::try
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
platform-checks-materialized-1      |   17: std::panic::catch_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
platform-checks-materialized-1      |   18: tokio::runtime::task::harness::poll_future
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
platform-checks-materialized-1      |   19: tokio::runtime::task::harness::Harness<T,S>::poll_inner
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
platform-checks-materialized-1      |   20: tokio::runtime::task::harness::Harness<T,S>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
platform-checks-materialized-1      |   21: tokio::runtime::task::raw::RawTask::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
platform-checks-materialized-1      |   22: tokio::runtime::task::LocalNotified<S>::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
platform-checks-materialized-1      |   23: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
platform-checks-materialized-1      |   24: tokio::coop::with_budget::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
platform-checks-materialized-1      |   25: std::thread::local::LocalKey<T>::try_with
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:445:16
platform-checks-materialized-1      |   26: std::thread::local::LocalKey<T>::with
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:9
platform-checks-materialized-1      |   27: tokio::coop::with_budget
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
platform-checks-materialized-1      |   28: tokio::coop::budget
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
platform-checks-materialized-1      |   29: tokio::runtime::thread_pool::worker::Context::run_task
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
platform-checks-materialized-1      |   30: tokio::runtime::thread_pool::worker::Context::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:401:24
platform-checks-materialized-1      |   31: tokio::runtime::thread_pool::worker::run::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
platform-checks-materialized-1      |   32: tokio::macros::scoped_tls::ScopedKey<T>::set
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
platform-checks-materialized-1      |   33: tokio::runtime::thread_pool::worker::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
platform-checks-materialized-1      |   34: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
platform-checks-materialized-1      |   35: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
platform-checks-materialized-1      |   36: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
platform-checks-materialized-1      |   37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
platform-checks-materialized-1      |   38: tokio::runtime::task::core::CoreStage<T>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
platform-checks-materialized-1      |   39: tokio::runtime::task::harness::poll_future::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
platform-checks-materialized-1      |   40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
platform-checks-materialized-1      |   41: std::panicking::try::do_call
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
platform-checks-materialized-1      |   42: std::panicking::try
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
platform-checks-materialized-1      |   43: std::panic::catch_unwind
platform-checks-materialized-1      |              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
platform-checks-materialized-1      |   44: tokio::runtime::task::harness::poll_future
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
platform-checks-materialized-1      |   45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
platform-checks-materialized-1      |   46: tokio::runtime::task::harness::Harness<T,S>::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
platform-checks-materialized-1      |   47: tokio::runtime::task::raw::RawTask::poll
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
platform-checks-materialized-1      |   48: tokio::runtime::task::UnownedTask<S>::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
platform-checks-materialized-1      |   49: tokio::runtime::blocking::pool::Task::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
platform-checks-materialized-1      |   50: tokio::runtime::blocking::pool::Inner::run
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
platform-checks-materialized-1      |   51: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
platform-checks-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
platform-checks-materialized-1      | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment] 2022-11-08 08:24
Git bisect reports:

```
commit c15ff5a89742795836c03a33c66e495586787bb9 (HEAD)
Author: Chae Jubb <chae@materialize.com>
Date:   Mon Nov 7 11:59:08 2022 -0800

    [sinks] [status] Put sink status collection behind unsafe (#15744)
```

That is, this PR enables the feature under --unsafe that was previously disabled altogether. CI uses --unsafe.

To reproduce:

```
bin/mzcompose --find platform-checks down -v ; bin/mzcompose --find platform-checks run default --scenario RestartPostgresBackend  --check=SinkUpsert
```

**Comment by bkirwi** [comment] 2022-11-08 15:58
Interesting! I don't think the sink actually writes via the controller... but it's possible that the periodic bump of the upper is conflicting with actual writes in the sink.

(Before the recent work, write contention on the collections the controller writes to was very rare. We fixed one related bug in https://github.com/MaterializeInc/materialize/pull/15675; looks like there might be another.

Handing this one to @cjubb39 for now - let me know if you don't think you can get to it!

**Comment by petrosagg** [comment] 2022-11-10 12:25
It strange that we delegate writing to this collection to some remote machines but those remote machines can't also periodically bump the upper. Since the collection is not managed by the storage controller can we move the upper bumping logic to the same place that the writes happen?

**Comment by bkirwi** [comment] 2022-11-10 15:49
Tempting, but writes are happening on potentially dozens of remote machines; there's no obvious other single location to bump the upper, and having all of them do it would dramatically increase the load on persist.

>  Since the collection is not managed by the storage controller [...]

I'm not quite sure what's meant by "managed", but the storage controller does handle quite a lot for this collection, including queries. Only writes do not exclusively go through the controller. (We've talked about changing that, but that would substantially increase the write load from environmentd. We'll see!)

**Comment by cjubb39** [comment] 2022-11-10 19:47
@philip-stoev did this reproduce every time for you? I was having trouble getting it locally (running os x so maybe a similar issue as before?) and we only seeing it sporadically in the the nightly job on CI.  I want to make sure I'm doing my best to repro so I know if my solution actually makes it go away!

**Comment by philip-stoev** [comment] 2022-11-11 10:42
It reproduces often enough in CI, that is, multiple times a day. I suggest you use a `ci` -type scratch machine and then run 

```
cd test/platform-checks
while bash -c -e "./mzcompose down -v ; ./mzcompose run default --scenario=RestartPostgresBackend --check=SinkUpsert" ;  do : ; done
```

It will panic almost immediately, there is not even a need for the while loop.

**Comment by cjubb39** [comment] 2022-11-11 15:40
okay -- thanks!  I got it pretty reliably on a CI scratch after I did another rebase

**Closed** 2022-11-14 21:44 UTC
Labels: C-bug, A-STORAGE
