### ISSUE TITLE
time cast panicked at src/expr/src/scalar/func/impls/interval.rs:48:10: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24684] opened 2024-01-25 13:40 UTC
### What version of Materialize are you using?

1efa5662efee8394372ee1e43a6c807529983f9d

### What is the issue?

The panic can be reproduced with:
```
CREATE TABLE t (x INTERVAL);
INSERT INTO t VALUES ('-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL);
SELECT CAST (x AS TIME) FROM t;
```

Backtrace:
```
output-consistency-materialized-1  | called `Option::unwrap()` on a `None` value
output-consistency-materialized-1  | stack backtrace:
output-consistency-materialized-1  |    0: rust_begin_unwind
output-consistency-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
output-consistency-materialized-1  |    1: core::panicking::panic_fmt
output-consistency-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
output-consistency-materialized-1  |    2: core::panicking::panic
output-consistency-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
output-consistency-materialized-1  |    3: mz_expr::scalar::func::impls::interval::cast_interval_to_time
output-consistency-materialized-1  |    4: <mz_expr::scalar::func::impls::interval::CastIntervalToTime as mz_expr::scalar::func::EagerUnaryFunc>::call
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/scalar/func/macros.rs:153:21
output-consistency-materialized-1  |    5: <mz_expr::scalar::func::impls::interval::CastIntervalToTime as mz_expr::scalar::func::LazyUnaryFunc>::eval
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/scalar/func.rs:4374:26
output-consistency-materialized-1  |    6: <mz_expr::interpret::ColumnSpecs as mz_expr::interpret::Interpreter>::unary::{closure#0}
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:817:34
output-consistency-materialized-1  |    7: <mz_expr::interpret::ResultSpec>::flat_map::<<mz_expr::interpret::ColumnSpecs as mz_expr::interpret::Interpreter>::unary::{closure#0}>
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:296:55
output-consistency-materialized-1  |    8: <mz_expr::interpret::ColumnSpecs as mz_expr::interpret::Interpreter>::unary
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:815:13
output-consistency-materialized-1  |    9: <mz_expr::interpret::MfpEval<mz_expr::interpret::ColumnSpecs> as mz_expr::interpret::Interpreter>::unary
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:496:9
output-consistency-materialized-1  |   10: <mz_expr::interpret::MfpEval<mz_expr::interpret::ColumnSpecs> as mz_expr::interpret::Interpreter>::expr
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:394:17
output-consistency-materialized-1  |   11: <mz_expr::interpret::MfpEval<mz_expr::interpret::ColumnSpecs>>::new
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:469:26
output-consistency-materialized-1  |   12: <mz_expr::interpret::ColumnSpecs as mz_expr::interpret::Interpreter>::mfp_plan_filter
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/expr/src/interpret.rs:430:24
output-consistency-materialized-1  |   13: mz_storage_operators::persist_source::filter_may_match
output-consistency-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-039767af70b7dd710-1/materialize/tests/src/storage-operators/src/persist_source.rs:373:18
```

ci-regexp: called `Option::unwrap()` on a `None` value

Seen in: https://buildkite.com/materialize/nightlies/builds/6151#018d409c-ee61-42ca-836c-a26da6a9cacc

**Comment by jkosh44** [comment] 2024-01-29 15:35
Here's a more targeted repro:
```
materialize=> SELECT CAST ('-86400000001 us'::INTERVAL AS TIME);
ERROR:  internal error: unexpected panic during query optimization
```

The issue is in the cast implementation:

https://github.com/MaterializeInc/materialize/blob/44ce09a397e1cb4a6363b3ee77d4806804d521c6/src/expr/src/scalar/func/impls/interval.rs#L28-L50

Negative intervals are updated using the following psuedo code:
```
new_interval = '86400000000 us'::INTERVAL + old_interval;
```
If the old interval is smaller than -86400000000 us, then the new interval will still be negative. `hours()`, `minutes()`, `seconds()`, `nanoseconds()` will all return negative numbers which we then cast to `u32` using `as`, which results in large positive numbers. `from_hms_nano_opt()` then returns `None`, since the provided numbers are out of range.

**Comment by jkosh44** [comment] 2024-01-29 16:34
Probably a separate issue, but the original repro is not a valid interval in PostgreSQL

```
postgres=# SELECT CAST ('-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL AS TIME);
ERROR:  invalid input syntax for type interval: "-178956970 years -8 months -2147483648 days -2562047788:00:54.775808"
LINE 1: SELECT CAST ('-178956970 years -8 months -2147483648 days -2...
                     ^
```

**Comment by nrainer-materialize** [comment] 2024-01-29 16:45
> Probably a separate issue, but the original repro is not a valid interval in PostgreSQL

True. Though, it is possible to repro if you remove one digit from the very last value. The issue does still occur in mz with that value.

**Comment by jkosh44** [comment] 2024-01-29 17:08
Interestingly, if you found this two months ago, you would have also found a bug in PostgreSQL:

```
postgres=# SELECT CAST ('-2562047788:00:54.77580'::INTERVAL AS TIME);
      time       
-----------------
 28:00:54.775816
(1 row)

postgres=# SELECT version();
                                                              version                                                              
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
(1 row)

postgres=# SELECT '28:00:54.775816'::TIME;
ERROR:  date/time field value out of range: "28:00:54.775816"
LINE 1: SELECT '28:00:54.775816'::TIME;
               ^

```

but it looks like that was fixed in v17, which isn't out yet: https://github.com/postgres/postgres/commit/3850d4dec1d91c4fdce274f42986840444d5593e

**Closed** 2024-01-29 19:18 UTC
Labels: C-bug
