### ISSUE TITLE
Support CockroachDB Source

### ISSUE THREAD

**Issue by danthegoodman1** [MaterializeInc/materialize#8991] opened 2021-11-08 12:26 UTC
CockroachDB would be awesome to use as a source/sink similar to how Postgres can be used. I prefer CRDB over Postgres due to the scalability and distribute nature.

**Comment by danthegoodman1** [comment] 2021-11-08 12:35
For example, using Kafka and Materialize is great for CQRS patterns, however leaning on a single Materialize node could cause availability concerns. Being able to store the materialized results in a DB like CRDB (and Cassandra/Scylla, see #8992 ), would reduce those availability concerns.

It also means that data would need to be less spread-out. For example if someone wanted to join a set on userID's stored in their CRDB, typically they might have to replicate that to S3 on some interval. With support for CRDB, they could just JOIN on the user table instead of having another datastore to maintain.

**Comment by danthegoodman1** [comment] 2021-11-08 12:37
It seems like HA deployments are at least intendend to be supported, however the docs for it seem to go nowhere: https://materialize.com/blog-roadmap/#:~:text=a%20single-node%20streaming%20database

**Comment by elindsey** [comment] 2022-05-09 19:58
Marking as duplicate of https://github.com/MaterializeInc/materialize/issues/5508

**Closed by elindsey** 2022-05-09 19:58 UTC
Labels: C-feature
