### ISSUE TITLE
MATERIALIZED keyword not persisted to catalog

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5703] opened 2021-02-10 09:30 UTC
### What version of Materialize are you using?

```
$ materialized -v
materialized v0.7.1-dev (48b0c8c9e)

```

### What was the issue?

If a view is created as MATERIALIZED, this is not persisted in the catalog and is not reflected in ```SHOW CREATE VIEW```

### Is the issue reproducible? If so, please provide reproduction instructions.

```
materialize=> create materialized view v1 as select 1;
CREATE VIEW
materialize=> show create view v1;
         View          |                     Create View                     
-----------------------+-----------------------------------------------------
 materialize.public.v1 | CREATE VIEW "materialize"."public"."v1" AS SELECT 1
(1 row)

```

**Comment by umanwizard** [comment] 2021-02-10 16:47
This is expected, because `CREATE MATERIALIZED VIEW` is actually syntax sugar for `CREATE VIEW ...` followed by `CREATE INDEX ...`.

Take a look at the output of  `SHOW INDEXES FROM v1`

**Comment by cirego** [comment] 2021-02-10 16:50
> This is expected, because `CREATE MATERIALIZED VIEW` is actually syntax sugar for `CREATE VIEW ...` followed by `CREATE INDEX ...`.
> 
> Take a look at the output of `SHOW INDEXES FROM v1`

I'm not sure this is the behavior expected by users. I find it confusing that `SHOW` doesn't give back the `CREATE` required to recreate a view.

**Comment by philip-stoev** [comment] 2021-02-10 16:50
Oh. I suspect this is going to be a problem from a customer support view. People will be tripped

**Comment by benesch** [comment] 2021-02-10 16:52
Duplicate of #3404. Let's centralize discussion there! I think both sides of this debate will find their opinions have been well represented already. :)

**Closed by benesch** 2021-02-10 16:52 UTC
Labels: C-bug

**Comment by umanwizard** [comment] 2021-02-10 16:58
Sorry, I wasn't trying to imply that the behavior is good or bad (I don't have any strong opinion in this debate). I was just saying it's currently "working as designed".
