### ISSUE TITLE
Incorrectly allows and / or with boolean and text

### ISSUE THREAD

**Issue by ruchirK** [MaterializeInc/materialize#7204] opened 2021-06-25 22:01 UTC
Materialize permits the following:

```
materialize=> select true or 'test';
 ?column?
----------
 t
(1 row)

materialize=> select false and 'test';
 ?column?
----------
 f
(1 row)
```

Postgres does not

```
Test=# select true or 'test';
ERROR:  invalid input syntax for type boolean: "test"
LINE 1: select true or 'test';
                       ^
Test=# select false and 'test';
ERROR:  invalid input syntax for type boolean: "test"
LINE 1: select false and 'test';
                         ^
Test=#
```

Curiously, this only seems to happen with a boolean and a string in that order, e.g. these are correctly detected

```
materialize=> select 'test' and false;
ERROR:  invalid input syntax for type boolean: "test"
materialize=> select 'test' or true;
ERROR:  invalid input syntax for type boolean: "test"
materialize=>
```

and more specifically, it has to trigger short circuiting, so these are correctly detected

```
materialize=> select false or 'test';
ERROR:  invalid input syntax for type boolean: "test"
materialize=> select true and 'test';
ERROR:  invalid input syntax for type boolean: "test"
materialize=>
```

Similarly, things work correctly if I manually cast `'test'` to `text` which i thought was a no-op

```
materialize=> select true or 'test'::text;
ERROR:  OR argument must have type boolean, not type text
materialize=> select false and 'test'::text;
ERROR:  AND argument must have type boolean, not type text
materialize=>
```

Finally, I tried to repro with other types besides `text` and could not

```
materialize=> select true or 5;
ERROR:  OR argument must have type boolean, not type integer
materialize=> select true or '{}'::int[];
ERROR:  OR argument must have type boolean, not type integer[]
materialize=> select true or 4.5e4;
ERROR:  OR argument must have type boolean, not type integer
materialize=> select typeof (4.5e4);
ERROR:  function typeof(integer) does not exist
materialize=>
```

**Comment by benesch** [comment] 2021-06-26 04:35
I'm actually inclined to call this not a bug! PostgreSQL explicitly allows not evaluating the RHS in cases like this: https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-EXPRESS-EVAL

I agree it's weird with a simple example like this, but guaranteeing that we always produce all possible errors makes it nearly impossible to perform a lot of optimizations.

**Comment by benesch** [comment] 2021-06-26 04:36
I guess maybe we could/should force all implicit literal coercions to happen? Idk.

**Comment by ruchirK** [comment] 2021-06-28 15:00
Yeah I agree this is not a bug wrt to the spec sorry should have been clearer about that. I filed the issue because the behavior differed from Postgres and it seemed so close to doing the right thing for this specific case that I wondered if there was an easy fix / off by one type of thing happening.

Feel free to close if you don't think this is something that needs to be fixed.

**Comment by benesch** [comment] 2024-06-10 04:15
Closing as this is in spec for the moment, and we don't have current plans for more eager constant folding.

**Closed by benesch** 2024-06-10 04:15 UTC
Labels: C-bug
