### ISSUE TITLE
regression: Postgres source fails to advance after an upgrade

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#23365] opened 2023-11-22 12:18 UTC
ci-regexp: deadline has elapsed
ci-apply-to: checks-upgrade-matrix

### What version of Materialize are you using?

4ff6077fcd

### What is the issue?

The test that performs gradual upgrades from old Mz versions, through intermediate versions all the way to HEAD has started failing as follows:

```
2023-11-22 10:50:43 UTC	> SELECT f1, max(f2), SUM(LENGTH(f3)) FROM postgres_source_tableA_true GROUP BY f1;
2023-11-22 10:55:43 UTC	
2023-11-22 10:55:43 UTC	7:1: error: deadline has elapsed
```

What this means is that the `SELECT` in question hangs and fails to ever return. The reason is that the timestamp of the source does not advance at all:

```
mz_system=> explain timestamp for select * from postgres_source_tableA_true;
                                 Timestamp                                 
---------------------------------------------------------------------------
                 query timestamp: 1700654231607 (2023-11-22 11:57:11.607) +
           oracle read timestamp: 1700654231607 (2023-11-22 11:57:11.607) +
 largest not in advance of upper: 1700654077000 (2023-11-22 11:54:37.000) +
                           upper:[1700654077001 (2023-11-22 11:54:37.001)]+
                           since:[1700654076000 (2023-11-22 11:54:36.000)]+
         can respond immediately: false                                   +
                        timeline: Some(EpochMilliseconds)                 +
               session wall time: 1700654231934 (2023-11-22 11:57:11.934) +
                                                                          +
 source materialize.public.postgres_source_tablea_true (u11, storage):    +
                   read frontier:[1700654076000 (2023-11-22 11:54:36.000)]+
                  write frontier:[1700654077001 (2023-11-22 11:54:37.001)]+
 
(1 row)
```

To reproduce:

```
cd test/upgrade-matrix
./mzcompose --ignore-docker-version down -v ; ./mzcompose --ignore-docker-version run default  --seed=018bf46f-5733-4079-86b1-66cd0a5e564f 
```
and then wait for ~30 min for the entire thing to reach the hanging state.

**Comment by def-** [comment] 2023-11-22 16:32
This is caused by https://github.com/MaterializeInc/materialize/pull/23335
https://buildkite.com/materialize/nightlies/builds/5326 is the state of #23335 and has the failure, https://buildkite.com/materialize/nightlies/builds/5327 is the state just before the PR and is green (at least already past the problematic `postgres_source_tableA_true`).

**Comment by petrosagg** [comment] 2023-12-07 16:37
Removing the release blocker label because the offending PR has been reverted in #23374

**Comment by benesch** [comment] 2024-01-28 17:48
Closing as this is not currently an outstanding issue.

**Closed by benesch** 2024-01-28 17:48 UTC
Labels: C-bug
