### ISSUE TITLE
Tables with indexes return stale data under the "serializable" isolation level 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15694] opened 2022-10-26 07:23 UTC
### What version of Materialize are you using?

v0.30.0-dev (65f6d9343)

### How did you install Materialize?

Docker image

### What is the issue?

```
SET transaction_isolation='serializable';
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (f1 INTEGER);
CREATE DEFAULT INDEX ON t1;
INSERT INTO t1 VALUES (1);
SELECT * FROM t1;
 f1 
----
(0 rows) <- table is reported as empty, even though we just inserted in it.
```

This is not a valid sequence of events under any isolation level, let alone `SERIALIZABLE`. If no index is used, the result is correct. If `STRICT SERIALIZABLE` is used, the result is correct.

### Relevant log output

```source
materialize=> EXPLAIN TIMESTAMP FOR SELECT * FROM t1;
                              Timestamp                              
---------------------------------------------------------------------
           query timestamp: 1666768914940 (2022-10-26 07:21:54.940) +
                     since:[1666768914675 (2022-10-26 07:21:54.675)]+
                     upper:[1666768914941 (2022-10-26 07:21:54.941)]+
          global timestamp: 1666768914940 (2022-10-26 07:21:54.940) +
   can respond immediately: true                                    +
                                                                    +
 source materialize.public.t1 (u35, storage):                       +
             read frontier:[1666768914675 (2022-10-26 07:21:54.675)]+
            write frontier:[1666768914941 (2022-10-26 07:21:54.941)]+
 
(1 row)

Time: 12.933 ms
materialize=> CREATE DEFAULT INDEX ON t1;
CREATE INDEX
Time: 116.981 ms
materialize=> EXPLAIN TIMESTAMP FOR SELECT * FROM t1;
                              Timestamp                              
---------------------------------------------------------------------
           query timestamp: 1666768914675 (2022-10-26 07:21:54.675) +
                     since:[1666768914675 (2022-10-26 07:21:54.675)]+
                     upper:[1666768914675 (2022-10-26 07:21:54.675)]+
          global timestamp: 1666768915076 (2022-10-26 07:21:55.076) +
   can respond immediately: false                                   +
                                                                    +
 source materialize.public.t1_primary_idx (u36, compute):           +
             read frontier:[1666768914675 (2022-10-26 07:21:54.675)]+
            write frontier:[1666768914675 (2022-10-26 07:21:54.675)]+
```
```

**Comment by frankmcsherry** [comment] 2022-10-26 11:03
Serializable isolation does not provide "ready your writes". This is not incorrect, as far as I can tell. We have discussed wanting strict session serializability, which would provide read your writes, but I think are waiting on e.g. session timelines to do that.

**Comment by frankmcsherry** [comment] 2022-10-26 11:10
E.g. from https://jepsen.io/consistency/models/serializable: 

> The requirement for a total order of transactions is strong—but still allows pathological orderings. For instance, a serializable database can always return the empty state for any reads, by appearing to execute those reads at time 0. ...

**Comment by benesch** [comment] 2022-10-26 11:46
> This is not incorrect, as far as I can tell.

I agree! I think this is not a bug!

**Comment by jkosh44** [comment] 2022-10-26 14:15
I agree that technically this is not a violation of Serializability. Had this all been a single transaction then it would be, but since each statement is a separate transaction we can re-order them.

This is a violation of read-your-writes (https://jepsen.io/consistency/models/read-your-writes), which we don't guarantee in Serializable. However, I think this is probably a bad UX and we should consider providing it. One way to implement that is the following. If you write to a table `t` at `ts`, then your write doesn't return until all downstream objects (sinks, indexes, materialized views) have advanced to `ts`. I think that's a good compromise, because only writes to tables with downstream objects will have to wait and writes to tables without downstream objects will not have to wait.

I also think this matches the expected behavior of most other databases. Creating indexes on a table will slow down writes to that table because generally the write doesn't return until the index has been updated.

**Comment by jkosh44** [comment] 2022-10-26 14:49
I opened up a feature request for this here: https://github.com/MaterializeInc/materialize/issues/15706. If @philip-stoev agrees I think we should close this issue for that feature request.

**Comment by ggnall** [comment] 2022-11-09 16:41
See Joe's comment above. @philip-stoev feel free to re-open if the suggested change isn't sufficient.

**Closed by ggnall** 2022-11-09 16:41 UTC
Labels: C-bug, T-correctness, A-ADAPTER, C-triage
