### ISSUE TITLE
Some cargo test executions get stuck and time out

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#22995] opened 2023-11-07 14:54 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/68013#018ba8f1-2b5f-4584-9d8f-6716daf08810

### Relevant log output

```source
right: `CreateSinks([CreateSinkCommand { id: User(0), description: StorageSinkDesc { from: Explain, from_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Array(List { element_type: Float64, custom_id: None }), nullable: false }, ColumnType { scalar_type: Record { fields: [(ColumnName("wFyጾჍ2𐎰Fc𛅐!\u{1c37}e/h$ⁱ⮇ઍஒ"), ColumnType { scalar_type: RegProc, nullable: false }), (ColumnName("🠾.ꬓ:"), ColumnType { scalar_type: Time, nullable: true }), (ColumnName("𑖧ㅙ&*ßM0:"), ColumnType { scalar_type: Bool, nullable: true }), (ColumnName("/\\{/`ᨬ𖿢#T:v?{/⑅?&$Eਛ`hꟗf𞹤P\u{1e004}𐖹P\u{1cf1a}U"), ColumnType { scalar_type: TimestampTz { precision: Some(TimestampPrecision(206)) }, nullable: true })], custom_id: None }, nullable: true }, ColumnType { scalar_type: Bytes, nullable: true }, ColumnType { scalar_type: Map { value_type: Interval, custom_id: None }, nullable: true }, ColumnType { scalar_type: Int2Vector, nullable: false }, ColumnType { scalar_type: RegProc, nullable: true }, ColumnType { scalar_type: RegClass, nullable: false }, ColumnType { scalar_type: Jsonb, nullable: true }, ColumnType { scalar_type: Range { element_type: Char { length: Some(CharLength(2874467887)) } }, nullable: true }, ColumnType { scalar_type: Time, nullable: false }, ColumnType { scalar_type: PgLegacyChar, nullable: false }, ColumnType { scalar_type: Map { value_type: Float32, custom_id: Some(System(7016736614681417899)) }, nullable: true }, ColumnType { scalar_type: Array(Oid), nullable: false }, ColumnType { scalar_type: Record { fields: [(ColumnName("T\u{ac7}I?%Ѩ\u{9d7}r=“೩?*T\"=Ⱥ�N"), ColumnType { scalar_type: RegClass, nullable: false }), (ColumnName("\u{b82}𖭭🕴Mb࠹{[ᭁ\u{bd7}"), ColumnType { scalar_type: RegProc, nullable: true }), (ColumnName("𚿾\u{a4d}𐖍t꠲=Fᤜk\\\u{11300}*d[8𞅈ꧨ𞹟ꥻ௪%¥!87<𐀆ⶾYø"), ColumnType { scalar_type: Bool, nullable: true }), (ColumnName("N\u{11301}\\🕴>DȺk🩦΄Ѩ/𞋿½🇶khñ𝅈𞸷{"), ColumnType { scalar_type: Jsonb, nullable: false }), (ColumnName("?ᜇ.?&1K𐒿"), ColumnType { scalar_type: VarChar { max_length: None }, nullable: true }), (ColumnName("&/.:"), ColumnType { scalar_type: Int64, nullable: true }), (ColumnName("ખ{Hf\u{ce2}�E=/F'/Ѩ/'_ொ๏\u{a4c}'"), ColumnType { scalar_type: RegClass, nullable: true }), (ColumnName("kѨ\"g𐼚?Ѩ൏/\u{1172a}�🟈𑵓\\坋🂹𐝅𖬌Jࢮ𞹟"), ColumnType { scalar_type: Uuid, nullable: false }), (ColumnName("𑙐ঝ\u{1daa4}𐀊?'Z:𑊀ÄQ"), ColumnType { scalar_type: PgLegacyChar, nullable: false })], custom_id: Some(Explain) }, nullable: false }, ColumnType { scalar_type: TimestampTz { precision: None }, nullable: false }, ColumnType { scalar_type: List { element_type: RegClass, custom_id: Some(User(17717237128020105539)) }, nullable: false }, ColumnType { scalar_type: Map { value_type: Time, custom_id: Some(System(2327259684988972033)) }, nullable: true }, ColumnType { scalar_type: Range { element_type: Date }, nullable: true }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: PgLegacyChar, nullable: true }, ColumnType { scalar_type: Float64, nullable: true }, ColumnType { scalar_type: PgLegacyChar, nullable: false }, ColumnType { scalar_type: Oid, nullable: true }, ColumnType { scalar_type: VarChar { max_length: None }, nullable: false }, ColumnType { scalar_type: List { element_type: PgLegacyChar, custom_id: None }, nullable: true }, ColumnType { scalar_type: Range { element_type: TimestampTz { precision: None } }, nullable: false }, ColumnType { scalar_type: List { element_type: Char { length: None }, custom_id: None }, nullable: true }, ColumnType { scalar_type: List { element_type: Numeric { max_scale: None }, custom_id: None }, nullable: true }], keys: [[14469294067408324395, 12488522853632515274, 9439574348947946136, 3861696882514261546, 1640747751490070290, 424777074097142976, 14047802397527899200, 626423982428959071, 2236270942129766873, 6061282988605662232, 1596966189502383045], [14081532511962750552, 8260643905412892778, 16552798422426383224, 14350103512779676080, 17174535754824471673, 5913740549825444075, 17717735778307482939, 17773131191048855135, 3208828478299938322, 6619676764914839833, 8970406108198006179, 3661992572446827350, 9065990919296394428, 16155220625582526038, 13277382605594600301, 7179299129479904929, 11861585556595069721, 14460699706250937816, 7245960194814506235, 3144545061073378463, 2357301125367429116, 8894381000492705261, 11974043050844779281, 12859195724685221055, 7177421191356172594, 13919013726274351163, 8955519655184101700, 14069559380604909972, 16889024862204818759, 8683643788596105057, 12742306954779553717, 11705175104588262611, 11837279848754655185, 6704812121407291678, 

[...]

17891349528000669263, 2190515312659626624, 1362299236014105911, 4982755407227470616, 15931481254348693846]] }, names: [ColumnName("Ѩ\u{dd6}𑂓£I`Ѩ`ⴧ\"૪Ѩ$\u{10f82}𑅒\u{a3c}?{{\u{cd6}wᚤ𛲒ଏR"), ColumnName("m𞸂�V@&Ѩ<\u{c4d}﹪`}\u{10a3a}z\u{1752}|ѨG[\u{1e023}I"), ColumnName("\u{1cf25}S]\"𞁌ઃ% ⽜7p🕴\\ຄ𑩺Ⱥѻ‿Ѩ𛅕�$𐎫ഏ�"), ColumnName("%{'Os?{/ᆮ:~B.ℲዃI|&𑊛.𖼍c="), ColumnName("%cই*"), ColumnName(",﬩¥S:𞸁Ѩ\\ѨM*v{🕴?ճ'"), ColumnName("ë🕴j=ß𝔽@\\hm.ዊ\u{7ed}r"), ColumnName("%p\u{1e024}🩺🩤𛅤'𑤉<\u{11074}࡞.𑤌*XG#~𞹨𚿰alU𛅕=\\u𑂸𑂈x"), ColumnName("`\u{1e026}"), ColumnName("/<?𐝣൴*𑣂SWﹱ\\𝕁7¥🈵z~s§áὐ>:᱗MXéѨ"), ColumnName("ઐ<D"), ColumnName("%=𖿣$#Y🆀"), ColumnName("ஜz"), ColumnName("𐒧.¤y$𖪌Ã⁰\"n[\"¥y`\"v🕴`𑀵𖽲2Ⱥ𐕽\"\"")] }, txns_shard: None } } }])
successes: 29
local rejects: 0
global rejects: 0
', src/storage-client/src/client.rs:771:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl
             at ./src/client.rs:771:5
   3: mz_storage_client::client::tests::storage_command_protobuf_roundtrip
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/sugar.rs:158:15
   4: mz_storage_client::client::tests::storage_command_protobuf_roundtrip::{closure#0}
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/sugar.rs:158:15
   5: <mz_storage_client::client::tests::storage_command_protobuf_roundtrip::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

Some runs of cargo test time out after 45 minutes. Most are stuck in the above output. Successful runs terminate after around 25 minutes.

Other instances:
* https://buildkite.com/materialize/tests/builds/68052#018baa12-fd95-4043-90a3-000126891885
* https://buildkite.com/materialize/tests/builds/68001#018ba793-151b-4edb-8f80-286df7c24ea1
* https://buildkite.com/materialize/tests/builds/68011#018ba8df-c076-4557-8199-113c5fd85f40

**Comment by def-** [comment] 2023-11-07 15:12
Duplicate of https://github.com/MaterializeInc/materialize/issues/22987

**Closed** 2023-11-07 15:34 UTC
Labels: C-bug, ci-flake
