### ISSUE TITLE
Materialize is stuck after some period with `reuse_topic=true`

### ISSUE THREAD

**Issue by krpn** [MaterializeInc/materialize#8315] opened 2021-09-16 16:55 UTC
### What version of Materialize are you using?

`v0.9.3`

### How did you install Materialize?

`Docker image`

### What was the issue?

We are using Materialize for calculation states of entities depending on counters. Materialize gets ready counters from Kafka, joins with settings and calculates final state (exceeded or not). States results go into few sinks. There are 19 materialized views, 5 sources and 6 sinks (with `reuse_topic=true`) in Materialize. Materialize configured with `-w 8 --disable-telemetry --experimental` command.

So after some time (3 hours for `-w 8`), Materialize is stuck. We see in the logs only:

```
ERROR materialized::mux: error handling connection in http server: connection closed before message completed
```

`psql` can't connect to Materialize. Prometheus metrics are not available after this moment too.

We have noticed strange `coordinator` behavior in the Prometheus metrics:
![image](https://user-images.githubusercontent.com/16793635/133651438-fefaa77d-6b29-42e5-a9b5-77783a3e6341.png)

As you can see, coordinator's CPU consumption is growing always. Growth dynamics depend on workers quantity. After it gets 100%, Materialize is stuck.

We have tried:
- Restarting doesn't help (same error in the logs)
- `-w 16` doesn't help
- `--introspection-frequency 300s` doesn't help
- `--introspection-frequency off` doesn't help

Clearing all Kafka topics completely is one way to get Materialize to work.

### Is the issue reproducible? If so, please provide reproduction instructions.

It's reproducible for our configuration. Wa have Kafka cluster with permanent counters streaming values.

### Please attach any applicable log files.

```
ERROR materialized::mux: error handling connection in http server: connection closed before message completed
```

**Comment by ruchirK** [comment] 2021-09-16 17:18
Does this issue still reproduce if you get make the sinks be the standard nonce sinks (remove `reuse_topic=true`?). Probably to test that out i would recommend you start with a fresh catalog and then repopulate all source, view, and sink definitions.

**Comment by krpn** [comment] 2021-09-17 15:29
@ruchirK, thank you. Seems like it works.

With `reuse_topic=true`:
![image](https://user-images.githubusercontent.com/16793635/133810871-fb55ae32-9de0-4f59-8c25-ec8c93b2cae2.png)

Without `reuse_topic=true`:
![image](https://user-images.githubusercontent.com/16793635/133811297-edb006a6-52bb-4bcc-87c9-3d706abd59dc.png)

**Comment by ruchirK** [comment] 2021-09-17 15:47
@krpn thanks for checking my suspicion. Unfortunately, removing `reuse_topic=true` is not a general purpose fix as that option allows users to reuse sink topics, which people often need in production. It would be amazing if you could provide any more detailed instructions on how to reproduce this behavior. For example, could you share your catalog? Happy to find a more private channel if you don't feel comfortable sharing over github

cc: @aljoscha

**Comment by ruchirK** [comment] 2021-09-17 15:50
>  Materialize gets ready counters from Kafka, joins with settings and calculates final state (exceeded or not). States results go into few sinks.

if I'm understanding this correctly, is this sort of like -- you have a stream of integers that come in, you are doing some computation that ends with `max(...)` and then that `max` is written out to a sink? And perhaps, the case where the `max` is updated (exceeded) doesn't always happen frequently?

**Comment by krpn** [comment] 2021-09-17 15:58
@ruchirK, shared SQL sources with you by email from [commit](https://github.com/ruchirK/persisting-arrangements/commit/a1ac686ba1e885f4d6bc721557e77812896a0661.patch).

We are using compacted stream with counters (integers + floats) as source.

**Comment by krpn** [comment] 2021-09-20 06:28
Still working with normal CPU consumption (without `reuse_topic=true`:):
![image](https://user-images.githubusercontent.com/16793635/133963297-dbc3a90b-301f-4a81-991d-d2178bb32e10.png)

So there is problem with `reuse_topic=true`. Some leak or something like that.

**Comment by aljoscha** [comment] 2021-09-20 08:25
Hi @krpn,

to help in debugging, could you please look at these metrics when running with `reuse_topic=true` and post them here:

 - `mz_kafka_sink_rows_queued`
 - `mz_kafka_messages_sent_total`
 - `mz_kafka_sink_messages_in_flight`
 - `mz_kafka_message_send_errors_total`
 - `mz_kafka_message_send_errors_total`

**Comment by krpn** [comment] 2021-09-20 12:35
Hi @aljoscha,

![image](https://user-images.githubusercontent.com/16793635/134003176-737eb959-7bc1-4fef-b76a-0b4e0f31e849.png)

**Comment by ruchirK** [comment] 2021-09-20 20:00
Hi @krpn

I spent the last 5 or 6 hours trying to reproduce this on my end, with no luck, so I'm afraid I have only a few more questions for you.

1. Does this issue reproduce on freshly created sinks, or is it always encountered after a restart from previously created sinks and sources?
2. Are you hitting Materialize with other `SELECT` queries?
3. Roughly how many messages per second do you expect to see from the input topics, and written out to the output topics?
4. Is there any way you could send me profiler output of what Materialize, and specifically the coordinator thread is doing? I'm not sure how feasible getting that information is from within Docker depending on the host os so no worries if its not possible.
5. Does this issue still reproduce for you if you remove all but one of the 5 sinks?

**Comment by ruchirK** [comment] 2021-09-21 00:56
Actually @krpn I was able to reproduce something like this behavior if I get a kafka sink in an error-d state. When this happens however, Materialize spams the log file with info logs that look like

```
2021-09-21T00:52:15.318455Z  INFO dataflow::sink::kafka: shutting down sink: kafka-u28
```

with roughly one of these per second. Do you see any log lines like that when you run with `reuse_topics=true`?

**Comment by ruchirK** [comment] 2021-09-21 10:44
To reproduce one can do something like the following:

1. Patch the billing demo to create a few new exactly-once sinks

```
diff --git a/demo/billing/src/mz.rs b/demo/billing/src/mz.rs
index 2cb5d56c1..3a4acd5fa 100644
--- a/demo/billing/src/mz.rs
+++ b/demo/billing/src/mz.rs
@@ -58,9 +58,25 @@ pub async fn create_kafka_sink(
     sink_name: &str,
     schema_registry_url: &str,
 ) -> Result<String> {
+    let query = format!(
+            "CREATE SINK billing_daily FROM billing_agg_by_day INTO KAFKA BROKER '{kafka_url}' TOPIC 'billing_daily' \
+             WITH (consistency_topic = 'billing_daily-consistency', reuse_topic=true, partition_count=16) FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '{schema_registry}'",
+             kafka_url = kafka_url,
+             schema_registry = schema_registry_url
+         );
+    log::debug!("creating sink=> {}", query);
+    mz_client::execute(&mz_client, &query).await?;
+    let query = format!(
+            "CREATE SINK billing_top5 FROM billing_top_5_months_per_client INTO KAFKA BROKER '{kafka_url}' TOPIC 'billing_top5' \
+             WITH (consistency_topic = 'billing_top5-consistency', reuse_topic=true, partition_count=16) FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '{schema_registry}'",
+             kafka_url = kafka_url,
+             schema_registry = schema_registry_url
+         );
+    log::debug!("creating sink=> {}", query);
+    mz_client::execute(&mz_client, &query).await?;
     let query = format!(
             "CREATE SINK {sink} FROM billing_monthly_statement INTO KAFKA BROKER '{kafka_url}' TOPIC '{topic}' \
-             WITH (consistency_topic = '{topic}-consistency') FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '{schema_registry}'",
+             WITH (consistency_topic = '{topic}-consistency', reuse_topic=true, partition_count=16) FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '{schema_registry}'",
              sink = sink_name,
              kafka_url = kafka_url,
              topic = sink_topic_name,
```

2. Run materialize, and run the billing demo

from `demo/billing` run:

```
cargo run -- --message-count 200000 --messages-per-second 100 --preserve-source --low-memory
```

3. Whilst that is running, delete the consistency topic for one of the newly created sinks, with something like

```
./confluent-6.1.1/bin/kafka-topics --bootstrap-server localhost:9092 --delete --topic billing_daily-consistency
```

4. Now, when you inspect the set of timestamp bindings stored in the catalog they should grow unboundedly

so if we did `sqlite3 mzdata/catalog` and then

```
sqlite> select count(*) from timestamps;
80
sqlite> select count(*) from timestamps;
82
sqlite> select count(*) from timestamps;
83
sqlite> select count(*) from timestamps;
84
```

In practice, the billing demo only installs 2 or 3 sources, each of which should only retain one or two timestamps because the default compaction is pretty aggressive, so this indicates a resource leak. This resource leak then affects the coordinator because time spent attempting to compact these timestamps seems to grow linearly with the number of timestamps (even when we can't do compactions) - this also seems like a separate bug.

**Comment by krpn** [comment] 2021-09-21 11:49
Hi @ruchirK,

> Does this issue reproduce on freshly created sinks, or is it always encountered after a restart from previously created sinks and sources?

This issue reproduces on freshly created sinks. But there is something important: we are using precreated topics with custom configuration.

`(blue|green)_aggregated_landing_placement_reserved_limit_setting`:
```
      "config": {
        "cleanup.policy": "compact",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.001",
        "min.insync.replicas": "2",
        "retention.ms": "-1",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 5,
      "replication_factor": 3
```

`landing_placement_counter_daily`:
```
      "config": {
        "cleanup.policy": "compact,delete",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.001",
        "min.insync.replicas": "2",
        "retention.ms": "691200000",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

`landing_placement_counter_hourly`:
```
      "config": {
        "cleanup.policy": "compact,delete",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.001",
        "min.insync.replicas": "2",
        "retention.ms": "3600000",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

`landing_placement_counter_total`:
```
      "config": {
        "cleanup.policy": "compact",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.001",
        "min.insync.replicas": "2",
        "retention.ms": "-1",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

`landing_daily_limit_state_materialize_db`, `landing_placement_daily_limit_state_materialize_db`:
```
      "config": {
        "cleanup.policy": "delete",
        "min.insync.replicas": "2",
        "retention.ms": "691200000",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

`landing_hourly_limit_state_materialize_db`, `landing_placement_hourly_limit_state_materialize_db`:
```
      "config": {
        "cleanup.policy": "delete",
        "min.insync.replicas": "2",
        "retention.ms": "3600000",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

`landing_total_limit_state_materialize_db`, `landing_placement_total_limit_state_materialize_db`:
```
      "config": {
        "cleanup.policy": "compact",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.001",
        "min.insync.replicas": "2",
        "retention.ms": "-1",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 16,
      "replication_factor": 3
```

all consistency topics:
```
      "config": {
        "cleanup.policy": "compact",
        "delete.retention.ms": "86400000",
        "min.cleanable.dirty.ratio": "0.01",
        "min.insync.replicas": "2",
        "retention.ms": "-1",
        "segment.bytes": "5000000",
        "segment.ms": "10000"
      },
      "partitions": 1,
      "replication_factor": 3
```

So when we want to reinitialize Materialize, we change all these topics settings to `"retention.ms": "100", "cleanup.policy": "delete"`, wait until latest offsets are equal earliest offsets (clean is over), change settings to previous, run Materialize and create sources, views and sinks using `psql`. Materialize is working some time and then breaks. Restart doesn't help. Topics cleaning helps.

> Are you hitting Materialize with other SELECT queries?

No, we are reading sink topics and caching to the service memory only. That's why we want to use constant topic names.


> Roughly how many messages per second do you expect to see from the input topics, and written out to the output topics?

![image](https://user-images.githubusercontent.com/16793635/134164899-87a21ced-99b1-42d4-b4ea-7a652f5d976d.png)

> Is there any way you could send me profiler output of what Materialize, and specifically the coordinator thread is doing? I'm not sure how feasible getting that information is from within Docker depending on the host os so no worries if its not possible.

Yes, if you say how.

> Does this issue still reproduce for you if you remove all but one of the 5 sinks?

I will try.

> with roughly one of these per second. Do you see any log lines like that when you run with `reuse_topics=true`?

No, I don't see such text. We use default log level. I see only `ERROR materialized::mux: error handling connection in http server: connection closed before message completed` every minute and nothing else.

**Comment by krpn** [comment] 2021-09-22 07:45
@ruchirK, have you found problem? Do you need more details?

**Comment by ruchirK** [comment] 2021-09-24 13:44
Hi @krpn sorry for my delayed response. I think I have a relatively clear idea of what is happening, and a plausible theory for why, and am going to push out a branch that you can try out later today (I'm not sure when it will get merged)

What's happening: we need sinks with `reuse_topic=true` to communicate back to the coordinator thread "I've written data up to some timestamp X", so that the coordinator can then compact up timestamp information (mapping from input offsets -> timestamp) up to the minimum timestamp across all sinks. For some reason, one or more sinks are not sending this notification back to the coordinator which results in the coordinator retaining an unbounded amount of timestamp information, which takes a linearly increasing amount of time to maintain in sqlite because we aren't using proper indexes in sqlite.

Why is this happening: this I'm less clear about but my hypothesis is that the sink encounters some kind of error, and puts itself in a "I am erroring and will not write anymore" state. There could be other reasons I haven't understood yet, but that was the only way I could reproduce this issue on my machine.

My patch to fix this issue / make the root cause more obvious will make it so that when a sink encounters an error it will communicate to the coordinator that it is finished writing, so that the coordinator doesn't await write progress updates from it anymore.

At this point, I don't need further details.

**Comment by krpn** [comment] 2021-09-29 11:51
@ruchirK, unfortunately, it doesn't help:

![image](https://user-images.githubusercontent.com/16793635/135262878-ad2b565b-1f00-4366-aab7-decaff85e510.png)

**Comment by ruchirK** [comment] 2021-09-29 11:52
is there anything in the logs?

**Comment by krpn** [comment] 2021-09-29 11:54
@ruchirK, the same as before `ERROR materialized::mux: error handling connection in http server: connection closed before message completed`:

![image](https://user-images.githubusercontent.com/16793635/135263428-8141e4cf-681e-4679-a8be-70c0b8691f39.png)

**Comment by ruchirK** [comment] 2021-09-29 11:57
just to be super clear: theres no other error message in the logs besides that one? Specifically, there's no sink error output in the log?

**Comment by krpn** [comment] 2021-09-29 11:59
@ruchirK, no any messages in the log (default log level).

![image](https://user-images.githubusercontent.com/16793635/135264047-f7628dd0-f641-420a-80b2-4f4c060749ca.png)

**Comment by krpn** [comment] 2021-09-29 12:18
@ruchirK, do you need more information? Can I help you?

**Comment by ruchirK** [comment] 2021-09-29 12:31
@krpn yes thank you for asking. At this point I think I'm going to need some more info to reproduce what's happening locally:

1. does this error still occur even if you only install one sink (and the required sources and views for that sink) install of installing all 5 sinks and all of the sources and views required for that?

2. if 1 is true, does this reproduce even if you only send a small number of events (say <100 total) to the source?

My thought process is: we need to minimize the number of things happening in this environment, so that we can more easily isolate / reproduce what's wrong. My other thought is that all this time I've been testing with a kafka broker running on localhost, and I may need to try to run a more realistic broker setup / try to use your broker and topic configs to reproduce this issue

**Comment by krpn** [comment] 2021-09-30 11:07
@ruchirK, 1 topic with `reuse_topic=true` + 5 topics with `reuse_topic=false` seems to be working fine:

![image](https://user-images.githubusercontent.com/16793635/135444074-e15e5a0f-2dc9-4805-818f-8e675c50cfc1.png)

I will try apply `reuse_topic=true` to 2 topics later today.

**Comment by ruchirK** [comment] 2021-09-30 11:30
Very interesting, thanks for running the experiment!

This suggests to me that either:
 
1. There's a bug somewhere with multiple sinks with `reuse_topic=true`
and/or
2. One of the sink topic configurations is somehow clashing with what Materialize needs when reuse_topic is true.

**Comment by krpn** [comment] 2021-09-30 12:34
@ruchirK, broken with 2 topics with `reuse_topic=true`:

![image](https://user-images.githubusercontent.com/16793635/135455750-d4d0b630-89cd-4238-ac5c-ffaff8b46a77.png)

**Comment by ruchirK** [comment] 2021-09-30 13:35
@krpn ok very cool. Just to confirm when you tested with 2 topics that was with the sink you tested with previously which worked + another additional sink right? If so, I'd love to get one final test with only reuse_topics=true on the additional sink, and off everywhere else -- that should help nail down whether theres an issue with that particular sink, and if they both work individually, but fail together then theres clearly some other issue.

**Comment by krpn** [comment] 2021-09-30 13:39
@ruchirK,

> Just to confirm when you tested with 2 topics that was with the sink you tested with previously which worked + another additional sink right?

Yes.
First try was with `landing_placement_total_limit_state_materialize_db`.
Second try was with `landing_placement_total_limit_state_materialize_db` and `landing_placement_daily_limit_state_materialize_db_consistency`.

> If so, I'd love to get one final test with only reuse_topics=true on the additional sink, and off everywhere else -- that should help nail down whether theres an issue with that particular sink, and if they both work individually, but fail together then theres clearly some other issue.

I will try now with `landing_placement_daily_limit_state_materialize_db_consistency` only.

**Comment by krpn** [comment] 2021-09-30 15:20
@ruchirK, unfortunately, it doesn't work with one `reuse_topic=true` on `landing_placement_daily_limit_state_materialize_db_consistency` only:

![image](https://user-images.githubusercontent.com/16793635/135483856-9173ef46-94a6-4824-912f-c6af82841bb5.png)

**Comment by ruchirK** [comment] 2021-09-30 18:16
@krpn that's actually not unfortunate and could help us isolate the error to maybe something in the topic configuration!

**Comment by krpn** [comment] 2021-10-01 09:22
@ruchirK, we have found that broken sink (`landing_placement_daily_limit_state_sink`) doesn't have `envelope upsert` option. Working sink (`landing_placement_total_limit_state_sink`) has this option.

**Comment by krpn** [comment] 2021-10-01 10:39
Changing `landing_placement_daily_limit_state_sink` to `envelope upsert` mode doesn't help:

![image](https://user-images.githubusercontent.com/16793635/135606715-05e0e38e-006a-48e7-a668-5cdbf5c75804.png)

**Comment by krpn** [comment] 2021-10-01 11:41
Default topic settings for `landing_placement_daily_limit_state_materialize_db` and `landing_placement_daily_limit_state_materialize_db_consistency` + `reuse_topic=true` on `landing_placement_daily_limit_state_sink` only doesn't help.

**Comment by ruchirK** [comment] 2021-10-01 12:30
Hi @krpn thanks for these details. Let me think a little bit about what the best next step might be here, and then get back to you.

**Comment by ruchirK** [comment] 2021-10-04 17:47
@krpn I have good / bad news. Bad news - I don't have anything specific for you to try because I'm out of debugging ideas. Good news: I've recruited @philip-stoev to try to reproduce this issue, and hopefully having fresh eyes on this will help!

**Comment by elindsey** [comment] 2021-10-07 21:50
Hi @krpn, thank you for the bug report and for giving us all the info. Our team continued to look into this, and we've noticed there's a few similar reports for loss of interactivity with reuse_topic. I've collected these together and put a deeper investigation of the issue onto the team's backlog to be prioritized. I'm going to close this issue as it's captured in https://github.com/MaterializeInc/materialize/issues/8589 in the engineering team's queue, and you can follow along there for updates.

**Closed by elindsey** 2021-10-07 21:50 UTC
Labels: C-bug, P2

**Comment by krpn** [comment] 2022-04-20 15:36
Any news with this? If I restart Materialize after one week (`v0.15.0`), it will get stucked Materialize with `ERROR materialized::mux: error handling connection in http server: connection closed before message completed`. I have just updated Materialize to `v0.25.0`. Will check after one week.
