### ISSUE TITLE
 panic: Datum::unwrap_date called on Numeric(OrderedDecimal(1819.26))

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9027] opened 2021-11-10 15:09 UTC
### What version of Materialize are you using?

From the shell:

```
materialized v0.9.12-dev (4e6d18323)
```

### What was the issue?

A query that is fully-formed, properly typed and hopefully at least remotely realistic panics as follows:

```
2021-11-10T13:50:00.549281Z ERROR panic: Datum::unwrap_date called on Numeric(OrderedDecimal(1819.26))
thread: timely:work-1
location: src/expr/src/scalar/func.rs:1315:18
version: 0.9.12-dev (4e6d18323baa67b404ea47bca50296f98d0dcc20)
backtrace:
   0: materialized::handle_panic
             at src/materialized/src/bin/materialized/main.rs:675:21
   1: core::ops::function::Fn::call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
   7: repr::scalar::Datum::unwrap_date
             at src/repr/src/scalar.rs:345:18
   8: expr::scalar::func::sub_date_interval
             at src/expr/src/scalar/func.rs:1315:16
      expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2838:47
   9: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  10: expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2862:34
  11: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  12: expr::scalar::func::and
             at src/expr/src/scalar/func.rs:92:24
  13: expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2798:32
  14: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  15: expr::scalar::func::and
             at src/expr/src/scalar/func.rs:90:11
  16: expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2798:32
  17: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  18: expr::scalar::func::and
             at src/expr/src/scalar/func.rs:90:11
  19: expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2798:32
  20: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  21: expr::scalar::func::or
             at src/expr/src/scalar/func.rs:107:11
  22: expr::scalar::func::BinaryFunc::eval
             at src/expr/src/scalar/func.rs:2799:31
  23: expr::scalar::MirScalarExpr::eval
             at src/expr/src/scalar/mod.rs:950:17
  24: expr::linear::plan::SafeMfpPlan::evaluate_inner
             at src/expr/src/linear.rs:1214:20
  25: expr::linear::plan::SafeMfpPlan::evaluate_into
             at src/expr/src/linear.rs:1171:37
      dataflow::render::join::JoinClosure::apply
             at src/dataflow/src/render/join/mod.rs:80:9
      dataflow::render::join::linear_join::<impl dataflow::render::context::Context<G,repr::row::Row,T>>::differential_join_inner::{{closure}}
             at src/dataflow/src/render/join/linear_join.rs:437:17
      <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:396:13
  26: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:583:43
      differential_dataflow::operators::join::Deferred<K,V1,V2,T,R1,R2,R3,C1,C2,D>::work::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:740:42
  27: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:833:21
      differential_dataflow::operators::join::Deferred<K,V1,V2,T,R1,R2,R3,C1,C2,D>::work
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:738:21
  28: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/c696ec0/src/operators/join.rs:581:21
      <timely::dataflow::stream::Stream<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::binary_frontier::{{closure}}::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/dataflow/operators/generic/operator.rs:435:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/dataflow/operators/generic/builder_rc.rs:124:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/dataflow/operators/generic/builder_raw.rs:205:9
  29: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:684:30
  30: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:310:17
  31: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:684:30
  32: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:310:17
  33: timely::worker::Wrapper::step::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:749:57
      core::option::Option<T>::map
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/option.rs:836:29
      timely::worker::Wrapper::step
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:749:26
  34: timely::worker::Worker<A>::step_or_park
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:396:38
  35: dataflow::server::Worker<A>::run
             at src/dataflow/src/server.rs:738:13
  36: dataflow::server::serve::{{closure}}
             at src/dataflow/src/server.rs:405:9
      timely::execute::execute::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/execute.rs:285:22
      timely_communication::initialize::initialize_from::{{closure}}
             at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/communication/src/initialize.rs:291:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:125:18
  37: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:481:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:480:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys/unix/thread.rs:106:17
  39: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  40: clone
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Run this query:

```
SELECT
	CASE o_orderkey
	WHEN 1 THEN l_orderkey
	ELSE (
		SELECT
			l_orderkey
		WHERE
			l_shipdate = o_orderdate + ' 3 MONTH '
			OR o_orderdate = l_shipdate - ' 9 DAY '
				AND EXISTS(
						SELECT
							1
						WHERE
							true
							AND l_orderkey
								= ANY (
										SELECT
											o_orderkey
										FROM
											lineitem RIGHT JOIN orders ON true
										WHERE
											l_receiptdate IN ('1997-07-06') OR l_commitdate = o_orderdate - ' 7 DAY '
									)
					)
	)
	END
FROM
	lineitem JOIN orders ON true;
```

against this dataset [gh9027.sql.zip](https://github.com/MaterializeInc/materialize/files/7513731/gh9027.sql.zip)

**Comment by sploiselle** [comment] 2021-11-10 17:31
So far, this is the minimal query to trigger the crash:

```sql
SELECT
  1
FROM
  lineitem JOIN orders ON true
WHERE
  l_orderkey
  = ANY (
      SELECT
        o_orderkey
      FROM
        lineitem RIGHT JOIN orders ON true
      WHERE
        l_receiptdate IN ('1997-07-06')
        OR l_commitdate = o_orderdate - ' 7 DAY '
    );
```

What's happening is that this query plans the access to `o_orderdate` (4th col) as a reference to `o_totalprice (3rd col), so looks like there's an off-by-one error somewhere.

This also requires the `ANY` subquery to use a `RIGHT JOIN`.

Here's the plan of just the `ANY` subquery w/ my postfix comments (`--`):

```
----------------------------------------------------------------
 %0 =                                                          +
 | Get materialize.public.lineitem (u436)                      +
 | Project (#11, #12)                                          +
 | ArrangeBy ()                                                +
                                                               +
 %1 =                                                          +
 | Get materialize.public.orders (u432)                        +
 | Project (#0, #4) -- (o_orderkey, o_orderdate)
                                                               +
 %2 =                                                          +
 | Join %0 %1 -- (lineitem#11, lineitem#12, o_orderkey, o_orderdate)
 | | implementation = Differential %1 %0.()                    +
 | Filter ((#1 = 1997-07-06) || (datetots(#0) = (#3 - 7 days)))+
 | Project (#2)                                                +
```

Here's the failing query:

```
                         Optimized Plan                         
----------------------------------------------------------------
 %0 =                                                          +
 | Get materialize.public.lineitem (u436)                      +
 | Project ()                                                  +
 | ArrangeBy ()                                                +
                                                               +
 %1 =                                                          +
 | Get materialize.public.orders (u432)                        +
 | Project (#0) -- (o_orderkey)                                +
                                                               +
 %2 = Let l0 =                                                 +
 | Join %0 %1                                                  +
 | | implementation = Differential %1 %0.()                    +
                                                               +
 %3 =                                                          +
 | Get materialize.public.lineitem (u436)                      +
 | Project (#11, #12)                                          +
 | ArrangeBy ()                                                +
                                                               +
 %4 =                                                          +
 | Get %2 (l0)                                                 +
 | Filter !(isnull(#0))                                        +
 | Distinct group=(#0)                                         +
 | ArrangeBy (#0)                                              +
                                                               +
 %5 =                                                          +
 | Get materialize.public.orders (u432)                        +
 | ArrangeBy (#0)                                              +
                                                               +
 %6 =                                                          +
 | Join %3 %4 %5 (= #2 #3) -- (lineitem#11, lineitem#12, o_orderkey, o_orderkey, o_custkey, o_orderstatus, o_totalprice, o_orderdate,...)
 | | implementation = Differential %4.(#0) %5.(#0) %3.()       +
 | Filter ((#1 = 1997-07-06) || (datetots(#0) = (#7 - 7 days)))+
 | Project (#2)                                                +
 | Distinct group=(#0)                                         +
 | ArrangeBy (#0)                                              +
                                                               +
 %7 =                                                          +
 | Join %2 %6 (= #0 #1)                                        +
 | | implementation = Differential %2 %6.(#0)                  +
 | Project ()                                                  +
 | Map 1                                                       +
```

So you can see here that the column reference is correct on this line, i.e. it should be the eighth column:

```
Filter ((#1 = 1997-07-06) || (datetots(#0) = (#7 - 7 days)))
```

@antiguru Seems like this is likely related to the de-duplication work that landed in #8718. We have a row with a duplicated key (`o_orderkey`), and the wrong datum/column is getting fed into a function. Anything jump out at you?

**Comment by antiguru** [comment] 2021-11-10 21:10
Many thanks for the initial analysis. I can repro the issue, now need to understand where the error is introduced. I'll keep looking a bit, but will do more tomorrow.

**Comment by antiguru** [comment] 2021-11-10 22:13
Current brain dump: What I don't understand is why the closure wants to cast column #1 to a date. The input is `[Int32(257), Numeric(OrderedDecimal(6206.5)), Date(1992-10-08), Date(1992-10-24)]`, and we apply the following closure:
```
closure: JoinClosure {
  ready_equivalences: [],
  before: SafeMfpPlan {
    mfp: MapFilterProject {
      expressions: [],
      predicates: [
        (4, CallBinary {
          func: Or,
          expr1: CallBinary {
            func: Eq,
            expr1: Column(3),
            expr2: Literal(Ok(Row{[Date(1997-07-06)]}), ColumnType { scalar_type: Date, nullable: false })
          },
          expr2: CallBinary {
            func: Eq,
            expr1: CallUnary { func: CastDateToTimestamp, expr: Column(2) },
            expr2: CallBinary {
              func: SubDateInterval,
              expr1: Column(1), -- <-- I don't see why this is correct
              expr2: Literal(Ok(Row{[Interval(Interval { months: 0, duration: 604800000000000 })]}), ColumnType { scalar_type: Interval, nullable: false })
          }
        } 
      }
    )],
    projection: [0],
    input_arity: 4
    }
  }
}                                                                                                                        
```

I marked the point where `Column(1) is interpreted as a date, which I don't understand how this happens. It appears that `#2, #3` are indeed date-like values, but `#1` isn't. What I can's say is whether the output of the join matches the expectations or not, but I can't prove or disprove that this bug comes from the permutation PR :)

**Comment by frankmcsherry** [comment] 2021-11-10 22:25
In principle, we should be able to look at both the `EXPLAIN` and `EXPLAIN PHYSICAL PLAN` and see (or not see) that something has gone wrong there. The `JoinClosure` should be available to check there, and if there is e.g. a bug in going from MIR -> LIR we could see it there.

**Comment by sploiselle** [comment] 2021-11-11 00:54
@antiguru I spent some time bisecting this and the crash doesn't happen before #8718 lands,  but does happens in its final commit.

Re: your comments above: I'm not sure if you're confused why it's column 1 getting treated as a date (I have no idea), or why you're confused about where the assumption that we need a date in this spot comes from (SQL planning), but lmk if there's anything from the SQL side of things I can help with.

**Comment by antiguru** [comment] 2021-11-11 01:12
Great, thanks! I'll take a spin at debugging this tomorrow.

**Closed** 2021-11-11 21:24 UTC
Labels: C-bug, A-sql

**Comment by antiguru** [comment] 2021-11-12 16:13
The problem reproduces with the following minimal dataset:
```
INSERT INTO "lineitem" VALUES (581,7,1,1,41,37187,0.09,0.07,'N','O','1997-05-26','1997-04-06','1997-06-10','TAKE BACK RETURN','MAIL','even, bold excuses about the'),(581,10,1,2,14,12740.14,0.06,0.08,'N','O','1997-05-17','1997-04-14','1997-06-08','NONE','MAIL','furiously silent depths'),(581,11,1,3,49,44639.49,0.1,0.02,'N','O','1997-02-27','1997-04-24','1997-03-10','TAKE BACK RETURN','MAIL','furiously regular theodolites wake qu'),(581,8,1,4,30,27240,0.1,0.08,'N','O','1997-06-19','1997-05-21','1997-06-22','TAKE BACK RETURN','TRUCK','even deposits wa'),(582,6,1,1,7,6342,0.07,0,'N','O','1997-11-16','1997-11-29','1997-12-10','TAKE BACK RETURN','FOB','carefully final requests sleep slyly. even,'),(582,6,1,2,49,44394,0.05,0.03,'N','O','1997-12-17','1998-01-12','1997-12-31','COLLECT COD','REG AIR','carefully regular'),(582,15,1,3,42,38430.42,0.07,0,'N','O','1997-11-15','1997-12-21','1997-12-03','COLLECT COD','SHIP','pending, spe'),(582,17,1,4,36,33012.36,0.06,0.01,'N','O','1997-12-09','1997-11-27','1997-12-26','TAKE BACK RETURN','SHIP','slyly final foxes nag permanen');
INSERT INTO "orders" VALUES (547,10,'O',87538.95,'1996-06-22','3-MEDIUM','Clerk#000000976',0,'bold instructions print fluffily carefully id'),(548,13,'F',91796.96,'1994-09-21','1-URGENT','Clerk#000000435',0,'quickly regular accounts daz'),(549,11,'F',129199.61,'1992-07-13','1-URGENT','Clerk#000000196',0,'carefully regular foxes integrate ironic, fina'),(550,4,'O',27927.38,'1995-08-02','1-URGENT','Clerk#000000204',0,'carefully even asymptotes sleep furiously sp'),(551,10,'O',40845.41,'1995-05-30','1-URGENT','Clerk#000000179',0,'unusual, final accounts use above the special excuses. final depo'),(576,4,'O',17143.74,'1997-05-13','3-MEDIUM','Clerk#000000955',0,'pending theodolites about the carefu'),(577,7,'F',33465.32,'1994-12-19','5-LOW','Clerk#000000154',0,'blithely unusual packages sl'),(578,10,'O',60466.97,'1997-01-10','5-LOW','Clerk#000000281',0,'blithely pending asymptotes wake quickly across the carefully final'),(579,7,'O',116780.04,'1998-03-11','2-HIGH','Clerk#000000862',0,'slyly even requests cajole slyly. sil'),(580,7,'O',77490.74,'1997-07-05','2-HIGH','Clerk#000000314',0,'final ideas must have to are carefully quickly furious requests'),(581,7,'O',116599.09,'1997-02-23','4-NOT SPECIFIED','Clerk#000000239',0,'carefully regular dolphins cajole ruthlessl'),(582,5,'O',116419.79,'1997-10-21','1-URGENT','Clerk#000000378',0,'quietly ironic pinto beans wake carefully. ironic accounts across the dol');
```
