### ISSUE TITLE
Support propagating MySQL/Debezium DROP TABLE to Materialize

### ISSUE THREAD

**Issue by nacrooks** [MaterializeInc/materialize#1965] opened 2020-02-12 16:40 UTC
Consider the two MySQL, Materialize workflows:

**1) MySQL + Debezeum**
```
create table foo (a int PRIMARY KEY, b int);
insert into foo (1,1);
drop table foo ; 
create table foo (a int PRIMARY KEY, b int);
insert into foo (1,2)
select * from foo
a b
---
1,2
```

**2) Materialize**
```
create source foo ...
create view v as select * from foo;
select * from v
a b
----
1,1
1,2
```

Materialize incorrectly shows the two records as it is not aware of the intermediate drop table.

**The problem:** Debezeum does not delete topics  when dropping tables. Materialize either does not see or handle the drop table message, it only sees the two record insertions.

**Comment by benesch** [comment] 2020-02-17 21:00
(Closing as a duplicate of #555.)

**Closed by benesch** 2020-02-17 21:00 UTC
Labels: C-feature, docs-impact
