### ISSUE TITLE
docs: page for supported drivers and examples

### ISSUE THREAD

**Issue by cuongdo** [MaterializeInc/materialize#7234] opened 2021-06-28 18:42 UTC
## What

It would be great if we had a page that listed supported combinations of programming language + Postgres driver and sample code for Materialize. For example: [Cockroach's Hello World Example Apps page](https://www.cockroachlabs.com/docs/v21.1/hello-world-example-apps). We should make sure that the samples (or some subset of them) work with Cloud, which requires TLS certificates that some clients may not support.

Ideally, these samples are regularly tested, so they don't rot.

## Why

During last week's dogfooding day, it was not clear to at least some engineers which driver could be used for different programming languages. I got lucky with `node-postgres` + Node.js, but others got stuck on Cloud certificates. Also, it's beneficial to have prescribed defaults for connecting an app to Materialize.

## How

Once we decide on what languages want to document first, we could ask engineers which programming languages they are comfortable contributing sample code for.

**Comment by morsapaes** [comment] 2021-07-07 18:25
Linking to #5187.

**Comment by msudberg** [comment] 2021-08-17 20:28
Duplicate of #5187.

**Closed by msudberg** 2021-08-17 20:28 UTC
Labels: C-feature, A-docs, bugfix-day
