### ISSUE TITLE
Limit the total number of SUBSCRIBEs (or SQL connections) allowed per customer's region

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18341] opened 2023-03-22 20:38 UTC
Too many concurrent SUBSCRIBEs causes undue load on the underlying cluster on which the SUBSCRIBEs are run and potentially on CRDB, which then pegs the clusters. This is because each subscribe creates its own dataflow. This is tracked in  https://github.com/MaterializeInc/materialize/issues/18261.

The same could happen with concurrent SELECTs that require creating temporary dataflows as well, and we've seen that happen to the `mz_introspection` cluster with concurrent non-indexed web UI queries.

Since there can only be one subscribe per connection, we should consider limit the total number of SQL connections allowed. This in turn will limit both the total number of concurrent SELECTs and SUBSCRIBEs in the system.

If we feel limiting SQL connections overall is too restrictive, since we may want to allow certain concurrent SELECT use cases, we can alternatively just limit the number of subscribes.

**Comment by chaas** [comment] 2023-04-03 18:45
Update: @ggnall and I decided it makes sense to add two [config flags](https://www.notion.so/materialize/Managing-config-style-flags-f464f6567b0d46a0bbe99ab2ae53661d), one for limiting the number of subscribes and another for limiting the number of total SQL connections per customer region.

Subscribes are only a subset of things that can happen in a connection, so `number_of_connections is always >= number_of_subscribes` and thus `max_connections must always be >= max_subscribes`.

We don't have known exact limits in place yet, but we want to have the controls available in case we need to use them.
For now let's say `max_subscribes` is 100 and `max_connections` to 500.
If a user wants to do more than that, we can selectively choose to increase their config, but we'd like to understand their use case first.

**Comment by mjibson** [comment] 2023-04-04 17:09
Could we try to fix this problem at one level deeper than capping SUBSCRIBE and connection counts? If the problem is number of dataflows on a cluster, then that's what we should limit. A cap on SUBSCRIBE or connections will cause expanding usage to fail as users add new use cases. A cap on the number of dataflows on a cluster will not, since organizations can keep adding more clusters.

This is a bit more work now, but probably less overall?

**Comment by benesch** [comment] 2023-05-01 01:43
I think `max_connections` makes sense. Connections use up scarce `environmentd` resources, and it makes sense to limit them.

I'm not sold on `max_subscribes`. What resource are we trying to protect with that limit? Clusters are already a unit of isolation, and subscribes are not, as far as I can tell, inherently more expensive than a bunch of repeatedly-issued SELECTs. In fact the SELECTs are probably more expensive because they require dataflows to be repeatedly created and deleted, based on @teskje's comment here: https://github.com/MaterializeInc/materialize/issues/18261#issuecomment-1523346934

**Comment by andrewrodriguez-m** [comment] 2023-05-03 15:52
I'd propose closing this. The underlying issue (#18261) seems like it can't be reproduced and there doesn't seem to be much alignment for other knobs beyond max_connections

**Comment by mjibson** [comment] 2023-05-03 17:17
Concur!

**Closed by mjibson** 2023-05-03 17:17 UTC
Labels: A-ADAPTER
