### ISSUE TITLE
all nodes panic when a whole-cluster restart is attempted 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12233] opened 2022-05-03 18:18 UTC
### What version of Materialize are you using?

v0.26.1-dev

### How did you install Materialize?

Docker image

### What was the issue?

If an entire multi-node cluster goes down , it can not be restarted because all the nodes will panic upon restart.

This does not seem to affect single-node clusters, those can be brought down and restarted without a problem.

**Comment by philip-stoev** [comment] 2022-05-03 18:28
Test case:

```
# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

import time

from pathlib import Path

from materialize import spawn
from materialize.mzcompose import Composition
from materialize.mzcompose.services import (
    Computed,
    Materialized,
    Testdrive
)

SERVICES = [
    Computed(
        name="computed_1_1",
        options="--workers 2 --processes 2 --process 0 computed_1_1:2102 computed_1_2:2102 --storage-addr materialized:2101",
        ports=[2100, 2102],
    ),
    Computed(
        name="computed_1_2",
        options="--workers 2 --processes 2 --process 1 computed_1_1:2102 computed_1_2:2102 --storage-addr materialized:2101",
        ports=[2100, 2102],
    ),
    Materialized(extra_ports=[2101]),
    Testdrive(
        volumes=[
            "mzdata:/share/mzdata",
            "tmp:/share/tmp",
        ],
        no_reset = True
    ),
]


def workflow_default(c: Composition) -> None:
    c.up("testdrive", persistent = True)
    c.up("materialized")
    c.wait_for_materialized(service="materialized")

    for id in ["1_1", "1_2"]:
        c.up(f"computed_{id}")

    c.sql(
        "CREATE CLUSTER cluster1 REMOTE replica1 ('computed_1_1:2100', 'computed_1_2:2100');"
    )

    c.testdrive(input = """
> SET cluster=cluster1

> CREATE TABLE panic_table (f1 TEXT)

> CREATE TABLE other_table (f1 TEXT)

> CREATE MATERIALIZED VIEW panic_view AS SELECT mz_internal.mz_panic(f1) FROM panic_table;

> INSERT INTO panic_table VALUES ('panic!');

> INSERT INTO other_table VALUES ('other1');

> SET cluster=default

> SELECT * FROM other_table
other1

> DROP VIEW panic_view

> INSERT INTO other_table VALUES ('other2');
"""
)

    time.sleep(10)

    for id in ["1_1", "1_2"]:
        c.up(f"computed_{id}")

    c.testdrive(input = """
> SET cluster = cluster1

> INSERT INTO other_table VALUES ('other3');


> SELECT * FROM other_table
other1
other2
other3
""")
```

**Comment by umanwizard** [comment] 2022-05-04 18:18
Philip and I were not able to reproduce this (neither was Moritz). He thinks he may have simplified the test case too much. Assigning back to Philip to take a further look.

**Comment by umanwizard** [comment] 2022-05-05 01:13
I can now reproduce by running the script in a loop.

Here is what I _suspect_ is happening, but haven't confirmed yet:

1. The compute process crashes when evaluating `panic_view` (as expected)
2.  `materialized` doesn't yet realize it has gone down and continues sending messages to it
3. The new compute process comes up and receives the messages sent in step 2.
4. Since the new compute process was expecting a startup message, but received some random message instead, it crashes.
5. No new process is ever brought up, because the test script is hardcoded to only launch them twice.

If this is all true, it would mean that this bug can't reproduce in cloud, because Kubernetes will keep re-launching the process until it eventually succeeds in the initial connection handshake and has the full set of commands streamed back at it.

@antiguru , @frankmcsherry -- based on your understanding of how the client works, does this seem like it could happen?

**Comment by umanwizard** [comment] 2022-05-05 01:17
Relevant logs from the second time the compute process is started:

```
2022-05-05T01:14:34.447333Z  INFO computed: about to bind to "0.0.0.0:2100"
2022-05-05T01:14:34.447415Z TRACE mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE    
2022-05-05T01:14:34.447437Z  INFO computed: listening for coordinator connection on 0.0.0.0:2100...
2022-05-05T01:14:34.447451Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "materialized:2101"   
2022-05-05T01:14:34.448177Z TRACE mio::poll: registering event source with poller: token=Token(2), interests=READABLE | WRITABLE    
2022-05-05T01:14:34.448235Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server                       
2022-05-05T01:14:34.448321Z DEBUG mz_storage::boundary::tcp_boundary::client: client: connected to server
worker 0:       connection from worker 1                                                                                                                                           worker 0:       initialization complete                                                                                                                                            2022-05-05T01:14:35.292412Z TRACE mio::poll: registering event source with poller: token=Token(3), interests=READABLE | WRITABLE    
2022-05-05T01:14:35.292445Z  INFO computed: coordinator connection accepted
2022-05-05T01:14:35.871586Z TRACE tokio_util::codec::framed_impl: attempting to decode a frame                        
2022-05-05T01:14:35.871614Z TRACE tokio_util::codec::framed_impl: frame decoded from buffer
2022-05-05T01:14:35.871715Z TRACE mz_dataflow_types::client: SEND dataflow command: CreateDataflows([DataflowDescription { source_imports: {User(2): SourceInstanceDesc { descripti
on: SourceDesc { connector: Local { timeline: EpochMilliseconds }, desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: true }], keys: [] }, names: [ColumnName("f1")] } }, arguments: SourceInstanceArguments { operators: Some(LinearOperator { predicates: [], projection: [0] }) } }}, index_imports: {}, objects_to_build: [BuildDesc { id: Transient(9), plan: Get { id: Global(User(2)), keys: AvailableCollections { raw: true, arranged: [] }, plan: PassArrangements } }, BuildDesc { id: Transient(10), plan: ArrangeBy { input: Get { id: Global(Transient(9)), keys: AvailableCollections { raw: true, arranged: [] }, plan: PassArrangements }, forms: AvailableCollections { $
aw: true, arranged: [([Column(0)], {0: 0}, [])] }, input_key: None, input_mfp: MapFilterProject { expressions: [], predicates: [], projection: [0], input_arity: 1 } } }], index_exports: {Transient(10): (IndexDesc { on_id: Transient(9), key: [Column(0)] }, RelationType { column_types: [ColumnType { scalar_type: String, nullable: true }], keys: [] })}, sink_exports: {}, as_of: Some(Antichain { elements: [1651713275791] }), debug_name: "temp-view-t9", id: 6cc2db71-cb21-41b5-b106-425e9b3d235a }])
2022-05-05T01:14:35.871869Z TRACE tokio_util::codec::framed_impl: attempting to decode a frame                       
2022-05-05T01:14:35.871879Z TRACE tokio_util::codec::framed_impl: attempting to decode a frame                            
2022-05-05T01:14:35.871881Z TRACE tokio_util::codec::framed_impl: frame decoded from buffer                        
thread 'thread 'timely:work-0timely:work-1' panicked at '' panicked at 'called `Option::unwrap()` on a `None` valuecalled `Option::unwrap()` on a `None` value', ', /home/ubuntu/materialize/src/compute/src/server.rs/home/ubuntu/materialize/src/compute/src/server.rs::212212::4141
```

**Comment by frankmcsherry** [comment] 2022-05-05 02:05
Hrm. I think it wasn't the case that this could happen, though it relied on some single-threadedness that maybe changed. Or maybe it was wrong to begin. A connection reset would be returned as an error along the compute receive path, and that would result in the very next send being a `CreateInstance` command, which relied on all the `async` calls not being concurrent (which I think they shouldn't be, on account of there isn't shared ownership of any of the parts).

But .. I wouldn't stand behind any of this thinking if reality disagrees with it.

**Comment by umanwizard** [comment] 2022-05-05 02:18
It seems clear that the process is receiving something other than CreateInstance as its first command, and that that is what’s causing the crash.

I’m less confident about the rest of my explanation, and will dig in further tomorrow.

**Comment by umanwizard** [comment] 2022-05-05 06:19
Reopening until we can verify that #12269 fixed this.

**Comment by antiguru** [comment] 2022-05-05 16:58
Here's a `mzcompose.py` that surfaces the error reliably for me: https://gist.github.com/antiguru/b6f4912b89bc4287d945e885c6a53518

We concluded that the problem most likely comes from not bubbling up the connection error to the right layers. The partitioned client expects `parts` errors before it'll pass one along, and somehow this logic doesn't work as expected. Later, we don't rehydrate the newly connected instance because the replicated client doesn't get to see the error. Reading the code this shouldn't happen, but it's easy to miss parts and then async code doesn't make it simpler. I think we need to spend more time on analyzing the issue to determine where we're dropping the error, and come up with a plan on how to fix it.

Ideally, a fix would remove the hack of only passing through every `parts` error. If we determine that it's a simple change to fix this issue, let's do it, but we might want to revisit how we can ensure that we correctly reconnect partitioned clients, not only relying on their shared-fate architecture but actually enforcing it at the controller.

**Comment by umanwizard** [comment] 2022-05-09 14:19
Here is a concrete description of (at least one of) the ways this can surface:

1. `computed` process 1 begins panicking, and the controller's connection to it is torn down. This causes the corresponding `TcpClient` to begin trying to reconnect.
2. Process 1's TCP listener is still alive (the process has not totally terminated yet), and it accepts a new connection. When the corresponding `TcpClient` successfully establishes its connection, it returns an error up to `Partitioned`.
3. Process 1 fully terminates; this causes the zombie connection opened in step 2 to break. A second error is returned up to `Partitioned`. Since it has seen two errors, it will return an error back up to the `ActiveReplication` client, even though neither of the errors it has seen is from process 2!
4. The `ActiveReplication` client starts trying to re-hydrate the replica. A few messages get fanned out to the still-alive first incarnation of process 2 and to the dead connection for process 1 (where they just get eaten).
5. Process 2 notices that the process 1 it was connected to has crashed, and it crashes too. Assume this time the timing works out such that there is no zombie connection, and only one error gets reported, which `Partitioned` just stashes.
6. Regardless of which process gets restarted first, the `TcpClient` will happily restart its connection to it, and everything upstream of that will assume the replica is still fine, and continue sending commands at it, causing it not to receive `CreateInstance` as its first command.

**Comment by umanwizard** [comment] 2022-05-09 14:37
We could fix this particular manifestation of the issue by closing the TCP listener until we actually need to establish a new connection; i.e., the controller has gone away. But that strikes me as a bit fragile.

The fundamental problem is that different shards of the `Partitioned` client are communicating with different incarnations of the timely cluster, but the controller has no way of knowing that, and thinks they are all part of the same replica. A robust solution could involve the controller tracking which incarnation it thinks it's communicating with -- if a `computed` process ever receives one different from what it was first started with, it would ignore it if it's too low (I'm not sure how this can happen), or kill itself if too high.

**Comment by philip-stoev** [comment] 2022-05-09 16:26
Better tracking of who is who in the entire Mz instance may also help out with #11511

**Comment by umanwizard** [comment] 2022-05-16 23:11
The script @antiguru uploaded (with some modifications to conform to the current CREATE CLUSTER syntax) still fails, even after #12457 and #12479 have landed. However, I contend that that's not a bug, since our logic relies on periodically backing off when the connection quickly crashes after reconnect, in order to converge to a good state. But the script in question only attempts to reconnect once.

I would say this bug should remain open if we're not able to converge to a good replica when we _repeatedly_ restart it on crash (as Kubernetes will do).

Let's discuss in the planning tomorrow @antiguru and @philip-stoev if you guys are available.

**Comment by umanwizard** [comment] 2022-05-17 00:57
OK, after #12485 lands, I think we are ready to start testing this again.

**Comment by umanwizard** [comment] 2022-05-17 01:13
(But not exactly with the script Moritz posted -- let's discuss tomorrow)

**Comment by philip-stoev** [comment] 2022-05-17 11:34
As I am not going to be able to attend the meeting today I wanted to make my case in writing against relying on repeated restarts by Kubernetes until the cluster comes back up fully.

- Kubernetes may indeed attempt to restart nodes repeatedly, but it is not guaranteed that it will be configured to do so forever. We may for some other reason restrict the number of consequtive restarts before a pod is declared as broken, which in turn will cause issues with any "let Kubernetes restart until it works" approach
- There could be potentially unbounded downtime until Kubernetes restarts things enough times to get them up and running. Kubernetes may do repeated waves of thundering-herd restarts which needs to be accounted for
- Monitoring and logging will become further clogged by repeated panics that will have to somehow be disregarded as false positives
- Upgrade in production on the cloud would become even more complex to script than it is currently envisioned if every individual restart may in fact be a sequence of restarts. Extra downtime will be incurred while the infrastructure waits for the new-version clusters to stabilize or not before deciding to take corrective action (rolling back to the old version, again with a sequence of restarts). 
- Testing will become more difficult as all chaos testing scripts will need to be coded to restart repeatedly. This in turn may mask other issues that are not expected and that we would be interested in fixing.

**Comment by lluki** [comment] 2022-06-02 15:41
I just ran into this issue again. I have another way of reproducing it (quite reliably, at least on my setup) here: #12843

**Closed** 2022-07-04 17:55 UTC
Labels: C-bug, M-platform-blocker

**Comment by philip-stoev** [comment] 2022-08-19 11:37
> As I am not going to be able to attend the meeting today I wanted to make my case in writing against relying on repeated restarts by Kubernetes until the cluster comes back up fully.
> 
> * Kubernetes may indeed attempt to restart nodes repeatedly, but it is not guaranteed that it will be configured to do so forever. We may for some other reason restrict the number of consequtive restarts before a pod is declared as broken, which in turn will cause issues with any "let Kubernetes restart until it works" approach
> * There could be potentially unbounded downtime until Kubernetes restarts things enough times to get them up and running. Kubernetes may do repeated waves of thundering-herd restarts which needs to be accounted for
> * Monitoring and logging will become further clogged by repeated panics that will have to somehow be disregarded as false positives
> * Upgrade in production on the cloud would become even more complex to script than it is currently envisioned if every individual restart may in fact be a sequence of restarts. Extra downtime will be incurred while the infrastructure waits for the new-version clusters to stabilize or not before deciding to take corrective action (rolling back to the old version, again with a sequence of restarts).
> * Testing will become more difficult as all chaos testing scripts will need to be coded to restart repeatedly. This in turn may mask other issues that are not expected and that we would be interested in fixing.

Turns out my assessment was optimistic. In practice, K8s is never able to bring the things back up . See:

- https://github.com/MaterializeInc/materialize/issues/14301
