### ISSUE TITLE
Support Debezium's schema format for JSON records

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#5231] opened 2021-01-07 20:46 UTC
Debezium is [willing to emit JSON](https://debezium.io/documentation/reference/configuration/avro.html) (instead of Avro) data into Kafka, using the same schema format. 

We do not currently have a way to use Debezium Schemas to populate a table in the way that we do for Avro data.

**Comment by benesch** [comment] 2022-03-04 22:45
Retroactive dupe of #6377.

**Closed by benesch** 2022-03-04 22:45 UTC
Labels: C-feature
