### ISSUE TITLE
internal error: Non-positive multiplicity in DistinctBy

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18657] opened 2023-04-07 11:32 UTC
Also seeing this new failure:
```
--- [SQLsmith] Error XX000: ERROR:  Evaluation error: internal error: Non-positive multiplicity in DistinctBy
 (3 occurences)
From 11:58:33 until 12:29:49
Query: select  
  subq_0."c0" as c0
from 
  (select  
        (select "table_schema" from information_schema.tables limit 1 offset 2)
           as c0, 
        ref_0."import_id" as c1
      from 
        mz_internal.mz_compute_dependencies_per_worker as ref_0
      where true) as subq_0
where (select pg_catalog.jsonb_agg("port") from mz_internal.mz_dataflow_operator_reachability_per_worker)
     <> (select "details" from mz_internal.mz_sink_statuses limit 1 offset 4)
    ;
```
As usual, can't reproduce.

_Originally posted by @def- in https://github.com/MaterializeInc/materialize/issues/17874#issuecomment-1497813204_

**Comment by tokenrove** [comment] 2023-04-10 11:20
Looks to be another case of #18296.  (`mz_dataflow_operator_reachability_per_worker` selects from `_raw`)

**Comment by teskje** [comment] 2023-07-17 11:03
Closing as duplicate of #20405.

**Closed by teskje** 2023-07-17 11:03 UTC
Labels: C-bug
