### ISSUE TITLE
NULL literal is assumed to be of type TEXT in UNION branches

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5948] opened 2021-03-02 13:08 UTC
### What version of Materialize are you using?

```
v0.7.1-dev (3dda2520e)
```

### What was the issue?

if there is a stand-alone ```NULL``` literal in a ```UNION``` branch, it is assumed to have a type of text. This means that it can not be matched together with e.g. integers coming from another branch of the UNION.

This issue prevents a dbt user from running the default examples against Materialize. The example uses literal ```NULL``` values in order to avoid accessing an actual table.

### Is the issue reproducible? If so, please provide reproduction instructions.
```
materialize=> select null union all select 1;
ERROR:  UNION types text and integer cannot be matched
```

contrast with a non-union use of ```NULL```:

```
materialize=> select pg_typeof(null);
 pg_typeof 
-----------
 unknown
(1 row)
```

contrast with postgresql:
```pstoev=# select null union all select 1;
 ?column? 
----------
         
        1
(2 rows)
```

**Comment by JLDLaughlin** [comment] 2021-03-02 15:04
Added note: @philip-stoev found this test running the dbt starter project (not our project/demo) with Materialize. The error is in `./models/example/my_first_dbt_model.sql`.

Thanks, Philip!

**Comment by benesch** [comment] 2021-03-18 21:03
Duplicate of #3331. Unfortunately this is hard to fix.

**Closed by benesch** 2021-03-18 21:03 UTC
Labels: C-bug
