### ISSUE TITLE
[SQLancer] Temporary tables are missing in information_schema.tables and \dt

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17797] opened 2023-02-23 13:33 UTC
### What version of Materialize are you using?

v0.45.0-dev (f01773cb1)

### How did you install Materialize?

Built from source

### What is the issue?

```
database96=> CREATE TEMP TABLE IF NOT EXISTS t0(c0 VARCHAR(301) );
CREATE TABLE
database96=> CREATE TABLE IF NOT EXISTS t1(c0 VARCHAR(301) );
CREATE TABLE
database96=> SELECT table_name, table_schema, table_type, 1 as is_insertable_into FROM information_schema.tables WHERE table_schema='public' OR table_schema LIKE 'pg_temp_%' ORDER BY table_name;
 table_name | table_schema | table_type | is_insertable_into
------------+--------------+------------+--------------------
 t1         | public       | BASE TABLE |                  1
(1 row)
```
meanwhile on postgres:
```
deen=> SELECT table_name, table_schema, table_type, 1 as is_insertable_into FROM information_schema.tables WHERE table_schema='public' OR table_schema LIKE 'pg_temp_%' ORDER BY table_name;
 table_name | table_schema |   table_type    | is_insertable_into
------------+--------------+-----------------+--------------------
 t0         | pg_temp_3    | LOCAL TEMPORARY |                  1
 t1         | public       | BASE TABLE      |                  1
(2 rows)
```

Same in `\dt`:
```
                      List of relations
   Schema   |              Name              | Type  | Owner
------------+--------------------------------+-------+-------
[...]
 public     | t1                             | table |
(29 rows)
```
And postgres:
```
deen=> \dt
        List of relations
  Schema   | Name | Type  | Owner
-----------+------+-------+-------
 pg_temp_3 | t0   | table | deen
 public    | t1   | table | deen
(2 rows)
```
I'll try using `mz_tables` as a replacement for now. Edit: Also missing there:
```
database96=> select * from mz_tables join mz_schemas on mz_tables.schema_id = mz_schemas.id join mz_databases on mz_schemas.database_id = mz_databases.id where mz_databases.name = 'database96';
  id  |  oid  | schema_id | name | id  |  oid  | database_id |  name  | id  |  oid  |    name
------+-------+-----------+------+-----+-------+-------------+--------+-----+-------+------------
 u592 | 21496 | 110       | t1   | 110 | 21489 | 106         | public | 106 | 21488 | database96
(1 row)
```

Noticed when checking why SQLancer keeps creating same temp tables again and again.

**Comment by jkosh44** [comment] 2023-02-23 13:51
This is partially a duplicate of the following issues:
- https://github.com/MaterializeInc/materialize/issues/8805
- https://github.com/MaterializeInc/materialize/issues/4284

I put a list of what needs to be done to achieve this in #8805.

@def- I'll leave it up to you if you want to leave this open or close it as a dup.

**Closed** 2023-02-23 14:20 UTC
Labels: C-bug
