### ISSUE TITLE
CREATE SINK can produce consistency errors and incorrect audit events by creating and dropping temporary sinks

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#17014] opened 2023-01-06 21:08 UTC
There are a number of sub-issues stemming from the fact that `CREATE SINK` creates and drops a temporary sink in the creation process.

More details on the process:
> Sink creation involves two steps
> 1. Create a placeholder sink in the catalog and `mz_sinks` and start an asynchronous task to connect to the sink.
> 2. Once the async task is complete 
> (a) Remove the pending sink from the catalog and `mz_sinks`.
> (b) If the connection was successful add a new entry into the catalog and `mz_sinks`.

Issues this can cause:
**We emit audit log events for temporary sinks, so there's an extra `create` and `drop` record in the audit events.**
For a valid sink, the audit events look like TBD

For an invalid attempt at creating a sink e.g.
```
materialize=> CREATE SINK avro_sink
  FROM t
  INTO KAFKA CONNECTION kafka_connection (TOPIC 'test_avro_topic')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_ssl
  ENVELOPE DEBEZIUM
  WITH (SIZE = '1');
ERROR:  creating admin client failed: Client creation error: ssl.certificate.pem failed: not in PEM format?: error:0909006C:PEM routines:get_name:no start line: Expecting: CERTIFICATE
```
The audit events still look like
```
 event_type | object_type |                                               details                                                
------------+-------------+------------------------------------------------------------------------------------------------------
 create     | sink        | {"database":"materialize","id":"u10","item":"avro_sink","schema":"public","size":"1","type":"kafka"}
 drop       | sink         | {"database":"materialize","id":"u10","item":"avro_sink","schema":"public"}
```
SHOW CREATE SINK returns no results for this scenario
```
materialize=> SHOW CREATE SINK avro_sink;
ERROR:  unknown catalog item 'avro_sink'
```

**We can produce a consistency error where a sink is deleted from `mz_sinks` but not the in-memory catalog.**
In this scenario, a sink was created. There's no record in `mz_sinks`, but `SHOW CREATE SINK json_sink` returns the sink's DDL statement.
One guess is that step 2 of the sink creation process above failed, so the sink doesn't exist and it was removed from `mz_sinks` but we never remove it from the in memory catalog.
Another is that the step 2 succeed, but for some reason the re-created sink in step 2 wasn't written back into `mz_sinks` only the in-memory catalog.

**Comment by benesch** [comment] 2023-01-10 06:26
@RobinClowers noted on Slack that leaving a broken sink for a while (possibly through an environmentd restart) tends to surface this bug.

**Comment by benesch** [comment] 2023-03-29 04:07
I have a theory, from watching #18438, about how this happens. Suppose you create a sink that's valid except that the password is wrong. I think it's nondeterministic whether `CREATE SINK` fails, because librdkafka returns errors asynchronously and it's impossible to know whether a connection has been successfully established, or whether the connection is failing but librdkafka just hasn't told you yet.

I think sometimes we get unlucky and skate through the `CREATE SINK` validation, only to experience the error when we go to actually create the topic for the sink. I think that triggers a code path that is not particularly well tested, and might produce the inconsistencies observed here.

**Comment by benesch** [comment] 2023-05-28 05:53
Well, this just gets weirder and weirder. A few more discoveries:

* _On restart_ we do the temporary sink dance, and so the audit event log always contains some spurious `create`/`drop` events for every sink.
* `SHOW SINKS` doesn't show the sink until the sink is successfully created. _After restart_, if a sink fails to create, this leaves you in a very weird situation. The sink won't appear in `mz_sinks`. `SHOW SINKS` won't tell you about it. But it's in `mz_object_dependencies`, and `DROP SINK` will let you drop the sink.
* All this is doubly confusing because `mz_audit_events` has spurious create/drop events for the sink.

Here's a reproduction for the above:

  * In terminal 1, run `bin/environmentd`.
  * In terminal 2, start Kafka and the CSR: `confluent local services schema-registry start`
  * In terminal 3, run testdrive to get some sinks: `cargo run --bin testdrive -- test/testdrive/kafka-avro-upsert-sinks.td`. You can Ctrl-C this script as soon as `upsert_input_sink` is created.
  * In terminal 2, kill Kafka and the CSR: `confluent destroy`.
  * In terminal 1, Ctrl-C and restart `bin/environmentd`.
  * In terminal 3, `psql` in to the environment and run `SHOW SINKS`. Notice that `upsert_input_sink` isn't there... but if you run `DROP SINK upsert_input_sink` that succeeds.

**Comment by benesch** [comment] 2023-05-28 05:55
@chaas we may want to bump this up in priority.

**Comment by benesch** [comment] 2024-01-28 01:11
Fixed by https://github.com/MaterializeInc/materialize/pull/21852.

**Closed by benesch** 2024-01-28 01:11 UTC
Labels: C-bug, A-ADAPTER
