### ISSUE TITLE
"cluster tests 2" is flaky

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25207] opened 2024-02-13 18:16 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/75567#018da334-d55b-4e4d-9adb-742505c4954f

### Relevant log output

```source
_bk;t=1707840268304==> mzcompose: test case test-compute-controller-metrics failed: <class 'AssertionError'>: got 0.0
_bk;t=1707840268305Traceback (most recent call last):
_bk;t=1707840268305  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-04287e58adecb6ad2-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 541, in test_case
_bk;t=1707840268305    yield
_bk;t=1707840268305  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-04287e58adecb6ad2-1/materialize/tests/test/cluster/mzcompose.py", line 79, in workflow_default
_bk;t=1707840268305    c.workflow(name)
_bk;t=1707840268305  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-04287e58adecb6ad2-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 434, in workflow
_bk;t=1707840268305    func(self)
_bk;t=1707840268305  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-04287e58adecb6ad2-1/materialize/tests/test/cluster/mzcompose.py", line 2484, in workflow_test_compute_controller_metrics
_bk;t=1707840268305    assert count == 1, f"got {count}"
_bk;t=1707840268305           ^^^^^^^^^^
_bk;t=1707840268305AssertionError: got 0.0
```

**Comment by nrainer-materialize** [comment] 2024-02-13 19:14
This seems to have been a temporary problem.

**Comment by teskje** [comment] 2024-02-14 09:52
Closing as a duplicate of https://github.com/MaterializeInc/materialize/issues/25214.

**Closed by teskje** 2024-02-14 09:52 UTC
Labels: C-bug, ci-flake
