### ISSUE TITLE
Fix flaky tests introduced by 87495221ccf6b242b07a247f244c3c06be2c04c7

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#12786] opened 2022-05-31 18:35 UTC
### What version of Materialize are you using?

0.26.2

### How did you install Materialize?

Built from source

### What is the issue?

Since merging 87495221ccf6b242b07a247f244c3c06be2c04c7, many unit tests have become flaky and have been ignored so PRs aren't blocked in CI. This is a tracking issue to track which tests have been ignored, and attempt to fix them.

- [ ] [`materialized.tests.sql::test_no_block`](https://github.com/MaterializeInc/materialize/blob/f298ffc37dcf01731c6a2537eb888abcd683ad65/src/materialized/tests/sql.rs#L40-L114)
- [ ] [`materialized.tests.sql::test_tail_progress`](https://github.com/MaterializeInc/materialize/blob/f298ffc37dcf01731c6a2537eb888abcd683ad65/src/materialized/tests/sql.rs#L349-L432)
- [ ] [`materialized.tests.sql::test_tail_progress_non_nullable_columns`](https://github.com/MaterializeInc/materialize/blob/f298ffc37dcf01731c6a2537eb888abcd683ad65/src/materialized/tests/sql.rs#L434-L482)
- [ ] [`materialized.tests.pgwire::test_pgtest`](https://github.com/MaterializeInc/materialize/blob/2bd7fe34fe05f3579238133112b46732da546b5b/src/materialized/tests/pgwire.rs#L484-L491)
- [ ] [`materialized.tests.pgwire::test_pgtest_mz`](https://github.com/MaterializeInc/materialize/blob/2bd7fe34fe05f3579238133112b46732da546b5b/src/materialized/tests/pgwire.rs#L493-L501)

**Comment by jkosh44** [comment] 2022-06-01 13:21
Whenever `test_pgtest` and `test_pgtest_mz` fail, they consistently fail with 
> ```thread 'test_pgtest_mz' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11): waiting for ReadyForQuery, saw []```

This comes from the `until` method here: https://github.com/MaterializeInc/materialize/blob/bfe8aa7a49951047b386b8f6416ce981943cca92/src/pgtest/src/lib.rs#L145-L147 which calls `recv` here: https://github.com/MaterializeInc/materialize/blob/bfe8aa7a49951047b386b8f6416ce981943cca92/src/pgtest/src/lib.rs#L309-L330.

`recv`'s failure points are:
1. Failing to parse a message.
2. Failing to read from a `TCPStream`.
The error message does not indicate that a parsing failed, so the more likely reason is reading from the stream failed. Also I submitted some PRs with print statements injected into each failure point, and it was always the stream reading that failed.

If a read timeout is set on the TCP stream, then a `WouldBlock` error is returned if the read times out (https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout). We set the read timeout here: https://github.com/MaterializeInc/materialize/blob/bfe8aa7a49951047b386b8f6416ce981943cca92/src/pgtest/src/lib.rs#L120

On almost all systems `EWOULDBLOCK` is the same error as `EAGAIN` (https://man7.org/linux/man-pages/man3/errno.3.html). The number value for them is 11 (https://chromium.googlesource.com/chromiumos/docs/+/master/constants/errnos.md) which is why we are getting an OS error 11.

I'm not sure why 87495221ccf6b242b07a247f244c3c06be2c04c7 would cause the reads to start timing out all of a sudden. Some possibilities are:
- We've introduced a deadlock somewhere.
- There is increase stress and contention in the system, cause reads to take longer.

The read timeout is already set at 5 seconds (https://github.com/MaterializeInc/materialize/blob/bfe8aa7a49951047b386b8f6416ce981943cca92/src/pgtest/src/main.rs#L25-L33) which is pretty high, and when I changed it to 15 seconds that didn't help either.

**Comment by jkosh44** [comment] 2022-06-02 14:15
I've never gotten any actual failures from `materialized.tests.sql::test_tail_progress` or `materialized.tests.sql::test_tail_progress_non_nullable_columns`. `materialized.test.sql` was timing out on CI and leaving behind no logs. After a lot of iteration of ignoring different tests, it seemed to be originating from these two tests. However, I was never able to confirm this 100%.

**Comment by jkosh44** [comment] 2022-06-02 19:09
I have not been able to reproduce any of these failures locally or reproduce the failures on aws machines with `bin/mzcompose --find cargo-test run default`

**Comment by benesch** [comment] 2022-06-05 02:52
I also can't reproduce them when I SSH into a CI machine. So suspicious...

**Comment by benesch** [comment] 2022-06-05 04:15
On a hunch I swapped the Cargo tests from using SQLite as the persist/catalog backend to PostgreSQL. We were seeing hangs in CI before when using the SQLite backend—and swapped it for the PostgreSQL backend to fix those hangs. But we only did that for the mzcompose-based test suite, not the Cargo tests. I'm still baffled as to why this doesn't reproduce outside CI, but we want to get rid of the SQLite based implementations anyway, so I'm happy enough with this fix.

#12888 passed CI twice on a commit that failed linting. I pushed up a lint fix and marked for automerge. I figure if it passes cargo test three times in a row it's probably good.

**Comment by benesch** [comment] 2022-06-05 04:47
Fixed by #12888.

**Closed by benesch** 2022-06-05 04:47 UTC
Labels: C-bug
