### ISSUE TITLE
persist: unexpectedly high seqnos_held

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#15937] opened 2022-11-07 18:34 UTC
### What version of Materialize are you using?

v0.30.1

### How did you install Materialize?

Materialize Cloud

### What is the issue?

We expect `seqnos_held` to temporarily spike while reading in a big snapshot, but otherwise stay relatively small and flat (for some definition of small and flat). Instead, we're seeing it increase linearly, only resetting when we restart everything each week during the deploy. I increased the topk in the persist graphs to numbers for K much larger than 5 and, for every version of that query that loaded, it seems we had at least that many shards doing the bad thing. So it's possible this is affecting many or most shards in production.

Side note: It's very encouraging that things seem to be working even with such large seqno holds! We did that on purpose, but it would have been easy for something small to go wrong and mess it up. A seqno hold really just means extra data in CRDB (that isn't being read) and a delay to when we can delete data in s3 (also not being read). There is also a larger set of rollups kept in the current version of state, but it seems whatever growth on this within a week that we're seeing in practice (before all leases and thus seqno holds are cleared) is covered by "computers are fast".

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/52528/200387914-d1836779-cc3a-40d3-a006-3e1f370c7728.png">

**Comment by danhhz** [comment] 2022-11-07 18:38
Duration normal operation (not replaying a snapshot), seqno holds should advance as part of downgrade_since. If we are replaying a snapshot, ReadHandle is allowed to manually specify a seqno hold override. The bug likely falls into one or the other of these. I took a quick read of the code and nothing jumped out at me. The latter is far more complex (and we seem to see this repro pretty readily in prod), so I tried adding some debugging statements to the code the computes the seqno hold override and tried spinning it up locally. So far, haven't gotten a repro though.

**Comment by danhhz** [comment] 2022-11-07 20:31
Okay looked at the code a bit more. The handling of zero readers looks correct (defaults to the latest seqno). The only place we update the per-reader seqno hold is in downgrade_since (when `outstanding_seqno` is None). Notably, it's _not_ updated in heartbeat_reader (which, I can see why that's the case, but seems like a pretty big footgun)

So one possibility here is that there are ReadHandles that are only ever getting `heartbeat_reader` calls but not `downgrade_since`. We have a per-shard since metrics, so should be possible to check that.

**Comment by danhhz** [comment] 2022-11-07 20:34
I checked a shard that was ~400k seqnos behind (!) and the since was 5m ago, so that doesn't seem to be our problem (at least for this shard).

**Comment by danhhz** [comment] 2022-11-09 17:18
the debugging info has made it out to canaries, including seth's which exhibits this bug. it's... not showing up in the logs and I don't yet know what to make of that.

**Comment by danhhz** [comment] 2022-11-15 18:53
possible this is related to https://github.com/MaterializeInc/materialize/issues/15952, I'm gonna see if the repro described in that issue results in an unexpected seqno hold

**Comment by danhhz** [comment] 2022-11-15 21:51
oh interesting! is triggering that one something like running a non-trivial SELECT?

**Comment by benesch** [comment] 2022-11-15 22:11
Yeah, I think `SELECT * FROM mz_views` would do it (or any other table that is unindexed in your cluster). At least, that would create a temporary dataflow that uses the `persist_source` and then immediately drops it. No idea if that is enough on its own, or you also need to be putting other load on the cluster to tickle the race, or something like that.

**Comment by danhhz** [comment] 2022-11-15 22:35
I tried running `select * from t CROSS JOIN t as t2` a bunch of times but didn't see the persist bug tickle. need to focus on other things today anyway, so figured I'd wait for official repro instructions before spending more time on this

**Comment by teskje** [comment] 2022-11-16 11:10
I don't think #15952 explains the seqno leak. I tried reproducing it by simply creating and dropping materialized views in a loop on my staging env for ~20 minutes:

```
$ while true
      psql "..." -c 'create materialized view mv as select * from t;'
      psql "..." -c 'drop materialized view mv;'
  end
```

 This is what the seqnos look like:

![Screen Shot 2022-11-16 at 12 00 55](https://user-images.githubusercontent.com/4521314/202163881-85db122a-3616-44fc-8a9d-d931ff955fd9.png)

You can see that the seqno count for the shard of table t goes up initially but then plateaus (I assume as readers get cleaned up). We might have a leak of persist tasks, but that only seems to be at the persist_sink side, which means we accumulate a lot of materialized view shards but each with a small seqno count. The task leak does not explain high seqno counts on individual shards.

**Comment by pH14** [comment] 2022-11-16 18:59
Found this interesting... in one seqno leak on an internal environment, we can see it tick up right after creating a new materialized view, and it starts to tick up a few hours after each `computed` restart it's running on:

<img width="1206" alt="Screen Shot 2022-11-16 at 1 54 54 PM" src="https://user-images.githubusercontent.com/785446/202268455-d8fda3a8-ebc0-45ae-8523-1b7544583b14.png">

<img width="1213" alt="Screen Shot 2022-11-16 at 1 55 02 PM" src="https://user-images.githubusercontent.com/785446/202268451-4dc5da42-7a06-4a28-865a-1ecc5c319954.png">

Note that the seqnos piling up are for the shard of the materialized view itself, not from the shard it's reading from.

**Comment by danhhz** [comment] 2022-12-19 21:22
Poked at this again today, spot checking a new instances found via the seqnos_held graph in the persist dash. The handful I checked all had a purpose that fell into two buckets:
- "reclocking <foo>" -> https://github.com/MaterializeInc/materialize/blob/ed7fbbd01090dd083ff2330c2fc7c7d798ab59d5/src/storage/src/source/reclock/compat.rs#L132-L158. in these cases, neither the seqno nor the since is advancing, which means the downgrade_since is not getting called at all. it's entirely internal to the Listen::next call being used here. these were indeed on environment 089 with the remap operator issues last week where futures were not being driven forward by timely due to an overloaded worker
- "persist_source data <foo>". interestingly I even found an instance where same <foo> was being used twice on the same cluster (I think this means being used as an input to two dataflows), where one of them was fine and the other the since advancing but seqno stuck (as discussed above in this issue). I suspect this is leaded batches not being returned to the persist_source stage 1 operator, but still seeing if I can find a smoking gun

**Comment by danhhz** [comment] 2023-01-30 19:32
just a note that this was mitigated a while ago by https://github.com/MaterializeInc/materialize/pull/16553, but I forgot to mention that here. we shouldn't really see customer impact beyond data sticking around in s3 longer than necessary (so now it's more of a billing/cost issue)

**Comment by philip-stoev** [comment] 2023-04-10 07:14
I was able to hit the `INFO` line twice in a row (attached) with the attached RQG grammar (also attached) running for several hours: 

```
perl gentest.pl --dsn1="dbi:Pg:service=materialize"--seed=time --threads=10 --grammar=gh15937.yy --queries=10000000000000  --duration=21600
```

As the RQG is not yet mzcompose-packaged, please get back to me if you need this reproduced again or a fix tested.

[gh18488.yy.zip](https://github.com/MaterializeInc/materialize/files/11188485/gh18488.yy.zip)
[gh18488.log.zip](https://github.com/MaterializeInc/materialize/files/11188486/gh18488.log.zip)

**Comment by bkirwi** [comment] 2023-12-12 20:11
Discussed this one with the team. Since this ticket was created, we've made long seqno holds much less consequential, and much more rare, though they still happen.

We don't think we'll get this totally to zero with our current leasing mechanism: there are too many ways for a lease to be held on to longer than expected. So this would only be resolved by getting rid of the time-based leasing mechanism, as in https://github.com/MaterializeInc/materialize/issues/15209. We'll track any further reader-lease troubles as part of that work.

**Closed by bkirwi** 2023-12-12 20:11 UTC
Labels: C-bug, A-stability, C-triage
