### ISSUE TITLE
storage/sources/kafka: don't ignore `NULL` values in Kafka source

### ISSUE THREAD

**Issue by aljoscha** [MaterializeInc/materialize#17491] opened 2023-02-02 16:41 UTC
Spun out from this comment: https://github.com/MaterializeInc/materialize/issues/16547#issuecomment-1396421260:

Porting over some thoughts from Slack about how to make FORMAT AVRO produce NULL in the face of NULL Kafka message payloads.

> The design I had in mind was ENVELOPE NOTFLAT (better name pending) where the source had exactly one nullable column named data (maybe a better name here too?). And the type of that column would be exactly the type of the top-level Avro type.
> 
> So to express ENVELOPE UPSERT in SQL, you’d use ENVELOPE NOTFLAT to get the right semantics for top-level NULLs, do your upsert logic using TRANSFORM USING, and then flatten out your record if desired by writing SELECT data.f1, data.f2, data.f3 etc.

In other words: I think the implicit default of ENVELOPE FLATTEN was a mistake, and that probably should have been behavior that you have to explicitly opt in to.

**Comment by aljoscha** [comment] 2023-02-02 16:42
@benesch I spun this out as a separate issue

**Comment by benesch** [comment] 2023-02-02 17:30
Awesome! @philip-stoev pointed out that the `NULL` suppression behavior seems to apply to `FORMAT BYTES` too. Probably all the other formats too. I had been incorrectly thinking that it only applied to `FORMAT AVRO`.

**Comment by benesch** [comment] 2024-04-29 17:51
Closing as a duplicate of #10114.

**Closed by benesch** 2024-04-29 17:51 UTC
Labels: C-feature, A-STORAGE
