### ISSUE TITLE
doc: How to Determine Source Status from System Tables 

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#9378] opened 2021-12-01 17:52 UTC
In 0.9.12, we introduced a new table in the system catalog named <code>mz_kafka_source_statistics</code> which replaced <code>mz_kafka_consumer_partitions</code>. It would be helpful to users to document how to determine source status given this change. An example query that uses <code>mz_metrics</code> is the following: <pre><code>with 
all_topics as (
    select s.id as source_id, s.name as source_name, i.source_name as topic
    from mz_sources s
    left join mz_source_info i on i.source_id = s.id
    where s.connector_type = 'kafka'
    group by s.id, s.name, i.source_name
),
max_offsets as (
    select time, labels->>'topic' as topic, labels->'partition_id' as partition, value as max_offset from mz_metrics m where m.metric = 'mz_kafka_partition_offset_max'
),
ingested_offsets as (
    select time, labels->>'topic' as topic, labels->'partition_id' as partition, value as ingested_offset from mz_metrics m where m.metric = 'mz_partition_offset_ingested'
),
latest_lags_by_partition as (
    select i.time, i.topic, i.partition, o.max_offset, i.ingested_offset, o.max_offset - i.ingested_offset as lag
    from max_offsets o
    inner join ingested_offsets i on i.time = o.time and i.topic = o.topic and i.partition = o.partition
    where i.time = (select max(time) from mz_metrics)
),
latest_lags_by_topic as (
    select topic, sum(lag) as lag
    from latest_lags_by_partition
    group by time, topic
),
all_topics_lags as (
    select a.source_id, a.source_name, a.topic, coalesce(l.lag, 100) as lag
    from all_topics a
    left join latest_lags_by_topic l on l.topic = a.topic
)
select * from all_topics_lags where lag >= 100 </code></pre>

**NOTE:** This may not be the most optimal or recommended query (and probably is not). It is best to check with engineering.

**Comment by morsapaes** [comment] 2022-06-05 10:18
Duplicate of #10013.

**Closed by morsapaes** 2022-06-05 10:18 UTC
Labels: A-docs
