### ISSUE TITLE
Debezium deduplication logic does not make sense with multiple partitions

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#6044] opened 2021-03-09 22:38 UTC
We attempt to detect duplicated records by discarding those where the observed binlog position goes backwards.

However, if the records are sharded across different partitions, we might read the (logically later) record from partition 2 before the (logically earlier) record from partition 1, and then think that the record we read later (that actually came from an earlier binlog position) is a duplicate.

**Comment by frankmcsherry** [comment] 2021-03-09 23:37
Some further notes here: I think we believe that if the records carry their part identifier into the deduplication logic, and that logic maintains disjoint state by part, then nothing is known to be fundamentally broken with deduplication. The issue is (afaict) that we may (will) smear together multiple parts into the same operator and have them share state.

**Comment by benesch** [comment] 2022-06-25 19:59
This got fixed by #10375.

**Closed by benesch** 2022-06-25 19:59 UTC
Labels: C-bug
