### ISSUE TITLE
mz_storage::storage_state: halting process: new ingestion with ID u28 does not match existing ingestion

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19917] opened 2023-06-13 17:54 UTC
### What version of Materialize are you using?

be3c5f293c41a978303b6449bbd6f3474d058901

### What is the issue?

Seen in cloudtest#3 here: https://buildkite.com/materialize/tests/builds/57551#0188b5c3-c383-4c4f-b615-02b05d213fcc
```
[97;1mdefault/cluster-u8-replica-11-0[clusterd][0m[97;1m: [0m2023-06-13T17:25:34.017380Z  WARN mz_storage::storage_state: halting process: new ingestion with ID u28 does not match existing ingestion:
[97;1mdefault/cluster-u1-replica-1-0[clusterd][0m[97;1m: [0m2023-06-13T17:25:34.018952Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(0), storage_sink_minimum_batch_updates: Some(1024), stats_audit_percent: Some(0), stats_collection_enabled: Some(false), stats_filter_enabled: Some(false), pubsub_client_enabled: Some(false), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
[97;1mdefault/cluster-u8-replica-11-0[clusterd][0m[97;1m: [0mIngestionDescription { desc: SourceDesc { connection: Postgres(PostgresSourceConnection { connection_id: User(25), connection: PostgresConnection { host: "postgres", port: 5432, database: "postgres", user: String("postgres"), password: Some(User(24)), tunnel: Ssh(SshTunnel { connection_id: User(23), connection: SshConnection { host: "ssh-bastion-host", port: 22, user: "mz", public_keys: None } }), tls_mode: Require, tls_root_cert: None, tls_identity: None }, table_casts: {1: [CallUnary { func: CastStringToInt32(CastStringToInt32), expr: Column(0) }]}, publication: "mz_source", publication_details: PostgresSourcePublicationDetails { tables: [PostgresTableDesc { oid: 16389, namespace: "public", name: "t1", columns: [PostgresColumnDesc { name: "f1", col_num: Some(1), type_oid: 23, type_mod: -1, nullable: true }], keys: {} }], slot: "materialize_c2906a5ad7c341178ac49fd82f178301" } }), encoding: Single(DataEncoding { force_nullable_columns: false, inner: RowCodec(RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] }) }), envelope: None(NoneEnvelope { key_envelope: None, key_arity: 0 }), metadata_columns: [], timestamp_interval: 1s }, source_imports: {}, ingestion_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: Some(ShardId(920215cb-afb7-4e72-8984-511be06b972b)), data_shard: ShardId(fee51a66-c953-4e7b-9d43-29763c539856), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] } }, source_exports: {User(26): SourceExport { output_index: 1, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: None, data_shard: ShardId(2acd6f17-6ba4-40e1-967f-3aa10f9a94b0), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: true }], keys: [] }, names: [ColumnName("f1")] } } }, User(28): SourceExport { output_index: 0, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: Some(ShardId(920215cb-afb7-4e72-8984-511be06b972b)), data_shard: ShardId(fee51a66-c953-4e7b-9d43-29763c539856), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] } } }}, instance_id: User(8), remap_collection_id: User(27) }
[97;1mdefault/cluster-u8-replica-11-0[clusterd][0m[97;1m: [0mvs
[97;1mdefault/cluster-u8-replica-11-0[clusterd][0m[97;1m: [0mIngestionDescription { desc: SourceDesc { connection: Postgres(PostgresSourceConnection { connection_id: User(25), connection: PostgresConnection { host: "postgres", port: 5432, database: "postgres", user: String("postgres"), password: Some(User(24)), tunnel: Ssh(SshTunnel { connection_id: User(23), connection: SshConnection { host: "ssh-bastion-host", port: 22, user: "mz", public_keys: Some(("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFG92synQxvIJKemyHabBpyduMYBgrksZ/C35ubdrCij materialize", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDnHrDTtQL0Y06ZaLo1gPlxw7ayu+sTLdM5C2s4YiUQ materialize")) } }), tls_mode: Require, tls_root_cert: None, tls_identity: None }, table_casts: {1: [CallUnary { func: CastStringToInt32(CastStringToInt32), expr: Column(0) }]}, publication: "mz_source", publication_details: PostgresSourcePublicationDetails { tables: [PostgresTableDesc { oid: 16389, namespace: "public", name: "t1", columns: [PostgresColumnDesc { name: "f1", col_num: Some(1), type_oid: 23, type_mod: -1, nullable: true }], keys: {} }], slot: "materialize_c2906a5ad7c341178ac49fd82f178301" } }), encoding: Single(DataEncoding { force_nullable_columns: false, inner: RowCodec(RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] }) }), envelope: None(NoneEnvelope { key_envelope: None, key_arity: 0 }), metadata_columns: [], timestamp_interval: 1s }, source_imports: {}, ingestion_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: Some(ShardId(920215cb-afb7-4e72-8984-511be06b972b)), data_shard: ShardId(fee51a66-c953-4e7b-9d43-29763c539856), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] } }, source_exports: {User(26): SourceExport { output_index: 1, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: None, data_shard: ShardId(2acd6f17-6ba4-40e1-967f-3aa10f9a94b0), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: true }], keys: [] }, names: [ColumnName("f1")] } } }, User(28): SourceExport { output_index: 0, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://root@cockroach.default:26257?options=--search_path=consensus" }, remap_shard: Some(ShardId(920215cb-afb7-4e72-8984-511be06b972b)), data_shard: ShardId(fee51a66-c953-4e7b-9d43-29763c539856), status_shard: Some(ShardId(1d78001f-2dad-4153-a5f5-ad5298cbbbc4)), relation_desc: RelationDesc { typ: RelationType { column_types: [], keys: [] }, names: [] } } }}, instance_id: User(8), remap_collection_id: User(27) }
[97;1mdefault/cluster-u8-replica-11-0[clusterd][0m[97;1m: [0m2023-06-13T17:25:34.017410Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(0), storage_sink_minimum_batch_updates: Some(1024), stats_audit_percent: Some(0), stats_collection_enabled: Some(false), stats_filter_enabled: Some(false), pubsub_client_enabled: Some(false), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
[97;1mdefault/postgres-5bfb4c4dc8-2mh5f[postgres][0m[97;1m: [0m2023-06-13 17:25:34.022 UTC [82] LOG:  could not receive data from client: Connection reset by peer
[97;1mdefault/environmentd-0[environmentd][0m[97;1m: [0m2023-06-13T17:25:34.022792Z  WARN mz_compute_client::controller::replica: replica task for 11 failed: status: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} }
[97;1mdefault/environmentd-0[environmentd][0m[97;1m: [0m2023-06-13T17:25:34.022957Z  WARN mz_storage_client::controller::rehydration: storage cluster produced error, reconnecting: status: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} }
[97;1mdefault/postgres-5bfb4c4dc8-2mh5f[postgres][0m[97;1m: [0m2023-06-13 17:25:34.029 UTC [83] LOG:  could not receive data from client: Connection reset by peer
[97;1mdefault/postgres-5bfb4c4dc8-2mh5f[postgres][0m[97;1m: [0m2023-06-13 17:25:34.029 UTC [83] STATEMENT:  START_REPLICATION SLOT "materialize_c2906a5ad7c341178ac49fd82f178301" LOGICAL 0/1559FB8 ("proto_version" '1', "publication_names" 'mz_source')
[97;1mdefault/postgres-5bfb4c4dc8-2mh5f[postgres][0m[97;1m: [0m2023-06-13 17:25:34.029 UTC [83] LOG:  unexpected EOF on standby connection
[97;1mdefault/postgres-5bfb4c4dc8-2mh5f[postgres][0m[97;1m: [0m2023-06-13 17:25:34.029 UTC [83] STATEMENT:  START_REPLICATION SLOT "materialize_c2906a5ad7c341178ac49fd82f178301" LOGICAL 0/1559FB8 ("proto_version" '1', "publication_names" 'mz_source')
```

This seems to happen in test_ssh_tunnels. @guswynn @benesch Any idea if this is a serious issue or something that we should ignore?

**Comment by aljoscha** [comment] 2023-06-14 09:18
@sploiselle could this be caused by recent changes in reconciliation, maybe related to the `ALTER SOURCE...` work?

**Comment by def-** [comment] 2023-06-14 09:30
We are not sure if this is a regression, @nrainer-materialize only recently added collecting the kubernetes logs and this has been sporadically happening since then.

**Comment by teskje** [comment] 2024-07-12 12:32
This warning message was removed in https://github.com/MaterializeInc/materialize/pull/19310, which I think is the `ALTER SOURCE` work Aljoscha referred to above. I don't think it's worth trying to figure out what caused a warning that stopped occurring a year ago, so closing this. (Lmk if I'm crazy and it's actually still occurring!)

**Closed by teskje** 2024-07-12 12:32 UTC
Labels: C-bug, A-storage, ci-flake, A-controller
