### ISSUE TITLE
ILIKE in data-flow rendering produces incorrect results when used with multiple-process replicas

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#26177] opened 2024-03-21 09:05 UTC
### What version of Materialize are you using?

2a498517db

### What is the issue?

Given the following setup

```
DROP TABLE IF EXISTS t_dfr_horiz;
CREATE TABLE t_dfr_horiz (row_index INT, int2_null INT2, int2_zero INT2, int2_one INT2, int2_max INT2, int2_neg_max INT2, int4_null INT4, int4_zero INT4, int4_one INT4, int4_max INT4, int4_neg_max INT4, int8_null INT8, int8_zero INT8, int8_one INT8, int8_max INT8, int8_neg_max INT8, uint2_null UINT2, uint2_zero UINT2, uint2_one UINT2, uint2_max UINT2, uint4_null UINT4, uint4_zero UINT4, uint4_one UINT4, uint4_max UINT4, uint8_null UINT8, uint8_zero UINT8, uint8_one UINT8, uint8_max UINT8, decimal_39_0_null DECIMAL(39), decimal_39_0_zero DECIMAL(39), decimal_39_0_one DECIMAL(39), decimal_39_0_max DECIMAL(39), decimal_39_0_neg_max DECIMAL(39), decimal_39_0_tiny DECIMAL(39), decimal_39_0_nan DECIMAL(39), decimal_39_8_null DECIMAL(39,8), decimal_39_8_zero DECIMAL(39,8), decimal_39_8_one DECIMAL(39,8), decimal_39_8_max DECIMAL(39,8), decimal_39_8_neg_max DECIMAL(39,8), decimal_39_8_tiny DECIMAL(39,8), decimal_39_8_nan DECIMAL(39,8), decimal_39_8_tiny2 DECIMAL(39,8), decimal_39_8_tiny3 DECIMAL(39,8), decimal_39_8_tiny4 DECIMAL(39,8), decimal_39_8_tiny5 DECIMAL(39,8), real_null REAL, real_zero REAL, real_one REAL, real_max REAL, real_neg_max REAL, real_tiny REAL, real_nan REAL, real_tiny2 REAL, real_tiny3 REAL, real_tiny4 REAL, real_tiny5 REAL, double_null DOUBLE, double_zero DOUBLE, double_one DOUBLE, double_max DOUBLE, double_neg_max DOUBLE, double_tiny DOUBLE, double_nan DOUBLE, double_tiny2 DOUBLE, double_tiny3 DOUBLE, double_tiny4 DOUBLE, double_tiny5 DOUBLE, bool_null BOOL, bool_true BOOL, bool_false BOOL, date_null DATE, date_min_val DATE, date_max_val DATE, date_val_1 DATE, date_val_2 DATE, time_null TIME, time_min_val TIME, time_max_val TIME, time_val_1 TIME, timestamp_null TIMESTAMP, timestamp_min_val TIMESTAMP, timestamp_max_val TIMESTAMP, timestamp_val_1 TIMESTAMP, timestamp_val_2 TIMESTAMP, timestamptz_null TIMESTAMPTZ, timestamptz_min_val_utc TIMESTAMPTZ, timestamptz_max_val_utc TIMESTAMPTZ, timestamptz_val_1_utc TIMESTAMPTZ, timestamptz_min_val_cet TIMESTAMPTZ, timestamptz_max_val_cet TIMESTAMPTZ, timestamptz_val_1_cet TIMESTAMPTZ, timestamptz_min_val_plus8 TIMESTAMPTZ, timestamptz_max_val_plus8 TIMESTAMPTZ, timestamptz_val_1_plus8 TIMESTAMPTZ, timestamptz_min_val_america_new_york TIMESTAMPTZ, timestamptz_max_val_america_new_york TIMESTAMPTZ, timestamptz_val_1_america_new_york TIMESTAMPTZ, timestamptz_val2_1 TIMESTAMPTZ, timestamptz_val2_2 TIMESTAMPTZ, timestamptz_val2_3 TIMESTAMPTZ, timestamptz_val2_4 TIMESTAMPTZ, timestamptz_val2_5 TIMESTAMPTZ, interval_null INTERVAL, interval_min_val INTERVAL, interval_max_val INTERVAL, interval_val_1 INTERVAL, interval_val_2 INTERVAL, interval_val_3 INTERVAL, interval_val_4 INTERVAL, interval_val_5 INTERVAL, bytea_null BYTEA, bytea_empty BYTEA, bytea_val_space BYTEA, bytea_val_1 BYTEA, bytea_val_2 BYTEA, text_null TEXT, text_empty TEXT, text_val_1 TEXT, text_val_2 TEXT, text_val_3 TEXT, text_hex_val TEXT, text_val_w_spaces TEXT, jsonb_null JSONB, jsonb_empty JSONB, jsonb_empty_arr JSONB, jsonb_val_arr JSONB, jsonb_val_1 JSONB, jsonb_val_1b JSONB, jsonb_val_1c JSONB, jsonb_val_2 JSONB, jsonb_val_3 JSONB, jsonb_val_4 JSONB, jsonb_val_5 JSONB);
INSERT INTO t_dfr_horiz VALUES (0, NULL::INT2, 0::INT2, 1::INT2, 32767::INT2, -32768::INT2, NULL::INT4, 0::INT4, 1::INT4, 2147483647::INT4, -2147483648::INT4, NULL::INT8, 0::INT8, 1::INT8, 9223372036854775807::INT8, -9223372036854775808::INT8, NULL::UINT2, 0::UINT2, 1::UINT2, 65535::UINT2, NULL::UINT4, 0::UINT4, 1::UINT4, 4294967295::UINT4, NULL::UINT8, 0::UINT8, 1::UINT8, 18446744073709551615::UINT8, NULL::DECIMAL(39), 0::DECIMAL(39), 1::DECIMAL(39), 999999999999999999999999999999999999999::DECIMAL(39), -999999999999999999999999999999999999999::DECIMAL(39), 1::DECIMAL(39), 'NaN'::DECIMAL(39), NULL::DECIMAL(39,8), 0::DECIMAL(39,8), 1::DECIMAL(39,8), 9999999999999999999999999999999.99999999::DECIMAL(39,8), -9999999999999999999999999999999.99999999::DECIMAL(39,8), 0.00000001::DECIMAL(39,8), 'NaN'::DECIMAL(39,8), 0.49999999::DECIMAL(39,8), 1.00000001::DECIMAL(39,8), 0.50000001::DECIMAL(39,8), 0.99999999::DECIMAL(39,8), NULL::REAL, 0::REAL, 1::REAL, 99999999999999999999999999999999999999::REAL, 99999999999999999999999999999999999999::REAL, 0.000000000000000000000000000000000000001::REAL, 'NaN'::REAL, 0.500000000000000000000000000000000000001::REAL, 0.999999999999999999999999999999999999999::REAL, 0.499999999999999999999999999999999999999::REAL, 1.000000000000000000000000000000000000001::REAL, NULL::DOUBLE, 0::DOUBLE, 1::DOUBLE, 999999999999999999999999999999999999999::DOUBLE, -999999999999999999999999999999999999999::DOUBLE, 0.000000000000000000000000000000000000001::DOUBLE, 'NaN'::DOUBLE, 0.500000000000000000000000000000000000001::DOUBLE, 0.999999999999999999999999999999999999999::DOUBLE, 0.499999999999999999999999999999999999999::DOUBLE, 1.000000000000000000000000000000000000001::DOUBLE, NULL::BOOL, TRUE::BOOL, FALSE::BOOL, NULL::DATE, '0001-01-01'::DATE, '99999-12-31'::DATE, '2023-06-01'::DATE, '2024-02-29'::DATE, NULL::TIME, '00:00:00'::TIME, '23:59:59.999999'::TIME, '01:02:03.000001'::TIME, NULL::TIMESTAMP, '0001-01-01 00:00:00'::TIMESTAMP, '99999-12-31 23:59:59'::TIMESTAMP, '2023-02-28 11:22:33.44444'::TIMESTAMP, '2024-02-29 23:50:00'::TIMESTAMP, NULL::TIMESTAMPTZ, '0001-01-01 00:00:00 UTC'::TIMESTAMPTZ, '99999-12-31 23:59:59 UTC'::TIMESTAMPTZ, '2023-06-01 11:22:33.44444 UTC'::TIMESTAMPTZ, '0001-01-01 00:00:00 CET'::TIMESTAMPTZ, '99999-12-31 23:59:59 CET'::TIMESTAMPTZ, '2023-06-01 11:22:33.44444 CET'::TIMESTAMPTZ, '0001-01-01 00:00:00 +8'::TIMESTAMPTZ, '99999-12-31 23:59:59 +8'::TIMESTAMPTZ, '2023-06-01 11:22:33.44444 +8'::TIMESTAMPTZ, '0001-01-01 00:00:00 America/New_York'::TIMESTAMPTZ, '99999-12-31 23:59:59 America/New_York'::TIMESTAMPTZ, '2023-06-01 11:22:33.44444 America/New_York'::TIMESTAMPTZ, '2024-02-29 11:50:00 EST'::TIMESTAMPTZ, '2024-02-28 19:50:00 America/Los_Angeles'::TIMESTAMPTZ, '2024-03-31 01:20:00 Europe/Vienna'::TIMESTAMPTZ, '2024-03-31 02:20:00 Europe/Vienna'::TIMESTAMPTZ, '2024-03-31 03:20:00 Europe/Vienna'::TIMESTAMPTZ, NULL::INTERVAL, '-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL, '178956970 years 7 months 2147483647 days 2562047788:00:54.775807'::INTERVAL, '2 years 3 months 4 days 11:22:33.456789'::INTERVAL, '100 months 100 days'::INTERVAL, '44:45:45'::INTERVAL, '45 minutes'::INTERVAL, '70 minutes'::INTERVAL, NULL::BYTEA, '\x'::BYTEA, '\x20'::BYTEA, '\x68656c6c6f'::BYTEA, '\x68656c6c6f20f09f918b'::BYTEA, NULL::TEXT, ''::TEXT, 'a'::TEXT, 'abc'::TEXT, 'xAAx'::TEXT, 'ff00aa'::TEXT, ' mAA m
	 '::TEXT, NULL::JSONB, '{}'::JSONB, '[]'::JSONB, '["a", "b"]'::JSONB, '{"a": 1}'::JSONB, '{"a": 1,"b": 2}'::JSONB, '{"a": 1,"b": null}'::JSONB, '{"a": 1,"c": 3}'::JSONB, '{"a": 1,"b": 4, "m": {}}'::JSONB, '{"a": "2", "b": ["1", "2"]}'::JSONB, '{"a": "2", "b": { "b1": "1", "b2": { "b20": "2", "b21": "2" }}}'::JSONB);
DROP TABLE IF EXISTS t_dfr_vert;
CREATE TABLE t_dfr_vert (row_index INT, int2_val INT2, int4_val INT4, int8_val INT8, uint2_val UINT2, uint4_val UINT4, uint8_val UINT8, decimal_39_0_val DECIMAL(39), decimal_39_8_val DECIMAL(39,8), real_val REAL, double_val DOUBLE, bool_val BOOL, date_val DATE, time_val TIME, timestamp_val TIMESTAMP, timestamptz_val TIMESTAMPTZ, interval_val INTERVAL, bytea_val BYTEA, text_val TEXT, jsonb_val JSONB);
INSERT INTO t_dfr_vert VALUES (0, NULL::INT2, NULL::INT4, NULL::INT8, NULL::UINT2, NULL::UINT4, NULL::UINT8, NULL::DECIMAL(39), NULL::DECIMAL(39,8), NULL::REAL, NULL::DOUBLE, NULL::BOOL, NULL::DATE, NULL::TIME, NULL::TIMESTAMP, NULL::TIMESTAMPTZ, NULL::INTERVAL, NULL::BYTEA, NULL::TEXT, NULL::JSONB);
INSERT INTO t_dfr_vert VALUES (1, 0::INT2, 0::INT4, 0::INT8, 0::UINT2, 0::UINT4, 0::UINT8, 0::DECIMAL(39), 0::DECIMAL(39,8), 0::REAL, 0::DOUBLE, TRUE::BOOL, '0001-01-01'::DATE, '00:00:00'::TIME, '0001-01-01 00:00:00'::TIMESTAMP, '0001-01-01 00:00:00 UTC'::TIMESTAMPTZ, '-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL, '\x'::BYTEA, ''::TEXT, '{}'::JSONB);
INSERT INTO t_dfr_vert VALUES (2, 1::INT2, 1::INT4, 1::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), 1::DECIMAL(39,8), 1::REAL, 1::DOUBLE, FALSE::BOOL, '99999-12-31'::DATE, '23:59:59.999999'::TIME, '99999-12-31 23:59:59'::TIMESTAMP, '99999-12-31 23:59:59 UTC'::TIMESTAMPTZ, '178956970 years 7 months 2147483647 days 2562047788:00:54.775807'::INTERVAL, '\x20'::BYTEA, 'a'::TEXT, '[]'::JSONB);
INSERT INTO t_dfr_vert VALUES (3, 32767::INT2, 2147483647::INT4, 9223372036854775807::INT8, 65535::UINT2, 4294967295::UINT4, 18446744073709551615::UINT8, 999999999999999999999999999999999999999::DECIMAL(39), 9999999999999999999999999999999.99999999::DECIMAL(39,8), 99999999999999999999999999999999999999::REAL, 999999999999999999999999999999999999999::DOUBLE, TRUE::BOOL, '2023-06-01'::DATE, '01:02:03.000001'::TIME, '2023-02-28 11:22:33.44444'::TIMESTAMP, '2023-06-01 11:22:33.44444 UTC'::TIMESTAMPTZ, '2 years 3 months 4 days 11:22:33.456789'::INTERVAL, '\x68656c6c6f'::BYTEA, 'abc'::TEXT, '["a", "b"]'::JSONB);
INSERT INTO t_dfr_vert VALUES (4, -32768::INT2, -2147483648::INT4, -9223372036854775808::INT8, 0::UINT2, 0::UINT4, 0::UINT8, -999999999999999999999999999999999999999::DECIMAL(39), -9999999999999999999999999999999.99999999::DECIMAL(39,8), 99999999999999999999999999999999999999::REAL, -999999999999999999999999999999999999999::DOUBLE, FALSE::BOOL, '2024-02-29'::DATE, '00:00:00'::TIME, '2024-02-29 23:50:00'::TIMESTAMP, '0001-01-01 00:00:00 CET'::TIMESTAMPTZ, '100 months 100 days'::INTERVAL, '\x68656c6c6f20f09f918b'::BYTEA, 'xAAx'::TEXT, '{"a": 1}'::JSONB);
INSERT INTO t_dfr_vert VALUES (5, 0::INT2, 0::INT4, 0::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), 0.00000001::DECIMAL(39,8), 0.000000000000000000000000000000000000001::REAL, 0.000000000000000000000000000000000000001::DOUBLE, TRUE::BOOL, '0001-01-01'::DATE, '23:59:59.999999'::TIME, '0001-01-01 00:00:00'::TIMESTAMP, '99999-12-31 23:59:59 CET'::TIMESTAMPTZ, '44:45:45'::INTERVAL, '\x'::BYTEA, 'ff00aa'::TEXT, '{"a": 1,"b": 2}'::JSONB);
INSERT INTO t_dfr_vert VALUES (6, 1::INT2, 1::INT4, 1::INT8, 65535::UINT2, 4294967295::UINT4, 18446744073709551615::UINT8, 'NaN'::DECIMAL(39), 'NaN'::DECIMAL(39,8), 'NaN'::REAL, 'NaN'::DOUBLE, FALSE::BOOL, '99999-12-31'::DATE, '01:02:03.000001'::TIME, '99999-12-31 23:59:59'::TIMESTAMP, '2023-06-01 11:22:33.44444 CET'::TIMESTAMPTZ, '45 minutes'::INTERVAL, '\x20'::BYTEA, ' mAA m
	 '::TEXT, '{"a": 1,"b": null}'::JSONB);
INSERT INTO t_dfr_vert VALUES (7, 32767::INT2, 2147483647::INT4, 9223372036854775807::INT8, 0::UINT2, 0::UINT4, 0::UINT8, 0::DECIMAL(39), 0.49999999::DECIMAL(39,8), 0.500000000000000000000000000000000000001::REAL, 0.500000000000000000000000000000000000001::DOUBLE, TRUE::BOOL, '2023-06-01'::DATE, '00:00:00'::TIME, '2023-02-28 11:22:33.44444'::TIMESTAMP, '0001-01-01 00:00:00 +8'::TIMESTAMPTZ, '70 minutes'::INTERVAL, '\x68656c6c6f'::BYTEA, ''::TEXT, '{"a": 1,"c": 3}'::JSONB);
INSERT INTO t_dfr_vert VALUES (8, -32768::INT2, -2147483648::INT4, -9223372036854775808::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), 1.00000001::DECIMAL(39,8), 0.999999999999999999999999999999999999999::REAL, 0.999999999999999999999999999999999999999::DOUBLE, FALSE::BOOL, '2024-02-29'::DATE, '23:59:59.999999'::TIME, '2024-02-29 23:50:00'::TIMESTAMP, '99999-12-31 23:59:59 +8'::TIMESTAMPTZ, '-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL, '\x68656c6c6f20f09f918b'::BYTEA, 'a'::TEXT, '{"a": 1,"b": 4, "m": {}}'::JSONB);
INSERT INTO t_dfr_vert VALUES (9, 0::INT2, 0::INT4, 0::INT8, 65535::UINT2, 4294967295::UINT4, 18446744073709551615::UINT8, 999999999999999999999999999999999999999::DECIMAL(39), 0.50000001::DECIMAL(39,8), 0.499999999999999999999999999999999999999::REAL, 0.499999999999999999999999999999999999999::DOUBLE, TRUE::BOOL, '0001-01-01'::DATE, '01:02:03.000001'::TIME, '0001-01-01 00:00:00'::TIMESTAMP, '2023-06-01 11:22:33.44444 +8'::TIMESTAMPTZ, '178956970 years 7 months 2147483647 days 2562047788:00:54.775807'::INTERVAL, '\x'::BYTEA, 'abc'::TEXT, '{"a": "2", "b": ["1", "2"]}'::JSONB);
INSERT INTO t_dfr_vert VALUES (10, 1::INT2, 1::INT4, 1::INT8, 0::UINT2, 0::UINT4, 0::UINT8, -999999999999999999999999999999999999999::DECIMAL(39), 0.99999999::DECIMAL(39,8), 1.000000000000000000000000000000000000001::REAL, 1.000000000000000000000000000000000000001::DOUBLE, FALSE::BOOL, '99999-12-31'::DATE, '00:00:00'::TIME, '99999-12-31 23:59:59'::TIMESTAMP, '0001-01-01 00:00:00 America/New_York'::TIMESTAMPTZ, '2 years 3 months 4 days 11:22:33.456789'::INTERVAL, '\x20'::BYTEA, 'xAAx'::TEXT, '{"a": "2", "b": { "b1": "1", "b2": { "b20": "2", "b21": "2" }}}'::JSONB);
INSERT INTO t_dfr_vert VALUES (11, 32767::INT2, 2147483647::INT4, 9223372036854775807::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), 0::DECIMAL(39,8), 0::REAL, 0::DOUBLE, TRUE::BOOL, '2023-06-01'::DATE, '23:59:59.999999'::TIME, '2023-02-28 11:22:33.44444'::TIMESTAMP, '99999-12-31 23:59:59 America/New_York'::TIMESTAMPTZ, '100 months 100 days'::INTERVAL, '\x68656c6c6f'::BYTEA, 'ff00aa'::TEXT, '{}'::JSONB);
INSERT INTO t_dfr_vert VALUES (12, -32768::INT2, -2147483648::INT4, -9223372036854775808::INT8, 65535::UINT2, 4294967295::UINT4, 18446744073709551615::UINT8, 'NaN'::DECIMAL(39), 1::DECIMAL(39,8), 1::REAL, 1::DOUBLE, FALSE::BOOL, '2024-02-29'::DATE, '01:02:03.000001'::TIME, '2024-02-29 23:50:00'::TIMESTAMP, '2023-06-01 11:22:33.44444 America/New_York'::TIMESTAMPTZ, '44:45:45'::INTERVAL, '\x68656c6c6f20f09f918b'::BYTEA, ' mAA m
	 '::TEXT, '[]'::JSONB);
INSERT INTO t_dfr_vert VALUES (13, 0::INT2, 0::INT4, 0::INT8, 0::UINT2, 0::UINT4, 0::UINT8, 0::DECIMAL(39), 9999999999999999999999999999999.99999999::DECIMAL(39,8), 99999999999999999999999999999999999999::REAL, 999999999999999999999999999999999999999::DOUBLE, TRUE::BOOL, '0001-01-01'::DATE, '00:00:00'::TIME, '0001-01-01 00:00:00'::TIMESTAMP, '2024-02-29 11:50:00 EST'::TIMESTAMPTZ, '45 minutes'::INTERVAL, '\x'::BYTEA, ''::TEXT, '["a", "b"]'::JSONB);
INSERT INTO t_dfr_vert VALUES (14, 1::INT2, 1::INT4, 1::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), -9999999999999999999999999999999.99999999::DECIMAL(39,8), 99999999999999999999999999999999999999::REAL, -999999999999999999999999999999999999999::DOUBLE, FALSE::BOOL, '99999-12-31'::DATE, '23:59:59.999999'::TIME, '99999-12-31 23:59:59'::TIMESTAMP, '2024-02-28 19:50:00 America/Los_Angeles'::TIMESTAMPTZ, '70 minutes'::INTERVAL, '\x20'::BYTEA, 'a'::TEXT, '{"a": 1}'::JSONB);
INSERT INTO t_dfr_vert VALUES (15, 32767::INT2, 2147483647::INT4, 9223372036854775807::INT8, 65535::UINT2, 4294967295::UINT4, 18446744073709551615::UINT8, 999999999999999999999999999999999999999::DECIMAL(39), 0.00000001::DECIMAL(39,8), 0.000000000000000000000000000000000000001::REAL, 0.000000000000000000000000000000000000001::DOUBLE, TRUE::BOOL, '2023-06-01'::DATE, '01:02:03.000001'::TIME, '2023-02-28 11:22:33.44444'::TIMESTAMP, '2024-03-31 01:20:00 Europe/Vienna'::TIMESTAMPTZ, '-178956970 years -8 months -2147483648 days -2562047788:00:54.775808'::INTERVAL, '\x68656c6c6f'::BYTEA, 'abc'::TEXT, '{"a": 1,"b": 2}'::JSONB);
INSERT INTO t_dfr_vert VALUES (16, -32768::INT2, -2147483648::INT4, -9223372036854775808::INT8, 0::UINT2, 0::UINT4, 0::UINT8, -999999999999999999999999999999999999999::DECIMAL(39), 'NaN'::DECIMAL(39,8), 'NaN'::REAL, 'NaN'::DOUBLE, FALSE::BOOL, '2024-02-29'::DATE, '00:00:00'::TIME, '2024-02-29 23:50:00'::TIMESTAMP, '2024-03-31 02:20:00 Europe/Vienna'::TIMESTAMPTZ, '178956970 years 7 months 2147483647 days 2562047788:00:54.775807'::INTERVAL, '\x68656c6c6f20f09f918b'::BYTEA, 'xAAx'::TEXT, '{"a": 1,"b": null}'::JSONB);
INSERT INTO t_dfr_vert VALUES (17, 0::INT2, 0::INT4, 0::INT8, 1::UINT2, 1::UINT4, 1::UINT8, 1::DECIMAL(39), 0.49999999::DECIMAL(39,8), 0.500000000000000000000000000000000000001::REAL, 0.500000000000000000000000000000000000001::DOUBLE, TRUE::BOOL, '0001-01-01'::DATE, '23:59:59.999999'::TIME, '0001-01-01 00:00:00'::TIMESTAMP, '2024-03-31 03:20:00 Europe/Vienna'::TIMESTAMPTZ, '2 years 3 months 4 days 11:22:33.456789'::INTERVAL, '\x'::BYTEA, 'ff00aa'::TEXT, '{"a": 1,"c": 3}'::JSONB);
```

and a mz configuration containing `--bootstrap-default-cluster-replica-size=4-4`,

mz will produce incorrect and not stable results for a query like
```
SELECT '<' || text_val || '>', (text_val NOT ILIKE '%A%') FROM t_dfr_vert WHERE (row_index IN (1, 17, 15)) ORDER BY row_index ASC;
```

Executing the query a couple of times, I got:
```
materialize=> SELECT '<' || text_val || '>', (text_val NOT ILIKE '%A%') FROM t_dfr_vert WHERE (row_index IN (1, 17, 15)) ORDER BY row_index ASC;
 ?column? | ?column? 
----------+----------
 <>       | t
 <abc>    | t
 <ff00aa> | t
(3 rows)

materialize=> SELECT '<' || text_val || '>', (text_val NOT ILIKE '%A%') FROM t_dfr_vert WHERE (row_index IN (1, 17, 15)) ORDER BY row_index ASC;
 ?column? | ?column? 
----------+----------
 <>       | t
 <abc>    | t
 <ff00aa> | f
(3 rows)

materialize=> SELECT '<' || text_val || '>', (text_val NOT ILIKE '%A%') FROM t_dfr_vert WHERE (row_index IN (1, 17, 15)) ORDER BY row_index ASC;
 ?column? | ?column? 
----------+----------
 <>       | t
 <abc>    | t
 <ff00aa> | f
(3 rows)

materialize=> SELECT '<' || text_val || '>', (text_val NOT ILIKE '%A%') FROM t_dfr_vert WHERE (row_index IN (1, 17, 15)) ORDER BY row_index ASC;
 ?column? | ?column? 
----------+----------
 <>       | t
 <abc>    | f
 <ff00aa> | t
(3 rows)
```

The correct result should be
```
 ?column? | ?column? 
----------+----------
 <>       | t
 <abc>    | f
 <ff00aa> | f
(3 rows)
```

### Further observations
* The problem does only occur with `ILIKE '%A%'` but not with `LIKE '%A%'` or `LIKE '%a%'`
* The problem does not occur with constant folding.
* The parameter `--bootstrap-default-cluster-replica-size=4-4` is crucial for reproducing this bug.

### See also
https://buildkite.com/materialize/nightlies/builds/6980

**Comment by teskje** [comment] 2024-03-21 10:36
I edited the title: This is not an issue with multiple replicas but with _multi-process_ replicas.

The number of workers per process also doesn't seem to matter. I get wrong results with sizes `2-1`, `4-1`, and `4-4`, but not with `1`, `2`, `4`.

**Comment by teskje** [comment] 2024-03-21 10:50
Minimal repro:

```sql
CREATE TABLE t (text_val TEXT);
INSERT INTO t VALUES ('abc');

CREATE CLUSTER test SIZE '2-1';
SET cluster = test;

SELECT text_val NOT ILIKE '%A%' FROM t;
SELECT text_val NOT ILIKE '%A%' FROM t;
SELECT text_val NOT ILIKE '%A%' FROM t;
SELECT text_val NOT ILIKE '%A%' FROM t;
```

**Comment by ggevay** [comment] 2024-03-21 11:50
This is very scary! Will look into it!

**Comment by teskje** [comment] 2024-03-21 12:28
I think it's this bug @ggevay has opened a while ago on `serde-regex`: https://github.com/tailhook/serde-regex/issues/14. The issue is that `serde-regex` drops the case-insensitive flag during a serialization-deserialization roundtrip. So whenever we serialize and then deserialize an MFP plan that contains a case-insensitive regex, like we get from `ILIKE` statements, we should expect the resulting MFP plan to be wrong.

On a single-process replica that doesn't matter because plans are not serialized with `serde`. They are only serialized using protobuf when they get sent from the controller to worker 0, then worker 0 sends them to the other workers in the same process without serialization. However, on a multi-process replica, plans need to be serialized when they are sent from worker 0 to workers on different processes. We let Timely do that serialization for us, which uses `serde` under the hood, and thus we get corrupted `ILIKE` plans.

**Comment by ggevay** [comment] 2024-03-21 19:30
Fixed with https://github.com/MaterializeInc/materialize/pull/26183

**Closed by ggevay** 2024-03-21 19:30 UTC
Labels: C-bug, T-correctness, A-COMPUTE
