### ISSUE TITLE
parallel workload tests fail due to "Invalid MySQL table reference"

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#26924] opened 2024-05-06 11:18 UTC
### What version of Materialize are you using?

23aeae09de70872952733f7cfeb5d41a7e068b41

### What is the issue?

[Parallel workload tests](https://buildkite.com/materialize/nightly/builds/7652) and data-ingest started failing with the merge of https://github.com/MaterializeInc/materialize/pull/26827 due to:
```
materialize.parallel_workload.worker_exception.WorkerFailedException: ^^^ +++ Thread worker_6 failed, exiting
("{'S': 'ERROR', 'C': 'XX000', 'M': 'MYSQL source validation: Invalid MySQL table reference: mytable0'}", 'CREATE SOURCE "db-pw-1714993685-0"."s-0-1".mysql_source0\n                    IN CLUSTER "cluster-2"\n                    FROM MYSQL CONNECTION mysql0\n                    FOR TABLES (mytable0 AS mytable0)')
```

@sploiselle, could you take a look, please? The relevant test code should be in `MySqlExecutor` in `misc/python/materialize/data_ingest/executor.py`. `CREATE SOURCE` seems to no longer be able to find the just created table. Happy to assist if needed!

CC @rjobanp

**Comment by nrainer-materialize** [comment] 2024-05-06 11:19
Marking this proactively as a release-blocker, feel free to remove the tag if you disagree.

**Comment by sploiselle** [comment] 2024-05-06 12:32
@rjobanp Do you see what the problem here is? https://github.com/MaterializeInc/materialize/pull/26827/files#diff-d0bbd11375c4c51235769f6f6c27b4b77df907e90c924c0e3f53f54180fa3261L359-R359

I have [another issue](https://materializeinc.slack.com/archives/CTESPM7FU/p1714784793099809) that's pressing that I have to look at today, so an assist here's greatly appreciated. If you don't have time or don't see what the issue is in the test, lmk.

**Comment by nrainer-materialize** [comment] 2024-05-06 12:59
Oh, wait, I think we just need to revert this change. It works with `mysql` prefix. I wasn't aware that the PR also touched this test code.

**Comment by rjobanp** [comment] 2024-05-06 13:23
Yep @nrainer-materialize is right -- in that line of code we need to bring back the `mysql.` prefix since further up in that test file you can see the tables are created in the `mysql` mysql database:
```
self.mysql_conn = pymysql.connect(
            host="localhost",
            user="root",
            password=MySql.DEFAULT_ROOT_PASSWORD,
            database="mysql",
            port=self.ports["mysql"],
        )
```
and for mysql source parameters we require qualified-table-references 

@nrainer-materialize will you open a revert PR for that line or should I?

**Comment by nrainer-materialize** [comment] 2024-05-06 13:31
I will do it:
=> https://github.com/MaterializeInc/materialize/pull/26925

**Comment by sploiselle** [comment] 2024-05-06 15:02
Thank you and apologies for borking this!

Fixed via https://github.com/MaterializeInc/materialize/pull/26925

**Closed by sploiselle** 2024-05-06 15:02 UTC
Labels: C-bug
