### ISSUE TITLE
computed: panic: Protocol error: starting frontier tracking for already present identifier User(32) due to command CreateDataflows

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#13355] opened 2022-06-29 19:17 UTC
### What version of Materialize are you using?

materialize/computed:unstable-45e2acde087c27a661b5e67db587375c0b628fde

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Was running some feature-benchmarks against a cloud instance and got this panic.

### Relevant log output

```
2022-06-28T21:38:59.375286Z  INFO computed: about to bind to "0.0.0.0:2100"
2022-06-28T21:38:59.375318Z  INFO computed: serving internal HTTP server on 0.0.0.0:6875
worker 0:    initialization complete
2022-06-28T21:38:59.376388Z  INFO mz_dataflow_types::client::tcp: Starting to listen on 0.0.0.0:2100
2022-06-28T21:39:03.408197Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Environment context=environment variable not set
2022-06-28T21:39:03.408257Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Profile context=No profiles were defined
2022-06-28T21:39:03.408544Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}:send_operation{operation="AssumeRoleWithWebIdentity" service="sts"}: aws_http::auth: provider returned CredentialsNotLoaded, ignoring
2022-06-28T21:39:03.547172Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: loaded credentials provider=WebIdentityToken
2022-06-28T21:39:03.627783Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
2022-06-29T15:32:57.401984Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Environment context=environment variable not set
2022-06-29T15:32:57.402044Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Profile context=No profiles were defined
2022-06-29T15:32:57.402374Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}:send_operation{operation="AssumeRoleWithWebIdentity" service="sts"}: aws_http::auth: provider returned CredentialsNotLoaded, ignoring
2022-06-29T15:32:57.549298Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: loaded credentials provider=WebIdentityToken
2022-06-29T16:02:13.000506Z  INFO mz_dataflow_types::client::tcp: Connection severed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
2022-06-29T16:02:13.000655Z  WARN computed: Lost connection: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
2022-06-29T16:02:13.000668Z  INFO computed: coordinator connection gone; waiting for reconnect
thread 'main' panicked at 'Protocol error: starting frontier tracking for already present identifier User(32) due to command CreateDataflows([DataflowDescription { source_imports: {User(30): SourceInstanceDesc { description: SourceDesc { connection: Local { timeline: EpochMilliseconds }, desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: true }], keys: [] }, names: [ColumnName("f1")] } }, arguments: SourceInstanceArguments { operators: Some(LinearOperator { predicates: [], projection: [0] }) }, storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://mzcloud-staging-us-east-1-persistence-0c945ace/system:serviceaccount:environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0:environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0", consensus_uri: "postgres://environment_e36869fc477f4c48bc6f08d14a6a2071:6zCpHWid7BnzfxaTvOfgbR2ylairK70F@mzcloud-staging-us-east-1-aurora.cluster-chq4fkbfgstu.us-east-1.rds.amazonaws.com:5432/environment_e36869fc477f4c48bc6f08d14a6a2071?options=--search_path=consensus" }, timestamp_shard_id: ShardId(25c45aa1-96dd-4bd9-8228-fd8284701b2a), persist_shard: ShardId(f3ae9e9a-fb31-49c4-9330-050d067b4bdb) } }}, index_imports: {}, objects_to_build: [BuildDesc { id: User(31), plan: Get { id: Global(User(30)), keys: AvailableCollections { raw: true, arranged: [] }, plan: Collection(MapFilterProject { expressions: [CallBinary { func: MulInt32, expr1: Column(0), expr2: Literal(Ok(Row{[Int32(1)]}), ColumnType { scalar_type: Int32, nullable: false }) }, Literal(Ok(Row{[Int32(1)]}), ColumnType { scalar_type: Int32, nullable: false })], predicates: [], projection: [1, 2], input_arity: 1 }) } }, BuildDesc { id: User(32), plan: ArrangeBy { input: Get { id: Global(User(31)), keys: AvailableCollections { raw: true, arranged: [] }, plan: PassArrangements }, forms: AvailableCollections { raw: true, arranged: [([Column(0), Column(1)], {1: 1, 0: 0}, [])] }, input_key: None, input_mfp: MapFilterProject { expressions: [], predicates: [], projection: [0, 1], input_arity: 2 } } }], index_exports: {User(32): (IndexDesc { on_id: User(31), key: [Column(0), Column(1)] }, RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: true }, ColumnType { scalar_type: Int32, nullable: false }], keys: [] })}, sink_exports: {}, as_of: Some(Antichain { elements: [1656518567181] }), debug_name: "1.6.v1_primary_idx", id: 311b03e4-2687-473d-82ad-c406e71a3baa }])', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client/partitioned.rs:386:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: mz_dataflow_types::client::partitioned::PartitionedComputeState<T>::observe_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client/partitioned.rs:386:13
   3: <mz_dataflow_types::client::partitioned::PartitionedComputeState<T> as mz_dataflow_types::client::partitioned::PartitionedState<mz_dataflow_types::client::ComputeCommand<T>,mz_dataflow_types::client::ComputeResponse<T>>>::split_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client/partitioned.rs:402:9
   4: <mz_dataflow_types::client::partitioned::Partitioned<P,C,R> as mz_dataflow_types::client::GenericClient<C,R>>::send::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client/partitioned.rs:140:25
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
   7: <mz_dataflow_types::client::LocalClient<C,R> as mz_dataflow_types::client::GenericClient<C,R>>::send::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client.rs:806:30
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  10: <alloc::boxed::Box<dyn mz_dataflow_types::client::ComputeClient<T>> as mz_dataflow_types::client::GenericClient<mz_dataflow_types::client::ComputeCommand<T>,mz_dataflow_types::client::ComputeResponse<T>>>::send::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/dataflow-types/src/client.rs:745:27
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  13: computed::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/compute/src/bin/computed.rs:209:52
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  15: computed::run::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/compute/src/bin/computed.rs:189:32
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  17: computed::main::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/compute/src/bin/computed.rs:100:32
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  19: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  20: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  21: std::thread::local::LocalKey<T>::try_with
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  22: std::thread::local::LocalKey<T>::with
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  23: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  24: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  25: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  26: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  27: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/mod.rs:90:9
  28: tokio::runtime::Runtime::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/mod.rs:482:43
  29: computed::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-01f3321ac953ef261-1/materialize/tests/src/compute/src/bin/computed.rs:100:5
  30: core::ops::function::FnOnce::call_once
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0/compute-cluster-1-replica-1-0 (default)

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by mjibson** [comment] 2022-06-30 02:55
This got hit again while running https://github.com/MaterializeInc/materialize/blob/a8ba78517861efd58bc43e715f135f80c44db4e6/test/feature-benchmark/scenarios.py#L636 in a loop.

**Comment by mjibson** [comment] 2022-06-30 03:11
Logs from the envd instance where this happened again. That error was complaining about `User(381)`:

```
2022-06-30T00:43:25.981179Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Environment context=environment variable not set
2022-06-30T00:43:25.981234Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: provider in chain did not provide credentials provider=Profile context=No profiles were defined
2022-06-30T00:43:25.981504Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}:send_operation{operation="AssumeRoleWithWebIdentity" service="sts"}: aws_http::auth: provider returned CredentialsNotLoaded, ignoring
2022-06-30T00:43:26.065409Z  INFO send_operation{operation="GetObject" service="s3"}:provide_credentials{provider=default_chain}: aws_config::meta::credentials::chain: loaded credentials provider=WebIdentityToken
2022-06-30T00:43:27.619524Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
2022-06-30T00:43:27.817968Z  INFO mz_coord::catalog: create source materialize.public.s1 (u380)
2022-06-30T00:43:27.818026Z  INFO mz_coord::catalog: create index materialize.public.s1_primary_idx (u381)
2022-06-30T00:43:27.844190Z  INFO mz_coord::catalog: create source materialize.public.s1 (u380)
2022-06-30T00:43:27.844237Z  INFO mz_coord::catalog: create index materialize.public.s1_primary_idx (u381)
2022-06-30T00:43:27.903056Z  INFO mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: connected
2022-06-30T00:43:28.210842Z  INFO mz_dataflow_types::client::tcp: Reconnected to storage-u380-0.storage-u380.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100
2022-06-30T00:43:29.610169Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica 1
environmentd v0.26.1-dev (45e2acde0) listening...
 SQL address: 0.0.0.0:6875
 HTTP address: 0.0.0.0:443
 Internal SQL address: 127.0.0.1:6877
 Internal HTTP address: 0.0.0.0:9099
2022-06-30T00:43:29.777608Z ERROR mz_dataflow_types::client::tcp: connection unexpectedly errored: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
2022-06-30T00:43:29.783078Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 20ms
2022-06-30T00:43:29.805374Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 40ms
2022-06-30T00:43:29.847262Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 80ms
2022-06-30T00:43:29.930277Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 160ms
2022-06-30T00:43:30.093118Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 320ms
2022-06-30T00:43:30.416191Z  WARN mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: Connection refused: transport error. Backoff 640ms
2022-06-30T00:43:31.060560Z  INFO mz_dataflow_types::client::tcp: GrpcComputedClient http://compute-cluster-1-replica-1-0.compute-cluster-1-replica-1.environment-d2ae5399-b934-491b-9e51-cd051ebf2b94-0.svc.cluster.local:2100: connected
2022-06-30T00:43:31.060623Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica 1
2022-06-30T00:49:24.666471Z  WARN mz_environmentd::http: HTTP request failed authentication: missing authorization header
2022-06-30T00:49:25.334261Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: unexpected EOF
2022-06-30T00:49:25.778511Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)
2022-06-30T00:49:26.228204Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)
2022-06-30T00:49:26.698786Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: unexpected EOF
2022-06-30T00:49:27.130296Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)
2022-06-30T00:49:27.356065Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1685:: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1685:
2022-06-30T00:49:28.026228Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)
2022-06-30T00:49:28.471462Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: Connection reset by peer (os error 104): Connection reset by peer (os error 104)
2022-06-30T00:49:28.693026Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1779:: error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1779:
2022-06-30T00:49:29.137131Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:ssl/statem/extensions_srvr.c:697:: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share:ssl/statem/extensions_srvr.c:697:
2022-06-30T01:42:38.045819Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: unexpected EOF
2022-06-30T01:57:59.414345Z  WARN mz_environmentd::http: HTTP request failed authentication: missing authorization header
2022-06-30T02:11:44.273702Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: unexpected EOF
2022-06-30T02:15:40.750401Z  WARN mz_environmentd::http: HTTP request failed authentication: missing authorization header
2022-06-30T02:25:52.726641Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2283:: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2283:
2022-06-30T02:34:02.127236Z  WARN mz_environmentd::http: HTTP request failed authentication: missing authorization header
```

**Comment by umanwizard** [comment] 2022-12-12 16:54
The code has changed so much since this was filed that I doubt it's reproducible, but I'll check.

**Comment by teskje** [comment] 2023-01-11 13:47
@umanwizard Did you find time to check? 

My guess would also be that the issue was fixed in one of the refactors we made since. But it seems hard to verify this without a good repro. At least Sentinel doesn't seem to know this error.

**Comment by antiguru** [comment] 2023-02-01 15:01
Not recently observed.

**Closed by antiguru** 2023-02-01 15:01 UTC
Labels: C-bug, A-COMPUTE
