### ISSUE TITLE
Two materialize instances can be started against the same mzdata  directory

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6383] opened 2021-04-08 07:17 UTC
### What version of Materialize are you using?

```
v0.7.2-dev (1221d30e7)
```

### What was the issue?

It is possible to start two materialize instances that share the same mzdata directory. Sometimes SQLlite will react against it by reporting ```sqlite error: attempt to write a readonly database``` but this is by no means certain. In other cases both MZ instances will be able to create tables and see each other-s tables.

As more stuff is being persisted into the mzdata directory, the chance for corruption increases, e.g. two mzdata processes attempting recovery or compaction at the same time.

This is a recipe for disaster and MySQL and NuoDB enforce explicit locking of the data directory to prevent it. Users may cause this situation to happen inadvertently by using symlinks, shared drives, you name it.

There are no warnings in the logs.

### Is the issue reproducible? If so, please provide reproduction instructions.

```
$ target/release/materialized &

$ target/release/materialized -w 16 --listen-addr 127.0.0.1:16875 &

$ psql -p 6875 -h 127.0.0.1 -U materialize
psql (12.5 (Ubuntu 12.5-0ubuntu0.20.04.1), server 9.5.0)
Type "help" for help.

materialize=> create table t1 (f1 integer);
CREATE TABLE
materialize=> \q
$ psql -p 16875 -h 127.0.0.1 -U materialize
psql (12.5 (Ubuntu 12.5-0ubuntu0.20.04.1), server 9.5.0)
Type "help" for help.

materialize=> create table t1 (f1 integer);
ERROR:  catalog item 't1' already exists
```

**Comment by benesch** [comment] 2022-03-19 01:15
Retroactive duplicate of #7816, which was fixed by #7821.

**Closed by benesch** 2022-03-19 01:15 UTC
Labels: C-bug, A-coordinator, T-correctness
