### ISSUE TITLE
storage/connections/kafka: mz E2E fails due to SaslAuthenticateRequest failed: Local: Broker handle destroyed

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24901] opened 2024-02-02 09:48 UTC
### What version of Materialize are you using?

c6081c9b7832405757844acf15962836ff83ea7d

### What is the issue?

https://buildkite.com/materialize/nightlies/builds/6285#018d673a-376e-44db-b1a1-69acc1db37d5

```
ERROR:  Internal kafka error: [thrd:sasl_ssl://pkc-n00kk.us-east-1.aws.confluent.cloud:9092/bootstr]: sasl_ssl://pkc-n00kk.us-east-1.aws.confluent.cloud:9092/bootstrap: SASL authentication error: SaslAuthenticateRequest failed: Local: Broker handle destroyed (after 0ms in state DOWN)
```

**Comment by benesch** [comment] 2024-02-03 01:38
I'm going to optimistically close this as something caused by the librdkafka bump that's since been reverted.

**Comment by nrainer-materialize** [comment] 2024-02-05 07:40
Assuming that this has already happened with https://github.com/MaterializeInc/materialize/pull/24919, I fear it did not fix the issue: https://buildkite.com/materialize/nightlies/builds/6306#018d741b-e593-451b-8c46-3173a5668653

**Comment by benesch** [comment] 2024-02-05 08:12
Indeed. Thanks for reopening! Added to the storage mega tracker.

**Comment by benesch** [comment] 2024-02-05 08:13
Maybe a test issue? Apparently this log line can get emitted naturally when librdkafka is shutting down: https://github.com/confluentinc/librdkafka/issues/2854

**Comment by benesch** [comment] 2024-02-05 08:13
I wonder if its a glitch in our error detection for validating Kafka connections. Maybe we need to disable sniffing of `log` and `error` messages when we drop the context.

**Comment by benesch** [comment] 2024-02-05 08:18
I think this might fix the issue.

```diff
diff --git a/src/storage-types/src/connections.rs b/src/storage-types/src/connections.rs
index 5e5e06ccb6..e01f2e2004 100644
--- a/src/storage-types/src/connections.rs
+++ b/src/storage-types/src/connections.rs
@@ -623,6 +623,7 @@ impl KafkaConnection {
         let consumer: BaseConsumer<_> = self
             .create_with_context(storage_configuration, context, &BTreeMap::new())
             .await?;
+        let consumer = Arc::new(consumer);
 
         let timeout = storage_configuration
             .parameters
@@ -641,7 +642,10 @@ impl KafkaConnection {
         // error is buried in the librdkafka logs, which are not visible to users.
         let result = mz_ore::task::spawn_blocking(
             || "kafka_get_metadata",
-            move || consumer.fetch_metadata(None, timeout),
+            {
+                let consumer = Arc::clone(&consumer);
+                move || consumer.fetch_metadata(None, timeout)
+            },
         )
         .await?;
         match result {
@@ -659,6 +663,11 @@ impl KafkaConnection {
                     _ => cur,
                 });
 
+                // Don't drop the consumer until after we've drained the errors
+                // channel. Dropping the consumer can introduce spurious errors.
+                // See #24901.
+                drop(consumer);
+
                 match main_err {
                     Some(err) => Err(err.into()),
                     None => Err(err.into()),

```

**Comment by benesch** [comment] 2024-02-06 18:27
Note to self: failed SASL auth was also the cause of https://github.com/MaterializeInc/materialize/issues/25009, but the error message was awful. Hopefully it's easy to fix that error message as well.

**Comment by benesch** [comment] 2024-02-11 18:32
@MaterializeInc/testing, now that the error message improvement (https://github.com/MaterializeInc/materialize/pull/24959) is on track to merge, can I kick this one back to y'all? Should just be a matter of updating the API key for the Confluent Cloud account that this test uses.

**Comment by nrainer-materialize** [comment] 2024-02-12 08:06
> @MaterializeInc/testing, now that the error message improvement (#24959) is on track to merge, can I kick this one back to y'all? Should just be a matter of updating the API key for the Confluent Cloud account that this test uses.

Of course.

**Comment by benesch** [comment] 2024-02-17 23:35
Fixed by https://github.com/MaterializeInc/i2/commit/94762d204dbe44f83a123cc2b571f474078a06d2!

**Closed by benesch** 2024-02-17 23:35 UTC
Labels: C-bug, A-STORAGE
