### ISSUE TITLE
materialize crash on protobuf + Kafka source

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#8930] opened 2021-11-03 13:19 UTC
### What version of Materialize are you using?

@krishmanoh2 can you supply this information?

### What was the issue?

Materialize crashes after a Protobuf source is installed.

### Is the issue reproducible? If so, please provide reproduction instructions.

@krishmanoh2 can you please provide reproduction instructions? What specific Protobuf schema and data causes this crash?

### Please attach any applicable log files.

https://gist.github.com/benesch/83e03d89eb5b9e8a64e256b8791cfac4

**Comment by benesch** [comment] 2021-11-03 17:10
@krishmanoh2, in the future, could you follow the issue template to the extent possible, or at the very least format the backtrace using code blocks so that the they're readable? I've updated this one to follow the template, which exposes a big holes in our ability to diagnose this bug: the lack of reproduction instructions. Do we have the schema and data that triggers this panic? It will be _much_ faster to track this down with that information in hand.


I want to flag that there are two separate issues at play. The first issue, about not being able to parse the statistics JSON, is a bug in librdkafka that will be fixed by #8904. That's a red herring here.

The second issue looks like a real glitch, perhaps in protobuf parsing, but hard to investigate more without details.

**Comment by benesch** [comment] 2021-11-23 07:59
I'm close to having a fix for this. #9240 improves our proto testing infra. Then I'll split up #9019 and get it reviewed + merged, which will actually fix up the bug.

**Closed** 2021-11-30 19:03 UTC
Labels: C-bug
