### ISSUE TITLE
wrong-result: The result of an outer JOIN with multi-part ON clause fluctuates between executions with --workers > 1

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5622] opened 2021-02-05 10:42 UTC
[dbt3.zip](https://github.com/MaterializeInc/materialize/files/5931864/dbt3.zip)

materialized v0.6.2-dev (733dd8575

### What was the issue?

Repeated invocations of the same query result in different result sets.

```
materialize=>  SELECT COUNT(*)  FROM part  JOIN partsupp  ON ( p_partkey  = ps_partkey  ) RIGHT JOIN lineitem  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
 count 
-------
   586
(1 row)

materialize=>  SELECT COUNT(*)  FROM part  JOIN partsupp  ON ( p_partkey  = ps_partkey  ) RIGHT JOIN lineitem  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
 count 
-------
   730
(1 row)
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, please load the attached schema and data and run the query several dozen times.

**Comment by ruchirK** [comment] 2021-02-05 14:14
Does this still happen if you run Materialize with `--logical-compaction-window=off` ( https://materialize.com/docs/cli/#compaction-window ) and create your sources with say `timestamp_frequency_ms=10s` (see: https://materialize.com/docs/sql/create-source/avro-kafka/#with-options ) ?

I think its a bug no matter what but if its harder to reproduce without compaction / with coarser timestamps then that gives us a pretty strong indication of where to look

**Comment by frankmcsherry** [comment] 2021-02-07 16:45
Is it possible this is that the data is still loading? It could be that this particular join is slow enough (outer joins on complex keys can be, as they probably use an awkward default plan; can explain more).

**Comment by philip-stoev** [comment] 2021-02-08 11:30
@ruchirK Unfortunately ``` --logical-compaction-window=off``` does not help. ```imestamp_frequency_ms=10s``` can not be used because it is a ```CREATE TABLE``` and not a ```CREATE SOURCE``` situation.

@frankmcsherry I do not think this is a question of the data still loading. The result fluctuates between one value and the other over time. In 1000 executions, 966 returned 586, 14 returned 727 and 20 returned 730.

The first and the last executions return 586. Postgresql agrees that the correct result is 586.

**Comment by frankmcsherry** [comment] 2021-02-10 21:15
Can you help me reproduce this? I grabbed the data and queries, and saw:
```
materialize=> SELECT COUNT(*)  FROM part  JOIN partsupp  ON ( p_partkey  = ps_partkey  ) RIGHT JOIN lineitem  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
 count 
-------
   586
(1 row)

materialize=> SELECT COUNT(*)  FROM part  JOIN partsupp  ON ( p_partkey  = ps_partkey  ) RIGHT JOIN lineitem  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
 count 
-------
   586
(1 row)

materialize=> SELECT COUNT(*)  FROM part  JOIN partsupp  ON ( p_partkey  = ps_partkey  ) RIGHT JOIN lineitem  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
 count 
-------
   586
(1 row)

materialize=> 
```

**Comment by frankmcsherry** [comment] 2021-02-10 22:07
Oh I see, a more careful reading of your report says that 96.6% of the time it does give this answer, but some times it does not.

**Comment by frankmcsherry** [comment] 2021-02-10 22:18
Hrm. I'm running 1k times now and it hasn't produced a non-586 answer yet. My scrollback has been reached, but all 200 answers in the scrollback at the moment are 586. Just checked again and same is true. What configuration parameters were you using?

**Comment by philip-stoev** [comment] 2021-02-11 07:10
@frankmcsherry apparently this requires workers > 1 to reproduce:

With 4 workers:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/bugs$ cat 5622.sql | psql -p 6875 -h 127.0.0.1 -U materialize  | sort | uniq -c
   1000 
   1000 -------
   1000 (1 row)
    926    586
     30    727
     44    730
   1000  count 
```

With 16 workers:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/bugs$ cat 5622.sql | psql -p 6875 -h 127.0.0.1 -U materialize  | sort | uniq -c
   1000 
   1000 -------
   1000 (1 row)
    830    586
     11    607
     10    609
     21    610
     23    616
     17    617
      8    618
     13    620
     16    623
      1    630
      7    638
      2    639
      2    640
      4    641
      6    643
     14    645
      1    647
      1    653
      1    654
      1    659
      1    661
      1    664
      1    668
      1    673
      1    676
      1    677
      1    679
      1    695
      1    712
      1    713
      1    725
   1000  count 
```

With 32 workers:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/bugs$ cat 5622.sql | psql -p 6875 -h 127.0.0.1 -U materialize  | sort | uniq -c
   1000 
   1000 -------
   1000 (1 row)
     10    586
      1    610
      1    611
      6    612
      1    613
      7    616
      4    617
      2    618
      1    623
      1    633
      4    635
      2    636
      3    637
      4    638
      2    639
      3    640
      5    641
      6    642
      6    643
      4    644
      2    645
      1    646
      9    647
      1    648
      2    649
      1    650
      1    651
      3    652
      1    653
      2    654
      2    655
      2    656
      2    657
      2    659
      5    660
      3    661
      5    662
      7    663
      2    664
      4    665
      5    666
      7    667
      5    668
      4    669
      2    670
      4    671
      9    672
      5    673
     11    674
      3    675
      5    676
      4    677
      4    678
      7    679
      4    680
      2    681
      5    682
      5    683
      5    684
      3    685
      5    686
      2    687
      9    688
      6    689
      6    690
      6    691
      4    692
      8    693
      6    694
      4    695
      7    696
      7    697
      8    698
     14    699
     16    700
     14    701
     11    702
     13    703
     11    704
      9    705
     11    706
     10    707
     11    708
      8    709
      8    710
      7    711
      3    712
      8    713
      5    714
      2    715
      4    716
      9    717
      7    718
      2    719
      7    720
      9    721
      5    722
      7    723
     12    724
      5    725
      3    726
     11    727
      4    728
      7    729
      9    730
     10    731
      9    732
      9    733
      9    734
      5    735
      6    736
      9    737
     10    738
      8    739
      6    740
     13    741
     10    742
      7    743
      7    744
      6    745
      3    746
      7    747
      4    748
      3    749
      4    750
      5    751
      2    752
      8    753
      6    754
      7    755
      7    756
      3    757
      6    758
      6    759
     10    760
      8    761
      5    762
      6    763
      9    764
      9    765
      9    766
      6    767
      3    768
      7    769
      4    770
      7    771
      2    772
      6    773
      3    774
      2    775
      5    776
      4    777
      5    778
      7    779
      1    780
      2    781
      3    782
      1    783
      2    784
      6    785
      6    787
      5    788
      2    789
      3    790
      2    791
      2    792
      2    793
      1    794
      3    795
      1    796
      3    797
      6    798
      2    799
      2    801
      5    802
      4    803
      4    805
      1    806
      4    807
      1    808
      3    809
      1    811
      1    813
      1    814
      3    815
      3    816
      2    817
      2    818
      1    820
      2    821
      1    823
      3    824
      1    825
      1    827
      1    828
      1    829
      1    830
      2    835
      1    838
      1    841
      1    842
      2    846
      1    847
      1    849
      1    858
      1    862
      1    863
      1    864
      1    871
      1    878
      1    883
      1    885
   1000  count 
```

**Comment by philip-stoev** [comment] 2021-02-11 07:21
@frankmcsherry In order words, with 32 workers even a couple individual invocations of the query will produce distinct results.

I have attached a simplified, all-in-one test case [5622-full.zip](https://github.com/MaterializeInc/materialize/files/5963549/5622-full.zip) that returns the following with 4 workers:

```
...
 count 
-------
     8
(1 row)

 count 
-------
    11
(1 row)

 count 
-------
     9
(1 row)

 count 
-------
     8
(1 row)
...
```

**Comment by frankmcsherry** [comment] 2021-02-11 11:58
Oh this looks very helpful, thank you!

**Comment by frankmcsherry** [comment] 2021-02-11 12:45
I've minimized the example. With 32 workers, the following is consistently inconsistent:
```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE partsupp (
    ps_partkey     integer NOT NULL,
    ps_suppkey     integer NOT NULL
);

CREATE TABLE lineitem (
    l_partkey        integer NOT NULL,
    l_suppkey        integer NOT NULL
);

CREATE INDEX fk_lineitem_partsuppkey ON lineitem (l_partkey ASC, l_suppkey ASC);
INSERT INTO "lineitem" VALUES
    (6,1 );
INSERT INTO "partsupp" VALUES
    (6,1 );

SELECT COUNT(*)  FROM lineitem;
SELECT COUNT(*)  FROM partsupp;

SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
SELECT * FROM lineitem LEFT JOIN partsupp  ON ps_partkey  = l_partkey  AND ps_suppkey  = l_suppkey     ;
```

**Comment by frankmcsherry** [comment] 2021-02-11 12:50
One thought (note to self, as this may make no sense): delta queries (which these joins are) had a quirk where you weren't allowed to compact past the time *minus one*, because they reach a bit in to the past with their `AltNeu` timestamps. That got fixed up in a bunch of other code that saw it, but it is possible we've totally ignored the same thing here.

The DD issue: https://github.com/TimelyDataflow/differential-dataflow/issues/234

**Comment by frankmcsherry** [comment] 2021-02-17 02:36
I can confirm that this seems to be a non-determinism in the `lookup` operator in delta join execution. At least, the multiple runs produce output that looks like this on a "correct" run of the above
```
Path-0: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613529003164, neu: false }, 1)
Path-1: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613529003164, neu: false }, 1)
0-1: (Row{[Int32(6), Int32(1), Int32(6), Int32(1)]}, AltNeu { time: 1613529003164, neu: false }, 1)
JoinOutput: (Row{[Int32(6), Int32(1), Int32(6), Int32(1)]}, 1613529003164, 1)
Path-0: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613529003164, neu: false }, 1)
Path-1: (Row{[Int32(1), Int32(6)]}, AltNeu { time: 1613529003164, neu: false }, 1)
0-1: (Row{[Int32(6), Int32(1), Int32(1), Int32(6)]}, AltNeu { time: 1613529003164, neu: false }, 1)
JoinOutput: (Row{[Int32(6), Int32(1), Int32(1), Int32(6)]}, 1613529003164, 1)
```
where the two repeated fragments are records spilling out of both joins (there are two in this plan; one to discover where to instill null values for the outer join).

On faulty runs, the same reporting produces
```
Path-1: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613527614312, neu: false }, 1)
Path-0: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613527614312, neu: false }, 1)
0-1: (Row{[Int32(6), Int32(1), Int32(6), Int32(1)]}, AltNeu { time: 1613527614312, neu: false }, 1)
JoinOutput: (Row{[Int32(6), Int32(1), Int32(6), Int32(1)]}, 1613527614312, 1)
Path-0: (Row{[Int32(6), Int32(1)]}, AltNeu { time: 1613527614312, neu: false }, 1)
Path-1: (Row{[Int32(1), Int32(6)]}, AltNeu { time: 1613527614312, neu: false }, 1)
```
where the difference is that the lines 
```
0-1: (Row{[Int32(6), Int32(1), Int32(1), Int32(6)]}, AltNeu { time: 1613529003164, neu: false }, 1)
JoinOutput: (Row{[Int32(6), Int32(1), Int32(1), Int32(6)]}, 1613529003164, 1)
```
are missing, these being just after the lookup, and at the end of the delta join fragment.

This seems totally plausible, and is in line with the theory up above that an arrangement may have been allow to compact further than we can permit. I have to figure out which one, though if it is the one the plan above incriminates, it is an arrangement we build ourselves, here:
```
 %4 =                                  +
 | Get %2 (l0)                         +
 | Distinct group=(#1, #0)             +
 | ArrangeBy (#0, #1)                  +
```
I still have to dig in and sort out what sort of state it happens to have before I can sort out why it is glitchy. The second `Path-1` line does mean that the data are there, as they spill out into the second dataflow path just fine. But, for whatever reason we aren't finding them in the arrangement (or something related).

**Comment by frankmcsherry** [comment] 2021-02-17 03:30
More debugging log: it doesn't seem to be an arrangement compaction issue so much as a scheduling issue. For as-yet unclear reasons, the `lookup_map` starts to process a tuple earlier than it should in the faulty case, which results in it not finding the data in the arrangement when it looks. In the correct case, it waits until the arrangement is populated.

**Comment by frankmcsherry** [comment] 2021-02-17 03:38
Well, it looks like the `lookup_map` operator is being told it has an empty input frontier: 
```
4       frontier AntichainRef { frontier: [] } !<= cap AltNeu { time: 0, neu: false }
```
which seems pretty wrong, I think. It's possible that it is correct and that elsewhere something is screwed up, but the inputs derive from tables, and it is possible that there will be further inputs, so an empty frontier seems pretty alarming. No clue yet if progress tracking issue, or weird set-up issue.

**Comment by frankmcsherry** [comment] 2021-02-17 09:27
Should be resolved in https://github.com/TimelyDataflow/timely-dataflow/pull/360

Great to have the additional stress testing!

**Comment by philip-stoev** [comment] 2021-02-17 10:13
@frankmcsherry should I wait for the TimelyDataflow change to be propagated to where a standard "cargo build"  on materialize will pick it up, or I should force a particular TimelyDataflow hash to be linked in and retest?

**Comment by frankmcsherry** [comment] 2021-02-17 12:31
I'll probably merge it today, and PR the updated cargo.lock file for Materialize. If you are bored you can certainly learn about the `patch` directive for `Cargo.toml`, which is how you override what we use with another reference. But, no rush imo (I confirmed that it no longer repro'd on my minimal example, and that it fixes a smaller repro in the timely repository; bigger tests will be good too, but I think it should land anyhow and we can iterate).

**Comment by philip-stoev** [comment] 2021-02-17 12:43
Thank you. I will wait for the merge and learn about the directive simultaneously.

**Closed** 2021-02-18 12:10 UTC
Labels: C-bug
