### ISSUE TITLE
Type coercion of decimal precision doesn't happen across a UNION

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#4686] opened 2020-11-03 14:37 UTC
This might be a more general bug, but a user reports:

```
mz> show columns in value_source;
+-----------------+------------+---------+
| name            | nullable   | type    |
|-----------------+------------+---------|
| this            | False      | text    |
| that            | False      | text    |
| value           | False      | numeric |
+-----------------+------------+---------+
SELECT 4
Time: 0.026s
mz> CREATE MATERIALIZED VIEW value AS
 SELECT this, that, value
 FROM value_source
 UNION
 (SELECT that, this, 1 / value
  FROM value_source);
CREATE SOURCE
UNION types decimal(12, 5) and decimal(38, 11) cannot be matched
```

An easy reproduction confirms this:

```
materialize=> create table value_source (this text, that text, value numeric);
CREATE TABLE
materialize=> create materialized view value as select this, that, value from value_source union (select that, this, 1 / value from value_source);
ERROR:  UNION types decimal(38, 0) and decimal(38, 6) cannot be matched
materialize=> create materialized view value as select this, that, value from value_source union (select that, this, (1 / value)::decimal(38,0) from value_source);
CREATE VIEW
materialize=>
```

Assigned to @sploiselle for triage and potential reassignment. I'm including the original user error for completeness.

**Comment by benesch** [comment] 2020-11-03 14:40
I'll take this one. It's an extension of #4683.

**Comment by benesch** [comment] 2020-11-03 14:41
And is also a duplicate of #3331.

**Closed by benesch** 2020-11-03 14:41 UTC
Labels: C-bug
