### ISSUE TITLE
Add support for PostgreSQL range types

### ISSUE THREAD

**Issue by rotten** [MaterializeInc/materialize#14748] opened 2022-09-09 20:58 UTC
### Feature request

PostgreSQL supports a variety of "range types":  https://www.postgresql.org/docs/current/rangetypes.html#:~:text=PostgreSQL%20comes%20with%20the%20following,of%20numeric%20%2C%20nummultirange%20%E2%80%94%20corresponding%20Multirange

I didn't see an issue on the backlog for this, so I thought I should add it.

I've recently encountered the need to publish a postgrseql table to materialize that has a `daterange` column in it.

At this time we are forced to replicate the whole table because
    1. We are not using postgresql 15 yet - which allows for selected column replication
    2. And because "create views from source" does not permit a partial table to be selected (i'll open a separate issue for this since I don't see an feature request for it yet either).
    
Not supporting this column type means we can't use materialize for our use case.  Unless there is a way to insert the oid into mz_types and throw away the data by stashing it as an unreadable binary or text  field as a temporary work around.

**Comment by morsapaes** [comment] 2022-12-24 16:25
We've started working towards supporting range types with #16796 (though we're targeting internal usage in the first iteration, and not exposing it in the SQL layer just yet).

**Comment by chaas** [comment] 2023-03-09 19:53
@morsapaes / @sploiselle should I close this ticket as a duplicate of #17342?

**Comment by sploiselle** [comment] 2023-03-09 20:24
@chaas Yeah, work in progress has a little more detail there

**Comment by chaas** [comment] 2023-03-09 20:55
Duplicate of #17342

**Closed by chaas** 2023-03-09 20:55 UTC
Labels: C-feature
