### ISSUE TITLE
parallel-workload: all the specified refreshes of the materialized view would be too far in the past, and thus they would never happen

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24288] opened 2024-01-08 22:06 UTC
### What version of Materialize are you using?

d7b5ee0761

### What is the issue?

```
Query failed:
CREATE MATERIALIZED VIEW "db-pw-1704718825-2"."s-6"."v-85" WITH (REFRESH AT mz_now()::string::int8 + 2326280, ASSERT NOT NULL "headers-wh-2-v-44") AS SELECT "db-pw-1704718825-2"."s-2"."v-44"."ih4-wh-2" AS "ih4-wh-2-v-44", "db-pw-1704718825-2"."s-2"."v-44"."ih1-wh-2" AS "ih1-wh-2-v-44", "db-pw-1704718825-2"."s-2"."v-44"."headers-wh-2" AS "headers-wh-2-v-44", "db-pw-1704718825-0"."s-8"."t-30"."c-0-jsonb" AS "c-0-jsonb-t-30", "db-pw-1704718825-0"."s-8"."t-30"."c-7-text" AS "c-7-text-t-30" FROM "db-pw-1704718825-0"."s-8"."t-30" JOIN "db-pw-1704718825-2"."s-2"."v-44" ON TRUE;
{'S': 'ERROR', 'C': '22000', 'M': 'all the specified refreshes of the materialized view would be too far in the past, and thus they would never happen', 'D': 'The specified last refresh is at 1704722361567, while the earliest possible time to compute the materialized view is 1704722797857.'}
```
Seen in https://buildkite.com/materialize/nightlies/builds/5881#018ce922-1007-45fc-b960-02dc00d1d353
Based on a discussion with @ggevay this seems unexpected, thus opening this issue. It only happened on aarch64 so far. (edit: also happened on x86-64 a few times now)

**Comment by def-** [comment] 2024-01-10 09:11
Even specifying the refreshes to be 30 min in the future with https://github.com/MaterializeInc/materialize/pull/24276/files, there are still the same errors: https://buildkite.com/materialize/nightlies/builds/5905#018cf288-07e4-407d-a060-16f64964aae2

**Comment by ggevay** [comment] 2024-01-23 17:20
Looking into this now. @def- could you tell what kind of object `"db-pw-1705970322-0"."s-0"."v-1"` might be in the failing test (table, view, mat view, source) and whether it might be indexed?

**Comment by def-** [comment] 2024-01-23 17:26
```
[MainThread] CREATE MATERIALIZED VIEW "db-pw-1705970322-0"."s-0"."v-1" WITH (REFRESH AT mz_now()::string::int8 + 2985752, ASSERT NOT NULL "c-7-float8-t-9") AS SELECT "db-pw-1705970322-0"."s-0"."t-9"."c-6-map[text=>text]" AS "c-6-map[text=>text]-t-9", "db-pw-1705970322-0"."s-0"."t-6"."c-3-jsonb" AS "c-3-jsonb-t-6", "db-pw-1705970322-0"."s-0"."t-9"."c-9-jsonb" AS "c-9-jsonb-t-9", "db-pw-1705970322-0"."s-0"."t-9"."c-1-float8" AS "c-1-float8-t-9", "db-pw-1705970322-0"."s-0"."t-6"."c-1-float4" AS "c-1-float4-t-6", "db-pw-1705970322-0"."s-0"."t-9"."c-7-float8" AS "c-7-float8-t-9", "db-pw-1705970322-0"."s-0"."t-9"."c-2-float8" AS "c-2-float8-t-9", mz_unsafe.mz_sleep(2) FROM "db-pw-1705970322-0"."s-0"."t-9" JOIN "db-pw-1705970322-0"."s-0"."t-6" ON TRUE;
```
No index.

Via the parallel-workload-queries.log.zst file

**Comment by ggevay** [comment] 2024-01-23 17:49
Ok, I found a simple repro:
```
create table t (x int, y int);

create materialized view mv1 with (refresh at mz_now()::string::int8 + 10000) as
select * from t;

create materialized view mv2 with (refresh at creation) as
select * from mv1;
```

I'll try to figure out what's happening here.

**Comment by ggevay** [comment] 2024-01-23 18:08
Oh, this is actually not a bug! `mv2` wants to read from `mv1`, but `mv1`'s first refresh is later than `mv2`'s first refresh, so `mv2`'s first refresh would never happen (as the error msg says), because it's not possible to read `mv1` at the time of `mv2`'s refresh.

But the "in the past" part of the error msg is misleading, because the specified refresh is not "in the past" in this case, just earlier than the least possible time that we can read from `mv1` (which is 10 seconds from now). I'll think about how to improve the error msg.

@def-
The test could be deflaked by remembering the last random refresh time that we generated, and then generating only later refreshes.

**Comment by def-** [comment] 2024-01-23 22:38
Makes sense, thanks for looking into this, this should fix it: https://github.com/MaterializeInc/materialize/pull/24623

**Comment by ggevay** [comment] 2024-02-07 11:35
Happening again
https://buildkite.com/materialize/nightlies/builds/6343#018d80fc-757d-4dc2-90cf-b5bf0083a200

**Comment by ggevay** [comment] 2024-02-14 15:27
Closing this, as https://github.com/MaterializeInc/materialize/pull/25231 hopefully mitigates this.

(A better long-term fix is tracked in https://github.com/MaterializeInc/materialize/issues/25127.)

**Closed by ggevay** 2024-02-14 15:27 UTC
Labels: C-bug
