### ISSUE TITLE
/sql endpoint does not allow DDLs - "statement can not be run inside a transaction"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#11799] opened 2022-04-14 10:38 UTC
### What version of Materialize are you using?

v0.25.0?

### How did you install Materialize?

Materialize Cloud

### What was the issue?

The /sql endpoint that the cloud will use to send SQL statement to the Platform for execution currently only accepts `SELECT` statements. DDLs  and other such are rejected with "statement can not be used inside a transaction". I assume that running DDLs via the endpoint will be required shortly, so I am opening this ticket now.

**Comment by benesch** [comment] 2022-07-19 06:50
Ah, turns out this was a duplicate of #11938 which I fixed a while back in #11941.

**Closed by benesch** 2022-07-19 06:50 UTC
Labels: C-bug, A-platform, M-platform-blocker, A-ADAPTER
