### ISSUE TITLE
doc: more explicit information about Postgres compatibility

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#10563] opened 2022-02-09 18:47 UTC
### What pages are affected?

I believe the only place we reference our Postgres compatibility is on the "[SQL Overview](https://materialize.com/docs/sql/)" page of the docs.

<img width="594" alt="Screen Shot 2022-02-09 at 10 41 29 AM" src="https://user-images.githubusercontent.com/5766027/153268099-df430320-2d0c-460c-a21b-80eca944558a.png">

### What needs to be changed or added?

I think we should add an entire "PostgreSQL Compatibility" page to our docs because: 
1. It's kind of unclear right now! "We model our implementation after PostgreSQL" could mean a lot of different things, and it doesn't look like it's giving the impression we want currently. ([A blog that linked Postgres-compatible tools](https://datastation.multiprocess.io/blog/2022-02-08-the-world-of-postgresql-wire-compatibility.html) linked us, and then claimed we have a "custom SQL dialect".)
2. It would give us a space to explain _why_ we're aiming for Postgres compatibility, and a natural link to our driver and ecosystem pages.
2. It is probably a good search term to match on.

### Feature description

Courtesy of that [blog post from DataStation](https://datastation.multiprocess.io/blog/2022-02-08-the-world-of-postgresql-wire-compatibility.html), here are links to how other companies explain that they're Postgres compatible:
- [Cockroach docs](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html) and [blog post](https://www.cockroachlabs.com/blog/why-postgres/)
- [Spanner](https://cloud.google.com/blog/topics/developers-practitioners/postgresql-interface-adds-familiarity-and-portability-cloud-spanner) announcement
- [crate.io](https://crate.io/docs/crate/reference/en/4.7/appendices/compatibility.html)
- [QuestDB](https://questdb.io/docs/reference/api/postgres/)

**Comment by JLDLaughlin** [comment] 2022-02-09 18:48
cc @ruf-io

**Comment by ruf-io** [comment] 2022-02-09 18:53
OK to merge this with https://github.com/MaterializeInc/materialize/issues/8396

**Comment by JLDLaughlin** [comment] 2022-02-10 17:53
yes!

**Comment by ruf-io** [comment] 2022-02-10 19:37
Duplicate of #8396 - will move info there.

**Closed by ruf-io** 2022-02-10 19:37 UTC
Labels: A-docs
