### ISSUE TITLE
Listing databases with "\l" throws Parse error when running against fresh materialized install

### ISSUE THREAD

**Issue by theronic** [MaterializeInc/materialize#2156] opened 2020-03-02 11:04 UTC
On OSX, terminal 1:

    brew install MaterializeInc/materialize/materialized
    materialized

Terminal 2:

```
psql -h localhost -p 6875 materialize                                                                                  ✔  10150  13:00:00
psql (10.4, server 9.5.0)
Type "help" for help.

materialize=> \l
ERROR:  Parse error:
       pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
                                             ^^^^
Expected ), found: '\n'
materialize=>
```

Furthermore, if I replace E'\n' with just '\n', I get the following:

```
materialize=> select * from pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges";
ERROR:  Parse error:
select * from pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges";
                                                    ^^^^
Expected ), found: '\n'
materialize=> select * from pg_catalog.array_to_string(d.datacl, '\n') AS "Access privileges";
ERROR:  qualified function names are not supported
```

**Comment by umanwizard** [comment] 2020-03-02 13:35
Confirmed, thanks for the report.

**Comment by umanwizard** [comment] 2020-03-02 13:37
This is caused by a more general issue: (currently) incomplete support in Materialize for certain Postgres-specific queries generated by `psql`.

To get unblocked in the immediate term: `show databases` will let you list the user databases in Materialize.

**Comment by theronic** [comment] 2020-03-02 14:39
Thanks. Curiously, `\c` works:

![image](https://user-images.githubusercontent.com/1011676/75686086-534a6d80-5ca4-11ea-8ecd-50d90791396f.png)

**Comment by umanwizard** [comment] 2020-03-02 16:43
That is expected, since the `\c` meta-command does not cause the client to send any SQL to the server, but instead just causes `psql` to print some of its internal state.

**Comment by umanwizard** [comment] 2020-03-02 16:45
@theronic At the company, many of us are using https://github.com/materializeinc/mzcli instead of `psql`, which you might find does a better job of avoiding sending postgres-specific stuff (but @quodlibetor would know for sure).

Anyway, I recommend trying it -- it has nice features like syntax highlighting.

**Comment by rjnn** [comment] 2020-09-22 19:01
@awang we should solve this before going further down `pg_catalog` for more complicated things like Hasura. This gives a good first impression to users, and at this point we should just burn down the various queries like `\l`, `ld` since each emits a fixed `pg_catalog` query

**Comment by mjibson** [comment] 2020-09-22 20:16
In addition to the pg_catalog additions, this also demonstrates a need to improve literal handling to support tokens like `E'\n'`.

**Comment by JLDLaughlin** [comment] 2020-09-22 21:54
The query issued by `psql` when `\` is run:
```
SELECT d.datname AS "Name", pg_catalog.pg_get_userbyid(d.datdba) AS "Owner", pg_catalog.pg_encoding_to_char(d.encoding) AS "Encoding", d.datcollate AS "Collate", d.datctype AS "Ctype", pg_catalog.array_to_string(d.datacl, '
') AS "Access privileges" FROM pg_catalog.pg_database AS d ORDER BY 1
```

**Comment by JLDLaughlin** [comment] 2020-09-22 22:21
It looks like supporting `\l` will require supporting:
- Qualified function names: https://github.com/MaterializeInc/materialize/issues/4258
- `pg_catalog.Pg_get_userbyid()`: https://github.com/MaterializeInc/materialize/issues/4272
- `pg_catalog.Pg_encoding_to_char()`: https://github.com/MaterializeInc/materialize/issues/4273
-  `pg_catalog.Array_to_string`: https://github.com/MaterializeInc/materialize/issues/4274
- `pg_catalog.pg_database`: https://github.com/MaterializeInc/materialize/issues/4275

**Comment by JLDLaughlin** [comment] 2020-09-22 23:04
On second thought, qualified function names aren't necessary to complete this issue!

**Comment by quodlibetor** [comment] 2020-09-23 01:27
> theronic At the company, many of us are using https://github.com/materializeinc/mzcli instead of psql, which you might find does a better job of avoiding sending postgres-specific stuff

mzcli is unlikely to help in this case: it will still send this specific command if you request it by typing a  literal `\l`, but it is easier for us to intercept and send something that materialized can handle. Currently we don't intercept any of the backslash commands, as we've always intended to support pg_catalog and no one has asked specifically, yet.

That said, the fact that `mzcli` has autocomplete that generally works means that exploring databases is less reliant on psql magic commands (in my experience). And any bugs in it are much easier for us to fix than in psql.

**Comment by benesch** [comment] 2020-09-24 04:35
> In addition to the pg_catalog additions, this also demonstrates a need to improve literal handling to support tokens like `E'\n'`.

Good news on this front: support for `E` string literals was added in v0.3.1, which shipped after this issue was filed!

**Comment by JLDLaughlin** [comment] 2020-10-09 14:48
We now support `\l`! `\l` works currently off `main`, and will be included in the next release.

**Closed by JLDLaughlin** 2020-10-09 14:48 UTC
Labels: A-integration, A-sql, C-bug
