### ISSUE TITLE
Schema resolution/validation errors cause a hot retry loop on Schema Registry.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#4180] opened 2020-09-10 16:53 UTC
We should be caching the failure in SchemaCache.

**Comment by umanwizard** [comment] 2020-09-10 17:14
This is made a bit annoying by the fact that anyhow::Error isn't Clone.

**Comment by benesch** [comment] 2020-09-10 18:39
Duplicate of #3576.

**Closed by benesch** 2020-09-10 18:39 UTC
Labels: C-bug
