### ISSUE TITLE
demo/billing minor bugs and notes

### ISSUE THREAD

**Issue by z3n-badam** [MaterializeInc/materialize#2770] opened 2020-04-24 17:01 UTC
The demo/billing example has a few gotchas. Using docker for Mac on Catalina.

Connecting with pgsql needs to use the port mapped by docker rather than 6875

After initially connecting, the `SHOW sources;` command works promptly as expected. However, subsequent commands recommended in the demo have a very long initial startup time - so long that it appears they are hung. Probably worth noting that there may be a long delay and to just wait - like, get coffee wait.

The demo appears to be non-recoverable after shutting it down. Destroying all docker containers and starting over appears to work fine.

**Comment by rjnn** [comment] 2020-04-24 19:34
This is very true! Thanks for raising this, we should fix that. In the meantime - not to excuse us from documenting this - we hope to change this over the next couple of releases! In particular, as we add in persistence of sources to disk, shutting things down and starting them back up should work fine. So part of the confusion here is we've mixed up 'how things will eventually be' with 'how things are right now'.

This has happened before in other areas, so its an important point, so thank you for bringing that to our attention! We'll fix this up in the text.

**Comment by ruchirK** [comment] 2020-05-13 02:39
Hi @z3n-badam thanks for filing this and apologies for my late response! I can confirm that the port binding issue + the container nonrecoverability issues reproduce for me as well -- I'm going to see if I can't diagnose that right now.

Unfortunately, I can't reproduce the slowness you were observing with queries on my laptop. Just to double check -- were you running the demo with a 1000 messages (the default) value? On my laptop every query in the instructions returns in < 100 ms

**Comment by ruchirK** [comment] 2020-05-13 20:12
Hi @z3n-badam the port binding and reusability issues should now be resolved if you `git fetch` to get latest master and run `./mzcompose up` again it should pull down fresh containers and do the right thing.

Let me know if the slowness still happens for you. Thanks again for filing the issue!

**Comment by ruchirK** [comment] 2020-06-08 17:11
Closing this for now! @z3n-badam if you run into the performance issues again feel free to reopen. Thanks again!

**Closed by ruchirK** 2020-06-08 17:11 UTC
Labels: A-docs, C-bug, U-community
