### ISSUE TITLE
Postgres sources stuck in status STARTING even though they are running. 

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/materialize#24079] opened 2023-12-21 18:43 UTC
### What version of Materialize are you using?

v0.80.2 

### What is the issue?

Postgres sources only show status STARTING even though they are running and queryable.

**Comment by benesch** [comment] 2023-12-21 18:53
Duplicate of https://github.com/MaterializeInc/materialize/issues/24044.

**Closed by benesch** 2023-12-21 18:53 UTC
Labels: C-bug, A-STORAGE
