### ISSUE TITLE
process orchestrator: mz_cluster::communication: failed to listen on address ... Address already in use

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17845] opened 2023-02-27 08:21 UTC
### What version of Materialize are you using?

v0.45.0-dev (e1619e7f5)

### How did you install Materialize?

Docker image

### What is the issue?

The process orchestrator has started failing as seen below. 

https://buildkite.com/materialize/release-qualification/builds/96#01868330-89c3-4ee4-b4b9-fea49452d097

ci-regexp: failed to listen on address

@benesch how should I route those process orchestrator issues?

### Relevant log output

```source
zippy-materialized-1     | cluster-u1-replica-364: 2023-02-26T03:42:46.626706Z  WARN mz_cluster::communication: failed to listen on address /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-364/compute-0: Address already in use (os error 98)
zippy-materialized-1     | cluster-u1-replica-364: 2023-02-26T03:42:46.631149Z  WARN mz_cluster::communication: failed to listen on address /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-364/compute-2: Address already in use (os error 98)
zippy-materialized-1     | cluster-u1-replica-364: 2023-02-26T03:42:47.627636Z  WARN mz_cluster::communication: failed to listen on address /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-364/compute-0: Address already in use (os error 98)
zippy-materialized-1     | cluster-u1-replica-364: 2023-02-26T03:42:47.632333Z  WARN mz_cluster::communication: failed to listen on address /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-364/compute-2: Address already in use (os error 98)
```

**Comment by benesch** [comment] 2023-02-27 13:38
I think in this particular case either @guswynn or @umanwizard would be well suited to look into this. Routing them to me for triage is good in the meantime, though!

Going to assign this one to the compute team for lack of a better home.

**Comment by umanwizard** [comment] 2023-02-28 19:01
@philip-stoev is this easily reproducible?

**Comment by philip-stoev** [comment] 2023-03-28 06:52
Happened again https://buildkite.com/materialize/release-qualification/builds/142#01871b45-db3d-4a55-821a-79e930903fe3 , so once per month I guess.

**Comment by philip-stoev** [comment] 2023-03-31 06:57
@umanwizard Our CI log processing script also ignores ERROR lines :-(

**Comment by philip-stoev** [comment] 2023-03-31 06:57
Once this is figured out, consider reverting https://github.com/MaterializeInc/materialize/pull/18500

**Comment by umanwizard** [comment] 2023-04-11 15:50
If this is only happening in the process orchestrator, it is owned by @benesch (per CODEOWNERS), reassigning to him. Feel free to assign back to me if we have evidence that this is happening with the kubernetes orchestrator on normal TCP sockets (as opposed to Unix-domain sockets)

**Comment by benesch** [comment] 2023-04-11 17:22
Clearing my assignment, because I simply don't have the bandwidth. 

Let's come up with a shared ownership model for the process orchestrator (cc @antiguru). I would still like to be CC'd on all reviews but I do not have the bandwidth to make improvements myself.

@philip-stoev — it looks like Zippy is not running `environmentd` with `INFO` logging enabled. It seems to be limited to WARN and ERROR logs. This makes this issue very difficult to track down. Can we change this?

**Comment by benesch** [comment] 2023-04-11 17:34
@umanwizard I think this is broken on the cluster replica side, though. Here is how this can go wrong:

  1. Cluster replica process binds successfully to UDS (e.g. /tmp/cluster-u1-replica-1-0).
  2. Timely initialization fails (e.g. because another process in the replica does not boot successfully) but cluster replica process stays online.
  3. Timely initialization is retried, but cluster replica process cannot bind to the UDS because ... it previously bound to the UDS.

The fix may be as simple as moving the code that unlinks stale UDS sockets from [here](https://github.com/MaterializeInc/materialize/blob/9fb85a99955f2ddd580b807e0de320419355d0fe/src/orchestrator-process/src/lib.rs#L523-L529) to immediately before the `bind` call in `clusterd`.

**Comment by umanwizard** [comment] 2023-04-14 18:02
It's possible that's true, I just have no idea how the process orchestrator/UDS stuff works, and wasn't involved at all in developing it, so I can't evaluate the plausibility of any fix without learning a new huge chunk of code.

**Comment by benesch** [comment] 2023-04-25 04:34
> It's possible that's true, I just have no idea how the process orchestrator/UDS stuff works, and wasn't involved at all in developing it, so I can't evaluate the plausibility of any fix without learning a new huge chunk of code.

I think you undersell your capabilities. Regardless, I put up a candidate fix: https://github.com/MaterializeInc/materialize/pull/18937. Are you up for the review? It is hopefully quick. 

If not, perhaps @teskje can suggest someone else from the compute team who might be willing to skill up on this code.

**Comment by tokenrove** [comment] 2023-04-25 11:44
The suggested fix looks reasonable but I'm more than happy to take issues around this if they come up again.

**Closed** 2023-04-25 14:36 UTC
Labels: C-bug
