### ISSUE TITLE
materialized-view-refresh-options.td:215:1: error: non-matching rows with read frontiers

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25157] opened 2024-02-11 22:08 UTC
### What version of Materialize are you using?

5ea509e5c848

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/75427
```
> SELECT ft.read_frontier > fm.read_frontier
FROM mz_internal.mz_frontiers fm
JOIN mz_materialized_views m ON (m.id = fm.object_id)
JOIN mz_internal.mz_frontiers ft ON (true)
JOIN mz_tables t ON (t.id = ft.object_id)
WHERE m.name = 'mv7' AND t.name = 't4'
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 21s
^^^ +++
materialized-view-refresh-options.td:215:1: error: non-matching rows: expected:
[["true"]]
got:
[["false"]]
Poor diff:
+ false
- true

     |
  10 | $ postgres-execute c ... [rest of line truncated for security]
 214 | 
 215 | > SELECT ft.read_frontier > fm.read_frontier
     | ^
```
Seems to be a flake, haven't seen it before. The test was merged 1 week ago: https://github.com/MaterializeInc/materialize/pull/24487

ci-regexp: materialized-view-refresh-options.td:215:1: error: non-matching rows

**Comment by nrainer-materialize** [comment] 2024-02-12 10:21
This also occurred in [Nightly in "testdrive with SIZE 8".](https://buildkite.com/materialize/nightlies/builds/6398#018d9cd3-5f4f-4f2d-88a5-36498ab5658b)

**Comment by nrainer-materialize** [comment] 2024-02-13 08:34
Further occurrence in [Nightly in "testdrive 4 replicas".](https://buildkite.com/materialize/nightlies/builds/6413#018d9fe0-2841-4208-8603-d3a134bcee1a)

**Comment by teskje** [comment] 2024-02-13 09:11
I have tried to reproduce this on a scratch instance by running this loop for a night, with no success:
```
export BUILDKITE_PARALLEL_JOB=5
export BUILDKITE_PARALLEL_JOB_COUNT=8
while true; do bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default || break; done
```

Looking at the service logs of the various failed CI runs, nothing jumps out either. We see that both replicas acknowledge the creation of `mv7` and then silence for a while. I'm not sure if the silence indicates some kind of hang or if no further log messages are expected while testdrive is retrying the frontier query.

```
testdrive-materialized-1     | environmentd: 2024-02-13T01:33:12.034521Z  INFO message_command:coord::handle_execute{session="8a615c8b-a94d-413f-96d1-d86a05ef772b"}:coord::handle_execute_inner{stmt="CREATE MATERIALIZED VIEW mv7 IN CLUSTER refresh_cluster WITH (REFRESH = AT CREATION) AS SELECT * FROM t4"}:sequence_create_materialized_view:create_materialized_view_finish:coord::catalog_transact_with_side_effects:coord::catalog_transact_with_side_effects::side_effects_fut: mz_compute_client::controller::instance: creating dataflow name=materialized_view_refresh_options.public.mv7 import_ids=[u1211] export_ids=[u1213] as_of=[1707787991708] until=[1707787991709]
testdrive-materialized-1     | cluster-u238-replica-u260: 2024-02-13T01:33:12.035252Z  INFO mz_compute::compute_state: creating dataflow name=materialized_view_refresh_options.public.mv7 import_ids=[u1211] export_ids=[u1213] as_of=[1707787991708] until=[1707787991709]
testdrive-materialized-1     | cluster-u238-replica-u261: 2024-02-13T01:33:12.035314Z  INFO mz_compute::compute_state: creating dataflow name=materialized_view_refresh_options.public.mv7 import_ids=[u1211] export_ids=[u1213] as_of=[1707787991708] until=[1707787991709]
testdrive-materialized-1     | environmentd: 2024-02-13T01:35:15.339991Z  INFO message_command:coord::handle_execute{session="95c6957c-3a8a-49db-8ce0-58aea00febc4"}:coord::handle_execute_inner{stmt="ALTER SYSTEM RESET ALL"}:sequence_alter_system_reset_all:coord::catalog_transact:coord::catalog_transact_with:coord::catalog_transact_with::finalize: mz_timestamp_oracle::postgres_oracle: Applying configuration update! params=PostgresTimestampOracleParameters { pg_connection_pool_max_size: Some(50), pg_connection_pool_max_wait: Some(Some(60s)), pg_connection_pool_ttl: Some(300s), pg_connection_pool_ttl_stagger: Some(6s), pg_connection_pool_connect_timeout: Some(5s), pg_connection_pool_tcp_user_timeout: Some(30s) }
```

**Comment by nrainer-materialize** [comment] 2024-02-13 09:44
@teskje: If it helps, we could try to spin up an AWS instance to repro it.

**Comment by teskje** [comment] 2024-02-13 09:49
My attempts were on a scratch instance (`big-dev-box`). I was assuming this is close enough to the CI instances, but if that's not the case trying on a different one might be worth a shot!

**Comment by nrainer-materialize** [comment] 2024-02-13 13:24
I will prepare one.

**Comment by ggevay** [comment] 2024-02-15 10:51
This also happened now locally for me. I'm on Intel x86, Arch Linux. It might also matter that I was running a release build in the background, so the CPU was heavily occupied.

**Comment by teskje** [comment] 2024-02-15 14:41
I finally managed to get this reproduced in a useful way. Looks like it's an actual bug in compute, not a weird interaction with the tests.

The table read frontier is held back exactly to the read frontier of the MV: 
```sql
materialize=> select name, read_frontier, write_frontier from mz_internal.mz_frontiers join mz_objects on (id = object_id) where name in ('t4', 'mv7');
 name | read_frontier | write_frontier
------+---------------+----------------
 mv7  | 1708003020295 |
 t4   | 1708003020295 | 1708004651430
(2 rows)
```

If we look at the per-replica frontiers, we see that only one replica has reported the empty frontier for the MV:
```sql
materialize=> select name, replica_id, write_frontier from mz_internal.mz_cluster_replica_frontiers join mz_objects on (id = object_id) where name = 'mv7';
 name | replica_id | write_frontier
------+------------+----------------
 mv7  | u37        |
 mv7  | u38        | 1708003020295
(2 rows)
```

We can run introspection queries to find out more about the state of this replica.

First of all: The queries still respond. This rules out the possibility that the replica somehow got wedged or crashed.

The replica's reported frontier agrees with that known to the compute controller. This rules out a bug in frontier communication.
```sql
materialize=> select time from mz_internal.mz_compute_frontiers join mz_objects on (id = export_id) where name = 'mv7';
     time
---------------
 1708003020295
(1 row)
```

Dataflow operators also still exist:
```sql
materialize=> select * from mz_internal.mz_dataflow_operator_dataflows where dataflow_name like '%mv7' order by id;
 id  |                           name                            | dataflow_id |                     dataflow_name
-----+-----------------------------------------------------------+-------------+--------------------------------------------------------
 325 | Dataflow: materialized_view_refresh_options.public.mv7    | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 353 | txns_progress_source(u149)                                | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 355 | FlatMap                                                   | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 357 | Exchange                                                  | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 359 | Map                                                       | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 361 | txns_progress_frontiers(u149)                             | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 376 | Source(User(149))                                         | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 378 | InputRegion: materialized_view_refresh_options.public.mv7 | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 436 | Feedback                                                  | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 437 | persist_sink u151 mint_batch_descriptions                 | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 441 | InspectBatch                                              | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 443 | persist_sink u151 write_batches                           | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 445 | FlatMap                                                   | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 447 | Exchange                                                  | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 449 | Map                                                       | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 454 | InspectBatch                                              | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 456 | persist_sink u151 append_batches                          | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 462 | PersistSink(User(151))                                    | 7           | Dataflow: materialized_view_refresh_options.public.mv7
(18 rows)
```

But note that most dataflow operators are missing! It seems like what's left is parts of `persist_source` and `persist_sink`, but the whole `BuildRegion` is gone. That means that the `persist_source` must have advanced to the empty frontier and most of the operators have observed this.

For comparison, here are the operators still around on the replica that did advance to the empty frontier:

```sql
materialize=> select * from mz_internal.mz_dataflow_operator_dataflows where dataflow_name like '%mv7' order by id;
 id  |                           name                            | dataflow_id |                     dataflow_name
-----+-----------------------------------------------------------+-------------+--------------------------------------------------------
 325 | Dataflow: materialized_view_refresh_options.public.mv7    | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 353 | txns_progress_source(u149)                                | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 355 | FlatMap                                                   | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 357 | Exchange                                                  | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 359 | Map                                                       | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 361 | txns_progress_frontiers(u149)                             | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 376 | Source(User(149))                                         | 7           | Dataflow: materialized_view_refresh_options.public.mv7
 378 | InputRegion: materialized_view_refresh_options.public.mv7 | 7           | Dataflow: materialized_view_refresh_options.public.mv7
(8 rows)
```

It seems like the `tens_progress` operators just don't clean up after themselves, which is probably a separate issue. But on this operator the `persist_sink` has been cleaned up.

There are two things that are strange about this and that I need to dig into:
* Neither of the two replicas seems to have received an `AllowCompaction([])` command (otherwise the `tens_progress` operators would have been dropped as well). But they should have, since we don't need to keep around the MV anymore when one replica has advanced to the empty frontier.
* Why is the `persist_sink` stuck on the second replica? Does it get confused about things advancing to the empty frontier?

**Comment by teskje** [comment] 2024-02-16 15:32
Figured it out. There are actually two bugs!

* `persist_sink` can get stuck when other replicas advance the output shard to the empty frontier concurrently. See https://github.com/MaterializeInc/materialize/issues/25316 for details.
* The compute controller has a bug where it always applies replica frontier updates as global frontier updates, even when that means the global frontier regresses. Fixed in https://github.com/MaterializeInc/materialize/pull/25329.

To make `materialized-view-refresh-options.td` fail, the following sequence of events had to happen:

* Materialized view `mv7` is created reading from table `t4`.
* The compute controller installs the `mv7` dataflow on both replicas in the `refresh_cluster`.
* Replica 1 processes the snapshot and advances `mv7`'s frontier to the `as_of` and then to the empty frontier `[]`.
* The compute controller observes the advancement to the empty frontier and advances `mv7`'s global frontier to the empty frontier.
  * This makes it drop the `implied_capability` for `mv7`, but not the `warmup_capability`, since the warmup capabilities are only downgraded once per second. So `mv7`'s read frontier does not advance to the empty frontier yet and no `AllowCompaction(mv7, [])` command is sent.
* Replica 2 processes the snapshot and advances `mv7`'s frontier to the `as_of`, but then becomes stuck (because of #25316).
* The compute controller observes the advancement to the `as_of` and sets `mv7`'s global frontier to the `as_of` as well (because of https://github.com/MaterializeInc/materialize/pull/25329).
* The compute controller updates the warmup capabilities. It has special handling that drops capabilities for collections that have advanced to the empty frontier, but `mv7`'s write frontier is at `as_of`, so its `warmup_capability` is kept.

And this leaves us in this state were replica 2 does not advance `mv7` to the empty frontier because the `persist_sink` is stuck, and the compute controller never sends `AllowCompaction(mv7, [])` (which would allow replica 2 to drop the dataflow) because it thinks `mv7`'s write frontier is still at the `as_of`. We keep per-replica read holds on dataflow inputs, which is why the read frontier of `t4` cannot advance, which is what makes the test fail.

Both of the described bugs are necessary to make the test fail, so in a way we were lucky. https://github.com/MaterializeInc/materialize/pull/25329 is the more serious of the two, but fortunately also easy to fix. https://github.com/MaterializeInc/materialize/issues/25316 is not really an issue if `AllowCompaction` commands are sent correctly, it's more of a smell.

**Closed** 2024-02-16 17:21 UTC
Labels: C-bug, ci-flake
