### ISSUE TITLE
coverage: cargo-test mz::local tests::test_local fails

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25976] opened 2024-03-13 07:37 UTC
### What version of Materialize are you using?

main

### What is the issue?

```
2024-03-12 23:02:51 UTC	Output: The profile name 'default' already exists. You can either use 'mz profile init -f' to replace it or 'mz profile init --profile <PROFILE>' to choose another name.
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	Output: The profile name 'alternative' already exists. You can either use 'mz profile init -f' to replace it or 'mz profile init --profile <PROFILE>' to choose another name.
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	thread 'tests::test_local' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5:
2024-03-12 23:02:51 UTC	Unexpected failure.
2024-03-12 23:02:51 UTC	code-<interrupted>
2024-03-12 23:02:51 UTC	stderr=```""```
2024-03-12 23:02:51 UTC	command=`"/mnt/build/llvm-cov-target/release/mz" "profile" "config" "get" "region" "--profile" "alternative" "--config" "/home/materialize/.cache/materialize/mz_test_config.toml"`
2024-03-12 23:02:51 UTC	code=<interrupted>
2024-03-12 23:02:51 UTC	stdout="aws/eu-west-1\n"
2024-03-12 23:02:51 UTC	stderr=""
2024-03-12 23:02:51 UTC	
2024-03-12 23:02:51 UTC	stack backtrace:
2024-03-12 23:02:51 UTC	   0: rust_begin_unwind
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
2024-03-12 23:02:51 UTC	   1: core::panicking::panic_fmt
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
2024-03-12 23:02:51 UTC	   2: core::panicking::panic_display::<assert_cmd::assert::AssertError>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
2024-03-12 23:02:51 UTC	   3: <assert_cmd::assert::AssertError>::panic::<assert_cmd::assert::Assert>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:26:9
2024-03-12 23:02:51 UTC	   4: <<assert_cmd::assert::AssertError>::panic<assert_cmd::assert::Assert> as core::ops::function::FnOnce<(assert_cmd::assert::AssertError,)>>::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	   5: <core::result::Result<assert_cmd::assert::Assert, assert_cmd::assert::AssertError>>::unwrap_or_else::<<assert_cmd::assert::AssertError>::panic<assert_cmd::assert::Assert>>
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1426:23
2024-03-12 23:02:51 UTC	   6: <assert_cmd::assert::Assert>::success
2024-03-12 23:02:51 UTC	             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/assert_cmd-2.0.5/src/assert.rs:156:28
2024-03-12 23:02:51 UTC	   7: local::tests::test_local::test_impl
2024-03-12 23:02:51 UTC	             at ./tests/local.rs:151:23
2024-03-12 23:02:51 UTC	   8: local::tests::test_local::{closure#0}
2024-03-12 23:02:51 UTC	             at ./tests/local.rs:101:20
2024-03-12 23:02:51 UTC	   9: <local::tests::test_local::{closure#0} as core::ops::function::FnOnce<()>>::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	  10: core::ops::function::FnOnce::call_once
2024-03-12 23:02:51 UTC	             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
2024-03-12 23:02:51 UTC	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in coverage build in https://buildkite.com/materialize/coverage/builds/392#018e34a8-85be-4805-b662-1c26eefcd298 but probably just timing dependent. This is currently blocking cargo-test from finishing in coverage tests, so pretty annoying. This code was previously written by Joaquin. @chaas Is the surfaces team the right assignee for the issue?

ci-regexp: thread 'tests::test_local' panicked

**Comment by nrainer-materialize** [comment] 2024-03-13 07:43
Further occurrence: https://buildkite.com/materialize/coverage/builds/388

**Comment by chaas** [comment] 2024-03-14 19:36
>  Is the surfaces team the right assignee for the issue?
Yeah, nobody's actively developing `mz`, but we're still the place to route issues.

**Comment by chaas** [comment] 2024-03-14 19:44
I can reproduce this locally. It always happens when I run `cargo test`, but never if I run `cargo test RUST_BACKTRACE=full`. So I agree, probably something with timing, since setting `RUST_BACKTRACE=full` makes the test run slower.

**Comment by bobbyiliev** [comment] 2024-03-25 22:43
I’ll further look into this tomorrow morning!

**Comment by bobbyiliev** [comment] 2024-03-26 13:29
I finally managed to replicate this consistently! I'll work on a patch for this today.

**Comment by bobbyiliev** [comment] 2024-03-26 16:42
Submitted another PR with a possible fix for this: https://github.com/MaterializeInc/materialize/pull/26274 as initially suggested by Dennis this could be just a timing issue.

I was able to replicate a failure on a Linux VM by:

- Simulate high CPU load with `stress --cpu 50`
- In another terminal, run the test
- Similar to the CI, the test failed without any stderr but only a code interruption:


```
running 2 tests
test tests::test_local ... Config path: /home/ubuntu/.cache/materialize/test_local_config_37ba65f1-784a-4373-b5f6-5b0e9066eafb.toml
thread 'tests::test_local' panicked at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code-<interrupted>
stderr=```""```
command=`"/home/ubuntu/materialize/target/debug/mz" "profile" "config" "get" "region" "--profile" "alternative" "--config" "/home/ubuntu/.cache/materialize/test_local_config_37ba65f1-784a-4373-b5f6-5b0e9066eafb.toml"`
code=<interrupted>
stdout=""
stderr=""
```

**Comment by chaas** [comment] 2024-04-10 17:42
Closing this again since it seems the latest fix worked! Please reopen if it fails again

**Closed by chaas** 2024-04-10 17:42 UTC
Labels: C-bug, ci-flake
