### ISSUE TITLE
Kafka Sources: Support accessing message metadata in dataflows

### ISSUE THREAD

**Issue by quodlibetor** [MaterializeInc/materialize#7004] opened 2021-06-08 20:20 UTC
Split off from #5863 , Kafka metadata properties like timestamp, offset, etc have been variously requested either for internal purposes or by users.

**Comment by ruchirK** [comment] 2021-06-08 21:04
Possible duplicate of #1577 and #2268

**Comment by elindsey** [comment] 2021-07-27 13:44
Closing this one as a duplicate of 1577

**Closed by elindsey** 2021-07-27 13:44 UTC
Labels: C-feature
