### ISSUE TITLE
Sink AS OF might end up behind the compaction frontier by the time we create the sink.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5729] opened 2021-02-11 15:41 UTC
Because Kafka sinks are created asynchronously (as they require an admin call to create the topics), it might be the case that when the sink finally ends up being created, we no longer have data for the `AS OF` timestamp, due to compaction.

The proposed solution is to start running the dataflow immediately on `CREATE SINK`, but to insert some buffering in the final operator (or just before it) that will refuse to actually forward the messages to Kafka until it receives a notification that the sink is ready.

This blocks https://github.com/MaterializeInc/materialize/pull/5335 from landing, since that change makes a much tighter compaction window the default, making it more difficult to create sinks. Cc @frankmcsherry , @benesch

**Comment by frankmcsherry** [comment] 2021-02-11 15:42
Possible dupe of https://github.com/MaterializeInc/materialize/issues/5423?

**Comment by umanwizard** [comment] 2021-02-11 15:44
Oh, right. Sorry!

**Closed** 2021-02-11 16:01 UTC
Labels: C-bug
