### ISSUE TITLE
persistence: "panic: Binding with invalid diff" with realtime filtering on source 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#9328] opened 2021-11-29 07:56 UTC
### What version of Materialize are you using?

From the shell:

```
9288038c89f394e5a786053daffc42a14ed105d9
```

### What was the issue?

Running a fragment from `kafka-upsert-sources-new-syntax.td` causes a panic if Mz is run with `--persistent-kafka-upsert-source`:

```
2021-11-29T07:50:56.131776Z ERROR panic: Binding with invalid diff. Binding (SourceTimestamp { partition: Kafka(0), offset: MzOffset { offset: 9 } }, AssignedTimestamp(1638172254699)), diff: -1.
thread: timely:work-3
location: src/dataflow/src/source/mod.rs:1733:21
version: 0.10.1-dev (9288038c89f394e5a786053daffc42a14ed105d9)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:825:21
   1: core::ops::function::Fn::call
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:628:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   6: core::panicking::panic_fmt
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
   7: dataflow::source::SourceReaderPersistence::internal_restore::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/source/mod.rs:1733:21
      core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:269:13
      core::iter::traits::iterator::Iterator::find::check::{{closure}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/traits/iterator.rs:2377:20
      core::iter::traits::iterator::Iterator::try_fold
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/traits/iterator.rs:1994:21
      core::iter::traits::iterator::Iterator::find
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/traits/iterator.rs:2381:9
      <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/adapters/filter.rs:56:9
      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/adapters/map.rs:103:9
      <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
      <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/vec/spec_from_iter.rs:33:9
   8: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/vec/mod.rs:2486:9
      core::iter::traits::iterator::Iterator::collect
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/iter/traits/iterator.rs:1745:9
      dataflow::source::SourceReaderPersistence::internal_restore
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/source/mod.rs:1729:32
      dataflow::source::SourceReaderPersistence::restore
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/source/mod.rs:1638:35
   9: dataflow::source::create_source::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/source/mod.rs:1292:47
      core::result::Result<T,E>::and_then
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:966:22
      dataflow::source::create_source
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/source/mod.rs:1291:26
  10: dataflow::render::sources::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::import_source
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/render/sources.rs:294:56
  11: dataflow::render::build_dataflow::{{closure}}::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/render/mod.rs:222:17
      <timely::dataflow::scopes::child::Child<G,T> as timely::dataflow::scopes::Scope>::scoped
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/fa63c3a/timely/src/dataflow/scopes/child.rs:129:13
      timely::dataflow::scopes::Scope::region_named
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/fa63c3a/timely/src/dataflow/scopes/mod.rs:187:9
  12: dataflow::render::build_dataflow::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/render/mod.rs:205:9
      timely::worker::Worker<A>::dataflow_core
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/fa63c3a/timely/src/worker.rs:639:13
  13: dataflow::render::build_dataflow
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/render/mod.rs:200:5
  14: dataflow::server::Worker<A>::handle_command
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/server.rs:677:21
  15: dataflow::server::Worker<A>::run
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/server.rs:480:17
  16: dataflow::server::serve::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-097598a436e6a733c-1/materialize/tests/src/dataflow/src/server.rs:124:9
      timely::execute::execute::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/fa63c3a/timely/src/execute.rs:285:22
      timely_communication::initialize::initialize_from::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/fa63c3a/communication/src/initialize.rs:316:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:125:18
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:481:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
      std::panicking::try
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:480:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys/unix/thread.rs:106:17
  19: start_thread
  20: clone
```

### Is the issue reproducible? If so, please provide reproduction instructions.

The fragment in question:

```
$ kafka-create-topic topic=realtimefilteravro

$ set keyschema3={
    "type": "record",
    "name": "Key3",
    "fields": [
        {"name": "k1", "type": ["null", "string"]},
        {"name": "k2", "type": ["null", "long"]}
    ]
  }

$ set schema2={
    "type": "record",
    "name": "test2",
    "fields": [
        {"name": "f1", "type": ["null", "string"]},
        {"name": "f2", "type": ["null", "long"]}
    ]
  }

$ kafka-ingest format=avro topic=realtimefilteravro key-format=avro key-schema=${keyschema3} schema=${schema2} publish=true
{"k1": null, "k2": {"long": 2}} {"f1": {"string": "date"}, "f2": {"long": 5}}
{"k1": {"string": "épicerie"}, "k2": {"long": 10}} {"f1": {"string": "melon"}, "f2": {"long": 2}}
{"k1": {"string": "boucherie"}, "k2": {"long": 5}} {"f1": {"string": "apple"}, "f2": {"long": 7}}
{"k1": {"string": "boulangerie"}, "k2": null} {"f1":{"string": "date"}, "f2": {"long": 10}}
{"k1": {"string": "épicerie"}, "k2": {"long": 10}} {"f1": {"string": "pear"}, "f2": {"long": 2}}
{"k1": null, "k2": {"long": 2}} {"f1": {"string": "date"}, "f2": null}
{"k1": {"string": "boulangerie"}, "k2": null} {"f1":null, "f2": {"long": 10}}
{"k1": {"string": "boucherie"}, "k2": {"long": 5}} {"f1": {"string": "apple"}, "f2": {"long": 3}}

> CREATE SOURCE realtimefilteravro
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-realtimefilteravro-${testdrive.seed}'
  KEY FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  VALUE FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

# filter on key only
> CREATE MATERIALIZED VIEW filterforkey AS
  SELECT f1 FROM realtimefilteravro WHERE k1='épicerie';

> SELECT * from filterforkey
f1
----
pear

# filter on value only
> CREATE MATERIALIZED VIEW filterforvalue AS
  SELECT f2 FROM realtimefilteravro WHERE f1='date';

> SELECT * from filterforvalue
f2
-------
<null>

# filter with a predicate containing key + value
> CREATE MATERIALIZED VIEW filterforkeyvalue AS
  SELECT f1, f2 FROM realtimefilteravro WHERE k2+f2=12;

> SELECT * from filterforkeyvalue
f1   f2
-------
pear 2
```

### Please attach any applicable log files.

```
For more details, see https://materialize.com/docs/cli#experimental-mode
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-11-29T07:50:52.017014Z  INFO coord::catalog: create database materialize    
2021-11-29T07:50:52.017038Z  INFO coord::catalog: create schema materialize.public    
2021-11-29T07:50:52.868168Z  INFO coord::catalog: create source materialize.public.realtimefilteravro (u1)    
2021-11-29T07:50:52.888164Z  INFO coord::timestamp: Timestamping Source u1 with Real Time Consistency.    
2021-11-29T07:50:52.892577Z  INFO coord::timestamp: Discovered 1 new (1 total) kafka partitions for topic testdrive-realtimefilteravro-2336810696 (source u1)    
2021-11-29T07:50:52.965427Z  INFO coord::catalog: create view materialize.public.filterforkey (u2)    
2021-11-29T07:50:52.965483Z  INFO coord::catalog: create index materialize.public.filterforkey_primary_idx (u3)    
2021-11-29T07:50:53.425301Z  INFO dataflow::source::kafka: Activating Kafka queue for testdrive-realtimefilteravro-2336810696 [0] (source u1/29) on worker 2    
2021-11-29T07:50:53.647326Z ERROR persist::operators::stream: Error sealing conditional_seal(kafka-u1/29) (primary) up to 1638172252880: invalid seal for Id(3): 1638172252880 not at or in advance of current seal frontier Antichain { elements: [1638172253500] }    
2021-11-29T07:50:53.647364Z ERROR dataflow::render::sources: ("Error sealing conditional_seal(kafka-u1/29) (primary) up to 1638172252880: invalid seal for Id(3): 1638172252880 not at or in advance of current seal frontier Antichain { elements: [1638172253500] }", 1638172252880, 1)    
2021-11-29T07:50:54.684337Z  INFO coord::catalog: create view materialize.public.filterforvalue (u4)    
2021-11-29T07:50:54.684386Z  INFO coord::catalog: create index materialize.public.filterforvalue_primary_idx (u5)    
2021-11-29T07:50:55.028743Z  INFO dataflow::source::kafka: Activating Kafka queue for testdrive-realtimefilteravro-2336810696 [0] (source u1/30) on worker 2    
2021-11-29T07:50:55.116973Z ERROR persist::operators::stream: Error sealing conditional_seal(kafka-u1/30) (condition) up to 1638172254699: invalid seal for Id(2): 1638172254699 not at or in advance of current seal frontier Antichain { elements: [1638172254700] }    
2021-11-29T07:50:55.116994Z ERROR persist::operators::stream: Error sealing conditional_seal(kafka-u1/30) (condition) up to 1638172254700: invalid seal for Id(2): 1638172254700 not at or in advance of current seal frontier Antichain { elements: [1638172255100] }    
2021-11-29T07:50:55.117015Z ERROR dataflow::render::sources: ("Error sealing conditional_seal(kafka-u1/30) (condition) up to 1638172254699: invalid seal for Id(2): 1638172254699 not at or in advance of current seal frontier Antichain { elements: [1638172254700] }", 1638172254699, 1)    
2021-11-29T07:50:55.117027Z ERROR dataflow::render::sources: ("Error sealing conditional_seal(kafka-u1/30) (condition) up to 1638172254700: invalid seal for Id(2): 1638172254700 not at or in advance of current seal frontier Antichain { elements: [1638172255100] }", 1638172254700, 1)    
2021-11-29T07:50:55.204204Z  INFO coord::catalog: create view materialize.public.filterforkeyvalue (u6)    
2021-11-29T07:50:55.204257Z  INFO coord::catalog: create index materialize.public.filterforkeyvalue_primary_idx (u7)    
2021-11-29T07:50:56.131776Z ERROR panic: Binding with invalid diff. Binding (SourceTimestamp { partition: Kafka(0), offset: MzOffset { offset: 9 } }, AssignedTimestamp(1638172254699)), diff: -1.
```

**Comment by philip-stoev** [comment] 2021-11-29 07:59
Running the test again (preserving the mzdata directory across runs) results in panic on Mz startup:

```
foo.td:50:1: error: executing query failed: db error: ERROR: Source error: kafka-u4/31-upsert: persistence: In persist(kafka-u4/31-upsert), error writing data for time 1638172162099: update for Id(5) with time 1638172162099 before sealed frontier: Antichain { elements: [1638172163000] }
```

The same error may be returned on the SQL query instead:
```
foo.td:50:1: error: executing query failed: db error: ERROR: Source error: kafka-u4/31-upsert: persistence: In persist(kafka-u4/31-upsert), error writing data for time 1638172162099: update for Id(5) with time 1638172162099 before sealed frontier: Antichain { elements: [1638172163000] }
     |
  49 | 
  50 | > SELECT * from filterforvalue
     | ^
```

**Comment by aljoscha** [comment] 2021-11-29 13:23
I'm afraid this is the second known bug on #8810 (haven't get spun this out into a separate bug/issue but will do so now.

The problem is that multiple instances of the same source, which is what is being created for each of the `MATERIALIZED VIEW` statements, will clash with each other because they will try and write to the same underlying persisted collection.

I wanted to fix this by disallowing multiple instantiations of the same source, because it would be wasteful to write the same data to persistence multiple times. An alternative solution would be to really create three separate instances of the same source but make sure that they don't clash by creating unique persistence names.

You can prevent creating multiple instances of the source by turning the one source into a `MATERIALIZED SOURCE`, which will make it so that we only have one instance of the source. (That's not a real fix for this, of course...)

**Closed by aljoscha** 2021-11-29 13:23 UTC
Labels: C-bug, A-persistence
