### ISSUE TITLE
storage/sources: invert subsource dependencies

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#24773] opened 2024-01-28 04:38 UTC
## Product outcome

Sources depend on their subsources, rather than the other way around.

This makes various queries that follow dependencies through the catalog (e.g., the workflow graph in the console) much easier to write.

## Work items

* [x] #24773
* [x] #24235
* [ ] Clean up state for subsource shards? #8185

## Decision log

* **15 March 2024.** Slip release date to Mar 29, still with low confidence, due to picking up some blocking pv2 work.
* **21 February 2024.** Updating release date to Mar 20 with low confidence. We're now prioritizing this work ahead of RTR as it turns out to be blocking RTR.
* **27 January 2024.** Issue created.

cc @sploiselle

**Comment by benesch** [comment] 2024-02-22 03:23
@sploiselle I tossed in a release date of Mar 20 with low confidence. Let me know if you feel like that's way off base. But I wanted to get a tighter bound on the books now that we're prioritizing this work ahead of RTR.

**Comment by sploiselle** [comment] 2024-05-08 15:27
This is re-opened due to #26976––which was caused by merging #26826 (which originally closed this issue).

**Closed** 2024-06-10 10:06 UTC
Labels: Epic, A-storage, T-subsource
