### ISSUE TITLE
materialize enters into a restart loop if computed crashes

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12091] opened 2022-04-27 11:48 UTC
### What version of Materialize are you using?

materialized v0.26.1-dev (826b2ae90)

### How did you install Materialize?

Built from source

### What was the issue?

If computed crashes because of a SQL query that triggers a bug, the following will happen:

1. the SQL client will hang
2. materialized will keep restarting computed over and over again

Instead, the following should have happened:

1. The SQL client should have received some error indication
2. materialized should have restarted computed, but computed should have stayed up unless another crashing query is submitted 

To reproduce:

```
create table t1 (f1 text);
insert into t1 values ('abc');
select mz_internal.mz_panic(f1) from t1;
```

The same thing happens with materialized views -- there, the excuse could be that the view is crashing on startup as it is being re-hydrated. But even in this case I think there is a solution -- a view should have been automatically marked as crashing so that it is not rehydrated on startup, unless the `ALTER TABLE ENABLE INDEXES` option is in effect, that is, an extension of sorts to the previous `--disable-indexes` behavior.

**Comment by frankmcsherry** [comment] 2022-04-27 11:53
Imo this isn't a bug, but a feature request! You should be able to cancel the `select`, which will push a `CancelPeek` at the controller for that compute instance, and on future restarts the peek will not be issued. It sounds like you have a different take on how to resolve this, other than awaiting the user to either cancel the `select` or drop the view, both of which "should" work (might not, but those would be bugs).

**Comment by philip-stoev** [comment] 2022-04-27 11:57
Cancelling the SELECT I assume requires a `psql`-like client that is capable of issuing the right call to the server, right? If so I am afraid that it is not a general-enough solution.

To ease user adoption, I think we should strive to behave more like traditional databases. SELECTs that hang/are retried internally until some data is available were a departure from this, but I think returning an error if there has been a crash is something that people can reasonably be expecting from a database product.

**Comment by philip-stoev** [comment] 2022-05-03 19:17
This is still reproducible -- even though now one can use Ctrl+C to terminate the statement and get back a "ERROR:  canceling statement due to user request", computed does not exit the crash loop.

```
thread 'timely:work-0' panicked at 'called `Option::unwrap()` on a `None` value', /home/pstoev/materialize/src/compute/src/compute_state.rs:165:80
```

**Comment by benesch** [comment] 2022-07-10 16:08
@philip-stoev I gave this a try just now and pressing Ctrl+C or terminating the client that issued the panicky query will allow `computed` to exit the crash loop.

> The same thing happens with materialized views -- there, the excuse could be that the view is crashing on startup as it is being re-hydrated. But even in this case I think there is a solution -- a view should have been automatically marked as crashing so that it is not rehydrated on startup, unless the ALTER TABLE ENABLE INDEXES option is in effect, that is, an extension of sorts to the previous --disable-indexes behavior.
>
> To ease user adoption, I think we should strive to behave more like traditional databases. SELECTs that hang/are retried internally until some data is available were a departure from this, but I think returning an error if there has been a crash is something that people can reasonably be expecting from a database product.

It's unfortunately not possible to ascertain why `computed` crashed. There's no way to tell, in general, whether it crashed because of a particular `SELECT` query, a particular materialized view, some other query that ran it out of memory, a random networking failure, cosmic rays, etc. So we take the approach of classifying all crashes in `computed` as transient and solvable with a restart.

I don't know of an alternative to this policy that would guarantee that we retry all possible transient failures. I also don't want to invest too much in the UX around `computed` crashes; those are events that will hopefully trend in the "increasingly rare" direction, and that wil result in a Materialize engineer getting paged automatically.

**Comment by antiguru** [comment] 2022-09-15 13:37
Closing because it is expected behavior at this point.

**Closed by antiguru** 2022-09-15 13:37 UTC
Labels: C-bug, M-platform-blocker, A-COMPUTE
