### ISSUE TITLE
replica-isolation is flaky

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#14590] opened 2022-09-02 13:57 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/40789#0182fe48-6eab-40f2-9766-683441b075f4
https://buildkite.com/materialize/tests/builds/40850#018306de-8bc4-4591-8161-dceab4a05757

### Relevant log output

```source
> SELECT * FROM v1;
# Received cancellation signal, interrupting
🚨 Error: The command exited with status -1
user command error: The plugin mzcompose command hook exited with status -1
```

### Additional thoughts

Buildkite says the test timed out. I couldn't find any other relevant errors in the logs.

**Comment by lluki** [comment] 2022-09-05 09:01
Might be the same root cause as #14569 :
 * Same obeservation, time out without any relevant log message 
 * Happens only when restarting computeds
 * Both test involve a kafka source, which is necessary for #14569 to appear.

**Comment by uce** [comment] 2022-09-26 08:01
@teskje I talked to Philip about this and he believes the test is correct. Can you help triage this to the proper team? I've assigned to compute in the mean time.

**Comment by philip-stoev** [comment] 2022-09-26 09:32
Unfortunately this is not actionable at this time:
- for some reason, the services.log from the two failures initially provided is missing **all** output from environmentd et al., so it is entirely impossible to figure out what is going on
- the Buildkite and the Buildkite Analytics's UI makes it impossible to find the other instances where the test has failed
- the test has not failed on main over the past 1 month
- I ran the test in a loop hundreds of times in a Buildkite-identical AWS machine and it has not failed for me.

So I am closing this, please re-open once you have a new failure whose logs can be extracted.

**Closed by philip-stoev** 2022-09-26 09:32 UTC
Labels: C-bug, ci-flake
