### ISSUE TITLE
Materialize benchmark performance

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#3721] opened 2020-07-24 03:20 UTC
run chbench and ysb tests on Materialize

(this task is probably too broad and vague, so we should break it up and close it out to be more actionable)

**Comment by rjnn** [comment] 2020-07-24 18:10
Not YCSB, but the YSB (https://github.com/yahoo/streaming-benchmarks).

@frankmcsherry some of the YSB queries don't have clear view maintenance analogs, correct? It's more a "stream processing" benchmark than an IVM benchmark.

**Comment by frankmcsherry** [comment] 2020-07-24 18:16
YSB has built in "windowing" as part of the definition, so the view maintenance analogy would be to more advanced SQL. I suspect we could go a few ways here; the data are small enough that literally maintaining all aggregates without dropping the windows would probably work just fine (for .. hours to days). It would eventually fall over, though.

But basically it is a join and then a reduce, with an append-only stream of inputs.

**Comment by frankmcsherry** [comment] 2020-07-31 13:38
Related to / duplicate of #1547

**Closed** 2020-07-31 14:09 UTC
Labels: A-measurement, C-feature, T-performance
