### ISSUE TITLE
[Epic] Monitor and report Active Replica health

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#11587] opened 2022-04-05 06:51 UTC
### Feature request

https://github.com/MaterializeInc/materialize/issues/11240 calls for "active replication" of compute instances, which we intend to achieve by running multiple concurrent instantiations of the instance. These concurrent instances (should) each produce comparable results, and the first response back from the replicas can be returned to the user, masking slowness and failure.

At the same time, we would like to report on the "health" of the replicas so that a user can observe the level of protection they are currently afforded. If two out of three replicas are in continual restart loops, the user should be aware they are not currently protected against even a single additional fault. More qualitatively, if one of the replicas is continually 2x slower than another, any hiccup experienced by the fast replica translates directly to impaired performance.

As a sketch, in addition to reporting the first result to the user, we should track and surface the characteristics of responses from *all* of the replicas, perhaps relative to the first response. These could mirror the stats produced by timely dataflow, for example introspection collections of
1. the currently outstanding peeks on each replica
2. the write frontiers (aka `mz_materialization_frontiers`) on each replica
3. the distribution of peek response times on each replica, from the pov of the controller.

There are potentially more, or less, we could report, but these give a sense for measurements that would inform a user about their replica health and whether they might want to bring up a new one / restart or retire a specific failing replica.

-----
We discussed this in the Compute team meeting and decided we probably don't need to use introspection sources for this.

One idea that would be straightforward to implement would be keeping track (in the compute controller) of the most recently recently received response from each replica, and creating an API endpoint that cloud can query for this information. If any dataflows are installed, we should be constantly receiving frontier updates and updating this number; a significant lag suggests some health issue. The only edge case is when there are no dataflows installed at all, but this requires disabling introspection and in such a case we would probably not show the user any metrics regardless.

Once we have introspection sources working with replication, we can come up with some fuller metrics based on those, in collaboration with @jpepin and @hlburak .

### Goals
Report various replica health metrics in the Cloud UI.
### Acceptance Criteria
**P1**: Customers should be able to tell which replicas are fully hosed.
**P2**: Customers should be able to answer questions like "if I disable my one fastest replica, will performance degrade" ?
### Tasks
* Consult with Surfaces/Cloud on what to expose
* Expose the metrics in `environmentd`
* Wire up the cloud UI to query `environmentd` for these metrics and expose them. 
### Testing
* Testing that the database side returns some numbers should be added to CI. We should also check that if we artificially delay a replica (e.g. by forcing it to evaluate `mz_sleep`), the number reported increases
### Bugs
Unknown
### Questions
What set of metrics do the Surfaces and Cloud folks think would be useful/needed ?

**Comment by lluki** [comment] 2022-06-17 13:34
This seems to be the agreed upon way on how to provide feedback to users about replicas. There is another issue on my plate (#11511) that should also provide feedback when a configuration error has been made in `create cluster`. However providing a synchronous error (as suggested in the issue) on `create cluster` is hard, as we would have to guess the time until a computed comes up. 

My proposal to integrate #11511 into this issue is as follows:
We extend the status enum of the [`mz_cluster_replicas` system table ](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/20220413_cluster_replica.md#system-catalog-changes) with a "connecting" state, that would get set if we are still connecting. The user can (asynchronously) check this table to understand that the replica is not up at all. 

I know `create cluster .... remote` (as mentioned in #11511) is not a production feature, but implementing this would allow us to also detect network problems (DNS outage, broken cable etc.), as well as double connects.

To detect if a `GrpcComputedClient` is connected, the state member can be checked (its connected iff. state is `Connected`).

What do you think?

**Comment by umanwizard** [comment] 2022-06-22 12:46
Next steps here:

(1) Nail down with product exactly what we need as P1 and beyond (discussion ongoing in #eng-wg-replica-health )
(2) Surface connection status metrics (e.g. "last message receieved") from environmentd, probably in system tables if possible, or some other way otherwise

**Comment by benesch** [comment] 2022-06-23 05:19
I'd encourage everyone to play with the latest Materialize Cloud and see how the existing `mz_cluster_replicas` and `mz_audit_event` tables feel. I think it will help anchor our discussion. Here's a transcript of my session:

```
$ psql "postgres://benesch%40materialize.com@vde8tfe9e5wsndd0ihfnsfyd.us-east-1.aws.materialize.cloud:6875/materialize"
Password for user benesch@materialize.com: 
psql (14.2, server 9.5.0)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

materialize=> select * from mz_cluster_replicas;
 cluster_id | id |      name       |  size   | availability_zone | status  
------------+----+-----------------+---------+-------------------+---------
          1 |  1 | default_replica | default |                   | healthy
(1 row)

materialize=> create cluster foo replicas (r1 (size 'small'));
CREATE CLUSTER
materialize=> select * from mz_cluster_replicas;
 cluster_id | id |      name       |  size   | availability_zone |  status   
------------+----+-----------------+---------+-------------------+-----------
          2 |  2 | r1              | small   |                   | unhealthy
          1 |  1 | default_replica | default |                   | healthy
(2 rows)

--- Time passes ---

materialize=> select * from mz_cluster_replicas;
 cluster_id | id |      name       |  size   | availability_zone | status  
------------+----+-----------------+---------+-------------------+---------
          2 |  2 | r1              | small   |                   | healthy
          1 |  1 | default_replica | default |                   | healthy
(2 rows)

materialize=> select * from mz_audit_events;
-[ RECORD 1 ]-+------------------------------------------------------------------
uuid          | 2427ccaa-2c3d-4785-9f50-827bdb8dcc8f
event_type    | create
object_type   | cluster
event_details | {"name":"foo"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:04:55.099389+00
-[ RECORD 2 ]-+------------------------------------------------------------------
uuid          | ed4af585-ef4b-48a8-93cc-27723861c8f4
event_type    | create
object_type   | cluster-replica
event_details | {"cluster_name":"foo","logical_size":"small","replica_name":"r1"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:04:55.099413+00

materialize=> drop cluster foo;
DROP CLUSTER
materialize=> select * from mz_audit_events;
-[ RECORD 1 ]-+------------------------------------------------------------------
uuid          | 58193149-8b70-4d14-a180-7c66422c48f6
event_type    | drop
object_type   | cluster
event_details | {"name":"foo"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:06:46.295305+00
-[ RECORD 2 ]-+------------------------------------------------------------------
uuid          | 2427ccaa-2c3d-4785-9f50-827bdb8dcc8f
event_type    | create
object_type   | cluster
event_details | {"name":"foo"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:04:55.099389+00
-[ RECORD 3 ]-+------------------------------------------------------------------
uuid          | 2a70a00b-e62d-4e96-8151-b5f89d634e31
event_type    | drop
object_type   | cluster-replica
event_details | {"cluster_name":"foo","replica_name":"r1"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:06:46.295056+00
-[ RECORD 4 ]-+------------------------------------------------------------------
uuid          | ed4af585-ef4b-48a8-93cc-27723861c8f4
event_type    | create
object_type   | cluster-replica
event_details | {"cluster_name":"foo","logical_size":"small","replica_name":"r1"}
user          | benesch@materialize.com
occurred_at   | 2022-06-23 05:04:55.099413+00

materialize=> select event_details->>'replica_name' replica_name, event_details->>'logical_size' logical_size, (select occurred_at from mz_audit_events where event_type = 'drop' and object_type = 'cluster-replica' and event_details->>'replica_name' = out.event_details->>'replica_name') - occurred_at time_alive from mz_audit_events out where event_type = 'create' and object_type = 'cluster-replica';
 replica_name | logical_size |   time_alive    
--------------+--------------+-----------------
 r1           | small        | 00:01:51.195642
(1 row)
```

> Sounds like `mz_cluster_replicas` gets us most of the way there but may need a field for `health`.

This already exists, but is called `status`—see above!

> Sounds like `mz_audit_events` maybe already gets us this.

This is exactly what `mz_audit_events` was designed for! If there is something unsuitable about `mz_audit_events` in its current form, the sooner we can surface that the better, since the motivating use case for `mz_audit_events` was our internal billing needs.

**Comment by brennanvincent** [comment] 2022-07-12 13:33
We now have the `mz_cluster_replica_heartbeats` system table which allows us to see how recently a replica has responded; from the compute team's perspective, this was the most important metric for determining whether a replica is healthy.

I believe with the information Nikhil provided, there should be enough data also for the cloud team to use for billing purposes -- @hlburak , please correct me if that's wrong.

Thus all urgent P1 tasks have been resolved; however, I think we can leave this issue open for general discussion of what information to surface (I'm sure in the fullness of time we will want to surface more stuff, especially once we have a better story about querying the introspection state for all the replicas)

**Comment by hlburak** [comment] 2022-07-12 19:54
@brennanvincent Yes, P1 tasks for Cloud billing from the compute team are completed. Thanks!

**Comment by uce** [comment] 2022-08-23 12:25
> Thus all urgent P1 tasks have been resolved; however, I think we can leave this issue open for general discussion of what information to surface (I'm sure in the fullness of time we will want to surface more stuff, especially once we have a better story about querying the introspection state for all the replicas)

@brennanvincent I'm closing this issue as done. Let's create new issues when we want to surface more information.

**Closed by uce** 2022-08-23 12:25 UTC
Labels: C-feature, M-platform-blocker, A-COMPUTE
