### ISSUE TITLE
logs: implement capability to log events based on levels

### ISSUE THREAD

**Issue by krishmanoh2** [MaterializeInc/materialize#4604] opened 2020-10-23 17:37 UTC
It is an easy way to educate one-self by turning on logging and then running commands. In materialize, I could not find a simple way to enable logging at various levels (debug, info, warn etc).

The current process is to set MZ_LOG=debug/trace and run materialize with the log-file = stderr.

Having the ability to do this more easier will be helpful for customers and also support. Ideally, we would have a log-level flag that will write out messages to the log-file based on the options passed to log-level.

@rjnn

**Comment by rjnn** [comment] 2020-10-23 22:09
I think this is a place where we don't yet know what the levels are. In my experience, the levels are revealed gradually over time as we work out our own workflow. @benesch/@umanwizard/@wangandi curious for your thoughts, given that you've done a bunch of debugging on materialize clusters - is there a clear hierarchy of log levels that would make sense to expose today, or should we close this issue?

**Comment by rjnn** [comment] 2020-10-23 22:09
@benesch / @umanwizard / @wangandi since apparently slashes do not trigger username recognition

**Comment by krishmanoh2** [comment] 2020-10-23 22:14
Some of the levels are present today - I am able to see INFO, WARN, DEBUG, ERROR in stderr output. No CRIT yet.

**Comment by umanwizard** [comment] 2020-10-24 01:38
I’m not sure what is being asked for? Is it

(a) We should log things differently from how we do now, or,

(b) The currently logging levels are OK, but we should expose them in a more user-friendly way.

In either case, I would welcome suggestions.

**Comment by umanwizard** [comment] 2020-10-24 01:40
> is there a clear hierarchy of log levels that would make sense to expose today

Not really. Perhaps it would make sense to spend some time thinking through what counts as error/warn/info more intentionally.

**Comment by wangandi** [comment] 2020-10-26 15:44
> Some of the levels are present today - I am able to see INFO, WARN, DEBUG, ERROR in stderr output. No CRIT yet.

I'm also confused about the ask: Is it to add CRIT level logging?

> I think this is a place where we don't yet know what the levels are.

I personally think that it's less that and more we don't yet have logging for tracing the causes of performance problems that would make it desirable for a user to set the log-level to anything less fine than INFO. Currently, if we enabled allowing the customer to set `log-level=warn` or `log-level=error`, and the customer had a OOM or query slowdown, the log would be blank. This is because the vast majority of the time, they created valid views, so there's no error there. We currently can't warn about expensive operations because the expensiveness of an operation depends on a bunch of things we do not know about the future incoming data, like how large, how fast, and how different values there are. Also, whether the operation is "WARN"-level expensive is also machine dependent.

**Comment by krishmanoh2** [comment] 2020-10-27 20:30
In my opinion, it is more of this 

(b) The current logging levels are OK, but we should expose them in a more user-friendly way.

The request to add logging levels helps in several ways

1. A log scraping program like splunk can read the logs and generate alerts as needed. INFO and above levels, we reduce the logs generated. 

2. It is a method for understanding how the product works. Currently, there is not a whole lot of information on the internals of materialize. Exposing some of this via logs helps the early adopters (who are in a sense builders) learn the product and help themselves fix any issues they see. This also helps build competence in the external community.

I personally learnt a good deal by turning on debug mode to see the messages being generated.

**Comment by benesch** [comment] 2022-07-26 03:01
No longer relevant with platform.

**Closed by benesch** 2022-07-26 03:01 UTC
Labels: C-feature, needs-discussion
