### ISSUE TITLE
Tables cannot be joined with any other source

### ISSUE THREAD

**Issue by wangandi** [MaterializeInc/materialize#3975] opened 2020-08-17 20:05 UTC
Sources created by `CREATE SOURCE` are in the wall-clock time domain, but tables are in the ms-since-epoch time domain. These two time domains are not compatible for joining information.

**Comment by frankmcsherry** [comment] 2020-08-20 14:18
I believe this should be fixed by #3955 and #3998, but we should double check.

**Comment by benesch** [comment] 2020-08-20 16:52
It works, but there are some weird performance defects. Joining a (non-tailing) CSV source against a table sometimes takes like more than a second (?!) to come back.

```
materialize=> select * from t;
 a 
---
 b
(1 row)

Time: 0.848 ms
materialize=> select *, mz_logical_timestamp() from foo join t on column1 = a;
 column1 | column2 | mz_line_no | a | mz_logical_timestamp 
---------+---------+------------+---+----------------------
 b       | 2       |          2 | b |        1597942309874
(1 row)

Time: 9.351 ms
materialize=> select *, mz_logical_timestamp() from foo join t on column1 = a;
 column1 | column2 | mz_line_no | a | mz_logical_timestamp 
---------+---------+------------+---+----------------------
 b       | 2       |          2 | b |        1597942311592
(1 row)

Time: 10.085 ms
materialize=> select *, mz_logical_timestamp() from foo join t on column1 = a;
 column1 | column2 | mz_line_no | a | mz_logical_timestamp 
---------+---------+------------+---+----------------------
 b       | 2       |          2 | b |        1597942312520
(1 row)

Time: 713.835 ms
materialize=> select *, mz_logical_timestamp() from foo join t on column1 = a;
 column1 | column2 | mz_line_no | a | mz_logical_timestamp 
---------+---------+------------+---+----------------------
 b       | 2       |          2 | b |        1597942315333
(1 row)

Time: 9.676 ms
materialize=> select *, mz_logical_timestamp() from foo join t on column1 = a;
 column1 | column2 | mz_line_no | a | mz_logical_timestamp 
---------+---------+------------+---+----------------------
 b       | 2       |          2 | b |        1597942316157
(1 row)

Time: 1078.909 ms (00:01.079)
materialize=> 
```

**Comment by benesch** [comment] 2020-08-20 16:52
And this was a release build, for the record.

**Comment by frankmcsherry** [comment] 2020-08-20 16:54
Is this because the heartbeat that goes out of the coordinator is roughly 1Hz? We could crank that up?

**Comment by benesch** [comment] 2020-08-20 18:06
That sounds entirely plausible! Is just cranking that up the right solution though? Seems like it'll annoy everyone CPU-usage wise?

**Comment by frankmcsherry** [comment] 2020-08-20 20:57
I repro'd this locally, and got the following read-out from `mz_peek_durations`:
```
materialize=> select * from mz_peek_durations;
 worker | duration_ns | count 
--------+-------------+-------
      0 |   536870912 |     1
      0 |  2147483648 |     1
      0 |      524288 |     1
      0 |     2097152 |     1
(4 rows)
```
This seems to indicate that the peeks are actually stalled out on the worker, which is surprising! I'll try and track down which timestamps are being used, and what frontiers look like.

**Comment by frankmcsherry** [comment] 2020-08-20 20:59
The worker isn't actually doing any stalling work, so that isn't the problem:
```
materialize=> select * from mz_scheduling_histogram order by duration_ns desc;
 id  | worker | duration_ns | count 
-----+--------+-------------+-------
 282 |      0 |      524288 |     1
 339 |      0 |      524288 |     1
 396 |      0 |      262144 |     1
 453 |      0 |      262144 |     1
 337 |      0 |      131072 |     1
 339 |      0 |      131072 |     1
...
```

**Comment by frankmcsherry** [comment] 2020-08-20 21:18
This looks pretty incriminating. I'm certain what is going on, except perhaps that we didn't properly downgrade a capability fast enough:
```
10.005210254s   peeking at: 1597958244363
10.005239631s   advanced all to: 1597958244371
11.064854201s   advanced all to: 1597958245432
11.065642741s   peek fulfilled
```

**Comment by frankmcsherry** [comment] 2020-08-20 21:28
I saw a few others that presented as above, but this one also surprised me a bit. The peek is fulfilled one second before the next tick. Maybe coincidence, or maybe the coordinator re-calibrates the ticking based on peek fulfillment.
```
24.01515253s    peeking at: 1597958576034
24.015173113s   advanced all to: 1597958576042
24.129433715s   peek fulfilled
25.129191767s   advanced all to: 1597958577157
```

**Comment by frankmcsherry** [comment] 2020-08-20 21:44
Here's another bit of trace that I'm not sure I understand. There are about 600ms that seem to be timely sleeping, 
```
...
5.455133879s    stepping
6.03334064s     stepping done
...
```
with no external wake-up. Perhaps an internal reschedule, but .. the sources are a table and a complete file source. Maybe logging wakes it back up? Anyhow, I'll sniff around a bit more and see if I can sort out why it would be sleeping (can it not actually make progress and something changes, or is there what would otherwise be a hanging bug?).

Also, will make `AllowCompaction` less spammy.

```
5.454636691s    peeking at: 1597959522840
5.454643345s    command: DropIndexes([User(178)])
5.45465485s     command: AdvanceAllLocalInputs { advance_to: 1597959522848 }
5.45465691s     advanced all to: 1597959522848
5.454684998s    stepping
5.454747098s    stepping done
<several steps>
5.455092301s    stepping
5.455096767s    stepping done
5.455104777s    command: AllowCompaction([(System(2010), Antichain { elements: [1597959462848] }), (System(2004), Antichain { elements: [1597959462848] }), (System(2008), Antichain { elements: [1597959462848] }), (System(2006), Antichain { elements: [1597959462848] }), (System(2002), Antichain { elements: [1597959462848] }), (User(2), Antichain { elements: [1597959462848] })])
5.455133879s    stepping
6.03334064s     stepping done
6.03340408s     stepping
6.034269968s    stepping done
6.034318653s    stepping
6.03514813s     stepping done
6.035476469s    stepping
6.035613976s    stepping done
6.035643257s    command: AllowCompaction([(System(1001), Antichain { elements: [1597959523000] }), (System(1025), Antichain { elements: [1597959523000] }), (System(1023), Antichain { elements: [1597959523000] }), (System(1005), Antichain { elements: [1597959523000] }), (System(1019), Antichain { elements: [1597959523000] }), (User(5), Antichain { elements: [1597959464001] }), (System(1021), Antichain { elements: [1597959523000] }), (System(1003), Antichain { elements: [1597959523000] }), (System(1017), Antichain { elements: [1597959523000] })])
6.035662576s    command: AdvanceAllLocalInputs { advance_to: 1597959523430 }
6.035665071s    advanced all to: 1597959523430
6.035798437s    stepping
6.035880098s    stepping done
6.035891959s    command: AllowCompaction([(System(1011), Antichain { elements: [1597959523000] }), (System(1009), Antichain { elements: [1597959523000] }), (System(1007), Antichain { elements: [1597959523000] }), (System(1013), Antichain { elements: [1597959523000] }), (System(1015), Antichain { elements: [1597959523000] })])
6.03592967s     peek fulfilled
```

**Comment by benesch** [comment] 2020-09-17 16:24
Actually, this seems to be a result of a pretty frustrating regression that slipped in via a refactor of file sources: https://github.com/MaterializeInc/materialize/blob/01560a720f103908213a2cac34af8d7b26bb8cdd/src/dataflow/src/source/file.rs#L273-L274

Working on a fix.

**Closed** 2020-09-17 18:29 UTC
Labels: C-bug, C-known-limitation
