### ISSUE TITLE
0dt: thread 'main' panicked at src/adapter/src/catalog/apply.rs:541:32: unknown ambient schema: pg_catalog

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28352] opened 2024-07-18 16:25 UTC
### What version of Materialize are you using?

e23b73ff4d (Pull Request #28191)

### What is the issue?

New nightly run, new failure. This is on main state with my testing-only PR applied on top: [Checks 0dt upgrade, whole-Mz restart](https://buildkite.com/materialize/nightly/builds/8650#0190c695-b0c0-4b89-b1e7-41d6d274e1ff)
```
thread 'main' panicked at src/adapter/src/catalog/apply.rs:541:32:
unknown ambient schema: pg_catalog
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: <mz_adapter::catalog::state::CatalogState>::apply_system_object_mapping_update::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:541:32
   3: <core::option::Option<&mz_sql::names::SchemaId>>::unwrap_or_else::<<mz_adapter::catalog::state::CatalogState>::apply_system_object_mapping_update::{closure#0}>
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:977:21
   4: <mz_adapter::catalog::state::CatalogState>::apply_system_object_mapping_update
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:541:14
   5: <mz_adapter::catalog::state::CatalogState>::apply_update
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:222:17
   6: <mz_adapter::catalog::state::CatalogState>::apply_updates_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:171:21
   7: <mz_adapter::catalog::apply::BootstrapApplyState>::apply::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:1725:17
   8: <mz_adapter::catalog::state::CatalogState>::with_enable_for_item_parsing::<alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate<&mz_catalog::builtin::BuiltinTable>>, <mz_adapter::catalog::apply::BootstrapApplyState>::apply::{closure#0}::{closure#0}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/state.rs:1001:19
   9: <mz_adapter::catalog::apply::BootstrapApplyState>::apply::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:1724:52
  10: <mz_adapter::catalog::state::CatalogState>::apply_updates_for_bootstrap::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:121:82
  11: <tracing::instrument::Instrumented<<mz_adapter::catalog::state::CatalogState>::apply_updates_for_bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::catalog::state::CatalogState>::apply_updates_for_bootstrap::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/apply.rs:95:5
  13: <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/open.rs:366:88
  14: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::initialize_state::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::catalog::state::CatalogState, alloc::collections::btree::set::BTreeSet<mz_repr::global_id::GlobalId>, alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate>, alloc::string::String), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  16: <mz_adapter::catalog::Catalog>::open::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/catalog/open.rs:477:22
  17: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  18: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::catalog::Catalog, alloc::collections::btree::set::BTreeSet<mz_repr::global_id::GlobalId>, alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate>, alloc::string::String), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  19: mz_adapter::coord::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/adapter/src/coord.rs:3399:10
  20: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::client::Handle, mz_adapter::client::Client), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  21: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::client::Handle, mz_adapter::client::Client), mz_adapter::error::AdapterError>> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  22: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/environmentd/src/lib.rs:500:10
  23: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  24: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/environmentd/src/lib.rs:269:5
  25: environmentd::run::{closure#11}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:958:14
  26: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  27: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  28: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  29: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  30: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  31: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  32: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:22
  33: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  34: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  35: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:50
  36: environmentd::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:884:18
  37: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01e9f0def89be8baa-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:568:23
  38: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
If this is already potentially fixed on an open PR, please close and ignore.

ci-regexp: unknown ambient schema: pg_catalog

**Comment by jkosh44** [comment] 2024-07-18 16:28
This is a duplicate of https://github.com/MaterializeInc/materialize/issues/28352, but with a better error message that I recently added.

**Closed by jkosh44** 2024-07-18 16:28 UTC
Labels: C-bug, T-platform-v2

**Comment by def-** [comment] 2024-07-18 16:35
Endless loop detected while following your link ;)

**Comment by jkosh44** [comment] 2024-07-18 16:41
> Endless loop detected while following your link ;)

I updated the link.
