### ISSUE TITLE
testdrive/kafka-avro-upsert-sinks.td:186:1: error: record 0 did not match

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23087] opened 2023-11-09 23:27 UTC
### What version of Materialize are you using?

fe7e9fef56

### What is the issue?

```
testdrive/kafka-avro-upsert-sinks.td:186:1: error: record 0 did not match
expected:
Record {
    headers: [
        "1",
    ],
    key: Some(
        {
            (
                "a",
                Long(1),
            ),
        },
    ),
    value: Some(
        {
            (
                "a",
                Long(1),
            ),
            (
                "b",
                Long(1),
            ),
        },
    ),
}

actual:
Record {
    headers: [
        "3",
    ],
    key: Some(
        {
            (
                "a",
                Long(1),
            ),
        },
    ),
    value: Some(
        {
            (
                "a",
                Long(1),
            ),
            (
                "b",
                Long(7),
            ),
        },
    ),
}
```
Seen in https://buildkite.com/materialize/nightlies/builds/5100#018bb5c3-08c3-4b58-8bf1-ab2f3d89f26e

I think this is another occurrence of things just being too slow in cloudtest and thus the test fails? I'm not sure if we have a good way of fixing this in the test though. Any ideas?

**Comment by def-** [comment] 2023-11-10 10:29
Also seen in other testdrive tests in nightly, I'm still not sure if this is a test problem or a product issue.

**Comment by def-** [comment] 2023-11-10 13:22
These also started with https://buildkite.com/materialize/nightlies/builds/5081, so marking as duplicate of https://github.com/MaterializeInc/materialize/issues/23096
CC @aljoscha

**Comment by def-** [comment] 2023-11-10 16:15
I'll try to reproduce this locally again.

**Comment by def-** [comment] 2023-11-10 17:35
@aljoscha My local attempt has been to run the test twice in a row to repro this: `bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive testdrive2 run default kafka-avro-upsert-sinks.td && bin/mzcompose --find testdrive run default kafka-avro-upsert-sinks.td`. This leads to hangs, similar to #23096, but without explicit timelines here. It started with #23022 .

The non-matching record I didn't get yet, will now try `while true; do bin/mzcompose --find testdrive down && bin/mzcompose --find testdrive run default kafka-avro-upsert-sinks.td || break; done` in a loop

**Comment by def-** [comment] 2023-11-10 21:50
I have proof that this was definitely introduced in #23022 : https://buildkite.com/materialize/nightlies/builds/5136#018bbafd-7f9f-46c6-8914-79ec1b05e543 is the state just before #23022 and it is green, https://buildkite.com/materialize/nightlies/builds/5137#018bbafd-c927-4dc9-b076-83e7525618a7 is just after it and it's stuck.

Additionally #23022 also broke the quickstart guide: https://materialize.com/docs/get-started/quickstart/
By running `bin/mzcompose --find testdrive --project-name testdrive2 down && bin/mzcompose --find testdrive --project-name testdrive2 run default` with the quickstart.td file from `https://github.com/MaterializeInc/materialize/pull/23041` it hangs instantly on
```
--- quickstart.td
Connecting to PostgreSQL server at postgres://mz_system:materialize@materialized:6877...
> DROP DATABASE materialize
> CREATE SOURCE auction_house
IN CLUSTER default
FROM LOAD GENERATOR AUCTION
(TICK INTERVAL '0.01s')
FOR ALL TABLES
rows match; continuing at ts 1699651502.8339155
> SHOW SOURCES
rows match; continuing at ts 1699651503.5307167
> SELECT id, seller, item FROM auctions WHERE id = 1
```
Even without having executed the same test twice.

**Comment by nrainer-materialize** [comment] 2023-11-14 15:45
Reopening this one because it still occurs after the duplicate https://github.com/MaterializeInc/materialize/issues/23096 being fixed in testdrive with 4 replicas (e.g., in https://buildkite.com/materialize/nightlies/builds/5191#018bcdd0-36fa-4c43-989c-6c18787a6b44)

**Comment by nrainer-materialize** [comment] 2023-11-14 15:45
@aljoscha, do you know more about this issue? Do we consider this a release blocker?

**Comment by aljoscha** [comment] 2023-11-14 15:51
@def- had figured out that this issue was caused by my changes which have since been reverted. So this must be a similar but different thing 🙈

**Comment by nrainer-materialize** [comment] 2023-11-14 15:54
Forget my last comment. The mentioned test is not failing in that build.

**Closed by nrainer-materialize** 2023-11-14 15:54 UTC
Labels: C-bug, release-blocker
