### ISSUE TITLE
persist: kafka sources: META and one UUID-named file is written to disk once every min_step_interval even if topic is idle

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8907] opened 2021-11-02 13:24 UTC
### What version of Materialize are you using?

```
c9080b3065442b5d04dfa2fca9ad07f0067f7ea8
```

### What was the issue?

If `--persistent-kafka-upsert-source` is in effect, the META file is written to disk once every min_step_interval, even if there are no incoming messages on the Kafka topic.

A new UUID-named file with around 800bytes in it is also written every min_step_interval. All of those files need to be read back on restart. The presence of so many UUID-named files causes the meta file to grow considerably.

This is in contrast with persistent user and system tables where META is only being written to if new inserts arrive into the table.

### Is the issue reproducible? If so, please provide reproduction instructions.

1. Run 
```
strace -f -F target/release/materialized --experimental --persistent-kafka-upsert-source --disable-persistent-system-tables-test  --timestamp-interval=10ms 2>&1 | grep openat
```
2. Observe that strace does not report any META activity
3. Run e.g. `kafka-upsert-sources.td` agaist the server
4. Observe an endless stream of `openat` calls

### Please attach any applicable log files.

```
...
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/58185e13-36b8-46d9-bc6f-283b075aed98", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0666 <unfinished ...>
[pid 1714844] <... openat resumed>)     = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/cbd22071-e9ab-4311-a477-7f80ff55a2e5", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0666 <unfinished ...>
[pid 1714844] <... openat resumed>)     = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666 <unfinished ...>
[pid 1714844] <... openat resumed>)     = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/78c6d885-fc22-4ed5-b3ae-fc3c64b4ea5d", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/META.tmp", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 55
[pid 1714844] openat(AT_FDCWD, "mzdata/persist/blob/a57dd02d-e48f-49ef-9b47-5ce419341305", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0666 <unfinished ...>
[pid 1714844] <... openat resumed>)     = 55
...
```

**Comment by aljoscha** [comment] 2021-11-15 17:36
I think the cause for this is that we write updated timestamp bindings every `timestamp_frequency_ms` and that we seal up collections whenever we downgrade the source capability. The former is not something that we can easily fix. The latter could potentially be fixed by only sealing if/when new data came through the `seal()`/`conditional_seal()` operator.

**Comment by aljoscha** [comment] 2021-11-16 14:14
@danhhz I see two top-level approaches to fixing this:

1. change persistence itself to better handle the write pattern of the source
2. change the source to not write as much/seal as often

Do you have an opinion/ideas about this?

**Comment by danhhz** [comment] 2021-11-16 15:40
The incremental meta stuff I'm working on will (hopefully) change these numbers pretty significantly. I plan to revisit this after we see what impact that has.

More generally, my answer is (1). I view it as persist's ultimate responsibility to (eventually) serve any production-like traffic patterns with reasonable latencies, storage, usage, memory footprint, etc.

**Comment by aljoscha** [comment] 2021-11-16 16:57
Sweet! I had an inkling that the incremental meta stuff would resolve this. And yes, I also like (1) more.

**Comment by philip-stoev** [comment] 2022-03-25 07:06
This is still the case as of today. Currently, the total number of UUID files stays constant and the META file does not grow, but both are still being rewritten constantly even on idle topics.

**Comment by aljoscha** [comment] 2022-09-01 09:30
@danhhz I'm closing this one because current persist has moved on quite a bit by now.

**Closed by aljoscha** 2022-09-01 09:30 UTC
Labels: C-bug, A-persistence
