### ISSUE TITLE
Show publication metadata in SHOW CREATE SOURCE for Postgres CDC sources

### ISSUE THREAD

**Issue by nharring-adjacent** [MaterializeInc/materialize#11346] opened 2022-03-22 18:14 UTC
### Feature request

As of `v0.23.0` `SHOW CREATE SOURCE` on a Postgres CDC source will display the hex-encoded string rendition of the binary encoded protobuf message which describes the tables and schemas that were part of the publication when the source was created. Understanding the behavior of Materialize relative to the contents of this protobuf would be much easier if it was possible to display in some other form such as JSON encoded.

**Comment by benesch** [comment] 2024-01-28 18:09
Closing as a retroactive duplicate of https://github.com/MaterializeInc/materialize/issues/17957.

**Closed by benesch** 2024-01-28 18:09 UTC
Labels: C-feature, A-source
