### ISSUE TITLE
ci: cluster smoke test: pg-snapshot-resumption times out

### ISSUE THREAD

**Issue by frankmcsherry** [MaterializeInc/materialize#14591] opened 2022-09-02 14:08 UTC
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

Observed in CI (https://buildkite.com/materialize/tests/builds/40788#0182fe06-d68f-4eeb-bae7-32bdcec92761/1151). Passed on next execution.
```
pg-snapshot-resumption/03-while-storaged-down.td | 0s
  | > SELECT COUNT(*) FROM t1;
  |  
  | pg-snapshot-resumption/03-while-storaged-down.td:10:1: error: deadline has elapsed
  | \|
  | 9 \|
  | 10 \| > SELECT COUNT(*) FROM t1;
  | \| ^
  | !!! Error Report | 0s
  | 1 errors were encountered during execution
  | files involved: pg-snapshot-resumption/03-while-storaged-down.td
  | mzcompose: test case pg-snapshot-resumption failed: running docker compose failed (exit status 1)



### Relevant log output

_No response_

**Comment by aljoscha** [comment] 2022-09-02 14:24
Duplicate of https://github.com/MaterializeInc/materialize/issues/14533, I believe.

**Closed by aljoscha** 2022-09-02 14:24 UTC
Labels: C-bug, C-triage
