### ISSUE TITLE
storage: dataflow-cleanup.td fails sporadically

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18757] opened 2023-04-13 07:27 UTC
ci-regexp: system-cluster.td:12:1: error: non-matching rows:

### What version of Materialize are you using?

bfb70fe4d2605adf8abb109461dbf5deaabd8022

### How did you install Materialize?

Docker image

### What is the issue?

```
[2023-04-12T21:04:00Z] > CREATE MATERIALIZED VIEW q14 AS SELECT   100.00 * sum(case     when p_type like 'PROMO%'       then l_extendedprice * (1 - l_discount)     else 0   end) / sum(l_extendedprice * (1 - l_discount)) AS promo_revenue FROM   lineitem,   part WHERE   l_partkey = p_partkey   AND l_shipdate >= DATE '1995-09-01'   AND l_shipdate < DATE '1995-09-01' + INTERVAL '1' month
[2023-04-12T21:04:00Z] rows match; continuing at ts 1681333440.693967
[2023-04-12T21:04:00Z] > SELECT count(*) > 0 FROM q14
[2023-04-12T21:04:05Z] rows match; continuing at ts 1681333445.0006583
[2023-04-12T21:04:05Z] > SELECT mz_internal.mz_sleep(1)
[2023-04-12T21:04:06Z] rows match; continuing at ts 1681333446.0144038
[2023-04-12T21:04:06Z] > SELECT count(*) > 0 FROM mz_internal.mz_dataflow_operators
[2023-04-12T21:06:06Z] rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 22s
^^^ +++
[2023-04-12T21:06:06Z] dataflow-cleanup.td:96:1: error: non-matching rows: expected:
[2023-04-12T21:06:06Z] [["false"]]
[2023-04-12T21:06:06Z] got:
[2023-04-12T21:06:06Z] [["true"]]
[2023-04-12T21:06:06Z] Poor diff:
[2023-04-12T21:06:06Z] - false
[2023-04-12T21:06:06Z] + true
[2023-04-12T21:06:06Z] 
[2023-04-12T21:06:06Z]      |
[2023-04-12T21:06:06Z]   95 | <null>
[2023-04-12T21:06:06Z]   96 | > SELECT count(*) > 0 FROM mz_internal.mz_dataflow_operators
[2023-04-12T21:06:06Z]      | ^
```
Seen in https://buildkite.com/materialize/nightlies/builds/2204#0187773e-fe03-4696-8fa4-8363e078ded0
This could be sporadic or Linux-specific. I'll try to reproduce it. Edit: Can't repro on M1 MBP, couldn't repro on Linux arm64 either, so seems sporadic.

Edit: Also seen in coverage run: https://buildkite.com/materialize/coverage/builds/54#0187b464-a909-4d67-bea6-ce3002879e04

**Comment by teskje** [comment] 2023-04-19 13:28
I am able to reproduce this locally by running `./mzcompose run default --redpanda dataflow-cleanup.td` in a loop.

The test that fails is this one:
```
# Regression test for https://github.com/MaterializeInc/materialize/issues/16326

> CREATE SOURCE lgtpch FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.1) FOR ALL TABLES WITH (SIZE = '1');
> CREATE MATERIALIZED VIEW q14 AS
  SELECT
    100.00 * sum(case
      when p_type like 'PROMO%'
        then l_extendedprice * (1 - l_discount)
      else 0
    end) / sum(l_extendedprice * (1 - l_discount)) AS promo_revenue
  FROM
    lineitem,
    part
  WHERE
    l_partkey = p_partkey
    AND l_shipdate >= DATE '1995-09-01'
    AND l_shipdate < DATE '1995-09-01' + INTERVAL '1' month
> SELECT count(*) > 0 FROM q14
true
> SELECT mz_internal.mz_sleep(1)
<null>
> SELECT count(*) > 0 FROM mz_internal.mz_dataflow_operators
false
```

It is based on the assumption that TPCH sources without a `TICK INTERVAL` advance to the empty frontier after having produced one batch of data. This seems to not be the case sometimes, as can be observed by connecting to the MZ instance after the test has failed:

```
 materialize=> explain timestamp for select * from lineitem, orders, nation, part;
                                 Timestamp
---------------------------------------------------------------------------
                 query timestamp: 1681910832298 (2023-04-19 13:27:12.298) +
           oracle read timestamp: 1681910832298 (2023-04-19 13:27:12.298) +
 largest not in advance of upper: 1681909755000 (2023-04-19 13:09:15.000) +
                           upper:[1681909755001 (2023-04-19 13:09:15.001)]+
                           since:[1681909754000 (2023-04-19 13:09:14.000)]+
         can respond immediately: false                                   +
                        timeline: Some(EpochMilliseconds)                 +
                                                                          +
 source materialize.public.lineitem (u8, storage):                        +
                   read frontier:[1681909754000 (2023-04-19 13:09:14.000)]+
                  write frontier:[1681909755001 (2023-04-19 13:09:15.001)]+
                                                                          +
 source materialize.public.nation (u9, storage):                          +
                   read frontier:[1681909754000 (2023-04-19 13:09:14.000)]+
                  write frontier:[1681909755001 (2023-04-19 13:09:15.001)]+
                                                                          +
 source materialize.public.orders (u10, storage):                         +
                   read frontier:[1681909754000 (2023-04-19 13:09:14.000)]+
                  write frontier:[1681909755001 (2023-04-19 13:09:15.001)]+
                                                                          +
 source materialize.public.part (u11, storage):                           +
                   read frontier:[1681909754000 (2023-04-19 13:09:14.000)]+
                  write frontier:[1681909755001 (2023-04-19 13:09:15.001)]+

(1 row)
```

Note how none of the `lgtpch` subsources has advanced to the empty frontier.

**Comment by teskje** [comment] 2023-04-20 11:25
I debugged this with @petrosagg a bit and this looks like a storage issue. We verified that the load generator source successfully completes and the operator shuts down. Trace logging reveals that the remap operator mints a binding for the empty frontier, but it never reaches the reclock operator for some reason.

```
environmentd: 2023-04-20T10:57:10.076786Z DEBUG create_collections: mz_storage_client::controller: mapping GlobalId=u101 to remap shard (Some(ShardId(e7984435-bf4e-4cb4-849f-9bb497a329bd))), data shard (se6c8efbb-71ce-40f2-a2dc-a1bdd3ebb420), status shard (Some(ShardId(f93c38c1-40fe-4daa-9c8a-13f93583bda5)))
cluster-u13-replica-15: 2023-04-20T10:57:11.797949Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) received source progress: source_upper={1}
cluster-u13-replica-15: 2023-04-20T10:57:11.808103Z  INFO mz_storage::source::reclock::compat: remap(u101) 0/1 initializing PersistHandle since=Antichain { elements: [0] } as_of=Antichain { elements: [0] } upper=Antichain { elements: [0] }
cluster-u13-replica-15: 2023-04-20T10:57:11.831832Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) emitting remap snapshot: source_upper={0} trace_updates=[(MzOffset { offset: 0 }, 0, 1)]
cluster-u13-replica-15: 2023-04-20T10:57:11.831865Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) received source upper: {1}
cluster-u13-replica-15: 2023-04-20T10:57:11.831943Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) received remap batch: updates=[(MzOffset { offset: 0 }, 0, 1)] upper={1681988232001}
cluster-u13-replica-15: 2023-04-20T10:57:11.832013Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101): processed 0, skipped 865939 messages
cluster-u13-replica-15: 2023-04-20T10:57:11.832048Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) downgrading timestamper: since={1681988232001}
cluster-u13-replica-15: 2023-04-20T10:57:12.024721Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) minted new bindings: updates=[(MzOffset { offset: 0 }, 1681988233000, -1), (MzOffset { offset: 1 }, 1681988233000, 1)] source_upper={1} trace_upper={1681988233001}
cluster-u13-replica-15: 2023-04-20T10:57:12.024810Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) received remap batch: updates=[(MzOffset { offset: 0 }, 1681988233000, -1), (MzOffset { offset: 1 }, 1681988233000, 1)] upper={1681988233001}
cluster-u13-replica-15: 2023-04-20T10:57:12.125814Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101): processed 865939, skipped 0 messages
cluster-u13-replica-15: 2023-04-20T10:57:12.125884Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) downgrading timestamper: since={1681988233001}
cluster-u13-replica-15: 2023-04-20T10:57:14.784670Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) minted new bindings: updates=[] source_upper={1} trace_upper={1681988233001}
cluster-u13-replica-15: 2023-04-20T10:57:14.785388Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) received source progress: source_upper={}
cluster-u13-replica-15: 2023-04-20T10:57:14.862663Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) minted new bindings: updates=[] source_upper={1} trace_upper={1681988235001}
cluster-u13-replica-15: 2023-04-20T10:57:14.862702Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) received source upper: {}
cluster-u13-replica-15: 2023-04-20T10:57:14.863106Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) received remap batch: updates=[] upper={1681988235001}
cluster-u13-replica-15: 2023-04-20T10:57:14.863313Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101): processed 0, skipped 0 messages
cluster-u13-replica-15: 2023-04-20T10:57:14.863328Z TRACE mz_storage::source::source_reader_pipeline: timely-0 reclock(u101) downgrading timestamper: since={1681988235001}
cluster-u13-replica-15: 2023-04-20T10:57:15.842499Z TRACE mz_storage::source::source_reader_pipeline: timely-0 remap(u101) minted new bindings: updates=[(MzOffset { offset: 1 }, 1681988236000, -1)] source_upper={} trace_upper={}
```

I'm re-assigning this to @MaterializeInc/storage, who are way better equipped for debugging this than I am.

**Comment by ggevay** [comment] 2023-05-10 14:07
Just recording that it seems this can also manifest as a fail in `system-cluster.td`, if I'm reading things correctly here: https://buildkite.com/materialize/tests/builds/55213#018805d7-3d9b-4283-bd12-e06c709ae1fe

**Comment by def-** [comment] 2023-05-23 07:46
@petrosagg This is still failing commonly in CI, have you had a chance to take a look?

**Comment by bkirwi** [comment] 2023-06-22 15:22
I'm going to close this one, since it was last seen three months ago and only in a dev build.

**Closed by bkirwi** 2023-06-22 15:22 UTC
Labels: C-bug, A-STORAGE

**Comment by def-** [comment] 2023-12-20 08:52
This is still happening often: https://buildkite.com/materialize/nightlies/builds/5665#018c8358-86f9-4580-9830-a6a55539120f

**Comment by def-** [comment] 2024-07-16 12:25
@petrosagg Is this bug maybe fixed by your fixes yesterday?

**Comment by petrosagg** [comment] 2024-07-22 13:29
It shouldn't be related unfortunately
