### ISSUE TITLE
panic: timestamp must go forwards but 1645107254500 <= 1645107254500

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10742] opened 2022-02-17 14:41 UTC
### What version of Materialize are you using?

version: 0.20.1-dev (b85145136d46ed187b85e43a50f9dee9dc38b976)

### How did you install Materialize?

Built from source

### What was the issue?

I got the panic below once and only once when running the test/kafka-source/before*.td tests against a mz instance that had persistence disabled.

### Relevant log output

```source
2022-02-17T14:14:14.604661Z ERROR panic: timestamp must go forwards but 1645107254500 <= 1645107254500
thread: timely:work-1
location: src/dataflow/src/source/timestamp.rs:192:13
version: 0.20.1-dev (b85145136d46ed187b85e43a50f9dee9dc38b976)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:610:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   6: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   7: mz_dataflow::source::timestamp::TimestampBindingBox::add_binding
   8: mz_dataflow::source::timestamp::TimestampBindingRc::update_timestamp
   9: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
  10: timely::progress::subgraph::PerOperatorState<T>::schedule
  11: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
  13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  14: timely::worker::Wrapper::step
  15: timely::worker::Worker<A>::step_or_park
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/thread.rs:106:17
  19: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  20: clone
```

**Comment by frankmcsherry** [comment] 2022-02-21 23:10
I just saw this as well, and @antiguru too to my understanding.

**Comment by antiguru** [comment] 2022-02-22 10:16
I created a PR that could help to diagnose the issue. It's a bit involved to reproduce, but here are the steps:

```
cargo build --bin materialized --release
gdb target/release/materialized
> r --workers 2
```

Separately:
```
cargo run --release --bin testdrive -- test/testdrive/*.td
```

I need to run Mz in gdb to print the stack trace, otherwise it won't show.

**Comment by antiguru** [comment] 2022-02-22 10:17
Here's the PR: https://github.com/MaterializeInc/materialize/pull/10810

**Comment by philip-stoev** [comment] 2022-02-22 14:14
Also seen on Nightly with --workers 32

**Comment by ruchirK** [comment] 2022-02-22 16:10
this might be my fault -- I merged a refactor recently that changed the timestamp bindings code to assert on strict forward assignment of timestamps

**Comment by ruchirK** [comment] 2022-02-22 16:11
https://github.com/MaterializeInc/materialize/pull/10647 is the pr that did the refactor.

**Comment by ruchirK** [comment] 2022-02-22 16:18
I can look into this more later today - sorry for the flakiness

**Comment by umanwizard** [comment] 2022-02-22 16:18
@philip-stoev From your log, it doesn't seem like this was in v20:

```
version: 0.20.1-dev (b85145136d46ed187b85e43a50f9dee9dc38b976)
```

**Comment by philip-stoev** [comment] 2022-02-23 10:11
Sorry, I have updated the version thing.

**Comment by ruchirK** [comment] 2022-02-23 12:54
I'm investigating this now!

**Comment by ruchirK** [comment] 2022-02-23 16:46
I believe I have a clear understanding of what's happening here:

In an ideal world, the source operator and the timestamp binding code:

1. read up to some offset, which corresponds to some proposed timestamp bindings at time t
2. finalize those bindings and save them in timestamp histories
3. downgrade capabilities to time t, and enable compaction of the timestamp histories up to time t

Unfortunately, step 2 is rate limited to only happen once per timestamp interval and so it can happen that

1. theres some already finalized binding at time t1, and some proposed binding at time t2
2. the source operator reads up to t2 and attempts to finalize the proposed binding
3. the proposed binding is not finalized
4. the source enables compaction up to t2
5. the binding at t1 is forwarded to t2
6. at some later point when the proposed binding is actually finalized it complains that a binding already exists at t2

this is also why we only ever see equivalent times, and never a time that was less than the time already present.

I can think of a couple of hacky fixes but I'm not sure what the best principled fix is here -- the rate limiting on finalizing bindings seems suspect.

**Comment by ruchirK** [comment] 2022-02-23 17:04
@umanwizard just as a heads up^

**Comment by petrosagg** [comment] 2022-02-23 17:18
Shouldn't the timestamp binding itself require that its `since` is never equal to `upper`? It sounds like this would solve the problem

**Comment by ruchirK** [comment] 2022-02-28 15:22
this is no longer a release blocker because the assertion has been reverted.

**Comment by philip-stoev** [comment] 2022-03-31 14:14
This was assigned to me for some reason, but the issue is now reproducible and I hope understood as well.

**Comment by frankmcsherry** [comment] 2022-03-31 14:16
:D
<img width="465" alt="Screen Shot 2022-03-31 at 10 16 33 AM" src="https://user-images.githubusercontent.com/5741500/161076716-60be20c9-f423-4682-b5f2-1f3637660c89.png">

**Comment by ruchirK** [comment] 2022-03-31 14:37
wait this assertion was removed? Are we seeing this crash again?

**Comment by frankmcsherry** [comment] 2022-03-31 14:39
I think you removed it? https://github.com/MaterializeInc/materialize/issues/10742#issuecomment-1054366501

@elindsey mentioned that we are seeing a lot of this in the logs though; not panics, but spammy errors abound!

**Comment by benesch** [comment] 2024-01-28 00:49
Closing as long stale. The code in question here has been majorly refactored since this issue was filed.

**Closed by benesch** 2024-01-28 00:49 UTC
Labels: C-bug, A-source
