### ISSUE TITLE
Support avro files on s3

### ISSUE THREAD

**Issue by schicks** [MaterializeInc/materialize#6726] opened 2021-05-12 12:13 UTC
This seems likely to already be planned, I was just curious about what the timeline for such a thing might be. In a very distributed organization, it may be easier for teams to set up s3 buckets than Kafka clusters.

**Comment by umanwizard** [comment] 2021-05-12 15:33
This is something we could do but we haven't put it on the roadmap just yet.

A few questions to understand the shape of what would help you - How is your data organized? One big avro file in an s3 object, multiple in a bucket, some set of multiple buckets that would have to be communicated out of band? Do all the files have the same schema?

**Comment by umanwizard** [comment] 2021-05-12 15:35
Cc @quodlibetor for visibility.

**Comment by schicks** [comment] 2021-05-12 17:21
Most of this is hypothetical at this point, just exploring what is and isn't possible.

> How is your data organized?

Multiple timestamped files in a bucket; one that is being updated, the rest that are archival segments of the stream.

> Do all files have the same schema?

No, recent files could have updated but backwards compatible schemas. There's definitely some gap between that and a well behaved materialize source though; I had been imagining that updating the schema in these files would give the materialize source the schema of the most recent file, but I definitely haven't thought through the pitfalls that might cause.

**Comment by umanwizard** [comment] 2021-05-12 17:44
We are architecturally unable to change the schema of a source or view in Materialize without dropping and re-creating it.

What we _could_ do is, for example, use the schema of your choice when you create the source, and as long as the schemas of the other files are compatible with it, we would be able to ingest data from them just fine. But if then, say, you added a new field, you wouldn't be able to query that field in materialize without dropping and re-creating.

**Comment by schicks** [comment] 2021-05-12 18:28
So if I make a backwards compatible change (add a nullable column, make an existing column nullable, add an allowed value to an enum, etc.) the new data would be visible in materialize but without the additional column until I created a new source? That is probably fine, I just want to check my understanding.

**Comment by umanwizard** [comment] 2021-05-12 19:05
And typically for nullable fields, the default is `null`, so those would work out the way you expect.

**Comment by schicks** [comment] 2021-05-12 19:12
Ok, so it sounds like that _would_ be a totally reasonable behavior for my use case, given the ability to set up a bucket with multiple timestamped avro files in it as a source; Either the source setup process would separately specify an avro schema, or it would just pick the most recent schema at source creation time.

**Comment by elindsey** [comment] 2021-07-07 18:32
I'm marking this as a duplicate of #5596

**Closed by elindsey** 2021-07-07 18:32 UTC
Labels: C-feature
