### ISSUE TITLE
regression: zippy: materialized view reports "Invalid data in source, saw retractions" even though view sources are all good

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#14919] opened 2022-09-21 19:50 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/41777#01836170-6267-4f7a-9973-81c0aa735b7c

### Relevant log output

```source
> SELECT * FROM sink5_view /* 0 1071670 1071671 1071671 */ ;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 111s 166s 34s
<stdin>:2:1: error: non-matching rows: expected:
[["0", "1071670", "1071671", "1071671"]]
got:
[["0", "401061", "401061", "401061"]]
Poor diff:
- 0 1071670 1071671 1071671
+ 0 401061 401061 401061
 
     |
   1 |
   2 | > SELECT * FROM sink5_view /* 0 1071670 1071671 1071671 */ ;
     | ^
!!! Error Report
1 errors were encountered during execution
files involved: -
mzcompose: test case workflow-default failed: running docker compose failed (exit status 1)
==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
202 {'id': '07cae776-b578-4421-a5a2-ec997904fc1e', 'run_id': '2d7d4de9-25fc-410d-8979-be7ede59e79d', 'queued': 1, 'skipped': 0, 'errors': [], 'run_url': 'https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/2d7d4de9-25fc-410d-8979-be7ede59e79d'}
mzcompose: error: at least one test case failed
🚨 Error: The command exited with status 1
user command error: The plugin mzcompose command hook exited with status 1
```

### Additional thoughts

A couple other instances:

- https://buildkite.com/materialize/tests/builds/41769#01836122-871f-4ee0-ab03-a3e10891db89
- https://buildkite.com/materialize/tests/builds/41770#01836126-f670-4f52-ba99-ec4b9c3a5c41

**Comment by jkosh44** [comment] 2022-09-21 19:51
I added the STORAGE flag because the test involves sinks, but I'm not actually sure what the test is testing.

**Comment by aljoscha** [comment] 2022-09-21 20:34
This one might be a timeout issue. But #14754 is also happening in this zippy test and I diagnosed that one here: https://github.com/MaterializeInc/materialize/issues/14754#issuecomment-1253013894

**Comment by andrioni** [comment] 2022-09-22 16:45
One more [data point](https://buildkite.com/materialize/tests/builds/41844#018365db-7750-4f5e-8746-90275ddd6c2c).

**Comment by philip-stoev** [comment] 2022-09-23 08:40
There is no panic in the logs, so different from #14754 . The default timeout for the operation is 600 seconds, this is **10 minutes** and yet the results are unable to converge.

**Comment by philip-stoev** [comment] 2022-09-23 10:32
This is a true regression of the most horrible kind.

1. A view based on a sink reports incorrect results. The issue is permanent and is not resolved by waiting any amount of time.
2. The reason for this is that the sink has not emitted all the records expected in the sink topic.
3. The reason for that in turn is that the view the sink is based on has errored out:

```
materialize=> select * from view2;
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int64(0), Int64(670609), Int64(670610), Int64(670610)]
```

4. The horrible thing is that neither of the inputs of the materialized view has an error:
```
materialize=> select count(*) from source10;
1071671
materialize=> select count(*) from source9;
1071671
```

5. Running the SQL from the materialized view as a one-off query returns the correct results:
```
materialize=> SELECT "pg_catalog"."min"("source10"."f1"), "pg_catalog"."max"("source10"."f1"), "pg_catalog"."count"("source10"."f1") AS "c1", "pg_catalog"."count"(DISTINCT "source10"."f1") AS "c2" FROM "materialize"."public"."source10" JOIN "materialize"."public"."source9" USING ("f1");

 min |   max   |   c1    |   c2    
-----+---------+---------+---------
   0 | 1071670 | 1071671 | 1071671
```

6. The operation Zippy ran just prior to the issue happening is a kill of the entire materialized container and its restart.

**Comment by aalexandrov** [comment] 2022-09-23 11:35
I've added `A-COMPUTE` as well and I'm not looking into this as we're not sure yet which of the two components causes the issue.

**Comment by teskje** [comment] 2022-09-23 12:24
This might be a duplicate of https://github.com/MaterializeInc/materialize/issues/13496.

**Comment by cjubb39** [comment] 2022-09-27 21:59
Actually, I would like to toss this back to compute (see [this conversation](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1664307460216479?thread_ts=1664306649.076129&cid=C02PPB50ZHS) in slack)

**Comment by uce** [comment] 2022-09-28 08:15
Thanks for the pointer, didn't see the convo. I'm assigning to Jan (who is also assigned to what is likely a duplicate).

**Comment by teskje** [comment] 2022-09-28 09:37
It's difficult to prove a negative, but I'm not able to reproduce this issue with @aljoscha's new `persist_sink` implementation (https://github.com/MaterializeInc/materialize/pull/14001). This makes me quite confident that this issue has the same cause as https://github.com/MaterializeInc/materialize/issues/13496 and both will be fixed once we merge #14001.

**Comment by aljoscha** [comment] 2022-09-28 14:53
aha! and you are able to somewhat reliable re-produce it locally when not running with my changes?

**Comment by teskje** [comment] 2022-09-28 14:58
Yeah, somewhat: I had to run the "short zippy" test three times to get the issue to reproduce on main. With your PR I couldn't reproduce it after 10 tries. It's still possible that I was just lucky!

**Closed** 2022-09-28 18:53 UTC
Labels: C-bug, P1, A-STORAGE, A-COMPUTE, ci-flake
