### ISSUE TITLE
sql: chaining of `sql_impl_cast`-backed casts results in an exponential explosion and a subsequent crash

### ISSUE THREAD

**Issue by mkysel** [MaterializeInc/materialize#9231] opened 2021-11-22 20:00 UTC
when working on #9195, we noticed that long chain of type casts such as `'bool'::regtype::text::regtype::text::regtype` will crash the server.

from @asenac:
We should file an issue for the fact that chaining `sql_impl_cast`-backed casts results in an exponential explosion when passing subqueries as parameters of those `sql_impl_casts`. I don't think that is fixable atm, but worth logging it, just in case we ever switch to QGM as the representation built during query planning.

**Comment by asenac** [comment] 2021-12-31 09:18
After the recent changes to make the optimizer stackoverflow-safe the cast in the description no longer makes the server crash. However, it stills leads to a massive decorrelated plan (I can't even paste a graph of the plan here because it crashes any image processing tool I normally use for generating them).

I did a quick check and we could simplify the resulting plan a lot by putting the value being casted behind a CTE as the following patch does:

```
diff --git a/src/sql/src/plan/typeconv.rs b/src/sql/src/plan/typeconv.rs
index 91c27db6c..1608c49e2 100644
--- a/src/sql/src/plan/typeconv.rs
+++ b/src/sql/src/plan/typeconv.rs
@@ -21,6 +21,8 @@ use expr::func;
 use expr::VariadicFunc;
 use repr::{ColumnName, ColumnType, Datum, RelationType, ScalarBaseType, ScalarType};
 
+use crate::plan::HirRelationExpr;
+
 use super::error::PlanError;
 use super::expr::{CoercibleScalarExpr, ColumnRef, HirScalarExpr, UnaryFunc};
 use super::query::{ExprContext, QueryContext};
@@ -31,9 +33,28 @@ fn sql_impl_cast(expr: &'static str) -> CastTemplate {
     let invoke = crate::func::sql_impl(expr);
     CastTemplate::new(move |ecx, _ccx, from_type, _to_type| {
         let mut out = invoke(&ecx.qcx, vec![from_type.clone()]).ok()?;
-        Some(move |e| {
-            out.splice_parameters(&[e], 0);
-            out
+        let cte_id = expr::LocalId::new(ecx.qcx.ctes.len() as u64);
+        let from_type = from_type.clone().nullable(true);
+        Some(move |mut e: HirScalarExpr| {
+            e.visit_columns_mut(0, &mut |depth, col| {
+                if col.level >= depth {
+                    col.level += 1;
+                }
+            });
+            let cte_value = HirRelationExpr::constant(vec![], RelationType::empty()).map(vec![e]);
+            let cte_ref = HirRelationExpr::Get {
+                id: expr::Id::Local(cte_id.clone()),
+                typ: RelationType::new(vec![from_type]),
+            };
+            let param = HirScalarExpr::Select(Box::new(cte_ref));
+            out.splice_parameters(&[param], 0);
+            let cte_body = HirRelationExpr::constant(vec![], RelationType::empty()).map(vec![out]);
+            HirScalarExpr::Select(Box::new(HirRelationExpr::Let {
+                name: "Cast".to_string(),
+                id: cte_id,
+                value: Box::new(cte_value),
+                body: Box::new(cte_body),
+            }))
         })
     })
 }
```

The resulting plan leads to 1/4 of the nodes the current one has:

![after](https://user-images.githubusercontent.com/1282736/147814648-4dddad09-ee44-4363-a66d-a75058a31f05.png)

**Comment by sploiselle** [comment] 2024-01-23 12:04
Duplicate of #20408, which we mitigated somewhat by growing the stack

**Closed by sploiselle** 2024-01-23 12:04 UTC
Labels: C-bug, A-sql
