### ISSUE TITLE
`dbt run` Eventually Fails Due to `environmentd` Crashing

### ISSUE THREAD

**Issue by nmeagan11** [MaterializeInc/materialize#15480] opened 2022-10-17 21:18 UTC
### What version of Materialize are you using?

Cloud

### How did you install Materialize?

Materialize Cloud

### What is the issue?

A customer executed `dbt run` and it failed with what looks like `psycopg2` timing out. The error was `SSL SYSCALL error: EOF detected` ([reference](https://materializeinc.slack.com/archives/C02LJ9EJP9S/p1665854009141549)). We originally thought this was due to introspection, but this customer has introspection disabled on their cluster.

Possibly related to https://github.com/MaterializeInc/materialize/issues/13772, an issue with `environmentd`, or something else not captured here.

**Comment by benesch** [comment] 2022-10-17 22:06
So this actually isn't a timeout! It's an `environmentd` crash.

**Comment by benesch** [comment] 2022-10-17 22:08
Or maybe it is? Either way, here's at least one crash from the relevant `environmentd` process:

```
thread 'coordinator' panicked at 'Peek endpoint terminated prematurely: Canceled', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/command_handler.rs:526:22
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::expect
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1064:23
   4: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_cancel::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/command_handler.rs:524:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   6: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/command_handler.rs:93:56
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   8: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:149:33
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  10: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:146:5
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  12: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:40:63
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  14: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord.rs:855:37
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  16: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
  17: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  18: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  19: std::thread::local::LocalKey<T>::with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  20: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
  21: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
  22: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
  23: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
  24: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/handle.rs:297:9
  25: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0efb11835bec0ffd2-1/materialize/tests/src/adapter/src/coord.rs:1000:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-0896c951-c2b2-41fd-a8e8-c50e07524783-0/environmentd-0 (environmentd)
```

**Comment by jkosh44** [comment] 2022-10-18 15:43
So what's happening here is that someone tried to cancel a peek and send a cancel response, but the client has already hung up their receiver. The exact panic is here: 
https://github.com/MaterializeInc/materialize/blob/39817b744496af119eda27184808de6d08028534/src/adapter/src/coord/command_handler.rs#L525-L527

I think the fix is to not panic there and instead log a warning. There are some paths where the client hangs up and never attempts to read from the corresponding `rows_ts` receiver. For example in this function:
https://github.com/MaterializeInc/materialize/blob/39817b744496af119eda27184808de6d08028534/src/pgwire/src/protocol.rs#L1059-L1113
The `rows: RowsFuture` parameter is the receiver waiting for a peek response. If the connection is closed, then this will be dropped without ever waiting for a response.

Furthermore, according to the Postgres spec, the cancel message doesn't have to be sent from the same connection. So it's a valid scenario that we receive a cancel request after the actual connection has been closed.

**Comment by jkosh44** [comment] 2022-10-18 15:53
If the connection explicitly sends a Terminate message then, we do explicitly try and remove all pending peeks though. So maybe there's a small race condition here where the connection hangs up before the terminate has fully processed.

On the other hand, I'm not sure what happens if a connection drops without sending a Terminate message. I'm not sure if we clean up that connections state.

**Comment by mjibson** [comment] 2022-10-18 16:00
We clean those up. When a connection drops the session gets dropped which will send a terminate: https://github.com/MaterializeInc/materialize/blob/f4ed657b7034660c28ef82083214405d7d929bca/src/adapter/src/client.rs#L373

**Comment by jkosh44** [comment] 2022-10-18 16:19
Ahh Ok that makes sense. Though I do think that the race condition exists where the receiver is dropped in `protocol::row_future_to_stream` as shown above, but the terminate hasn't been sent/received yet. Which would explain this panic.

**Comment by jkosh44** [comment] 2022-10-18 16:28
@mjibson is that explanation convincing for you? I'm not 100% convinced myself, more like 85%.

This panic means that there's a race condition where the connection has hung up and closed it's receiver, but the Coordinator hasn't cleaned up the connection state.

@nmeagan11 do you know if they were getting this error consistently or sporadically?

**Comment by nmeagan11** [comment] 2022-10-18 17:24
> do you know if they were getting this error consistently or sporadically?

They're reporting that this error is consistent.

**Comment by jkosh44** [comment] 2022-10-18 17:31
@mjibson and I huddled, this is definitely a race condition and from the stack trace it looks like it caused `environmentd` to crash for the customer. 

However, since the error they're facing is consistent it leads me to believe that the stack trace is not necessarily related to the timeouts because this race condition should be hard to trigger. Can someone send me a org-id information or a link to the customer logs so I can further investigate?

**Comment by jkosh44** [comment] 2022-10-19 18:14
Just to update everyone, the panic that caused the stack trace shown above has been fixed. However the timeouts were not caused by the panic, they were caused by a known issue that caused an OOM loop. I've unassigned myself.

**Comment by benesch** [comment] 2022-10-31 21:13
Closing as there are other issues to track the OOM issue.

**Closed by benesch** 2022-10-31 21:13 UTC
Labels: C-bug, C-triage
