### ISSUE TITLE
doc: You can create indexes on sequences of arbitrary expressions (not just columns)

### ISSUE THREAD

**Issue by msudberg** [MaterializeInc/materialize#9010] opened 2021-11-09 15:13 UTC
### For updates to existing documentation

* What pages are affected?

https://materialize.com/docs/sql/create-index/

* What needs to be added?

- why is this useful?
- possible memory implications?
- examples

Background: https://materializeinc.slack.com/archives/CPNFV9CVB/p1636397821027100

SMEs: @umanwizard, @frankmcsherry

**Comment by morsapaes** [comment] 2022-06-29 09:19
Duplicate of #10739. Fixed in #10744.

**Closed by morsapaes** 2022-06-29 09:19 UTC
Labels: A-docs
