### ISSUE TITLE
Cascading when dropping a table is supported, but not documented

### ISSUE THREAD

**Issue by jstuyts** [MaterializeInc/materialize#5901] opened 2021-02-26 10:31 UTC
Just like when dropping sources and views, with tables it is also possible to cascade-drop the objects depending on the table. But this is not documented: https://materialize.com/docs/sql/drop-table/

**Comment by msudberg** [comment] 2021-03-26 15:54
Duplicate of #5373

**Closed** 2021-03-26 15:53 UTC
Labels: A-docs, C-bug
