### ISSUE TITLE
Protobuf support for `SourceDesc`

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#11876] opened 2022-04-18 16:26 UTC
This story is part of the overall versioning epic that spans all teams.

## Goals

* Introduce protobuf types for transitive dependencies of [`SourceDesc`](https://dev.materialize.com/api/rust/mz_dataflow_types/sources/struct.SourceDesc.html)
* Implement mapping between regular and Protobuf-variants of types

## Non-Goals

* End-to-end version upgrades

## Subtasks

* [ ] Scope this task a la #11735.

## See also

* #11735

**Comment by andrioni** [comment] 2022-05-25 15:14
Dupe of #12358, which is done.

**Closed by andrioni** 2022-05-25 15:14 UTC
Labels: A-platform, A-STORAGE
