### ISSUE TITLE
Sources stuck with [0] read/write frontier

### ISSUE THREAD

**Issue by uce** [MaterializeInc/materialize#15317] opened 2022-10-10 17:55 UTC
### What version of Materialize are you using?

v0.27.0-alpha.25

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
                       Timestamp
---------------------------------------------------------------------
           query timestamp: 1665416268427 (2022-10-10 15:37:48.427) +
                     since:[            0 (1970-01-01 00:00:00.000)]+
                     upper:[            0 (1970-01-01 00:00:00.000)]+
          global timestamp: 1665416268427 (2022-10-10 15:37:48.427) +
   can respond immediately: false                                   +
                                                                    +
 source $ (u5, storage):                                            +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u6, storage):                                            +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u7, storage):                                            +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u9, storage):                                            +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u10, storage):                                           +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u11, storage):                                           +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u12, storage):                                           +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u13, storage):                                           +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
                                                                    +
 source $ (u14, storage):                                           +
  read frontier:[            0 (1970-01-01 00:00:00.000)]           +
 write frontier:[            0 (1970-01-01 00:00:00.000)]           +
(1 row)
```

via [Slack](https://materializeinc.slack.com/archives/C0403RW9NAZ/p1665416563709309)

### Relevant log output

```source
-
```

**Comment by uce** [comment] 2022-10-10 18:48
As @petrosagg notes in Slack, this could be an instance of https://github.com/MaterializeInc/materialize/issues/15300 if the sizes are using multiple workers.

**Comment by philip-stoev** [comment] 2022-10-10 18:58
Or https://github.com/MaterializeInc/materialize/issues/15155 no multi workers required.

**Comment by uce** [comment] 2022-10-11 07:23
Yes, #15155 seems to be the same issue. I'll keep this open, because it has been linked in a few release-related places.

**Comment by benesch** [comment] 2022-10-27 05:57
@uce is it ok to close this as a duplicate of #15155 now?

**Comment by benesch** [comment] 2022-11-05 01:45
#15155 is closed, so I'm closing this one too!

**Closed by benesch** 2022-11-05 01:45 UTC
Labels: C-bug, P1, A-STORAGE
