### ISSUE TITLE
Materialize using a huge amount of memory even when no messages are sucessfully decoded

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#4814] opened 2020-11-17 06:23 UTC
After starting the ingest benchmark with a bad datasource, Materialize memory grew until it was using all of the physical memory on my machine. I took a screenshot of where the memory was going, and downloaded the heap profile as well.

![Screenshot from 2020-11-16 22-20-26](https://user-images.githubusercontent.com/551285/99353746-01f60480-285a-11eb-8f86-9d7a88afb23e.png)

**Comment by cirego** [comment] 2020-11-23 17:44
@umanwizard and @ruchirK, you might find this interesting. If I start up Materialize on a "corrupt Kafka topic", then memory utilization balloons.

This issue reproduces reliably using the `chbench snapshot-test` workflow from #4833.

**Comment by umanwizard** [comment] 2020-11-23 17:46
what exactly is corrupt about the topic?

**Comment by umanwizard** [comment] 2020-11-23 17:47
@benesch possible leak in rust-rdkafka ?

**Comment by benesch** [comment] 2020-11-23 18:05
Or librdkafka, yeah.

**Comment by cirego** [comment] 2020-11-23 19:01
> what exactly is corrupt about the topic?

I'm not sure what exactly is corrupt, but these are the error messages that I am seeing:

```
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: IO error: UnexpectedEof                                                                                                                                         
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 2                                                                                               
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 109    
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 102                                                                                             
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 116    
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: IO error: UnexpectedEof                                                                                                                                         
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 109                                                                                             
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 102    
Nov 23 18:37:45.309 ERROR dataflow::decode::avro: avro deserialization error: wrong Confluent-style avro serialization magic: expected 0, got 116   
```

**Comment by umanwizard** [comment] 2020-11-23 19:13
Got it. Yep, that just means whatever you have in the topic either isn't Avro at all, or if it is, isn't formatted in the "Confluent Avro" format (i.e., literal 0 byte, then 4-byte schema ID, then Avro payload)

**Comment by benesch** [comment] 2022-02-05 02:19
Closing as working as intended. Unfortunately there's not a whole lot we can do with corrupt Avro messages.

**Closed by benesch** 2022-02-05 02:19 UTC
Labels: C-bug
