### ISSUE TITLE
postgres snapshot ingested at leisurely 44Mb/sec, CPU bound

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17997] opened 2023-03-08 12:04 UTC
### What version of Materialize are you using?

v0.45.0-dev (e27ae941f)

### How did you install Materialize?

Docker image

### What is the issue?

Ingesting a postgres snapshot:
- appears to be single-threaded
- 30% of the time is spent in cockroachdb, the rest is in clusterd
- proceeds at a speed of 44000 1-Kb rows/second

At the end, about 1K S3 blobs are created, and they appear to have the proper uniform sizeof 128Mb each

To reproduce:

1. Apply diff:
```
diff --git a/test/bounded-memory/mzcompose.py b/test/bounded-memory/mzcompose.py
index 1f0685e74..1bb239261 100644
--- a/test/bounded-memory/mzcompose.py
+++ b/test/bounded-memory/mzcompose.py
@@ -26,8 +26,8 @@ from materialize.mzcompose.services import (
 PAD_LEN = 1024
 STRING_PAD = "x" * PAD_LEN
 REPEAT = 16 * 1024
-ITERATIONS = 128
+ITERATIONS = 1024
 MATERIALIZED_MEMORY = "5Gb"
 CLUSTERD_MEMORY = "3.5Gb"
 
 SERVICES = [
```

And run:

```
./mzcompose down -v ; time ./mzcompose run default pg-cdc-snapshot
```

**Comment by aljoscha** [comment] 2023-03-08 13:06
Seems to be a duplicate of https://github.com/MaterializeInc/materialize/issues/16637?

**Comment by aljoscha** [comment] 2023-03-08 13:07
closing for now, but please re-open if you think it's not a duplicate

**Closed by aljoscha** 2023-03-08 13:07 UTC
Labels: C-bug, T-performance

**Comment by sploiselle** [comment] 2023-03-08 22:45
@MaterializeInc/persist Wanted to check with you all--does this seem like a usecase we could reasonably support? This test generates an 18gb dataset, which we then take an initial snapshot of. This seems like it generates a batch of ~1k parts (I can't validate this bc I don't know how to get the test to run on S3 and the dataset causes my scratch machine to OOM locally). Does that seem like a set of operations we should reasonably support?

**Comment by danhhz** [comment] 2023-03-08 22:49
there's a number of things we could do to tune persist throughput, if that's the question, but we've intentionally deprioritized them because customers haven't been asking for it. cc @dseisun-materialize

**Comment by sploiselle** [comment] 2023-03-09 01:39
@danhhz ty for the quick reply and sorry, my questions were poorly phrased. What I meant was "does this seem like a scale of work that we do currently support?" Trying to figure out if this issue is worth chasing down or if its scale exceeds our current estimates of what we currently handle.
