### ISSUE TITLE
Aggregate functions not protected against BIGINT overflow - wrap around and wrong results occur

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#5218] opened 2021-01-06 08:47 UTC
### What version of Materialize are you using?

```
$ materialized -v

0.6.0

```

### How did you install Materialize?

* [ ] Docker image

### What was the issue?

Aggregates are not protected against BIGINT overflow. It is possible for e.g. SUM to overflow, wrap around and return a wrong result.

### Is the issue reproducible? If so, please provide reproduction instructions.`
````
CREATE DATABASE test;
SET DATABASE = test;

DROP VIEW t2;
DROP TABLE t1;

CREATE TABLE t1 (f1 INTEGER);
INSERT INTO t1 VALUES (1),(2),(3),(4);
CREATE MATERIALIZED VIEW t2 (f1) AS select a1.f1 from t1 as a1, t1 as a2, t1 as a3, t1 as a4, t1 as a5, t1 as a6; 

INSERT INTO t1 VALUES (1),(2),(3),(4);

philips=>  select sum(a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1) from t2 as a1 , t2 as a2, t2 as a3;
         sum          
----------------------
 -8016407336719482880 <-- wrong result here
(1 row)

````

**Comment by philip-stoev** [comment] 2021-01-06 08:48
```COUNT``` is reported as zero when it overflows:

````philips=> select count(*) from t2 as a1 , t2 as a2, t2 as a3, t2 as a4;
 count 
-------
     0
(1 row)

philips=> select count(distinct a1.f1) from t2 as a1 , t2 as a2, t2 as a3, t2 as a4;
 count 
-------
     0
(1 row)
````

**Comment by ruchirK** [comment] 2021-01-06 14:02
Hi @philip-stoev thanks very much for this report! Let me investigate this and see what we can do

**Comment by ruchirK** [comment] 2021-01-07 17:21
I spent a bunch of time investigating this, and ended up simplifying the example a bit to make it easier to reason about whats going on

```
materialize=> CREATE TABLE t1 (f1 INTEGER);
CREATE TABLE
materialize=> INSERT INTO t1 VALUES (1),(1),(1),(1);
INSERT 0 1
materialize=> INSERT INTO t1 VALUES (1),(1),(1),(1);
INSERT 0 1
```

Made `t1` just consist of 8 1s so its easier to keep track of what the expected sum should be

now `t2`

```
materialize=> CREATE MATERIALIZED VIEW t2 (f1) AS select a1.f1 from t1 as a1, t1 as a2, t1 as a3, t1 as a4, t1 as a5, t1 as a6;
```

has 8^6 (or 2^18) elements

which means that this sum
```
materialize=> select sum(a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1 * a1.f1 * 10) from t2 as a1 , t2 as a2, t2 as a3;
        sum
--------------------
 180143985094819840
(1 row)
```

should compute 2^54 which it does. It also shows that we can overflow signed 64 bit integers by replacing each element with 2^9 (since signed 64 bit integers go as high as 2^63 - 1) and indeed that is what happens

```
materialize=> select sum(a1.f1 * 512) from t2 as a1 , t2 as a2, t2 as a3;
         sum
----------------------
 -9223372036854775808
(1 row)
```

Unfortunately, I can't reproduce this behavior on Postgres because trying to execute the 3-way self join on `t2` hangs forever. I tried defining a different view with 2^33 rows using other combinations of joins, and those didn't complete either.

Note that its not sufficient to try to cheat the sum by triggering an overflow to the arguments of the sum before the sum is computed or the results of the sum after the sum is computed

```
materialize=> select sum(f1 + 2147483647) from t1;
ERROR:  Evaluation error: numeric field overflow
```

Postgres does a slightly better job than materialize on view creation

Materialize:

```
materialize=> create materialized view test_bad_sum as select sum(f1 + 2147483647) from t1;
CREATE VIEW
materialize=> select * from test_bad_sum;
ERROR:  Evaluation error: numeric field overflow
```

but postgres can detect the error at view creation time (this seems hard for us to change)
```
Test=# create materialized view test_bad_sum as select sum(f1 + 2147483647) from t1;
ERROR:  integer out of range
```

similarly, trying to overflow the result of a sum after its computed gets caught as an error
```
materialize=> select sum(a1.f1) * 2147483647 from t2 as a1, t2 as a2;
ERROR:  Evaluation error: numeric field overflow
```

The count overflows unsigned 64 bits when we compute it for the 4-way self join of `t2` since the true size of that relation is 2^72. We downcast from a singed 128 bit int to a unsigned 64 bit int - thus the zero.

Unfortunately, I don't have an immediate plan for how to fix this

**Comment by ruchirK** [comment] 2021-01-07 19:32
cc: @frankmcsherry because you had thoughts on how to introduce errors in reduce rendering.

@philip-stoev is this error blocking you from doing something in Materialize? Let us know if so and I can try to find a workaround / prioritize fixing it more aggressively

**Comment by frankmcsherry** [comment] 2021-01-07 19:42
This is a bit unexpected. I expected we'd overflow `i128` which we use for aggregation, but if we are also overflowing `i64` then something else / in addition in afoot.

**Comment by frankmcsherry** [comment] 2021-01-07 19:45
Ah, though perhaps when we have to eventually take the accumulation back to an `i64` at the end (as we don't leave it as `numeric`) we could wrap there. But yes, this looks like something (if it is what I just said) that would require the ability to error in a place that doesn't currently allow erroring methods. If it is blocking you, I'd trying out using higher precision integer types in the accumulation for now.

**Comment by philip-stoev** [comment] 2021-01-07 19:45
@ruchirK  No, it is not blocking me at all. I ran into this as I was exploring various edge cases.

**Comment by ruchirK** [comment] 2021-01-07 20:36
@frankmcsherry yeah currently sums over `i32` and `i64` (using rust type names for the corresponding pg types) get cast back to `i64` at the end. pg requires that sums over `i64`s (bigint) be converted to `numeric` but we don't currently do that because our numeric type is different from pg's not sure why.

I don't think anything is stopping us from overflowing i128 as we compute the sum, just none of these examples have stressed that yet.

**Comment by ruchirK** [comment] 2021-01-08 00:01
btw @philip-stoev have you been able to get these commands to work successfully with Postgres at all?

Digging around the postgres source code (h/t @mjibson ) it seems like Postgres may also overflow in this test, as it uses a `int64` accumulator to store the computed sum, and only does unchecked addition as far as I can tell.

The relevant line of code seems to be here https://github.com/postgres/postgres/blob/fead67c24ada8c6a4b661dec6f159dca1447e3d8/src/backend/utils/adt/numeric.c#L6350

and a few lines above that, this comment seems to indicate that postgres doesn't see bigint overflow on int sums as a concern:

```
* To avoid overflow, we use accumulators wider than the input datatype.
 * A Numeric accumulator is needed for int8 input; for int4 and int2
 * inputs, we use int8 accumulators which should be sufficient for practical
 * purposes.
 ```
 
 I wouldn't be surprised if Postgres took a similar stance with `count` overflowing bigint as well, though I haven't checked the code myself. Like I said above, I haven't been able to successfully run these tests against Postgres, but if you had, I'd love to know what the result was

**Comment by philip-stoev** [comment] 2021-01-11 09:15
@ruchirK here is an example that works correctly in postgresql:

````
postgres=# create table t1 (f1 bigint);
CREATE TABLE
postgres=# insert into t1 values (9223372036854775807),(9223372036854775807);
INSERT 0 2
postgres=# select sum(f1) from t1;
         sum          
----------------------
 18446744073709551614
(1 row)

postgres=# select pg_typeof(sum(f1)) from t1;
 pg_typeof 
-----------
 numeric
(1 row)
```

The type of SUM in PostgreSQL is NUMERIC.

In Materialize:

```
philips=> create table t1 (f1 bigint);
CREATE TABLE
philips=> insert into t1 values (9223372036854775807),(9223372036854775807);
INSERT 0 1
philips=> select sum(f1) from t1;
 sum 
-----
  -2
(1 row)

philips=> select pg_typeof(sum(f1)) from t1;
 pg_typeof 
-----------
 int8
(1 row)
{code}

The type for SUM is int8, that is BIGINT, which is not sufficient to hold all possible results. Postgres's NUMERIC is the safer choice.

**Comment by ruchirK** [comment] 2021-01-11 15:34
@philip-stoev yes definitely put up a fix for `BIGINT` sums to correctly output `NUMERIC` - hopefully be the end of the day.

I'm less sure about `INTEGER` sums -- I actually think based on the Postgres code that Postgres would also overflow and that Materialize's current behavior of exposing the bigint overflow for int sums is ok for now. At the very least, we can add something in our known limitations page, and revisit if someone runs into it in a real use case. How does that sound?

**Comment by philip-stoev** [comment] 2021-01-11 15:43
@ruchirK since my last comment, the  query in PostgreSQL over an INTEGER column did indeed complete and it also wrapped around to a negative value.

I would agree that this is a corner case so I would say there is no need to battle it right now. Thanks for taking the time to get to the bottom of this.

**Comment by ruchirK** [comment] 2021-01-11 15:51
Awesome! No problem happy to help.

**Comment by ruchirK** [comment] 2021-01-12 21:39
The issue with bigint sums should be fixed now! I'm going to close this issue as I think we've fixed bigint sums and concluded that the behaviour for int sums is as expected but feel free to reopen if you feel like I've missed something.

**Closed by ruchirK** 2021-01-12 21:39 UTC
Labels: C-bug
