### ISSUE TITLE
thread 'coordinator' panicked at src/adapter/src/util.rs:277:23: dataflow creation cannot fail: SinceViolation(User(174))

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25411] opened 2024-02-21 09:30 UTC
### What version of Materialize are you using?

1d67217568

### What is the issue?

As suggested in https://github.com/MaterializeInc/materialize/issues/24130 a new issue:
```
thread 'coordinator' panicked at src/adapter/src/util.rs:277:23:
dataflow creation cannot fail: SinceViolation(User(174))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: <core::result::Result<(), mz_compute_client::controller::error::DataflowCreationError> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/util.rs:277:23
   3: <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord.rs:2655:9
   4: <futures_util::future::maybe_done::MaybeDone<<mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   5: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>, <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
   6: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:321:83
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:273:5
   9: <mz_adapter::coord::SubscribeStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:50:81
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>> as core::future::future::Future>::poll
             at ./rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/future/future.rs:125:9
  11: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::SubscribeStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:147:14
  13: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord/message_handler.rs:184:60
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/future/future.rs:125:9
  16: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord.rs:2535:48
  17: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/future/future.rs:125:9
  18: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  20: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  21: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  22: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  23: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  24: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  25: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  26: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  27: mz_adapter::coord::serve::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d34b032c48437b3f-1/materialize/tests/src/adapter/src/coord.rs:2985:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/nightlies/builds/6547. I didn't see any immediately suspicious changes in that run: https://github.com/MaterializeInc/materialize/compare/6312de4e1e...1d67217568 So maybe this is flaky.

ci-regexp: dataflow creation cannot fail: SinceViolation

**Comment by nrainer-materialize** [comment] 2024-02-21 09:32
Duplicate of (the just closed) issue https://github.com/MaterializeInc/materialize/issues/24130?

**Comment by teskje** [comment] 2024-02-21 09:40
Looks like a duplicate of https://github.com/MaterializeInc/materialize/issues/25375!

**Closed** 2024-02-21 10:13 UTC
Labels: C-bug, ci-flake
