### ISSUE TITLE
Support adding per-field default values in generated Avro schemas for sinks 

### ISSUE THREAD

**Issue by moulimukherjee** [MaterializeInc/materialize#21662] opened 2023-09-08 07:06 UTC
*Part of epic #17209.*

### Feature request

It's possible to specify default values for fields in Avro schemas. Currently in Materialize we don't provide the users the means to do so for the Avro schemas created for Sinks. 

The solution could look like a `DEFAULT ON …` option for the `FORMAT AVRO` in the `CREATE SINK` statement. 

Related issue: https://github.com/MaterializeInc/materialize/issues/21557 (to add `DOC ON` options for fields)

More context: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1694126238595679?thread_ts=1693346615.414889&cid=C01CFKM1QRF

**Comment by benesch** [comment] 2023-09-08 07:14
Also note we had a request for the _default_ default for a field to be `null` when that field is a standard nullable union. E.g., Materialize should never emit a field like

```json
{"name": "a", type: ["null", "string"]}
```

and instead should always specify a default of "null":

```json
{"name": "a", type: ["null", "string"], default: "null"}
```

I don't love this idea, though. At least not as the normal behavior of `FORMAT AVRO`. As @moulimukherjee unearthed, the Avro specification intentionally does not presume that the right default for a nullable field is `null`: https://issues.apache.org/jira/browse/AVRO-1803. It's perfectly valid to have a field like this, for example:

```json
{"name": "a", type: ["null", "string"], default: "bananas"}
```

That said, I think it's a common pattern. In addition to `DEFAULT ON`, we could also add an option like `DEFAULT NULLABLE FIELDS TO NULL` (better name pending) that automatically uses "null" as the default for any fields whose type is a nullable union, unless a more specific default is specified with `DEFAULT ON`.

**Comment by benesch** [comment] 2024-01-15 16:39
Just realized this is a duplicate of #18544.

**Closed by benesch** 2024-01-15 16:39 UTC
Labels: C-feature, A-STORAGE
