### ISSUE TITLE
tests flaky due to: failed preemptive refresh due to a conflict

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#19858] opened 2023-06-12 10:05 UTC
### Buildkite link

https://buildkite.com/materialize/tests/builds/57392#0188aeaf-7f16-44f9-8762-a03f3c5dfded

### Relevant log output

```
[2023-06-12T08:30:54Z]
thread 'test_auth_base' panicked at 'called `Result::unwrap()` on an `Err` value:
stash error: postgres: db error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError:
TransactionRetryError: retry txn
  (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1):
  "sql txn" meta={id=18a85773 key=/Table/3/1/653/2/1 pri=0.01136647 epo=0 ts=1686558367.077880878,1 min=1686558366.333602793,0 seq=20}
  lock=true stat=PENDING rts=1686558366.333602793,0 wto=false gul=1686558366.833602793,0
```

### Buildkite link
https://buildkite.com/materialize/tests/builds/57718#0188beb1-6e7e-44c8-8c5a-4740b64d7495

### Relevant log output

```
[2023-06-15T11:09:35Z] thread 'upgrade::v18_to_v19::tests::smoke_test' panicked at 'called `Result::unwrap()` on an `Err` value: StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E40001), message: "restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: committed value on key /Table/3/1/100/2/1): \"sql txn\" meta={id=8f21472a key=/Table/3/1/476/2/1 pri=0.01464942 epo=0 ts=1686827066.854639605,2 min=1686827062.423314964,0 seq=20} lock=true stat=PENDING rts=1686827062.423314964,0 wto=false gul=1686827062.923314964,0", detail: None, hint: Some("See: https://www.cockroachlabs.com/docs/v23.1/transaction-retry-error-reference.html#retry_serializable"), position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }) }', src/stash/src/upgrade/v18_to_v19.rs:210:76
```

**Comment by benesch** [comment] 2023-06-15 16:30
Closing as a duplicate of #19931.

**Closed by benesch** 2023-06-15 16:30 UTC
Labels: C-bug, ci-flake
