### ISSUE TITLE
Upgrade Docker base image to ubuntu 20

### ISSUE THREAD

**Issue by awang** [MaterializeInc/materialize#6489] opened 2021-04-16 14:25 UTC
Using Materialize with Ubuntu 18 is known to cause "metadata timeout" errors with Kerberos: https://github.com/MaterializeInc/materialize/issues/6916

**Comment by cirego** [comment] 2021-04-16 17:39
I'll go ahead and take a stab at this!

**Comment by benesch** [comment] 2021-04-16 18:24
Eek! Posted this on Slack, but I'm against this for two reasons:

1. Upgrading to Ubuntu 20.04 is as likely to cause new problems as it is to cause old problems. We'll have to upgrade eventually but I'd like to avoid doing it on short notice.

2. Papering over problems like this without understanding their root cause is bad engineering practice. To date we have spent zero time into investigating the metadata timeout errors with Kerberos. If we'd spent a week trying to understand the issue without making progress, then this would be a more reasonable hack, I think. But if we don't understand the root cause of the issue, we can't say with any confidence that upgrading to Ubuntu 20.04 really fixes the issue.

**Comment by cirego** [comment] 2021-04-16 18:29
@benesch, I agree that we should understand the root cause. My understanding was that the timeout issue was a known issue with 18.04 -- perhaps we should push back a little bit more on this!

**Comment by benesch** [comment] 2021-04-16 18:37
It’s known in that we had one customer observing the metadata timeout issue with our Docker image. They claim the issue was fixed by copying the binaries into an Ubuntu 20.04 Docker image. That fix has never made much sense to me. We’ve never been able to reproduce the issue, to my knowledge.

We largely stopped looking into the issue because the one customer that cares about Kerberos support found that dubious workaround. Now that we have another customer seeing issues, probably time to bump up the priority again. I’m fairly suspicious of our Kerberos support in general.

**Comment by alex-hunt-materialize** [comment] 2021-08-17 18:24
Relates to https://github.com/MaterializeInc/materialize/issues/5678

**Comment by alex-hunt-materialize** [comment] 2021-08-17 18:28
I agree that the previous reason given for upgrading to 20.04 is not great, but I think we should still upgrade to 20.04 to stay on the latest LTS which will have better support and documentation.

**Closed** 2021-08-18 20:48 UTC
Labels: C-refactoring
