### ISSUE TITLE
perist: persisting the system tables creates excessive I/O under simple SELECT workload

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8253] opened 2021-09-13 09:17 UTC
### What version of Materialize are you using?

```
v0.9.4-dev (42c8871dc)
```

### What was the issue?

If a workload is applied that just runs `SELECT * FROM t1` against Mz in 1 connection, persisting the system tables causes excessive I/O:

- strace reports:
 ** 300 (three hundred) files being opened within 1-second period
 ** 80 renames 
 ** 100 unlinks
- iostat reports 8Mb written every second
- iotop reports:

```
Total DISK READ:         0.00 B/s | Total DISK WRITE:      1166.47 K/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:       6.26 M/s
```

The difference between "Total" and "Current" I take to mean that the metadata operations against the filesystem cause massive write amplification.

With more concurrent connections, the I/O consumption increases to 12Mb/s -- I think it would have gone higher had ,Mz  been able to scale linearly.

### Is the issue reproducible? If so, please provide reproduction instructions.

Just run a simple `SELECT` workload using your favorite tool.

**Comment by philip-stoev** [comment] 2021-09-13 09:21
I fiddled with --retain-prometheus-metrics and  --metrics-scraping-interval and the I/O only goes up, never down.

**Comment by philip-stoev** [comment] 2021-09-13 09:32
If I have many materialized views, even if I do not select from most of them, the I/O goes to 30Mb/sec . I do not think this is sustainable.

**Comment by philip-stoev** [comment] 2021-09-13 09:46
So it seems that is is a chain of amplifications that goes something like this:
1. Every user SELECT gets amplified to an update to the persisted metrics table (even though TAIL-ing the metrics table does not show a torrent of new records arriving)
2. Every update to the metrics table gets amplified to a complete write of the entire table to disk (?)
3. Every write to disk gets amplified into a filesystem metdatata update that contains create + rename + unlink

**Comment by danhhz** [comment] 2021-09-13 15:51
Hey @philip-stoev thanks for filing this! Do you think you could provide detailed repro instructions? We've done some internal testing before turning this on (including running the release load tests) and haven't seen anything even remotely like this

**Comment by philip-stoev** [comment] 2021-09-13 16:07
To reproduce:

1. Start with this schema:
```
DROP SCHEMA public CASCADE;

CREATE SCHEMA public;

CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2, f1);

-- one NULL row in t1

INSERT INTO t1 VALUES (NULL, 0);

-- values 1 and 2 have 2 rows each in t1

INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (3, 3);
INSERT INTO t1 VALUES (4, 4);
INSERT INTO t1 VALUES (5, 5);
INSERT INTO t1 VALUES (6, 6);
INSERT INTO t1 VALUES (7, 7);
INSERT INTO t1 VALUES (8, 8);

-- value 9 not present in either table

CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t2i1 ON t2(f1);
CREATE INDEX i2i2 ON t2(f2, f1);

-- two NULL rows in t2

INSERT INTO t2 VALUES (NULL, 0);
INSERT INTO t2 VALUES (NULL, 0);

INSERT INTO t2 VALUES (1, 1);

-- value 2 has 2 rows in t2
INSERT INTO t2 VALUES (2, 2);
INSERT INTO t2 VALUES (2, 2);

-- value 3 has no rows in t2
INSERT INTO t2 VALUES (4, 4);
INSERT INTO t2 VALUES (5, 5);
INSERT INTO t2 VALUES (6, 6);
INSERT INTO t2 VALUES (7, 7);
INSERT INTO t2 VALUES (8, 8);

-- value 9 not present in either table
```

2. Run this statement in a loop in a single connection using your favorite client:
```SELECT * FROM t1```

If needed, I can provide a python script that just runs the statement in a loop, but I guess you can also pipe this statement repeatedly through the psql client

3. Observe I/O with iotop, iostat or strace.

**Comment by danhhz** [comment] 2021-09-13 17:17
Thank you! I'll take a look

**Comment by danhhz** [comment] 2021-09-13 17:59
Okay so what's happening here is that normally there's a fairly regular rate of `seal`s where coord advances the timestamp of the system tables. However, (pretty sure because of linearizability), we seem to call `seal` far more when under a high load of SELECTs (perhaps once per SELECT?). The immediate issue is that this caused persist to be overeager in its compactions, causing the high disk usage seen here. The fix is straightforward (internally call `step` less often), but there's a few different ways we can make that happen. I'll mull on this

FYI @ruchirK (nothing for you to do, just keeping you in the loop)

**Comment by ruchirK** [comment] 2021-09-13 18:27
hmmm there is a clear thing we can do here IMO. Right now, we mint a trace batch every time we call `step` and the seal frontier is greater than the seal frontier thats committed, even if there is no data to be put in that batch. All those empty batches are disk writes and then each batch drives more compaction, which is more disk writes

Instead, I think if trace managed separate antichains for `sealed` aka "this is what we've acknowledged is closed" and `upper` aka "this is the last timestamp for which we've moved data out of future" we wouldn't need to mint the empty batches. Right now, we track `upper` implicitly by looking at the `upper` of the most recent batch, which is what necessitates all of these empty batch writes in the first place.

Hope this is relatively coherent :D I can also sketch out a quick prototype later in the afternoon but tl;dr I don't think we need to call `step` less often, we just need to be a tiny bit smarter to not write out empty batches on subsequent `step` calls with no data, and just a `seal` frontier advancement.

**Comment by danhhz** [comment] 2021-09-13 20:28
Yeah, I like that. I resurrected my 100ms step rate limiter branch, which does seem to fix this but I'm worried about what else that affects. Your proposed fix is much more targeted and I can't think of any side effects it would have offhand. I'll take a pass at implementing it

**Comment by danhhz** [comment] 2021-09-13 22:16
Update: I tried a simpler version of this fix (in drain_unsealed, skip draining this collection if the trace batch it would mint would be empty pre-consolidate). It fixes the compaction usage, but there's still far too much disk usage from meta writes, including those from drain_pending. At some point, we need to be smarter in try_set_meta about not writing out meta if it hasn't changed, but that's a big change.

The more I think about it, the more I'm convinced seal rate limiting is the right short-term fix here. Local testing of my resurrected branch seems to pretty clearly have fixed the issue philip found here. Sadly, I didn't get a chance to clean up and PR this before I had to leave for the day.

Also figured out (h/t mjibson) that the reason the chbench load test (which does run many selects) didn't catch this is that the selects have to be over a view that's derived in some way from a table and chbench is running over views derived from kafka sources.

**Comment by danhhz** [comment] 2021-09-15 17:55
It turned out that my resurrected rate limiting branch only worked because it had a bug and was actually calling step far less often than I intended. With the bug fixed, the bytes written updating meta is still too high to call this fixed.

Thinking out loud, the ideal short-term (just the mz_metrics test) behavior we want here is to call drain_pending as soon as we have some writes and seals for those writes, and then severely rate limit calls (1s or more?) to drain_unsealed and compact. I think that's actually doable to code up, so I'm going to give it a shot

**Comment by ruchirK** [comment] 2021-09-15 20:16
@danhhz just so you know https://github.com/MaterializeInc/materialize/pull/8036 does exactly that I think?

**Comment by ruchirK** [comment] 2021-09-15 20:51
Got nerd sniped and patched 8036 to also do "only call drain_pending when there are writes to drain, don't call drain_pending when there's only seal updates". curious to see how our two branches compare

**Comment by danhhz** [comment] 2021-09-15 21:12
Some incoherent thoughts as I work through this:

They're similar in spirit, but the impl is a little different. No worth digging into because I don't think either of them will work. I'm currently trying a workload where i run `SELECT count(8) from mz_metrics` in a tight loop. I was hoping that what I could do is hold off the drain_pending until we have a seal that is later than our pending writes, but I keep seeing traffic where I get a few seals in a row after the writes and I can't figure out which one is the one that's going to unblock coord for my mz_metrics SELECT. The problem is that for any given seal, we don't know (a) if it's actually blocking a select over a persisted table and (b) if it's the last seal we'll see for a while (~15s between them sometimes for some reason I haven't dug into yet).

There's a tension between wanting to drain_pending immediately if we're selecting over a persisted table in a tight loop but delay it for a long time if we're selecting a user table in a tight loop. Possibly we could teach coord to tell us this at some point, but that's too big a change for getting this resolved by tomorrow morning.

So, I think in the end I might just have to brute force this and do a simple rate limit on drain_pending/step plus a ticker so we don't have long periods that go by with no chances to call step (because no commands were sent).

**Closed** 2021-09-16 02:37 UTC
Labels: C-bug
