### ISSUE TITLE
create HTTP sink type

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#1706] opened 2020-01-27 18:47 UTC
Inspired by #1701, and in contrast to #1704, it would be nice to have an HTTP _sink_ type: which asks Materialize to make a HTTP call to an IP address.

One design question that comes up: if Materialize get's a bad response code, does Materialize retry? What if the sink gets backed up? There's one solution that feels elegant (but requires more thinking through) that Materialize does retry, and accumulates 'sink batches', which allows for it to be used as a durable work-queue. cc @quodlibetor

**Comment by necaris** [comment] 2022-03-31 20:22
Retry until a `200 OK` response?

**Comment by benesch** [comment] 2024-01-27 23:55
Closing as a retroactive duplicate of the [webhook sink](https://github.com/MaterializeInc/materialize/issues/20316) feature request.

**Closed by benesch** 2024-01-27 23:55 UTC
Labels: C-feature, A-integration, A-sink, A-STORAGE
