### ISSUE TITLE
Tail not working in mzcompose cli

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/materialize#3416] opened 2020-06-18 22:12 UTC
### What version of Materialize are you using?

```
./mzcompose -v     
==> Collecting mzbuild dependencies
 materialize/chbenchmark:mzbuild-MHUW7NOAWAJAQFUO3PCSWAP4Q7IYCOVY
 materialize/ci-mz-sql-exporter:mzbuild-CTJHNGR3CZHNIV5UM2VZJ66ETSAWWQ53
 materialize/cli:mzbuild-GKSQGSSO2MR2Q4GDQ366HG3TGNAAMLBK
 materialize/dashboard:mzbuild-J6AGOMDMUNTYM37ZVDTERIYRPFMBMOEQ
 materialize/materialized:mzbuild-WSBU3DBX5NXP47GWVFOO7XX7XUXPBPPJ
 materialize/peeker:mzbuild-IPLMTUHP45ZR3SEMR473FZBKK4VLGESQ
 materialize/test-correctness:mzbuild-6JM5RL3VEEFR52HG4RU5JU2Y4JBDYQE7
==> Delegating to Docker Compose
docker-compose version 1.25.5, build 8a1c60f6
```

### How did you install Materialize?

* [X] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source

### What was the issue?

I ran `TAIL ... WITH SNAPSHOT`, I got the error "`can't execute COPY TO: use the copy_to() method instead`"

### Is the issue reproducible? If so, please provide reproduction instructions.

I followed the BI demo instructions. I installed `query07` as a view. Instead of running `select *`, instead I ran:

```
mz> SELECT * FROM query07; 
                                                                                                                                             
+---------------+---------------+----------+-----------+
| supp_nation   | cust_nation   | l_year   | revenue   |
|---------------+---------------+----------+-----------|
+---------------+---------------+----------+-----------+
SELECT 0
Time: 0.017s
mz> tail query07 with snapshot;                                                                                                              
can't execute COPY TO: use the copy_to() method instead
Time: 1.007s (a second), executed in: 1.007s (a second)
mz> tail query07;                                                                                                                            
another command is already in progress

Time: 0.001s
mz> tail query07;                                                                                                                            
another command is already in progress

Time: 0.000s
mz> show views;                                                                                                                              
another command is already in progress

Time: 0.001s

```

Notice how no further commands can run either.

### Please attach any applicable log files.

N/A

**Comment by benesch** [comment] 2020-06-20 02:26
Duplicate of https://github.com/MaterializeInc/materialize/issues/838.

**Closed by benesch** 2020-06-20 02:26 UTC
Labels: C-bug
