### ISSUE TITLE
feature-benchmark: MySqlInitialLoad 10% performance regression

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27478] opened 2024-06-06 01:53 UTC
### What version of Materialize are you using?

0c78f604a4

### What is the issue?

First seen in https://buildkite.com/materialize/nightly/builds/7978, but since it's right about 10% it's flaky:
```
NAME                                | TYPE      |      THIS       |      OTHER      |  Regression?  | 'THIS' is:
----------------------------------------------------------------------------------------------------
MySqlInitialLoad                    | wallclock |           1.852 |           1.681 |    !!YES!!    | 10.2 pct   more/slower
MySqlInitialLoad                    | messages  |            None |            None |      no       | N/A
MySqlInitialLoad                    | memory    |        1578.331 |        1525.879 |      no       | 3.4 pct   more/slower
```
It seems one of these PRs could be responsible: https://github.com/MaterializeInc/materialize/compare/9565162583...29f53f0407 (but not 100% sure because of flakiness) (includes https://github.com/MaterializeInc/materialize/pull/27376 and https://github.com/MaterializeInc/materialize/pull/27058)

I'm not sure how bad this regression is, just wanted to bring it up in case it's entirely unexpected.

**Comment by def-** [comment] 2024-06-06 03:36
Actually let me see if the test run for https://github.com/MaterializeInc/materialize/pull/27475 shows that it gets fixed: https://buildkite.com/materialize/nightly/builds/8004#018feb2b-4a3a-4f9e-b4af-814dc58c8199
Edit: Seems to be a duplicate of https://github.com/MaterializeInc/materialize/issues/27425, at least I didn't see it with the fix for it anymore.

**Comment by def-** [comment] 2024-06-06 07:44
Thanks to @petrosagg for noticing, the PR was only comparing against main and showed no difference there, but also no improvement. So not fixed after all.

**Comment by rjobanp** [comment] 2024-06-06 14:06
@petrosagg do you think this is related to the new reclock implementation? That list of commits linked by @def- doesn't show anything related to the mysql source pipeline directly besides the new reclock operator, so I'm suspicious of that. Have we seen a similar regression for PG in the same timeframe @def- ?

**Comment by petrosagg** [comment] 2024-06-06 14:33
Yeah this is caused by the new reclock impl. It's unclear why, the pg initial load doesn't have this behavior (maybe something related to more complicated frontiers?). It's going to be hard to tease out exactly what's going on here, I'll try to investigate if I find some time

**Comment by rjobanp** [comment] 2024-06-12 15:42
Now that the new reclock implementation has been reverted, I'll close this for now

**Closed by rjobanp** 2024-06-12 15:42 UTC
Labels: C-bug, T-performance, A-storage

**Comment by petrosagg** [comment] 2024-06-13 12:31
The root cause of this been fixed when the PR had not been reverted so it can remain closed in general. The fix was this one https://github.com/MaterializeInc/materialize/pull/27475
