### ISSUE TITLE
materialize crashes on start when trying to re-create sinks in directories that don't exist.

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#5394] opened 2021-01-20 22:05 UTC
e.g.:

```
materialized: recreating sink materialize.public.uuid_sink_572203242: unable to create avro ocf sink file /tmp/.tmpzICLBJ/uuid-sink-u662-1611180100-9422967276315490800.ocf : No such file or directory (os error 2)
```

**Comment by rjnn** [comment] 2021-01-20 22:59
Excellent find!

**Comment by benesch** [comment] 2021-01-20 23:06
Duplicate of #4401.

**Closed by benesch** 2021-01-20 23:06 UTC
Labels: C-bug
