### ISSUE TITLE
regression: cannot serve requested as_of Antichain

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16615] opened 2022-12-13 07:38 UTC
### What version of Materialize are you using?

environmentd v0.35.0-dev (92ab206d4)

### How did you install Materialize?

Docker image

### What is the issue?

The Zippy Cluster Replicas has not been giving any trouble recently but today it failed with the panic shown below

https://buildkite.com/materialize/nightlies/builds/1476#01850652-4087-4a3c-be73-68be965f03c7

### Relevant log output

```source
zippy-materialized-1     | thread 'timely:work-1' panicked at 'u61: sdeb68b47-064b-4522-b10f-1236ac29fb6f cannot serve requested as_of Antichain { elements: [1670849984462] }: Since(Antichain { elements: [1670850000000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-045f889100bf7f1b3-1/materialize/tests/src/storage-client/src/source/persist_source.rs:185:24
zippy-materialized-1     | stack backtrace:
zippy-materialized-1     | thread 'timely:work-1' panicked at 'u61: sdeb68b47-064b-4522-b10f-1236ac29fb6f cannot serve requested as_of Antichain { elements: [1670849984462] }: Since(Antichain { elements: [1670850000000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-045f889100bf7f1b3-1/materialize/tests/src/storage-client/src/source/persist_source.rs:185:24
```

**Comment by teskje** [comment] 2022-12-13 10:31
I recently merged a related change. Let me check!

**Comment by philip-stoev** [comment] 2022-12-14 07:33
Happened again https://buildkite.com/materialize/nightlies/builds/1487#_ . This is definitely a regression, marking as such.

**Comment by teskje** [comment] 2022-12-14 13:26
### Diagnosis

As suspected, #16288 did not introduce the bug, but rather made an incorrect assumption we had visible.

The assumption being: When computed drops a trace handle [in `handle_allow_compaction`](https://github.com/MaterializeInc/materialize/blob/65d206aec519e87b200228b682909eb0ee29406d/src/compute/src/compute_state.rs#L212), this will drop the dataflow's token, which will drop the dataflow's persist_sources.

This assumption does not hold if there are other trace handles pointing to the same trace still alive. For example, a pending peek holds a trace handle, so if there are peeks pending for an index that is allowed to compact to the empty frontier, the trace bundle is actually not dropped until the peek is fulfilled.

Because of the above, the following chain of events can happen:
1. There is a cluster with two replicas `R1` and `R2`.
2. The user performs a peek reading from a storage collection `S` (e.g., a source or a table).
3. The peek cannot use the fast path, so instead an ad-hoc dataflow must be created, peeked, and dropped again.
4. The compute controller sends the `CreateDataflows` command, followed by the `Peek` command, to both replicas.
5. `R1` is fast and immediately renders the dataflow, and fulfills the peek.
6. `R2` is slow and hasn't handled the `CreateDataflows` command yet.
7. The compute controller receives the `Peek` response, and reacts to it by sending `AllowCompaction([])` to the replicas for the ad-hoc dataflow that is now no longer needed.
8. `R1` receives the `AllowCompaction` command, drops the dataflow, and reports to the controller that it has stopped reading from the dataflow inputs.
9. `R2` finally wakes up. It sees the `CreateDataflows` and `Peek` commands, and handles them by creating the ad-hoc dataflow and installing a pending peek waiting for the dataflow to hydrate.
10. `R2` sees the `AllowCompaction` command, drops **one of** the dataflows trace handles, and reports to the controller that it has stopped reading from the dataflow inputs.
11. The controller receives word that both of the replicas have stopped reading from the dataflow inputs (the storage collection `S`) and therefore allows `S` to be compacted.
12. `R2` actually still has the dataflow alive because the pending peek keeps a trace handle. The dataflow tries to read from `S`, which has been compacted, and consequently panics with "cannot serve requested as_of".

The bug is that in step 10 `R2` immediately reports that the dataflow was dropped, even though it actually wasn't.

Reverting #16288 hides the bug because it makes the controller only allow compaction to the empty frontier once all replicas have responded to all peeks on the dataflow, so there is no pending peek left when the `AllowCompaction([])` command is received.

### Possible Solutions

Implementing https://github.com/MaterializeInc/materialize/issues/16275 (properly) will solve the issue.

As a lower-effort solution, we can think about having the controller send a `CancelPeeks` command in response to the first applicable `PeekResponse` it receives for a peek. This would ensure that pending peeks are removed prior to the replica receiving the `AllowCompaction([])` command. I am not entirely sure if that solves all edge-cases (for example, peeks are not the only thing keeping clones of trace handles, dependent dataflows do too), so we should implement this solution only if it makes sense to do so independently from this bug.

**Comment by teskje** [comment] 2022-12-14 14:27
@philip-stoev Now that the issue is diagnosed and mitigated, should we close this ticket? We have https://github.com/MaterializeInc/materialize/issues/16275 and https://github.com/MaterializeInc/materialize/issues/16641 to track solutions that are more satisfying than reverting #16275 (and that will allow us to un-revert again).

**Comment by philip-stoev** [comment] 2022-12-14 14:54
Yes please feel free to close.

**Closed** 2022-12-14 14:54 UTC
Labels: C-bug, release-blocker, A-STORAGE, A-COMPUTE
